### ISSUE TITLE
Bug: Can't download album with no cover art

### ISSUE THREAD

**Issue by sk-ed** [nathom/streamrip#168]
## Bug Report

**Current Behavior**
When I try to download an album on qobuz which has no cover, it fails as it cannot find the cover image.

**Command used:**

```bash
rip --verbose url https://play.qobuz.com/album/nli2ided2xyaa
```

**Expected behavior**
It should download the album with no error

**`streamrip` Configuration File (find using `rip config -o`):**

<!-- If the command isn't working, you can find the file at one of the following paths:-->

<!-- macOS: ~/Library/Application Support/streamrip -->

<!-- Linux: ~/.config/streamrip or ~/.streamrip -->

<!-- Windows: \Users\<username>\AppData\Local\streamrip  or C:\Users\<usename>\AppData\Roaming\streamrip-->


```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/home/arch/Documents/streamrip"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false


[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3


[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 4
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = "NO"
# This is an md5 hash of the plaintext password
password = "NO"
# Do not change
app_id = "NO"
# Do not change
secrets = ["NO", "NO"]


[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""


[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true


[soundcloud]
# Only 0 is available for now
quality = 0


[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.

[database.downloads]
enabled = true
path = "/home/arch/.config/streamrip/downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads

[database.failed_downloads]
enabled = true
path = "/home/arch/.config/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.

[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.

[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false


[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
max_width = 999999
max_height = 999999
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.

[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"

# Last.fm playlists are downloaded by searching for the titles of the tracks

[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"


[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"


[misc]
# Metadata to identify this config file. Do not change.
version = "1.4"
```

**Environment**

- `streamrip` version(s): 1.4
- Python version: 3.9.6
- OS: Arch Linux

**Traceback**
```bash
[arch@archpc qobuz]$ rip --verbose url https://play.qobuz.com/album/nli2ided2xyaa
Logging into qobuz


Downloading LIL DARKIE CLASSICS (Album)

Downloading cover art (large)
Cover |                                                                                                                                                                                                                    | ? left at ?B/s 

  Stack trace:

  11  ~/.local/lib/python3.9/site-packages/cleo/application.py:314 in run
        exit_code = self._run(io)

  10  ~/.local/lib/python3.9/site-packages/rip/cli.py:624 in _run
        super()._run(io)

   9  ~/.local/lib/python3.9/site-packages/cleo/application.py:409 in _run
        exit_code = self._run_command(command, io)

   8  ~/.local/lib/python3.9/site-packages/cleo/application.py:416 in _run_command
        return command.run(io)

   7  ~/.local/lib/python3.9/site-packages/cleo/commands/base_command.py:118 in run
        status_code = self.execute(io)

   6  ~/.local/lib/python3.9/site-packages/cleo/commands/command.py:85 in execute
        return self.handle()

   5  ~/.local/lib/python3.9/site-packages/rip/cli.py:87 in handle
        core.download()

   4  ~/.local/lib/python3.9/site-packages/rip/core.py:330 in download
        item.download(**arguments)

   3  ~/.local/lib/python3.9/site-packages/streamrip/media.py:1116 in download
        self._prepare_download(**kwargs)

   2  ~/.local/lib/python3.9/site-packages/streamrip/media.py:1514 in _prepare_download
        downsize_image(

   1  ~/.local/lib/python3.9/site-packages/streamrip/utils.py:509 in downsize_image
        image = Image.open(filepath)

  UnidentifiedImageError

  cannot identify image file '/tmp/cover_-8600539971123203697.jpg'

  at ~/.local/lib/python3.9/site-packages/PIL/Image.py:3023 in open
      3019│     if exclusive_fp:
      3020│         fp.close()
      3021│     for message in accept_warnings:
      3022│         warnings.warn(message)
    → 3023│     raise UnidentifiedImageError(
      3024│         "cannot identify image file %r" % (filename if filename else fp)
      3025│     )
      3026│ 
      3027│ 

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```
