### ISSUE TITLE
FLACNoHeaderError

### ISSUE THREAD

**Issue by ElEMISOR0524** [nathom/streamrip#171]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Command used:**

```bash
# Type the command that caused the bug here
```

**Expected behavior**

**`streamrip` Configuration File (find using `rip config -o`):**

```toml
# Paste the contents of config.toml here
# REMOVE YOUR CREDENTIALS
[your]
config = "file"
```

**Environment**

- `streamrip` version(s): [e.g. v0.5.2]
- Python version: [e.g. 3.8]
- OS: [e.g. OSX 10.13.4, Windows 10]

**Traceback**
```bash
# Paste the text that Python dumped on the error here
# Delete this section if there was no traceback
```

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
