### ISSUE TITLE
Test bug report 2

### ISSUE THREAD

**Issue by nathom** [nathom/streamrip#181]
### Describe the bug

asdf

### Command Used

asdf

### Debug Traceback

a
sdf
d
sf
d

### Config File

```toml
[my]
config = "test"
```

### Operating System

macOS

### streamrip version

1.5
