### ISSUE TITLE
[BUG] Video download not turning off in config.toml

### ISSUE THREAD

**Issue by Area0077** [nathom/streamrip#183]
### Describe the bug

cannot turn off downloading video, even with this option enabled in config.toml
```toml
[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 1
# This will download videos included in Video Albums.
download_videos = false
```

### Command Used

```bash
rip url https://tidal.com/browse/artist/17548
```

### Debug Traceback

```text
N/A
```

### Config File

```toml
N/A
```

### Operating System

Windows 10

### streamrip version

1.5
