### ISSUE TITLE
[BUG] <TypeError    object of type 'bool' has no len()>

### ISSUE THREAD

**Issue by CodyChrunos** [nathom/streamrip#184]
### Describe the bug

When I try to download lastfm playlist. I have changed the source from Qobuz to Tidal when searching lastfm tracks, but it still ask me to log in to Qobuz. Then use --source to specify Tidal.

### Command Used

```bash
rip lastfm --source=tidal https://www.last.fm/user/chrunos/playlists/12146879
```

### Debug Traceback

```text
TypeError

  object of type 'bool' has no len()

  at c:\users\b23289\appdata\local\programs\python\python39\lib\site-packages\rip\core.py:692 in search
      688│                 or results.get("albums", {}).get("data", False)
      689│             )
      690│             if items is None:
      691│                 raise NoResultsFound(query)
    → 692│             logger.debug("Number of results: %d", len(items))
      693│
      694│             for i, item in enumerate(items):
      695│                 logger.debug(item["title"])
      696│                 yield MEDIA_CLASS[media_type].from_api(item, client)  # type: ignore

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "C:\\Users\\B23289\\StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false



[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3



[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = "d41d8cd98f00b204e9800998ecf8427e"
# Do not change
app_id = ""
# Do not change
secrets = []




















[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = 181809340
country_code = "US"
access_token = "eyJraWQiOiJ2OU1GbFhqWSIsImFsZyI6IkVTMjU2In0.eyJ0eXBlIjoibzJfYWNjZXNzIiwidWlkIjoxODE4MDkzNDAsInNjb3BlIjoid19zdWIgcl91c3Igd191c3IiLCJnVmVyIjowLCJzVmVyIjowLCJjaWQiOjMwMDYsImV4cCI6MTYzMjQ0Mjc4Nywic2lkIjoiMjZlZDliNGItOGMyYy00ZjVlLTllNDctYmYzNDk5NTk1NTc4IiwiaXNzIjoiaHR0cHM6Ly9hdXRoLnRpZGFsLmNvbS92MSJ9.Jq_GBxp9gOg1dChk3H0yKrkl9joSedOZ5JG4xRBKgflqVmbFNKCBOBabeAW_KXjuzotjn00qCYFCqKfRyEoubw"
refresh_token = "eyJraWQiOiJoUzFKYTdVMCIsImFsZyI6IkVTNTEyIn0.eyJ0eXBlIjoibzJfcmVmcmVzaCIsInVpZCI6MTgxODA5MzQwLCJzY29wZSI6Indfc3ViIHJfdXNyIHdfdXNyIiwiY2lkIjozMDA2LCJzVmVyIjowLCJnVmVyIjowLCJpc3MiOiJodHRwczovL2F1dGgudGlkYWwuY29tL3YxIn0.Af2jXIR4xvuHfYMvM7E_hc6vsF-J8oWx3c1nxogiL_HIeTGOph-0pmGsPcGaxpkNSlgQne1nWm-byLzK6zdhGCEoAPI0XU3ZsQXZiagpl0VYsAli6NL9UkTxuWk-mGNW4IQjTYiKIIAdyip5yXo3nToKby3mDqQtq3_qfRrcabxHU1vR"
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = 1632442788.8552313




















[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = "916019dc795342b1921e07623c69112a233337e6b639527598d3722a7d207433bf8e315215a8e1e3ce7b90959cc412308b7b915c3fcfd04caaa270d0bdd45db00da406b77684ec128af6de5cb322cd9073c969d8490735c53bdd74eed70ea6b5"
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true




















[soundcloud]
# Only 0 is available for now
quality = 0



[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.


[database.downloads]
enabled = true
path = "C:\\Users\\B23289\\AppData\\Local\\streamrip\\streamrip\\downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads


[database.failed_downloads]
enabled = true
path = "C:\\Users\\B23289\\AppData\\Local\\streamrip\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.


[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.


[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false



[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true



[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.


[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# "id", and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false


# Last.fm playlists are downloaded by searching for the titles of the tracks


[lastfm]
# The source on which to search for the tracks.
source = "tidal"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"



[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"



[misc]
# Metadata to identify this config file. Do not change.
version = "1.5"
```

### Operating System

Windows 10

### streamrip version

 streamrip-1.5
