### ISSUE TITLE
Error encountered with search command

### ISSUE THREAD

**Issue by ludoludovic** [nathom/streamrip#189]
### Describe the bug

KeyError 'title' encountered when use of 'xxx' or "xxx" in search query 

### Command Used

```bash
rip search --type artist --source deezer 'bob dylan'
```

### Debug Traceback

```text
DEBUG:streamrip:Number of results: 25

  Stack trace:

  8  c:\users\familles\anaconda3\lib\site-packages\cleo\application.py:314 in run
      312│
      313│             try:
    → 314│                 exit_code = self._run(io)
      315│             except Exception as e:
      316│                 if not self._catch_exceptions:

  7  c:\users\familles\anaconda3\lib\site-packages\rip\cli.py:624 in _run
      622│             logger.addHandler(fh)
      623│
    → 624│         super()._run(io)
      625│
      626│     def create_io(self, input=None, output=None, error_output=None):

  6  c:\users\familles\anaconda3\lib\site-packages\cleo\application.py:409 in _run
      407│                 io.set_input(ArgvInput(argv))
      408│
    → 409│         exit_code = self._run_command(command, io)
      410│         self._running_command = None
      411│

  5  c:\users\familles\anaconda3\lib\site-packages\cleo\application.py:416 in _run_command
      414│     def _run_command(self, command: Command, io: IO) -> int:
      415│         if self._event_dispatcher is None:
    → 416│             return command.run(io)
      417│
      418│         # Bind before the console.command event,

  4  c:\users\familles\anaconda3\lib\site-packages\cleo\commands\base_command.py:118 in run
      116│         io.input.validate()
      117│
    → 118│         status_code = self.execute(io)
      119│
      120│         if status_code is None:

  3  c:\users\familles\anaconda3\lib\site-packages\cleo\commands\command.py:85 in execute
       83│
       84│         try:
    →  85│             return self.handle()
       86│         except KeyboardInterrupt:
       87│             return 1

  2  c:\users\familles\anaconda3\lib\site-packages\rip\cli.py:164 in handle
      162│         core = RipCore(config)
      163│
    → 164│         if core.interactive_search(query, source, type):
      165│             core.download()
      166│         else:

  1  c:\users\familles\anaconda3\lib\site-packages\rip\core.py:749 in interactive_search
      747│         :type media_type: str
      748│         """
    → 749│         results = tuple(self.search(source, query, media_type, limit=limit))
      750│
      751│         def title(res):

  KeyError

  'title'

  at c:\users\familles\anaconda3\lib\site-packages\rip\core.py:695 in search
      691│                 raise NoResultsFound(query)
      692│             logger.debug("Number of results: %d", len(items))
      693│
      694│             for i, item in enumerate(items):
    → 695│                 logger.debug(item["title"])
      696│                 yield MEDIA_CLASS[media_type].from_api(item, client)  # type: ignore
      697│                 if i >= limit - 1:
      698│                     return
      699│

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "C:\\Users\\FamilleS\\Music\\Streamrip"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false




[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3




[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = "x"
# This is an md5 hash of the plaintext password
password = "9dd4e461268c8034f5c8564e155c67a6"
# Do not change
app_id = ""
# Do not change
secrets = []




[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""




[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true




[soundcloud]
# Only 0 is available for now
quality = 0




[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.



[database.downloads]
enabled = true
path = "C:\\Users\\FamilleS\\AppData\\Local\\streamrip\\streamrip\\downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads



[database.failed_downloads]
enabled = true
path = "C:\\Users\\FamilleS\\AppData\\Local\\streamrip\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.



[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.



[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false




[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true




[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.



[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# "id", and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false


# Last.fm playlists are downloaded by searching for the titles of the tracks



[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"




[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"




[misc]
# Metadata to identify this config file. Do not change.
version = "1.5"
```

### Operating System

Windows

### streamrip version

1.5
