### ISSUE TITLE
[BUG] Video download failed

### ISSUE THREAD

**Issue by AminurAlam** [nathom/streamrip#195]
### Describe the bug

this only happens with all tidal videos, meanwhile songs are working fine

### Command Used

```bash
rip url https://tidal.com/video/48204106 -vvv
```

### Debug Traceback

```text
DEBUG:streamrip:Config loaded
DEBUG:streamrip:Parsed urls: [('tidal', 'video', '48204106')]     DEBUG:streamrip:Searching for {'id': '48204106'} in database
DEBUG:streamrip:Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)
DEBUG:streamrip:{'quality': 2, 'download_videos': True, 'user_id': [REMOVED], 'country_code': 'US', 'access_token': [REMOVED], 'refresh_token': [REMOVED], 'token_expiry': 1633452902.1938164}
DEBUG:streamrip:Logging in with access token
Logged into Tidal
DEBUG:streamrip:Config saved: /data/data/com.termux/files/home/.config/streamrip/config.toml
DEBUG:streamrip:{'downloads': {'folder': '/storage/emulated/0/Music', 'source_subdirectories': False, 'concurrency': {'enabled': True, 'max_connections': 3}}, 'qobuz': {'quality': 2, 'download_booklets': True, 'email': [REMOVED], 'password': [REMOVED], 'app_id': '', 'secrets': []}, 'tidal': {'quality': 2, 'download_videos': True, 'user_id': [REMOVED], 'country_code': 'US', 'access_token': [REMOVED], 'refresh_token': [REMOVED], 'token_expiry': 1633452902.1938164}, 'deezer': {'quality': 2, 'arl': '', 'use_deezloader': True, 'deezloader_warnings': True}, 'soundcloud': {'quality': 0, 'client_id': '', 'app_version': ''}, 'youtube': {'quality': 0, 'download_videos': False, 'video_downloads_folder': ''}, 'database': {'downloads': {'enabled': True, 'path': '/data/data/com.termux/files/home/.config/streamrip/downloads.db'}, 'failed_downloads': {'enabled': True, 'path': '/data/data/com.termux/files/home/.config/streamrip/failed_downloads.db'}}, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24}, 'filters': {'extras': False, 'repeats': False, 'non_albums': False, 'features': False, 'non_studio_albums': False, 'non_remaster': False}, 'artwork': {'embed': True, 'size': 'large', 'max_width': -1, 'max_height': -1, 'keep_hires_cover': True}, 'metadata': {'set_playlist_to_album': True, 'new_playlist_tracknumbers': True, 'exclude': []}, 'filepaths': {'add_singles_to_folder': False, 'folder_format': '{albumartist} - {title}', 'track_format': '{tracknumber} {title}', 'restrict_characters': False}, 'lastfm': {'source': 'qobuz', 'fallback_source': 'deezer'}, 'theme': {'progress_bar': 'dainty'}, 'misc': {'version': '1.6'}}
DEBUG:streamrip:Arguments from config: {'restrict_filenames': False, 'parent_folder': '/storage/emulated/0/Music', 'folder_format': '{albumartist} - {title}', 'track_format': '{tracknumber} {title}', 'embed_cover': True, 'embed_cover_size': 'large', 'keep_hires_cover': True, 'set_playlist_to_album': True, 'stay_temp': False, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24}, 'concurrent_downloads': True, 'max_connections': 3, 'new_tracknumbers': True, 'download_videos': True, 'download_booklets': True, 'download_youtube_videos': False, 'youtube_video_downloads_folder': '', 'add_singles_to_folder': False, 'max_artwork_width': -1, 'max_artwork_height': -1, 'exclude_tags': []}
DEBUG:streamrip:Loading metadata
DEBUG:streamrip:{'id': 48204106, 'title': 'Lush Life', 'volumeNumber': 1, 'trackNumber': 1, 'releaseDate': '2015-07-02T00:00:00.000+0000', 'imagePath': None, 'imageId': 'a54d8808-9aa2-4172-b7c3-7981253a278b', 'vibrantColor': '#c25cb3', 'duration': 203, 'quality': 'MP4_1080P', 'streamReady': True, 'streamStartDate': '2015-07-02T00:00:00.000+0000', 'allowStreaming': True, 'explicit': False, 'popularity': 24, 'type': 'Music Video', 'adsUrl': None, 'adsPrePaywallOnly': True, 'artist': {'id': 4815108, 'name': 'Zara Larsson', 'type': 'MAIN', 'picture': 'a1bb5c72-665b-4ec0-ac3f-e10f4dc01c85'}, 'artists': [{'id': 4815108, 'name': 'Zara Larsson', 'type': 'MAIN', 'picture': 'a1bb5c72-665b-4ec0-ac3f-e10f4dc01c85'}], 'album': None}
DEBUG:streamrip:{'id': 48204106, 'title': 'Lush Life', 'volumeNumber': 1, 'trackNumber': 1, 'releaseDate': '2015-07-02T00:00:00.000+0000', 'imagePath': None, 'imageId': 'a54d8808-9aa2-4172-b7c3-7981253a278b', 'vibrantColor': '#c25cb3', 'duration': 203, 'quality': 'MP4_1080P', 'streamReady': True, 'streamStartDate': '2015-07-02T00:00:00.000+0000', 'allowStreaming': True, 'explicit': False, 'popularity': 24, 'type': 'Music Video', 'adsUrl': None, 'adsPrePaywallOnly': True, 'artist': {'id': 4815108, 'name': 'Zara Larsson', 'type': 'MAIN', 'picture': 'a1bb5c72-665b-4ec0-ac3f-e10f4dc01c85'}, 'artists': [{'id': 4815108, 'name': 'Zara Larsson', 'type': 'MAIN', 'picture': 'a1bb5c72-665b-4ec0-ac3f-e10f4dc01c85'}], 'album': None}
DEBUG:streamrip:Removing tempfiles {}

  Stack trace:

  9  /data/data/com.termux/files/usr/lib/python3.9/site-packages/cleo/application.py:314 in run
      312│
      313│             try:
    → 314│                 exit_code = self._run(io)
      315│             except Exception as e:
      316│                 if not self._catch_exceptions:

  8  /data/data/com.termux/files/usr/lib/python3.9/site-packages/rip/cli.py:604 in _run
      602│             logger.addHandler(fh)
      603│
    → 604│         super()._run(io)
      605│
      606│     def create_io(self, input=None, output=None, error_output=None):

  7  /data/data/com.termux/files/usr/lib/python3.9/site-packages/cleo/application.py:409 in _run
      407│                 io.set_input(ArgvInput(argv))
      408│
    → 409│         exit_code = self._run_command(command, io)
      410│         self._running_command = None
      411│

  6  /data/data/com.termux/files/usr/lib/python3.9/site-packages/cleo/application.py:416 in _run_command
      414│     def _run_command(self, command: Command, io: IO) -> int:
      415│         if self._event_dispatcher is None:
    → 416│             return command.run(io)
      417│
      418│         # Bind before the console.command event,

  5  /data/data/com.termux/files/usr/lib/python3.9/site-packages/cleo/commands/base_command.py:118 in run
      116│         io.input.validate()
      117│
    → 118│         status_code = self.execute(io)
      119│
      120│         if status_code is None:

  4  /data/data/com.termux/files/usr/lib/python3.9/site-packages/cleo/commands/command.py:85 in execute
       83│
       84│         try:
    →  85│             return self.handle()
       86│         except KeyboardInterrupt:
       87│             return 1

  3  /data/data/com.termux/files/usr/lib/python3.9/site-packages/rip/cli.py:87 in handle
       85│
       86│         if len(core) > 0:
    →  87│             core.download()
       88│         elif not urls and path is None:
       89│             self.line("Must pass arguments. See rip url -h.")

  2  /data/data/com.termux/files/usr/lib/python3.9/site-packages/rip/core.py:316 in download
      314│
      315│             try:
    → 316│                 item.download(**arguments)
      317│                 for item_id in item.downloaded_ids:
      318│                     self.db.add([item_id])

  1  /data/data/com.termux/files/usr/lib/python3.9/site-packages/streamrip/media.py:869 in download
       867│
       868│         with DownloadPool(segment.uri for segment in parsed_m3u.segments) as pool:
    →  869│             bar = get_tqdm_bar(len(pool), desc=self._progress_desc, unit="Chunk")
       870│
       871│             def update_tqdm_bar():

  TypeError

  unsupported format string passed to NoneType.__format__

  at /data/data/com.termux/files/usr/lib/python3.9/site-packages/streamrip/media.py:942 in _progress_desc
       938│         pass
       939│
       940│     @property
       941│     def _progress_desc(self) -> str:
    →  942│         return style(f"Video {self.tracknumber:02}", fg="blue")
       943│
       944│     @property
       945│     def path(self) -> str:
       946│         """Get path to download the mp4 file.

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/storage/emulated/0/Music"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false












[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3












[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 2
# This will download booklet pdfs that are included with some albums
download_booklets = true






































[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 2
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below

country_code = "US"


# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = 1633452902.1938164





































[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true





































[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""












[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.











[database.downloads]
enabled = true
path = "/data/data/com.termux/files/home/.config/streamrip/downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads











[database.failed_downloads]
enabled = true
path = "/data/data/com.termux/files/home/.config/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.











[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.











[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false












[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true












[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.











[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", and "albumcomposer"
folder_format = "{albumartist} - {title}"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# "id", and "albumcomposer"
track_format = "{tracknumber} {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false


# Last.fm playlists are downloaded by searching for the titles of the tracks











[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"












[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"












[misc]
# Metadata to identify this config file. Do not change.
version = "1.6"
```

### Operating System

Android 8.1

### streamrip version

1.6

### Screenshots and recordings

![20210928_230035](https://user-images.githubusercontent.com/64137875/135136683-626fb2b2-5788-42cd-b0f2-c29a68ba5ad4.jpg)
![Screenshot_20210928-230051_Termux](https://user-images.githubusercontent.com/64137875/135136699-c8db58d3-c558-4de7-939d-d4a5d4f3dee9.jpg)
