### ISSUE TITLE
[BUG] <UNEXPECTED CHARACTER>

### ISSUE THREAD

**Issue by mftzy** [nathom/streamrip#201]
### Describe the bug

UnexpectedCharError
                                                                    

### Command Used

```bash
Unexpected character: '#' at line 15 col 32                         
  at /data/data/com.termux/files/usr/lib/python3.10/site-packages/tomlkit/parser.py:669 in _parse_value                                            665│                 return item                                      666│
       667│             raise self.parse_error(InvalidNumberError)           668│         else:                                                 →  669│             raise self.parse_error(UnexpectedCharError, c)       670│                                                                  671│     def _parse_true(self):
       672│         return self._parse_bool(BoolType.TRUE)                   673│
```

### Debug Traceback

```text
Stack trace:                                                                                                                                16  /data/data/com.termux/files/usr/lib/python3.10/site-packages/cleo/application.py:314 in run                                                  312│                                                                  313│             try:                                               → 314│                 exit_code = self._run(io)
       315│             except Exception as e:                               316│                 if not self._catch_exceptions:                                                                                    15  /data/data/com.termux/files/usr/lib/python3.10/site-packages/rip/cli.py:604 in _run                                                          602│             logger.addHandler(fh)                                603│                                                                → 604│         super()._run(io)                                         605│                                                                  606│     def create_io(self, input=None, output=None, error_output=None):                                                                                                                                    14  /data/data/com.termux/files/usr/lib/python3.10/site-packages/cleo/application.py:409 in _run                                                 407│                 io.set_input(ArgvInput(argv))
       408│                                                                → 409│         exit_code = self._run_command(command, io)               410│         self._running_command = None                             411│                                                                                                                                   13  /data/data/com.termux/files/usr/lib/python3.10/site-packages/cleo/application.py:416 in _run_command                                         414│     def _run_command(self, command: Command, io: IO) -> int:                                                                           415│         if self._event_dispatcher is None:                     → 416│             return command.run(io)                               417│                                                                  418│         # Bind before the console.command event,                                                                                  12  /data/data/com.termux/files/usr/lib/python3.10/site-packages/cleo/commands/base_command.py:118 in run                                        116│         io.input.validate()                                      117│                                                                → 118│         status_code = self.execute(io)                           119│                                                                  120│         if status_code is None:
                                                                        11  /data/data/com.termux/files/usr/lib/python3.10/site-packages/cleo/commands/command.py:85 in execute                                           83│                                                                   84│         try:                                                   →  85│             return self.handle()                                  86│         except KeyboardInterrupt:                                 87│             return 1                                                                                                              10  /data/data/com.termux/files/usr/lib/python3.10/site-packages/rip/cli.py:55 in handle                                                          53│         update_check.start()
        54│                                                                →  55│         config = Config()
        56│         path, codec, quality, no_db = clean_options(
        57│             self.option("file"),

   9  /data/data/com.termux/files/usr/lib/python3.10/site-packages/rip/config.py:57 in __init__                                                     55│                                                                   56│         if os.path.isfile(self._path):                         →  57│             self.load()                                           58│             if self.file["misc"]["version"] != self.defaults["misc"]["version"]:                                                        59│                 secho(                                                                                                             8  /data/data/com.termux/files/usr/lib/python3.10/site-packages/rip/config.py:136 in load                                                       134│         """Load infomation from the config files, making a deepcopy."""                                                                135│         with open(self._path) as cfg:                          → 136│             for k, v in tomlkit.loads(cfg.read().strip()).items():
       137│                 self.file[k] = v
       138│                 if hasattr(v, "copy"):                    
   7  /data/data/com.termux/files/usr/lib/python3.10/site-packages/tomlkit/api.py:34 in loads
        32│     Alias for parse().
        33│     """
     →  34│     return parse(string)
        35│                                                                   36│

   6  /data/data/com.termux/files/usr/lib/python3.10/site-packages/tomlkit/api.py:51 in parse
        49│     Parses a string into a TOMLDocument.                          50│     """                                                        →  51│     return Parser(string).parse()                                 52│                                                                   53│
                                                                         5  /data/data/com.termux/files/usr/lib/python3.10/site-packages/tomlkit/parser.py:160 in parse
        158│
        159│         while not self.end():
     →  160│             key, value = self._parse_table()                     161│             if isinstance(value, Table) and value.is_aot_element():                                                                    162│                 # This is just the first table in an AoT. Parse the rest of the array                                                                                                                   4  /data/data/com.termux/files/usr/lib/python3.10/site-packages/tomlkit/parser.py:1167 in _parse_table
       1165│                                                                 1166│                     if self._is_child(name, name_next):
     → 1167│                         key_next, table_next = self._parse_table(name, table)                                                         1168│
       1169│                         table.raw_append(key_next, table_next)                                                                 
   3  /data/data/com.termux/files/usr/lib/python3.10/site-packages/tomlkit/parser.py:1154 in _parse_table                                          1152│
       1153│         while not self.end():
     → 1154│             item = self._parse_item()                           1155│             if item:
       1156│                 _key, item = item
                                                                         2  /data/data/com.termux/files/usr/lib/python3.10/site-packages/tomlkit/parser.py:306 in _parse_item
        304│                     break                                        305│
     →  306│         return self._parse_key_value(True)
        307│                                                                  308│     def _parse_comment_trail(self):  # type: () -> Tuple[str, str, str]                                                        
   1  /data/data/com.termux/files/usr/lib/python3.10/site-packages/tomlkit/parser.py:397 in _parse_key_value                                        395│                                                                  396│         # Value                                               →  397│         val = self._parse_value()                                398│         # Comment                                                399│         if parse_comment:

  UnexpectedCharError

  Unexpected character: '#' at line 15 col 32

  at /data/data/com.termux/files/usr/lib/python3.10/site-packages/tomlkit/parser.py:669 in _parse_value
       665│                 return item
       666│
       667│             raise self.parse_error(InvalidNumberError)
       668│         else:
    →  669│             raise self.parse_error(UnexpectedCharError, c)
       670│
       671│     def _parse_true(self):                                       672│         return self._parse_bool(BoolType.TRUE)
       673│
                                                                      If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/data/data/com.termux/files/home/StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false



[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially..
# If you are converting the tracks, or have fast internet, this will.
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
fda5081f896539b584db6bfd64633198# If you have very fast internet, you
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3



[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
weedy@fanclub.pmquality = 4
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = "a"
# This is an md5 hash of the plaintext password
password = "a"
# Do not change
app_id = "950096963"
# Do not change
secrets = ["10b251c286cfbf64d6b7105f253d9a2e", "979549437fcc4a3faad486

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the
# time. If you haven't used streamrip in more than a week, you may hav
# in again using `rip config --tidal`
token_expiry = ""







[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezload
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer ac
# See [ADD LINK] for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip
# back to deezloader, which is unreliable
deezloader_warnings = true







[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""



[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.


[database.downloads]
enabled = true
path = "/data/data/com.termux/files/home/.config/streamrip/downloads.d

# If a download fails, the item ID is stored here. Then, `rip repair`
# called to retry the downloads


[database.failed_downloads]
enabled = true
path = "/data/data/com.termux/files/home/.config/streamrip/failed_down

# Convert tracks to a codec after downloading them.


[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth
# than this value.
bit_depth = 24

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filt


[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false



[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large,
# "original" images can be up to 30MB, and may fail embedding..
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If the
# are larger than the actual dimensions of the image, they will be ign
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true



[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist'
# This is useful if your music library software organizes tracks based
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for
exclude = []

# Changes the folder and file names generated by streamrip.


[filepaths]
# Create folders for single tracks within the downloads directory usin
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampli
# "container", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_
# Available keys: "tracknumber", "artist", "albumartist", "composer",
# "id", and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false


# Last.fm playlists are downloaded by searching for the titles of the


[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is search
# on this one.
fallback_source = "deezer"

[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"



[misc]
# Metadata to identify this config file. Do not change.
version = "1.6"
```

### Operating System

Termux

### streamrip version

1.6
