### ISSUE TITLE
[BUG] Not able to download YouTube videos

### ISSUE THREAD

**Issue by mikeyuhrengott** [nathom/streamrip#227]
### Describe the bug

Not able to download YouTube videos while using rip url command

### Command Used

```bash
rip url https://www.youtube.com/watch?v=8yOskhDn468
```

### Debug Traceback

```text
DEBUG:streamrip:Config loaded

  Stack trace:

  8  /usr/local/lib/python3.8/site-packages/cleo/application.py:314 in run
      312│
      313│             try:
    → 314│                 exit_code = self._run(io)
      315│             except Exception as e:
      316│                 if not self._catch_exceptions:

  7  /usr/local/lib/python3.8/site-packages/rip/cli.py:604 in _run
      602│             logger.addHandler(fh)
      603│
    → 604│         super()._run(io)
      605│
      606│     def create_io(self, input=None, output=None, error_output=None):

  6  /usr/local/lib/python3.8/site-packages/cleo/application.py:409 in _run
      407│                 io.set_input(ArgvInput(argv))
      408│
    → 409│         exit_code = self._run_command(command, io)
      410│         self._running_command = None
      411│

  5  /usr/local/lib/python3.8/site-packages/cleo/application.py:416 in _run_command
      414│     def _run_command(self, command: Command, io: IO) -> int:
      415│         if self._event_dispatcher is None:
    → 416│             return command.run(io)
      417│
      418│         # Bind before the console.command event,

  4  /usr/local/lib/python3.8/site-packages/cleo/commands/base_command.py:118 in run
      116│         io.input.validate()
      117│
    → 118│         status_code = self.execute(io)
      119│
      120│         if status_code is None:

  3  /usr/local/lib/python3.8/site-packages/cleo/commands/command.py:85 in execute
       83│
       84│         try:
    →  85│             return self.handle()
       86│         except KeyboardInterrupt:
       87│             return 1

  2  /usr/local/lib/python3.8/site-packages/rip/cli.py:84 in handle
       82│
       83│         if urls:
    →  84│             core.handle_urls(";".join(urls))
       85│
       86│         if len(core) > 0:

  1  /usr/local/lib/python3.8/site-packages/rip/core.py:161 in handle_urls
      159│         youtube_urls = YOUTUBE_URL_REGEX.findall(url)
      160│         if youtube_urls != []:
    → 161│             self.extend(YoutubeVideo(u) for u in youtube_urls)
      162│
      163│         parsed = self.parse_urls(url)

  TypeError

  Can't instantiate abstract class YoutubeVideo with abstract methods __str__, downloaded_ids, type

  at /usr/local/lib/python3.8/site-packages/rip/core.py:161 in <genexpr>
      157│         # youtube is handled by youtube-dl, so much of the
      158│         # processing is not necessary
      159│         youtube_urls = YOUTUBE_URL_REGEX.findall(url)
      160│         if youtube_urls != []:
    → 161│             self.extend(YoutubeVideo(u) for u in youtube_urls)
      162│
      163│         parsed = self.parse_urls(url)
      164│         if not parsed and len(self) == 0:
      165│             if "last.fm" in url:

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/music/download/Temp"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false








[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3








[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []








[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = false










[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true








[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""








[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "/music/download/Temp"

# This stores a list of item IDs so that repeats are not downloaded.







[database.downloads]
enabled = false
path = "/music/items/"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads







[database.failed_downloads]
enabled = false
path = ""

# Convert tracks to a codec after downloading them.







[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.







[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false








[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true








[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.







[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false


# Last.fm playlists are downloaded by searching for the titles of the tracks







[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"








[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"








[misc]
# Metadata to identify this config file. Do not change.
version = "1.7"
```

### Operating System

Linux

### streamrip version

1.7

### Screenshots and recordings

https://imgur.com/a/45QEbgE
