### ISSUE TITLE
[BUG] Tidal aR7 token not found

### ISSUE THREAD

**Issue by GhostDoctorDicky** [nathom/streamrip#230]
### Describe the bug

Token used in Tidal authorization seems to no longer work.

### Command Used

```bash
rip config --tidal
```

### Debug Traceback

```text
rip config --tidal -vvv

DEBUG:streamrip:Config loaded
DEBUG:streamrip:Logging in as a new user

  Stack trace:

  9  .local/lib/python3.8/site-packages/cleo/application.py:314 in run
      312│
      313│             try:
    → 314│                 exit_code = self._run(io)
      315│             except Exception as e:
      316│                 if not self._catch_exceptions:

  8  .local/lib/python3.8/site-packages/rip/cli.py:604 in _run
      602│             logger.addHandler(fh)
      603│
    → 604│         super()._run(io)
      605│
      606│     def create_io(self, input=None, output=None, error_output=None):

  7  .local/lib/python3.8/site-packages/cleo/application.py:409 in _run
      407│                 io.set_input(ArgvInput(argv))
      408│
    → 409│         exit_code = self._run_command(command, io)
      410│         self._running_command = None
      411│

  6  .local/lib/python3.8/site-packages/cleo/application.py:416 in _run_command
      414│     def _run_command(self, command: Command, io: IO) -> int:
      415│         if self._event_dispatcher is None:
    → 416│             return command.run(io)
      417│
      418│         # Bind before the console.command event,

  5  .local/lib/python3.8/site-packages/cleo/commands/base_command.py:118 in run
      116│         io.input.validate()
      117│
    → 118│         status_code = self.execute(io)
      119│
      120│         if status_code is None:

  4  .local/lib/python3.8/site-packages/cleo/commands/command.py:85 in execute
       83│
       84│         try:
    →  85│             return self.handle()
       86│         except KeyboardInterrupt:
       87│             return 1

  3  .local/lib/python3.8/site-packages/rip/cli.py:330 in handle
      328│
      329│             client = TidalClient()
    → 330│             client.login()
      331│             self._config.file["tidal"].update(client.get_tokens())
      332│             self._config.save()

  2  .local/lib/python3.8/site-packages/streamrip/clients.py:754 in login
       752│         else:
       753│             logger.debug("Logging in as a new user")
    →  754│             self._login_new_user()
       755│
       756│         self.logged_in = True

  1  .local/lib/python3.8/site-packages/streamrip/clients.py:839 in _login_new_user
       837│         :type launch: bool
       838│         """
    →  839│         login_link = f"https://{self._get_device_code()}"
       840│
       841│         secho(

  Exception

  Device authorization failed {'status': 401, 'error': 'invalid_client', 'error_description': 'Client with token aR7gUaTK1ihpXOEP not found', 'sub_status': 1005}

  at .local/lib/python3.8/site-packages/streamrip/clients.py:874 in _get_device_code
       870│         }
       871│         resp = self._api_post(f"{TIDAL_AUTH_URL}/device_authorization", data)
       872│
       873│         if "status" in resp and resp["status"] != 200:
    →  874│             raise Exception(f"Device authorization failed {resp}")
       875│
       876│         self.device_code = resp["deviceCode"]
       877│         self.user_code = resp["userCode"]
       878│         self.user_code_expiry = resp["expiresIn"]
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/home/sdfg/StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false



[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3



[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []



[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""



[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true



[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""



[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.


[database.downloads]
enabled = true
path = "/home/sdfg/.config/streamrip/downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads


[database.failed_downloads]
enabled = true
path = "/home/sdfg/.config/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.


[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.


[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false



[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true



[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = false
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = false
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.


[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false


# Last.fm playlists are downloaded by searching for the titles of the tracks


[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"



[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"



[misc]
# Metadata to identify this config file. Do not change.
version = "1.7"
```

### Operating System

Windows 10

### streamrip version

1.7
