### ISSUE TITLE
[BUG] Not downloading max quality from Tidal

### ISSUE THREAD

**Issue by jayden000** [nathom/streamrip#243]
### Describe the bug

When trying to download Nectar by Joji at full quality, it seems that it isn't downloading the proper files.

The folder says 24B-44.1kHz but when inspecting the mediainfo of each file, it seems that they are only 16B-44.1kHz.

tidal-dl successfully downloaded the 24B-44.1kHz files.

tidal-dl downloaded file media info:
```
General
Complete name                            : \download\Album\Joji\[ME]  Nectar [155112873] [2020]\15 - Joji - 777.flac
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
File size                                : 35.1 MiB
Duration                                 : 3 min 1 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 1 619 kb/s
Album                                    : Nectar
Album/Performer                          : Joji
Part                                     : 1
Part/Total                               : 1
Track name                               : 777
Track name/Position                      : 15
Track name/Total                         : 18
Performer                                : Joji
Recorded date                            : 2020-09-25
ISRC                                     : ZZOPM2002179
Copyright                                : ℗ 2020 88rising Records/Warner Records Inc.
Cover                                    : Yes
Cover MIME                               : image/jpeg

Audio
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Duration                                 : 3 min 1 s
Bit rate mode                            : Variable
Bit rate                                 : 1 607 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Bit depth                                : 24 bits
Compression mode                         : Lossless
Stream size                              : 34.8 MiB (99%)
Writing library                          : Mutagen 1.45.1
```

streamrip downloaded files:

```
General
Complete name                            : streamrip\Joji - Nectar (2020) [FLAC] [24B-44.1kHz]\15. Joji - 777 (Explicit).flac
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
File size                                : 19.6 MiB
Duration                                 : 3 min 1 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 904 kb/s
Album                                    : Nectar
Album/Performer                          : Joji
Part                                     : 01
Part/Total                               : 01
Track name                               : 777 (Explicit)
Track name/Position                      : 15
Track name/Total                         : 18
Performer                                : Joji
Recorded date                            : 2020-09-25
Copyright                                : © 2020 88rising Records/Warner Records Inc.
Cover                                    : Yes
Cover type                               : Cover (front)
Cover MIME                               : image/jpeg

Audio
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Duration                                 : 3 min 1 s
Bit rate mode                            : Variable
Bit rate                                 : 901 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossless
Stream size                              : 19.5 MiB (100%)
Writing library                          : Mutagen 1.45.1
```

### Command Used

```bash
rip url --max-quality 3 https://listen.tidal.com/album/155112873 --ignore-db

Also used rip url --max-quality 4 https://listen.tidal.com/album/155112873 --ignore-db and yielded same results.
```

### Debug Traceback

```text
https://pastebin.com/FvSJHR0e
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = ""
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false








[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3








[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []








[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = 
country_code =
access_token =
refresh_token =
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = 








[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true








[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""








[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.







[database.downloads]
enabled = true
path = 

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads







[database.failed_downloads]
enabled = true
path = 

# Convert tracks to a codec after downloading them.







[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.







[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false








[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true








[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.







[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false


# Last.fm playlists are downloaded by searching for the titles of the tracks







[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"








[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"








[misc]
# Metadata to identify this config file. Do not change.
version = "1.7"
```

### Operating System

Windows 10

### streamrip version

1.8
