### ISSUE TITLE
[BUG] AttributeError when downloading some songs on TIDAL

### ISSUE THREAD

**Issue by Slips-PC** [nathom/streamrip#255]
### Describe the bug

Some tidal tracks cannot be downloaded via the application due to a missing 'folder' attribute.

### Command Used

```bash
rip url https://tidal.com/track/129204258
```

### Debug Traceback

```text
DEBUG:streamrip:Config loaded
DEBUG:streamrip:Parsed urls: [('tidal', 'track', '129204258')]
DEBUG:streamrip:Searching for {'id': '129204258'} in database
DEBUG:streamrip:Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)
DEBUG:streamrip:{'quality': 3, 'download_videos': True, 'user_id': [REDACTED], 'country_code': 'US', 'access_token': '[REDACTED', 'refresh_token': '[REDACTED]', 'token_expiry': [REDACTED]}
DEBUG:streamrip:Logging in with access token
Logged into Tidal
DEBUG:streamrip:Config saved: /home/slips/.config/streamrip/config.toml
DEBUG:streamrip:{'id': '129204258'}
DEBUG:streamrip:{'downloads': {'folder': '', 'source_subdirectories': False, 'concurrency': {'enabled': True, 'max_connections': 3}}, 'qobuz': {'quality': 3, 'download_booklets': True, 'email': '', 'password': '', 'app_id': '', 'secrets': []}, 'tidal': {'quality': 3, 'download_videos': True, 'user_id': 184085608, 'country_code': 'US', 'access_token': '[REDACTED]', 'refresh_token': '[REDACTED]', 'token_expiry': [REDACTED]}, 'deezer': {'quality': 2, 'arl': '', 'use_deezloader': True, 'deezloader_warnings': True}, 'soundcloud': {'quality': 0, 'client_id': '', 'app_version': ''}, 'youtube': {'quality': 0, 'download_videos': False, 'video_downloads_folder': ''}, 'database': {'downloads': {'enabled': True, 'path': '/home/slips/.config/streamrip/downloads.db'}, 'failed_downloads': {'enabled': True, 'path': '/home/slips/.config/streamrip/failed_downloads.db'}}, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'filters': {'extras': False, 'repeats': False, 'non_albums': False, 'features': False, 'non_studio_albums': False, 'non_remaster': False}, 'artwork': {'embed': True, 'size': 'large', 'max_width': -1, 'max_height': -1, 'keep_hires_cover': True}, 'metadata': {'set_playlist_to_album': True, 'new_playlist_tracknumbers': True, 'exclude': []}, 'filepaths': {'add_singles_to_folder': False, 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}', 'restrict_characters': False}, 'lastfm': {'source': 'qobuz', 'fallback_source': 'deezer'}, 'theme': {'progress_bar': 'dainty'}, 'misc': {'version': '1.7'}}
DEBUG:streamrip:Arguments from config: {'restrict_filenames': False, 'parent_folder': '', 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}', 'embed_cover': True, 'embed_cover_size': 'large', 'keep_hires_cover': True, 'set_playlist_to_album': True, 'stay_temp': False, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'concurrent_downloads': True, 'max_connections': 3, 'new_tracknumbers': True, 'download_videos': True, 'download_booklets': True, 'download_youtube_videos': False, 'youtube_video_downloads_folder': '', 'add_singles_to_folder': False, 'max_artwork_width': -1, 'max_artwork_height': -1, 'exclude_tags': []}
DEBUG:streamrip:Loading metadata
DEBUG:streamrip:{'id': 129204258, 'title': 'Frequency Shifter', 'duration': 197, 'replayGain': -11.79, 'peak': 1.0, 'allowStreaming': True, 'streamReady': True, 'streamStartDate': '2020-01-24T00:00:00.000+0000', 'premiumStreamingOnly': False, 'trackNumber': 4, 'volumeNumber': 1, 'version': None, 'popularity': 0, 'copyright': 'Never Say Die Records Ltd', 'url': 'http://www.tidal.com/track/129204258', 'isrc': 'GB7YL2099604', 'editable': False, 'explicit': False, 'audioQuality': 'LOSSLESS', 'audioModes': ['STEREO'], 'artist': {'id': 7418538, 'name': 'Graphyt', 'type': 'MAIN', 'picture': None}, 'artists': [{'id': 7418538, 'name': 'Graphyt', 'type': 'MAIN', 'picture': None}, {'id': 3529150, 'name': 'Pierce', 'type': 'MAIN', 'picture': None}], 'album': {'id': 129204254, 'title': 'Outer Space EP', 'cover': 'cd5d5bc8-ac91-426f-90fc-76ef4920387b', 'vibrantColor': '#72babe', 'videoCover': None}, 'mixes': {}}
DEBUG:streamrip:{'id': 129204258, 'title': 'Frequency Shifter', 'duration': 197, 'replayGain': -11.79, 'peak': 1.0, 'allowStreaming': True, 'streamReady': True, 'streamStartDate': '2020-01-24T00:00:00.000+0000', 'premiumStreamingOnly': False, 'trackNumber': 4, 'volumeNumber': 1, 'version': None, 'popularity': 0, 'copyright': 'Never Say Die Records Ltd', 'url': 'http://www.tidal.com/track/129204258', 'isrc': 'GB7YL2099604', 'editable': False, 'explicit': False, 'audioQuality': 'LOSSLESS', 'audioModes': ['STEREO'], 'artist': {'id': 7418538, 'name': 'Graphyt', 'type': 'MAIN', 'picture': None}, 'artists': [{'id': 7418538, 'name': 'Graphyt', 'type': 'MAIN', 'picture': None}, {'id': 3529150, 'name': 'Pierce', 'type': 'MAIN', 'picture': None}], 'album': {'id': 129204254, 'title': 'Outer Space EP', 'cover': 'cd5d5bc8-ac91-426f-90fc-76ef4920387b', 'vibrantColor': '#72babe', 'videoCover': None}, 'mixes': {}}
Downloading Graphyt - Frequency Shifter


  Stack trace:

  9  .local/lib/python3.10/site-packages/cleo/application.py:314 in run
      312│ 
      313│             try:
    → 314│                 exit_code = self._run(io)
      315│             except Exception as e:
      316│                 if not self._catch_exceptions:

  8  .local/lib/python3.10/site-packages/rip/cli.py:604 in _run
      602│             logger.addHandler(fh)
      603│ 
    → 604│         super()._run(io)
      605│ 
      606│     def create_io(self, input=None, output=None, error_output=None):

  7  .local/lib/python3.10/site-packages/cleo/application.py:409 in _run
      407│                 io.set_input(ArgvInput(argv))
      408│ 
    → 409│         exit_code = self._run_command(command, io)
      410│         self._running_command = None
      411│ 

  6  .local/lib/python3.10/site-packages/cleo/application.py:416 in _run_command
      414│     def _run_command(self, command: Command, io: IO) -> int:
      415│         if self._event_dispatcher is None:
    → 416│             return command.run(io)
      417│ 
      418│         # Bind before the console.command event,

  5  .local/lib/python3.10/site-packages/cleo/commands/base_command.py:118 in run
      116│         io.input.validate()
      117│ 
    → 118│         status_code = self.execute(io)
      119│ 
      120│         if status_code is None:

  4  .local/lib/python3.10/site-packages/cleo/commands/command.py:85 in execute
       83│ 
       84│         try:
    →  85│             return self.handle()
       86│         except KeyboardInterrupt:
       87│             return 1

  3  .local/lib/python3.10/site-packages/rip/cli.py:87 in handle
       85│ 
       86│         if len(core) > 0:
    →  87│             core.download()
       88│         elif not urls and path is None:
       89│             self.line("Must pass arguments. See rip url -h.")

  2  .local/lib/python3.10/site-packages/rip/core.py:316 in download
      314│ 
      315│             try:
    → 316│                 item.download(**arguments)
      317│                 for item_id in item.downloaded_ids:
      318│                     self.db.add([item_id])

  1  .local/lib/python3.10/site-packages/streamrip/media.py:292 in download
       290│             secho(f"Downloading {self!s}\n", bold=True)
       291│ 
    →  292│         self._prepare_download(
       293│             quality=quality,
       294│             parent_folder=parent_folder,

  AttributeError

  'Track' object has no attribute 'folder'

  at .local/lib/python3.10/site-packages/streamrip/media.py:241 in _prepare_download
       237│         self.quality = min(
       238│             kwargs["quality"], self.client.max_quality, self.meta.quality
       239│         )
       240│ 
    →  241│         self.folder = kwargs["parent_folder"] or self.folder
       242│ 
       243│         if not self.part_of_tracklist and kwargs["add_singles_to_folder"]:
       244│             self.folder = os.path.join(
       245│                 self.folder,
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = ""
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false























[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3























[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []























[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = [REDACTED]
country_code = "US"
access_token = "[REDACTED]"
refresh_token = "[REDACTED]"
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = [REDACTED]























[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true























[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""























[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.






















[database.downloads]
enabled = true
path = "/home/slips/.config/streamrip/downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads






















[database.failed_downloads]
enabled = true
path = "/home/slips/.config/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.






















[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.






















[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false























[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true























[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.






















[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false


# Last.fm playlists are downloaded by searching for the titles of the tracks






















[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"























[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"























[misc]
# Metadata to identify this config file. Do not change.
version = "1.7"
```

### Operating System

Artix Linux x86_64

### streamrip version

1.8
