### ISSUE TITLE
[BUG] Error downloading album using both us-en and nl-nl qobuz

### ISSUE THREAD

**Issue by drumttocs8** [nathom/streamrip#267]
### Describe the bug

 Exception

  Error fetching metadata. "No result matching given argument"

  at AppData\Roaming\Python\Python310\site-packages\streamrip\clients.py:306 in _api_get
       302│         epoint = f"{media_type}/get"
       303│
       304│         response, status_code = self._api_request(epoint, params)
       305│         if status_code != 200:
    →  306│             raise Exception(f'Error fetching metadata. "{response["message"]}"')
       307│
       308│         return response
       309│
       310│     def _api_search(self, query: str, media_type: str, limit: int = 500) -> Generator:

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose

### Command Used

```bash
rip url https://www.qobuz.com/nl-nl/album/im-hole-aya/whwjqxpa5v6eb
```

### Debug Traceback

```text
DEBUG:streamrip:Config loaded
DEBUG:streamrip:Parsed urls: [('qobuz', 'album', 'whwjqxpa5v6eb')]
DEBUG:streamrip:Searching for {'id': 'whwjqxpa5v6eb'} in database
DEBUG:streamrip:Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)
Logging into qobuz
DEBUG:streamrip:Raw request signature: trackgetFileUrlformat_id7intentstreamtrack_id195125741641828444.676685810b251c286cfbf64d6b7105f253d9a2e
DEBUG:streamrip:Raw request signature: trackgetFileUrlformat_id7intentstreamtrack_id195125741641828444.6766858979549437fcc4a3faad4867b5cd25dcb
DEBUG:streamrip:Hashed request signature: be7eafffbe2907756db354e7863dce62
DEBUG:streamrip:Hashed request signature: 5f0cc6210246ba1adeac0488f3007eeb
DEBUG:streamrip:{"track_id":19512574,"duration":30,"url":"https:\/\/streaming-std.qobuz.com\/file?eid=19512574&fmt=7&profile=raw&range=20-30&app_id=950096963&etsp=1641832046&hmac=mfbpRe-ff4z-UFdyJngofbE3H20","format_id":7,"mime_type":"audio\/flac","sample":true,"restrictions":[{"code":"UserUnauthenticated"}],"sampling_rate":96,"bit_depth":24}
DEBUG:streamrip:{"status":"error","code":400,"message":"Invalid Request Signature parameter (be7eafffbe2907756db354e7863dce62)"}
DEBUG:streamrip:Test for 10b251c286cfbf64d6b7105f253d9a2e secret didn't work: Invalid app secret from params {'request_ts': 1641828444.6766858, 'request_sig': 'be7eafffbe2907756db354e7863dce62', 'track_id': '19512574', 'format_id': 7, 'intent': 'stream'}
DEBUG:streamrip:{"user":{"id":<redacted>,"publicId":"<redacted>","email":"<redacted>","login":"<redacted>","firstname":null,"lastname":null,"display_name":"<redacted>","country_code":"US","language_code":"en","zone":"US","store":"US-en","country":"US","avatar":"<redacted>","genre":"male","age":<redacted>,"creation_date":"2021-11-27","subscription":{"offer":"studio","periodicity":"monthly","end_date":"2022-01-26","is_canceled":false},"credential":{"id":1257103,"label":"streaming-studio","description":"Abonn\u00e9 Qobuz Studio","parameters":{"lossy_streaming":true,"lossless_streaming":true,"hires_streaming":true,"hires_purchases_streaming":true,"mobile_streaming":true,"offline_streaming":true,"hfp_purchase":false,"included_format_group_ids":[1,2,3,4],"color_scheme":{"logo":"#B8D729"},"label":"Qobuz Studio","short_label":"Studio","source":"subscription"}},"last_update":{"favorite":1637987634,"playlist":1637987634,"purchase":1637987980},"player_settings":{"sonos_audio_format":7},"externals":{}},"user_auth_token":"<redacted>"}
INFO:streamrip:Logged in to Qobuz
DEBUG:streamrip:Logged into Qobuz
DEBUG:streamrip:Qobuz client is ready to use
DEBUG:streamrip:{'downloads': {'folder': '<redacted>', 'source_subdirectories': False, 'concurrency': {'enabled': True, 'max_connections': 3}}, 'qobuz': {'quality': 3, 'download_booklets': True, 'email': 'drumttocs8@yahoo.com', 'password': '24cc799a3ca572801e19157fa9eb0249', 'app_id': '950096963', 'secrets': ['10b251c286cfbf64d6b7105f253d9a2e', '979549437fcc4a3faad4867b5cd25dcb']}, 'tidal': {'quality': 3, 'download_videos': True, 'user_id': '', 'country_code': '', 'access_token': '', 'refresh_token': '', 'token_expiry': ''}, 'deezer': {'quality': 2, 'arl': '', 'use_deezloader': True, 'deezloader_warnings': True}, 'soundcloud': {'quality': 0, 'client_id': '', 'app_version': ''}, 'youtube': {'quality': 0, 'download_videos': False, 'video_downloads_folder': ''}, 'database': {'downloads': {'enabled': True, 'path': 'C:\\Users\\Scott\\AppData\\Local\\streamrip\\streamrip\\downloads.db'}, 'failed_downloads': {'enabled': True, 'path': 'C:\\Users\\Scott\\AppData\\Local\\streamrip\\streamrip\\failed_downloads.db'}}, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'filters': {'extras': False, 'repeats': False, 'non_albums': False, 'features': False, 'non_studio_albums': False, 'non_remaster': False}, 'artwork': {'embed': True, 'size': 'large', 'max_width': -1, 'max_height': -1, 'keep_hires_cover': True}, 'metadata': {'set_playlist_to_album': True, 'new_playlist_tracknumbers': True, 'exclude': []}, 'filepaths': {'add_singles_to_folder': False, 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}', 'restrict_characters': False}, 'lastfm': {'source': 'qobuz', 'fallback_source': 'deezer'}, 'theme': {'progress_bar': 'dainty'}, 'misc': {'version': '1.7'}}
DEBUG:streamrip:Arguments from config: {'restrict_filenames': False, 'parent_folder': 'C:\\Users\\Scott\\StreamripDownloads', 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}', 'embed_cover': True, 'embed_cover_size': 'large', 'keep_hires_cover': True, 'set_playlist_to_album': True, 'stay_temp': False, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'concurrent_downloads': True, 'max_connections': 3, 'new_tracknumbers': True, 'download_videos': True, 'download_booklets': True, 'download_youtube_videos': False, 'youtube_video_downloads_folder': '', 'add_singles_to_folder': False, 'max_artwork_width': -1, 'max_artwork_height': -1, 'exclude_tags': []}
DEBUG:streamrip:Loading metadata
DEBUG:streamrip:request params: {'app_id': '950096963', 'album_id': 'whwjqxpa5v6eb', 'limit': 500, 'offset': 0}
DEBUG:streamrip:{"status":"error","code":404,"message":"No result matching given argument"}

  Stack trace:

  10  AppData\Roaming\Python\Python310\site-packages\cleo\application.py:314 in run
       312│
       313│             try:
     → 314│                 exit_code = self._run(io)
       315│             except Exception as e:
       316│                 if not self._catch_exceptions:

   9  AppData\Roaming\Python\Python310\site-packages\rip\cli.py:604 in _run
       602│             logger.addHandler(fh)
       603│
     → 604│         super()._run(io)
       605│
       606│     def create_io(self, input=None, output=None, error_output=None):

   8  AppData\Roaming\Python\Python310\site-packages\cleo\application.py:409 in _run
       407│                 io.set_input(ArgvInput(argv))
       408│
     → 409│         exit_code = self._run_command(command, io)
       410│         self._running_command = None
       411│

   7  AppData\Roaming\Python\Python310\site-packages\cleo\application.py:416 in _run_command
       414│     def _run_command(self, command: Command, io: IO) -> int:
       415│         if self._event_dispatcher is None:
     → 416│             return command.run(io)
       417│
       418│         # Bind before the console.command event,

   6  AppData\Roaming\Python\Python310\site-packages\cleo\commands\base_command.py:118 in run
       116│         io.input.validate()
       117│
     → 118│         status_code = self.execute(io)
       119│
       120│         if status_code is None:

   5  AppData\Roaming\Python\Python310\site-packages\cleo\commands\command.py:85 in execute
        83│
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

   4  AppData\Roaming\Python\Python310\site-packages\rip\cli.py:87 in handle
        85│
        86│         if len(core) > 0:
     →  87│             core.download()
        88│         elif not urls and path is None:
        89│             self.line("Must pass arguments. See rip url -h.")

   3  AppData\Roaming\Python\Python310\site-packages\rip\core.py:309 in download
       307│                 logger.debug("Loading metadata")
       308│                 try:
     → 309│                     item.load_meta(**arguments)
       310│                 except NonStreamable:
       311│                     self.failed_db.add((item.client.source, item.type, item.id))

   2  AppData\Roaming\Python\Python310\site-packages\streamrip\media.py:1460 in load_meta
       1458│         """Load detailed metadata from API using the id."""
       1459│         assert hasattr(self, "id"), "id must be set to load metadata"
     → 1460│         resp = self.client.get(self.id, media_type="album")
       1461│
       1462│         # update attributes based on response

   1  AppData\Roaming\Python\Python310\site-packages\streamrip\clients.py:200 in get
        198│         :rtype: dict
        199│         """
     →  200│         resp = self._api_get(media_type, item_id=item_id)
        201│         logger.debug(resp)
        202│         return resp

  Exception

  Error fetching metadata. "No result matching given argument"

  at AppData\Roaming\Python\Python310\site-packages\streamrip\clients.py:306 in _api_get
       302│         epoint = f"{media_type}/get"
       303│
       304│         response, status_code = self._api_request(epoint, params)
       305│         if status_code != 200:
    →  306│             raise Exception(f'Error fetching metadata. "{response["message"]}"')
       307│
       308│         return response
       309│
       310│     def _api_search(self, query: str, media_type: str, limit: int = 500) -> Generator:

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "<redacted>"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false


[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3


[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = "<redacted>"
# This is an md5 hash of the plaintext password
password = "<redacted>"
# Do not change
app_id = <redacted>
# Do not change
secrets = <redacted>


[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""


[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true


[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""


[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.

[database.downloads]
enabled = true
path = <redacted>

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads

[database.failed_downloads]
enabled = true
path = <redacted>

# Convert tracks to a codec after downloading them.

[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.

[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false


[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.

[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false


# Last.fm playlists are downloaded by searching for the titles of the tracks

[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"


[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"


[misc]
# Metadata to identify this config file. Do not change.
version = "1.7"
```

### Operating System

WIndows 10

### streamrip version

1.8
