### ISSUE TITLE
[BUG] [Errno 2] No such file or directory: 'tput' on Android Termux

### ISSUE THREAD

**Issue by thevigilante0** [nathom/streamrip#290]
### Describe the bug

FileNotFoundError when I use streamrip search command on Android Termux

`FileNotFoundError

  [Errno 2] No such file or directory: 'tput'

  at /data/data/com.termux/files/usr/lib/python3.10/subprocess.py:1840 in _execute_child
      1836│                     else:
      1837│                         err_filename = orig_executable
      1838│                     if errno_num != 0:
      1839│                         err_msg = os.strerror(errno_num)
    → 1840│                     raise child_exception_type(errno_num, err_msg, err_filename)
      1841│                 raise child_exception_type(err_msg)
      1842│
      1843│
      1844│         def _handle_exitstatus(self, sts,`

### Command Used

```bash
rip search --type artist --source qobuz 'bob dylan'
```

### Debug Traceback

```text
`Stack trace:	

  16  /data/data/com.termux/files/usr/lib/python3.10/site-packages/cleo/application.py:330 in run
       328│
       329│             try:
     → 330│                 exit_code = self._run(io)
       331│             except Exception as e:
       332│                 if not self._catch_exceptions:

  15  /data/data/com.termux/files/usr/lib/python3.10/site-packages/rip/cli.py:759 in _run
       757│             logger.addHandler(fh)
       758│
     → 759│         super()._run(io)
       760│
       761│     def create_io(self, input=None, output=None, error_output=None):

  14  /data/data/com.termux/files/usr/lib/python3.10/site-packages/cleo/application.py:425 in _run
       423│                 io.set_input(ArgvInput(argv))
       424│
     → 425│         exit_code = self._run_command(command, io)
       426│         self._running_command = None
       427│

  13  /data/data/com.termux/files/usr/lib/python3.10/site-packages/cleo/application.py:432 in _run_command
       430│     def _run_command(self, command: Command, io: IO) -> int:
       431│         if self._event_dispatcher is None:
     → 432│             return command.run(io)
       433│
       434│         # Bind before the console.command event,

  12  /data/data/com.termux/files/usr/lib/python3.10/site-packages/cleo/commands/base_command.py:118 in run
       116│         io.input.validate()
       117│
     → 118│         status_code = self.execute(io)
       119│
       120│         if status_code is None:

  11  /data/data/com.termux/files/usr/lib/python3.10/site-packages/cleo/commands/command.py:85 in execute
        83│
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

  10  /data/data/com.termux/files/usr/lib/python3.10/site-packages/rip/cli.py:202 in handle
       200│         core = RipCore(config)
       201│
     → 202│         if core.interactive_search(query, source, type):
       203│             core.download()
       204│         else:

   9  /data/data/com.termux/files/usr/lib/python3.10/site-packages/rip/core.py:781 in interactive_search
       779│             from simple_term_menu import TerminalMenu
       780│
     → 781│             menu = TerminalMenu(
       782│                 map(title, enumerate(results)),
       783│                 preview_command=from_title,

   8  /data/data/com.termux/files/usr/lib/python3.10/site-packages/simple_term_menu.py:720 in __init__
        718│         )
        719│         self._selection = self.Selection(len(self._menu_entries), self._preselected_indices)
     →  720│         self._viewport = self.Viewport(
        721│             len(self._menu_entries),
        722│             len(self._title_lines),

   7  /data/data/com.termux/files/usr/lib/python3.10/site-packages/simple_term_menu.py:380 in __init__
        378│             self._status_bar_lines_count = status_bar_lines_count
        379│             # Use the property setter since it has some more logic
     →  380│             self.preview_lines_count = preview_lines_count
        381│             self.search_lines_count = search_lines_count
        382│             self._num_lines = self._calculate_num_lines()

   6  /data/data/com.termux/files/usr/lib/python3.10/site-packages/simple_term_menu.py:460 in preview_lines_count
        458│             self._preview_lines_count = min(
        459│                 value if value >= 3 else 0,
     →  460│                 TerminalMenu._num_lines()
        461│                 - self._title_lines_count
        462│                 - self._status_bar_lines_count

   5  /data/data/com.termux/files/usr/lib/python3.10/site-packages/simple_term_menu.py:838 in _num_lines
        836│     @classmethod
        837│     def _num_lines(self) -> int:
     →  838│         return int(self._query_terminfo_database("lines"))
        839│
        840│     @classmethod

   4  /data/data/com.termux/files/usr/lib/python3.10/site-packages/simple_term_menu.py:829 in _query_terminfo_database
        827│             capname = codename
        828│         try:
     →  829│             return subprocess.check_output(["tput"] + capname.split(), universal_newlines=True)
        830│         except subprocess.CalledProcessError as e:
        831│             # The return code 1 indicates a missing terminal capability

   3  /data/data/com.termux/files/usr/lib/python3.10/subprocess.py:420 in check_output
        418│         kwargs['input'] = empty
        419│
     →  420│     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        421│                **kwargs).stdout
        422│

   2  /data/data/com.termux/files/usr/lib/python3.10/subprocess.py:501 in run
        499│         kwargs['stderr'] = PIPE
        500│
     →  501│     with Popen(*popenargs, **kwargs) as process:
        502│         try:
        503│             stdout, stderr = process.communicate(input, timeout=timeout)

   1  /data/data/com.termux/files/usr/lib/python3.10/subprocess.py:966 in __init__
        964│                             encoding=encoding, errors=errors)
        965│
     →  966│             self._execute_child(args, executable, preexec_fn, close_fds,
        967│                                 pass_fds, cwd, env,
        968│                                 startupinfo, creationflags, shell,

  FileNotFoundError

  [Errno 2] No such file or directory: 'tput'

  at /data/data/com.termux/files/usr/lib/python3.10/subprocess.py:1840 in _execute_child
      1836│                     else:
      1837│                         err_filename = orig_executable
      1838│                     if errno_num != 0:
      1839│                         err_msg = os.strerror(errno_num)
    → 1840│                     raise child_exception_type(errno_num, err_msg, err_filename)
      1841│                 raise child_exception_type(err_msg)
      1842│
      1843│
      1844│         def _handle_exitstatus(self, sts,

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose`
```

### Config File

```toml
`[downloads]
# Folder where tracks are downloaded to
folder = "/storage/emulated/0/Music/Streamrip"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false



[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3



[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 4
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = "950096963"
# Do not change
secrets = ["10b251c286cfbf64d6b7105f253d9a2e", "979549437fcc4a3faad4867b5cd25dcb"]



[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""



[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true



[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""



[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.


[database.downloads]
enabled = true
path = "/data/data/com.termux/files/home/.config/streamrip/downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads


[database.failed_downloads]
enabled = true
path = "/data/data/com.termux/files/home/.config/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.


[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.


[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false



[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true



[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.


[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false


# Last.fm playlists are downloaded by searching for the titles of the tracks


[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"



[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"



[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.2"`
```

### Operating System

Android

### streamrip version

1.9.3

### Screenshots and recordings

![Screenshot_20220129-125812_1](https://user-images.githubusercontent.com/98141969/151650299-de6fd721-9672-4409-a90a-15d75edb3dac.png)
