### ISSUE TITLE
[BUG] <File Name Too Long>

### ISSUE THREAD

**Issue by groove1027** [nathom/streamrip#301]
### Describe the bug

PJH:~ pjh$ rip url https://play.qobuz.com/album/z2x7y769ej57b
Logging into qobuz

  OSError

  [Errno 63] File name too long: '/Volumes/2TB/FLAC/Qobuz/Montserrat Caball, Giacomo Puccini - [2021] GRANDI VOCI MONTSERRAT CABALL Una collana dedicata con registrazioni originali Decca e Deutsche Grammophon rimasterizzate con le tecniche pi moderne che ne garantiscono eccellenza tecnica e artistica [16B-44.1kHz]'

  at /usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py:225 in makedirs
       221│             cdir = bytes(curdir, 'ASCII')
       222│         if tail == cdir:           # xxx/newdir/. exists if xxx/newdir exists
       223│             return
       224│     try:
    →  225│         mkdir(name, mode)
       226│     except OSError:
       227│         # Cannot rely on checking for EEXIST, since the operating system
       228│         # could give priority to other errors like EACCES or EROFS
       229│         if not exist_ok or not path.isdir(name):

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
PJH:~ pjh$ 

![스크린샷 2022-02-15 오전 1 40 02](https://user-images.githubusercontent.com/99673139/153906898-bb7dbacd-2c28-4001-8d10-9150edc49e10.png)

### Command Used

```bash
rip url https://play.qobuz.com/album/z2x7y769ej57b
```

### Debug Traceback

```text
Stack trace:

  10  /usr/local/lib/python3.9/site-packages/cleo/application.py:330 in run
        exit_code = self._run(io)

   9  /usr/local/lib/python3.9/site-packages/rip/cli.py:759 in _run
        super()._run(io)

   8  /usr/local/lib/python3.9/site-packages/cleo/application.py:425 in _run
        exit_code = self._run_command(command, io)

   7  /usr/local/lib/python3.9/site-packages/cleo/application.py:432 in _run_command
        return command.run(io)

   6  /usr/local/lib/python3.9/site-packages/cleo/commands/base_command.py:118 in run
        status_code = self.execute(io)

   5  /usr/local/lib/python3.9/site-packages/cleo/commands/command.py:85 in execute
        return self.handle()

   4  /usr/local/lib/python3.9/site-packages/rip/cli.py:124 in handle
        core.download()

   3  /usr/local/lib/python3.9/site-packages/rip/core.py:313 in download
        item.download(**arguments)

   2  /usr/local/lib/python3.9/site-packages/streamrip/media.py:1157 in download
        self._prepare_download(**kwargs)

   1  /usr/local/lib/python3.9/site-packages/streamrip/media.py:1518 in _prepare_download
        os.makedirs(self.folder, exist_ok=True)

  OSError

  [Errno 63] File name too long: '/Volumes/2TB/FLAC/Qobuz/Montserrat Caballé, Giacomo Puccini - [2021] GRANDI VOCI MONTSERRAT CABALLÉ Una collana dedicata con registrazioni originali Decca e Deutsche Grammophon rimasterizzate con le tecniche più moderne che ne garantiscono eccellenza tecnica e artistica [16B-44.1kHz]'

  at /usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py:225 in makedirs
       221│             cdir = bytes(curdir, 'ASCII')
       222│         if tail == cdir:           # xxx/newdir/. exists if xxx/newdir exists
       223│             return
       224│     try:
    →  225│         mkdir(name, mode)
       226│     except OSError:
       227│         # Cannot rely on checking for EEXIST, since the operating system
       228│         # could give priority to other errors like EACCES or EROFS
       229│         if not exist_ok or not path.isdir(name):

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/Volumes/2TB/FLAC"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = true


[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially.
# If you are converting the tracks, or have fast internet, this will
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 6


[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 4
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = [""]


[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""


[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true


[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""


[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.

[database.downloads]
enabled = true
path = "/Users/pjh/Library/Application Support/streamrip/downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads

[database.failed_downloads]
enabled = true
path = "/Users/pjh/Library/Application Support/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.

[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this.
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.

[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = true
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = true
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false


[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding.
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name.
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.

[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - [{year}] {title} [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber} - {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false


# Last.fm playlists are downloaded by searching for the titles of the tracks

[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for
# on this one.
fallback_source = "deezer"


[theme]
# Options: "dainty" or "plain"
progress_bar = "plain"


[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.2"
```

### Operating System

mac OS

### streamrip version

1.9.3
