### ISSUE TITLE
[BUG] Album download fails, maybe because album doesn't have covert art

### ISSUE THREAD

**Issue by jjnilton** [nathom/streamrip#302]
### Describe the bug

Program crashes when trying to download an album without cover art. 

### Command Used

```bash
$ rip url https://listen.tidal.com/album/79811273
```

### Debug Traceback

```text
user@host:~$ rip -vvv url https://tidal.com/browse/track/79811274
DEBUG:streamrip:Config loaded
DEBUG:streamrip:Parsed urls: [('tidal', 'track', '79811274')]
DEBUG:streamrip:Searching for {'id': '79811274'} in database
DEBUG:streamrip:Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)
DEBUG:streamrip:{'quality': 1, 'download_videos': True, 'user_id': user_id, 'country_code': 'BR', 'access_token': 'access_token', 'refresh_token': 'refresh_token', 'token_expiry': token_expiry}
DEBUG:streamrip:Logging in with access token
Logged into Tidal
DEBUG:streamrip:Config saved: /home/user/.config/streamrip/config.toml
DEBUG:streamrip:{'id': '79811274'}
DEBUG:streamrip:{'downloads': {'folder': '/home/user/Downloads/StreamripDownloads', 'source_subdirectories': False, 'concurrency': {'enabled': True, 'max_connections': 3}}, 'qobuz': {'quality': 3, 'download_booklets': True, 'email': '', 'password': '', 'app_id': '', 'secrets': []}, 'tidal': {'quality': 1, 'download_videos': True, 'user_id': user_id, 'country_code': 'BR', 'access_token': 'access_token', 'refresh_token': 'refresh_token', 'token_expiry': token_expire}, 'deezer': {'quality': 2, 'arl': '', 'use_deezloader': True, 'deezloader_warnings': True}, 'soundcloud': {'quality': 0, 'client_id': '', 'app_version': ''}, 'youtube': {'quality': 0, 'download_videos': False, 'video_downloads_folder': ''}, 'database': {'downloads': {'enabled': True, 'path': '/home/user/.config/streamrip/downloads.db'}, 'failed_downloads': {'enabled': True, 'path': '/home/user/.config/streamrip/failed_downloads.db'}}, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'filters': {'extras': False, 'repeats': False, 'non_albums': False, 'features': False, 'non_studio_albums': False, 'non_remaster': False}, 'artwork': {'embed': True, 'size': 'large', 'max_width': -1, 'max_height': -1, 'keep_hires_cover': True}, 'metadata': {'set_playlist_to_album': True, 'new_playlist_tracknumbers': True, 'exclude': []}, 'filepaths': {'add_singles_to_folder': False, 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}{explicit}', 'restrict_characters': False}, 'lastfm': {'source': 'qobuz', 'fallback_source': 'deezer'}, 'theme': {'progress_bar': 'dainty'}, 'misc': {'version': '1.9.2'}}
DEBUG:streamrip:Arguments from config: {'restrict_filenames': False, 'parent_folder': '/home/user/Downloads/StreamripDownloads', 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}{explicit}', 'embed_cover': True, 'embed_cover_size': 'large', 'keep_hires_cover': True, 'set_playlist_to_album': True, 'stay_temp': False, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'concurrent_downloads': True, 'max_connections': 3, 'new_tracknumbers': True, 'download_videos': True, 'download_booklets': True, 'download_youtube_videos': False, 'youtube_video_downloads_folder': '', 'add_singles_to_folder': False, 'max_artwork_width': -1, 'max_artwork_height': -1, 'exclude_tags': []}
DEBUG:streamrip:Loading metadata
DEBUG:streamrip:{'id': 79811274, 'title': 'Stand up Tragedy', 'duration': 225, 'replayGain': -12.36, 'peak': 0.930846, 'allowStreaming': True, 'streamReady': True, 'streamStartDate': '2018-03-16T00:00:00.000+0000', 'premiumStreamingOnly': False, 'trackNumber': 1, 'volumeNumber': 1, 'version': None, 'popularity': 2, 'copyright': '(P) 2018 The Fratellis under exclusive licence to Cooking Vinyl Limited', 'url': 'http://www.tidal.com/track/79811274', 'isrc': 'GBCEJ1700369', 'editable': False, 'explicit': False, 'audioQuality': 'LOSSLESS', 'audioModes': ['STEREO'], 'artist': {'id': 17029, 'name': 'The Fratellis', 'type': 'MAIN', 'picture': '051fa461-07a4-460e-ba8d-72aa12531173'}, 'artists': [{'id': 17029, 'name': 'The Fratellis', 'type': 'MAIN', 'picture': '051fa461-07a4-460e-ba8d-72aa12531173'}], 'album': {'id': 79811273, 'title': 'In Your Own Sweet Time', 'cover': None, 'vibrantColor': None, 'videoCover': None}, 'mixes': {'TRACK_MIX': '001620b4ac04744f7ee7f3fcb75720'}}
DEBUG:streamrip:{'id': 79811274, 'title': 'Stand up Tragedy', 'duration': 225, 'replayGain': -12.36, 'peak': 0.930846, 'allowStreaming': True, 'streamReady': True, 'streamStartDate': '2018-03-16T00:00:00.000+0000', 'premiumStreamingOnly': False, 'trackNumber': 1, 'volumeNumber': 1, 'version': None, 'popularity': 2, 'copyright': '(P) 2018 The Fratellis under exclusive licence to Cooking Vinyl Limited', 'url': 'http://www.tidal.com/track/79811274', 'isrc': 'GBCEJ1700369', 'editable': False, 'explicit': False, 'audioQuality': 'LOSSLESS', 'audioModes': ['STEREO'], 'artist': {'id': 17029, 'name': 'The Fratellis', 'type': 'MAIN', 'picture': '051fa461-07a4-460e-ba8d-72aa12531173'}, 'artists': [{'id': 17029, 'name': 'The Fratellis', 'type': 'MAIN', 'picture': '051fa461-07a4-460e-ba8d-72aa12531173'}], 'album': {'id': 79811273, 'title': 'In Your Own Sweet Time', 'cover': None, 'vibrantColor': None, 'videoCover': None}, 'mixes': {'TRACK_MIX': '001620b4ac04744f7ee7f3fcb75720'}}

  Stack trace:

  14  .local/lib/python3.9/site-packages/cleo/application.py:330 in run
       328│
       329│             try:
     → 330│                 exit_code = self._run(io)
       331│             except Exception as e:
       332│                 if not self._catch_exceptions:

  13  .local/lib/python3.9/site-packages/rip/cli.py:759 in _run
       757│             logger.addHandler(fh)
       758│
     → 759│         super()._run(io)
       760│
       761│     def create_io(self, input=None, output=None, error_output=None):

  12  .local/lib/python3.9/site-packages/cleo/application.py:425 in _run
       423│                 io.set_input(ArgvInput(argv))
       424│
     → 425│         exit_code = self._run_command(command, io)
       426│         self._running_command = None
       427│

  11  .local/lib/python3.9/site-packages/cleo/application.py:432 in _run_command
       430│     def _run_command(self, command: Command, io: IO) -> int:
       431│         if self._event_dispatcher is None:
     → 432│             return command.run(io)
       433│
       434│         # Bind before the console.command event,

  10  .local/lib/python3.9/site-packages/cleo/commands/base_command.py:118 in run
       116│         io.input.validate()
       117│
     → 118│         status_code = self.execute(io)
       119│
       120│         if status_code is None:

   9  .local/lib/python3.9/site-packages/cleo/commands/command.py:85 in execute
        83│
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

   8  .local/lib/python3.9/site-packages/rip/cli.py:124 in handle
       122│
       123│         if len(core) > 0:
     → 124│             core.download()
       125│         elif not urls and path is None:
       126│             self.line("Must pass arguments. See rip url -h.")

   7  .local/lib/python3.9/site-packages/rip/core.py:306 in download
       304│                 logger.debug("Loading metadata")
       305│                 try:
     → 306│                     item.load_meta(**arguments)
       307│                 except NonStreamable:
       308│                     self.failed_db.add((item.client.source, item.type, item.id))

   6  .local/lib/python3.9/site-packages/streamrip/media.py:211 in load_meta
        209│
        210│         self.resp = self.client.get(self.id, media_type="track")
     →  211│         self.meta = TrackMetadata(
        212│             track=self.resp, source=source
        213│         )  # meta dict -> TrackMetadata object

   5  .local/lib/python3.9/site-packages/streamrip/metadata.py:105 in __init__
       103│             self.update(track)
       104│         elif track is not None:
     → 105│             self.add_track_meta(track)
       106│
       107│         if isinstance(album, TrackMetadata):

   4  .local/lib/python3.9/site-packages/streamrip/metadata.py:266 in add_track_meta
       264│
       265│         if track.get("album"):
     → 266│             self.add_album_meta(track["album"])
       267│
       268│     def _mod_title(self, version: Optional[str], work: Optional[str]):

   3  .local/lib/python3.9/site-packages/streamrip/metadata.py:185 in add_album_meta
       183│             self.explicit = resp.get("explicit", False)
       184│             # 80, 160, 320, 640, 1280
     → 185│             self.cover_urls = get_cover_urls(resp, self.__source)
       186│             self.streamable = resp.get("allowStreaming", False)
       187│             self.id = resp.get("id")

   2  .local/lib/python3.9/site-packages/streamrip/utils.py:340 in get_cover_urls
       338│     if source == "tidal":
       339│         uuid = resp["cover"]
     → 340│         return {
       341│             sk: tidal_cover_url(uuid, size)
       342│             for sk, size in zip(COVER_SIZES, (160, 320, 640, 1280))

   1  .local/lib/python3.9/site-packages/streamrip/utils.py:341 in <dictcomp>
       339│         uuid = resp["cover"]
       340│         return {
     → 341│             sk: tidal_cover_url(uuid, size)
       342│             for sk, size in zip(COVER_SIZES, (160, 320, 640, 1280))
       343│         }

  AttributeError

  'NoneType' object has no attribute 'replace'

  at .local/lib/python3.9/site-packages/streamrip/utils.py:183 in tidal_cover_url
      179│     possibles = (80, 160, 320, 640, 1280)
      180│     assert size in possibles, f"size must be in {possibles}"
      181│     #print(TIDAL_COVER_URL, uuid, size)
      182│     #try:
    → 183│     return TIDAL_COVER_URL.format(uuid=uuid.replace("-", "/"), height=size, width=size)
      184│     #except:
      185│     #    return 'https://listen.tidal.com/2ced20dc482bb13b21966310c6bde8d7.svg'
      186│
      187│ def init_log(path: Optional[str] = None, level: str = "DEBUG"):
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/home/user/Downloads/StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 1
# This will download videos included in Video Albums.
download_videos = false

# Do not change any of the fields below
user_id = user_id
country_code = "BR"
access_token = "token"
refresh_token = "token"
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = expiry

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.

[database.downloads]
enabled = true
path = "/home/user/.config/streamrip/downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads

[database.failed_downloads]
enabled = true
path = "/home/user/.config/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.

[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.

[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true

[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.

[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false

# Last.fm playlists are downloaded by searching for the titles of the tracks

[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"

[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"

[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.2"
```

### Operating System

Debian 11 on WSL (Windows 10)

### streamrip version

1.9.4

### Additional context

Thanks for sharing the free software.

Tried to surround this with a try/except, but then I got the following message:

> Unable to stream The Fratellis - Stand up Tragedy. Message: File not found.

```
return TIDAL_COVER_URL.format(uuid=uuid.replace("-", "/"), height=size, width=size)
```
