### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Freddy-Mann** [nathom/streamrip#307]
### Describe the bug

I am able to enter my arl into the application, but when I use the "rip url URL" feature, it always fails. 

### Command Used

```bash
rip url https://www.deezer.com/us/album/66647162
```

### Debug Traceback

```text
DEBUG:streamrip:Config loaded
DEBUG:streamrip:Parsed urls: [('deezer', 'album', '66647162')]
DEBUG:streamrip:Searching for {'id': '66647162'} in database
DEBUG:streamrip:Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)
DEBUG:streamrip:{'downloads': {'folder': 'C:\\Users\\foifo\\StreamripDownloads', 'source_subdirectories': False, 'concurrency': {'enabled': True, 'max_connections': 3}}, 'qobuz': {'quality': 3, 'download_booklets': True, 'email': '', 'password': '', 'app_id': '', 'secrets': []}, 'tidal': {'quality': 3, 'download_videos': True, 'user_id': '', 'country_code': '', 'access_token': '', 'refresh_token': '', 'token_expiry': ''}, 'deezer': {'quality': 2, 'arl': '', 'use_deezloader': True, 'deezloader_warnings': True}, 'soundcloud': {'quality': 0, 'client_id': '', 'app_version': ''}, 'youtube': {'quality': 0, 'download_videos': False, 'video_downloads_folder': ''}, 'database': {'downloads': {'enabled': True, 'path': 'C:\\Users\\foifo\\AppData\\Local\\streamrip\\streamrip\\downloads.db'}, 'failed_downloads': {'enabled': True, 'path': 'C:\\Users\\foifo\\AppData\\Local\\streamrip\\streamrip\\failed_downloads.db'}}, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'filters': {'extras': False, 'repeats': False, 'non_albums': False, 'features': False, 'non_studio_albums': False, 'non_remaster': False}, 'artwork': {'embed': True, 'size': 'large', 'max_width': -1, 'max_height': -1, 'keep_hires_cover': True}, 'metadata': {'set_playlist_to_album': True, 'new_playlist_tracknumbers': True, 'exclude': []}, 'filepaths': {'add_singles_to_folder': False, 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}{explicit}', 'restrict_characters': False}, 'lastfm': {'source': 'qobuz', 'fallback_source': 'deezer'}, 'theme': {'progress_bar': 'dainty'}, 'misc': {'version': '1.9.2'}}
DEBUG:streamrip:Arguments from config: {'restrict_filenames': False, 'parent_folder': 'C:\\Users\\foifo\\StreamripDownloads', 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}{explicit}', 'embed_cover': True, 'embed_cover_size': 'large', 'keep_hires_cover': True, 'set_playlist_to_album': True, 'stay_temp': False, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'concurrent_downloads': True, 'max_connections': 3, 'new_tracknumbers': True, 'download_videos': True, 'download_booklets': True, 'download_youtube_videos': False, 'youtube_video_downloads_folder': '', 'add_singles_to_folder': False, 'max_artwork_width': -1, 'max_artwork_height': -1, 'exclude_tags': []}
DEBUG:streamrip:Loading metadata

  StopIteration

  0

  at AppData\Local\Programs\Python\Python310\lib\json\decoder.py:353 in raw_decode
      349│         have extraneous data at the end.
      350│
      351│         """
      352│         try:
    → 353│             obj, end = self.scan_once(s, idx)
      354│         except StopIteration as err:
      355│             raise JSONDecodeError("Expecting value", s, err.value) from None
      356│         return obj, end
      357│

The following error occurred when trying to handle this error:


  Stack trace:

  3  AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py:910 in json
      908│
      909│         try:
    → 910│             return complexjson.loads(self.text, **kwargs)
      911│         except JSONDecodeError as e:
      912│             # Catch JSON-related errors and raise as requests.JSONDecodeError

  2  AppData\Local\Programs\Python\Python310\lib\json\__init__.py:346 in loads
      344│             parse_int is None and parse_float is None and
      345│             parse_constant is None and object_pairs_hook is None and not kw):
    → 346│         return _default_decoder.decode(s)
      347│     if cls is None:
      348│         cls = JSONDecoder

  1  AppData\Local\Programs\Python\Python310\lib\json\decoder.py:337 in decode
      335│
      336│         """
    → 337│         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      338│         end = _w(s, end).end()
      339│         if end != len(s):

  JSONDecodeError

  Expecting value: line 1 column 1 (char 0)

  at AppData\Local\Programs\Python\Python310\lib\json\decoder.py:355 in raw_decode
      351│         """
      352│         try:
      353│             obj, end = self.scan_once(s, idx)
      354│         except StopIteration as err:
    → 355│             raise JSONDecodeError("Expecting value", s, err.value) from None
      356│         return obj, end
      357│

The following error occurred when trying to handle this error:


  Stack trace:

  12  AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\application.py:330 in run
       328│
       329│             try:
     → 330│                 exit_code = self._run(io)
       331│             except Exception as e:
       332│                 if not self._catch_exceptions:

  11  AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py:759 in _run
       757│             logger.addHandler(fh)
       758│
     → 759│         super()._run(io)
       760│
       761│     def create_io(self, input=None, output=None, error_output=None):

  10  AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\application.py:425 in _run
       423│                 io.set_input(ArgvInput(argv))
       424│
     → 425│         exit_code = self._run_command(command, io)
       426│         self._running_command = None
       427│

   9  AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\application.py:432 in _run_command
       430│     def _run_command(self, command: Command, io: IO) -> int:
       431│         if self._event_dispatcher is None:
     → 432│             return command.run(io)
       433│
       434│         # Bind before the console.command event,

   8  AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\commands\base_command.py:118 in run
       116│         io.input.validate()
       117│
     → 118│         status_code = self.execute(io)
       119│
       120│         if status_code is None:

   7  AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\commands\command.py:85 in execute
        83│
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

   6  AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py:124 in handle
       122│
       123│         if len(core) > 0:
     → 124│             core.download()
       125│         elif not urls and path is None:
       126│             self.line("Must pass arguments. See rip url -h.")

   5  AppData\Local\Programs\Python\Python310\lib\site-packages\rip\core.py:306 in download
       304│                 logger.debug("Loading metadata")
       305│                 try:
     → 306│                     item.load_meta(**arguments)
       307│                 except NonStreamable:
       308│                     self.failed_db.add((item.client.source, item.type, item.id))

   4  AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\media.py:1466 in load_meta
       1464│         """Load detailed metadata from API using the id."""
       1465│         assert hasattr(self, "id"), "id must be set to load metadata"
     → 1466│         resp = self.client.get(self.id, media_type="album")
       1467│
       1468│         # update attributes based on response

   3  AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\clients.py:528 in get
        526│
        527│         get_item = GET_FUNCTIONS[media_type]
     →  528│         item = get_item(meta_id)
        529│         if media_type in ("album", "playlist"):
        530│             tracks = getattr(self.client.api, f"get_{media_type}_tracks")(

   2  AppData\Local\Programs\Python\Python310\lib\site-packages\deezer\api.py:60 in get_album
        58│
        59│     def get_album(self, album_id):
     →  60│         return self.api_call(f'album/{str(album_id)}')
        61│
        62│     def get_album_by_UPC(self, upc):

   1  AppData\Local\Programs\Python\Python310\lib\site-packages\deezer\api.py:39 in api_call
        37│                 headers=self.http_headers,
        38│                 timeout=30
     →  39│             ).json()
        40│         except (requests.ConnectionError, requests.Timeout):
        41│             sleep(2)

  JSONDecodeError

  [Errno Expecting value] HTTP_BAD_REQUEST: 0

  at AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py:917 in json
      913│             # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
      914│             if is_py2: # e is a ValueError
      915│                 raise RequestsJSONDecodeError(e.message)
      916│             else:
    → 917│                 raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
      918│
      919│     @property
      920│     def links(self):
      921│         """Returns the parsed header links of the response, if any."""
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "C:\\Users\\foifo\\StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false



[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3



[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []







[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""







[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true







[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""



[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.


[database.downloads]
enabled = true
path = "C:\\Users\\foifo\\AppData\\Local\\streamrip\\streamrip\\downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads


[database.failed_downloads]
enabled = true
path = "C:\\Users\\foifo\\AppData\\Local\\streamrip\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.


[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.


[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false



[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true



[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.


[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false


# Last.fm playlists are downloaded by searching for the titles of the tracks


[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"



[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"



[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.2"
```

### Operating System

windows

### streamrip version

1.9.4
