### ISSUE TITLE
[BUG] can't download last.fm playlist from youtube

### ISSUE THREAD

**Issue by costaverde** [nathom/streamrip#321]
### Describe the bug

Error when rip a last.fm playlist from youtube:

### Command Used

```bash
rip lastfm --source=youtube https://www.last.fm/user/es456789/playlists/12348193
```

### Debug Traceback

```text
Fetching playlist at https://www.last.fm/user/es456789/playlists/12348193

  KeyError

  'youtube'

  at anaconda3/envs/py38/lib/python3.8/site-packages/rip/core.py:354 in get_client
      350│         :param source:
      351│         :type source: str
      352│         :rtype: Client
      353│         """
    → 354│         client = self.clients[source]
      355│         if not client.logged_in:
      356│             try:
      357│                 self.login(client)
      358│             except DeezloaderFallback:
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/home/****/StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false


[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially.
# If you are converting the tracks, or have fast internet, this will
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3


[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = "d41d8cd98f00b204e9800998ecf8427e"
# Do not change
app_id = ""
# Do not change
secrets = []


[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""


[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true


[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""


[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.

[database.downloads]
enabled = true
path = "/home/****/.config/streamrip/downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads

Warning: program returned non-zero exit code #1
```

### Operating System

linux debian

### streamrip version

1.9.4
