### ISSUE TITLE
[BUG] Cannot open the database file AND no such table exists

### ISSUE THREAD

**Issue by jeffward01** [nathom/streamrip#326]
### Describe the bug

![image](https://user-images.githubusercontent.com/12589359/167184903-7779b9bc-5cd5-4518-84cf-e4fa92cff30a.png)

![image](https://user-images.githubusercontent.com/12589359/167184440-1d3f44ba-5395-44f4-a891-fa8bec1bc4ea.png)

I ran into many issues when installing Streamrip due to conflicting Python versions. When I removed all the versions and got Streamrip 'running', I could not search modules because `pick` was missing.  I performed `pip install pick` and then it was working.

When I went to my first download, I received the error `No such table exists` and the download failed.  

Then when I ran `rip db --list failed-downloads` I ran into the second error that the database can not be opened.

**OS**

* Windows 10
* Python: Version 3.10.4 (Latest)

### Command Used

```bash
rip search "Mac Miller"
rip db --list failed-downloads
```

### Debug Traceback

```text
C:\Users\Jeff-Office-PC# rip db --list failed-downloads -vvv
DEBUG:streamrip:Config loaded

  Stack trace:

  8  C:\Python310\lib\site-packages\cleo\application.py:330 in run
      328│
      329│             try:
    → 330│                 exit_code = self._run(io)
      331│             except Exception as e:
      332│                 if not self._catch_exceptions:

  7  C:\Python310\lib\site-packages\rip\cli.py:759 in _run
      757│             logger.addHandler(fh)
      758│
    → 759│         super()._run(io)
      760│
      761│     def create_io(self, input=None, output=None, error_output=None):

  6  C:\Python310\lib\site-packages\cleo\application.py:425 in _run
      423│                 io.set_input(ArgvInput(argv))
      424│
    → 425│         exit_code = self._run_command(command, io)
      426│         self._running_command = None
      427│

  5  C:\Python310\lib\site-packages\cleo\application.py:432 in _run_command
      430│     def _run_command(self, command: Command, io: IO) -> int:
      431│         if self._event_dispatcher is None:
    → 432│             return command.run(io)
      433│
      434│         # Bind before the console.command event,

  4  C:\Python310\lib\site-packages\cleo\commands\base_command.py:118 in run
      116│         io.input.validate()
      117│
    → 118│         status_code = self.execute(io)
      119│
      120│         if status_code is None:

  3  C:\Python310\lib\site-packages\cleo\commands\command.py:85 in execute
       83│
       84│         try:
    →  85│             return self.handle()
       86│         except KeyboardInterrupt:
       87│             return 1

  2  C:\Python310\lib\site-packages\rip\cli.py:703 in handle
      701│
      702│         if self.option("list"):
    → 703│             getattr(self, f"_render_{db_name}")()
      704│
      705│         if self.option("reset"):

  1  C:\Python310\lib\site-packages\rip\cli.py:735 in _render_failed_downloads
      733│         id_table.set_header_title("Failed Downloads")
      734│         id_table.set_headers(["Source", "Media Type", "ID"])
    → 735│         id_table.add_rows(iter(self._db))
      736│         id_table.render()
      737│

  OperationalError

  unable to open database file

  at C:\Python310\lib\site-packages\rip\db.py:157 in __iter__
      153│         """Iterate through the rows of the table."""
      154│         if self.is_dummy:
      155│             return ()
      156│
    → 157│         with sqlite3.connect(self.path) as conn:
      158│             return conn.execute(f"SELECT * FROM {self.name}")
      159│
      160│     def reset(self):
      161│         """Delete the database file."""

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose


========
========

C:\Users\Jeff-Office-PC# rip search "Mac Miller"
Logging into qobuz


Downloading Self Care (Album)

Downloading cover art (large)
Cover |████████████████████████████████████████████████████████████████████████████████████████| 00:00 left at 841kB/s

Track 01 |████████████████████████████████████████████████████████████████████████████████████| 00:00 left at 12.8MB/s

  OperationalError

  no such table: downloads

  at C:\Python310\lib\site-packages\rip\db.py:129 in add
      125│         logger.debug("Items to add: %s", items)
      126│
      127│         with sqlite3.connect(self.path) as conn:
      128│             try:
    → 129│                 conn.execute(command, tuple(items))
      130│             except sqlite3.IntegrityError as e:
      131│                 # tried to insert an item that was already there
      132│                 logger.debug(e)
      133│

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "M:\\Music\\_streamrip\\_successfulDownloads\\_musicDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false




[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3




[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 4
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = "<removed-for-obvious-reasons>"
# This is an md5 hash of the plaintext password
password = "<removed-for-obvious-reasons>"
# Do not change
app_id = "<removed-for-obvious-reasons>"
# Do not change
secrets = ["<removed-for-obvious-reasons>", "<removed-for-obvious-reasons>"]




[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id =  <removed-for-obvious-reasons>
country_code = "US"
access_token =  "<removed-for-obvious-reasons>"
refresh_token = "<removed-for-obvious-reasons>"
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = 1652395995.1165123




[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true




[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""




[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "M:\\Music\\_streamrip\\_successfulDownloads\\_ytVideoDownloads"

# This stores a list of item IDs so that repeats are not downloaded.



[database.downloads]
enabled = true
path = "M:\\Music\\_streamrip\\.archive-success-streamrip"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads



[database.failed_downloads]
enabled = true
path = "M:\\Music\\_streamrip\\_failedDownloads"

# Convert tracks to a codec after downloading them.



[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "FLAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 96000 
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 1411

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.



[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false




[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true




[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.



[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false


# Last.fm playlists are downloaded by searching for the titles of the tracks



[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "tidal"




[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"




[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.2"
```

### Operating System

Windows 10

### streamrip version

1.9.4

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/12589359/167184903-7779b9bc-5cd5-4518-84cf-e4fa92cff30a.png)

![image](https://user-images.githubusercontent.com/12589359/167184440-1d3f44ba-5395-44f4-a891-fa8bec1bc4ea.png)
