### ISSUE TITLE
[BUG] the config.toml file is ignored by rip.exe on Windows 11

### ISSUE THREAD

**Issue by dajhorn** [nathom/streamrip#349]
### Describe the bug

The `config.toml` file is completely ignored when streamrip is running natively on Windows 11.

### Command Used

```bash
rip.exe config -vvv --reset
```

### Debug Traceback

```text
PS C:\Users\dajhorn> rip.exe config -vvv --path
DEBUG:streamrip:Config loaded
C:\Users\dajhorn\AppData\Local\streamrip\streamrip\config.toml

PS C:\Users\dajhorn> rip.exe config -vvv --reset
DEBUG:streamrip:Config loaded
DEBUG:streamrip:Config loaded
DEBUG:streamrip:Config saved: C:\Users\dajhorn\AppData\Local\streamrip\streamrip\config.toml
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "D:\Music"

# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 1

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = false
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.
[database.downloads]
enabled = true
path = ""

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
[database.failed_downloads]
enabled = true
path = ""

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "original"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = false

[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = false
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false

# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate", "container", "id", and "albumcomposer"
folder_format = "{albumartist}/{title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"

# Available keys: "tracknumber", "artist", "albumartist", "composer", "title", and "albumcomposer"
track_format = "{tracknumber} {title}{explicit}"

# Only allow printable ASCII characters in filenames.
restrict_characters = false


# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "deezer"
# If no results were found with the primary source, the item is searched for 
# on this one.
#fallback_source = ""

[theme]
# Options: "dainty" or "plain"
progress_bar = "plain"

[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.2"
```

### Operating System

Windows 11 Version 21H2 Build 22000.778

### streamrip version

1.9.5

### Additional context

I installed streamrip on Windows 11 by doing this:

1. Install Visual Studio 2022 with the _Desktop development with C++_ and _Python development_ components.
2. Install Python 3.9 from the Windows Store, which is the version supported by VS 2022.
3. Open "Developer PowerShell for VS 2022".
4. Run `pip install streamrip`.
5. Add `%USERPROFILE%\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts` to the PATH, which is where `pip` installs user packages.

Visual Studio is required because `pip` uses `cl.exe` to compile things in the `wheel` and `cchardetect` packages.

Expected behavior:

1a. `rip.exe` warns if the `config.toml` file does not exist.
1b. `rip.exe` loads options from the `config.toml` file.
1c. `rip.exe` writes the `config.toml` file when invoked with `config --reset`.

Actual behavior:

2a. `rip.exe` does not warn if the `config.toml` file does not exist.
2b. `rip.exe` ignores everything in `config.toml` if it does exist.
2c. `rip.exe` does not write anything to `config.toml` when invoked with `config --reset`.

The `appdirs` module is returning file names that seem good for Windows 11, but any I/O to `config.toml` seems to be a no-op.
