### ISSUE TITLE
[BUG] <streamrip refuses to download anything from tidal in mp3>

### ISSUE THREAD

**Issue by Aeiron2** [nathom/streamrip#357]
### Describe the bug

ffmpeg is installed and in the path
/ I've done all the commands but no matter what I try (and I tried alot) it just downloads it into AAC (m4a)

its either flac or M4A. Am I doing something wrong?

### Command Used

```bash
rip url --codec mp3 https://tidal.com/browse/track/22248418
rip url --ignore-db --max-quality 1 -- https://tidal.com/browse/track/22248418
rip url --ignore-db -convert mp3 -- https://tidal.com/browse/track/22248418
```

### Debug Traceback

```text
see top
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "D:\\StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false
```

### Operating System

windows 10 x64 bit

### streamrip version

Rip (version 1.9.5)
