### ISSUE TITLE
[BUG] SOLVED: InvalidUnicodeValueError for most commands. Playing with download folder in config.toml doesn't fix it.

### ISSUE THREAD

**Issue by SharpDecision** [nathom/streamrip#367]
### Describe the bug

I cannot type any rip command that seems to involve the config file. I've looked at the closed issues on this bug already and have tried the solution of fixing the download folder path, making the '\'s raw characters with '\\' and leaving the download path blank. I've also done a clean reinstall of streamrip and python 3.10. None of these have fixed the problem

### Command Used

```bash
rip config
rip discover
rip repair
rip search
rip url
```

### Debug Traceback

```text
C:\Users\me>rip config --open -vvv

  Stack trace:

  18  AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\application.py:330 in run
       328│
       329│             try:
     → 330│                 exit_code = self._run(io)
       331│             except Exception as e:
       332│                 if not self._catch_exceptions:

  17  AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py:760 in _run
       758│             logger.addHandler(fh)
       759│
     → 760│         super()._run(io)
       761│
       762│     def create_io(self, input=None, output=None, error_output=None):

  16  AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\application.py:425 in _run
       423│                 io.set_input(ArgvInput(argv))
       424│
     → 425│         exit_code = self._run_command(command, io)
       426│         self._running_command = None
       427│

  15  AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\application.py:432 in _run_command
       430│     def _run_command(self, command: Command, io: IO) -> int:
       431│         if self._event_dispatcher is None:
     → 432│             return command.run(io)
       433│
       434│         # Bind before the console.command event,

  14  AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\commands\base_command.py:118 in run
       116│         io.input.validate()
       117│
     → 118│         status_code = self.execute(io)
       119│
       120│         if status_code is None:

  13  AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\commands\command.py:85 in execute
        83│
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

  12  AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py:420 in handle
       418│         from .constants import CONFIG_DIR, CONFIG_PATH
       419│
     → 420│         self._config = Config()
       421│
       422│         if self.option("path"):

  11  AppData\Local\Programs\Python\Python310\lib\site-packages\rip\config.py:57 in __init__
        55│
        56│         if os.path.isfile(self._path):
     →  57│             self.load()
        58│             if self.file["misc"]["version"] != self.defaults["misc"]["version"]:
        59│                 secho(

  10  AppData\Local\Programs\Python\Python310\lib\site-packages\rip\config.py:136 in load
       134│         """Load infomation from the config files, making a deepcopy."""
       135│         with open(self._path) as cfg:
     → 136│             for k, v in tomlkit.loads(cfg.read().strip()).items():
       137│                 self.file[k] = v
       138│                 if hasattr(v, "copy"):

   9  AppData\Local\Programs\Python\Python310\lib\site-packages\tomlkit\api.py:34 in loads
        32│     Alias for parse().
        33│     """
     →  34│     return parse(string)
        35│
        36│

   8  AppData\Local\Programs\Python\Python310\lib\site-packages\tomlkit\api.py:51 in parse
        49│     Parses a string into a TOMLDocument.
        50│     """
     →  51│     return Parser(string).parse()
        52│
        53│

   7  AppData\Local\Programs\Python\Python310\lib\site-packages\tomlkit\parser.py:160 in parse
        158│
        159│         while not self.end():
     →  160│             key, value = self._parse_table()
        161│             if isinstance(value, Table) and value.is_aot_element():
        162│                 # This is just the first table in an AoT. Parse the rest of the array

   6  AppData\Local\Programs\Python\Python310\lib\site-packages\tomlkit\parser.py:1154 in _parse_table
       1152│
       1153│         while not self.end():
     → 1154│             item = self._parse_item()
       1155│             if item:
       1156│                 _key, item = item

   5  AppData\Local\Programs\Python\Python310\lib\site-packages\tomlkit\parser.py:306 in _parse_item
        304│                     break
        305│
     →  306│         return self._parse_key_value(True)
        307│
        308│     def _parse_comment_trail(self):  # type: () -> Tuple[str, str, str]

   4  AppData\Local\Programs\Python\Python310\lib\site-packages\tomlkit\parser.py:397 in _parse_key_value
        395│
        396│         # Value
     →  397│         val = self._parse_value()
        398│         # Comment
        399│         if parse_comment:

   3  AppData\Local\Programs\Python\Python310\lib\site-packages\tomlkit\parser.py:561 in _parse_value
        559│
        560│         if c == StringType.SLB.value:
     →  561│             return self._parse_basic_string()
        562│         elif c == StringType.SLL.value:
        563│             return self._parse_literal_string()

   2  AppData\Local\Programs\Python\Python310\lib\site-packages\tomlkit\parser.py:854 in _parse_basic_string
        852│     def _parse_basic_string(self):  # type: () -> String
        853│         with self._state:
     →  854│             return self._parse_string(StringType.SLB)
        855│
        856│     def _parse_escaped_char(self, multiline):

   1  AppData\Local\Programs\Python\Python310\lib\site-packages\tomlkit\parser.py:990 in _parse_string
        988│                 # attempt to parse the current char as an escaped value, an exception
        989│                 # is raised if this fails
     →  990│                 value += self._parse_escaped_char(delim.is_multiline())
        991│
        992│                 # no longer escaped

  InvalidUnicodeValueError

  Invalid unicode value at line 3 col 13

  at AppData\Local\Programs\Python\Python310\lib\site-packages\tomlkit\parser.py:897 in _parse_escaped_char
       893│                 self.inc_n(len(ue) + 1)
       894│
       895│                 return u
       896│
    →  897│             raise self.parse_error(InvalidUnicodeValueError)
       898│
       899│         raise self.parse_error(InvalidCharInStringError, self._current)
       900│
       901│     def _parse_string(self, delim):  # type: (StringType) -> String

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose

C:\Users\me>
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "C:\\Users\\me\\Music\\streamrip downloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.
[database.downloads]
enabled = true
path = ""

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
[database.failed_downloads]
enabled = true
path = ""

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true

[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false


# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"

[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"

[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.2"
```

### Operating System

Windows

### streamrip version

1.9.5
