### ISSUE TITLE
[BUG] Error installing on Linux

### ISSUE THREAD

**Issue by rodrigosplopes06** [nathom/streamrip#380]
### Describe the bug

I try to install on Linux on Python 3.10.8, but I get an error.
I saw other bug report saying that is a problem related to "cchardet", but I can't see an alternative that works, and I can't downgrade Python due to system dependencies and other programs I have.

neither pip3 nor pip work for me

And I can't put debug traceback with "-vvv" because it will generate a huge text and GitHub doesn't let me sumbit

Is there a way to ignore "cchardet" (and replace to other module) ?

Sorry for my bad English :)

### Command Used

```bash
pip install streamrip --upgrade
```

### Debug Traceback

```text
Defaulting to user installation because normal site-packages is not writeable
Collecting streamrip
  Using cached streamrip-1.9.5-py3-none-any.whl (84 kB)
Requirement already satisfied: Pillow<10.0.0,>=9.0.0 in /usr/lib64/python3.10/site-packages (from streamrip) (9.1.0)
Requirement already satisfied: m3u8<0.10.0,>=0.9.0 in ./.local/lib/python3.10/site-packages (from streamrip) (0.9.0)
Requirement already satisfied: click<9.0.0,>=8.0.1 in /usr/lib/python3.10/site-packages (from streamrip) (8.0.4)
Requirement already satisfied: mutagen<2.0.0,>=1.45.1 in /usr/local/lib/python3.10/site-packages (from streamrip) (1.46.0)
Collecting cchardet<3.0.0,>=2.1.7
  Using cached cchardet-2.1.7.tar.gz (653 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tomlkit<0.8.0,>=0.7.2 in ./.local/lib/python3.10/site-packages (from streamrip) (0.7.2)
Collecting appdirs<2.0.0,>=1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting aiofiles<0.8.0,>=0.7.0
  Using cached aiofiles-0.7.0-py3-none-any.whl (13 kB)
Requirement already satisfied: pathvalidate<3.0.0,>=2.4.1 in ./.local/lib/python3.10/site-packages (from streamrip) (2.5.2)
Requirement already satisfied: pycryptodomex<4.0.0,>=3.10.1 in ./.local/lib/python3.10/site-packages (from streamrip) (3.16.0)
Collecting aiohttp<4.0.0,>=3.7.4
  Using cached aiohttp-3.8.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
Requirement already satisfied: tqdm<5.0.0,>=4.61.1 in ./.local/lib/python3.10/site-packages (from streamrip) (4.64.1)
Requirement already satisfied: cleo==1.0.0a4 in ./.local/lib/python3.10/site-packages (from streamrip) (1.0.0a4)
Requirement already satisfied: deezer-py==1.3.6 in ./.local/lib/python3.10/site-packages (from streamrip) (1.3.6)
Collecting aiodns<4.0.0,>=3.0.0
  Using cached aiodns-3.0.0-py3-none-any.whl (5.0 kB)
Requirement already satisfied: requests<3.0.0,>=2.25.1 in /usr/lib/python3.10/site-packages (from streamrip) (2.27.1)
Requirement already satisfied: simple-term-menu<2.0.0,>=1.2.1 in ./.local/lib/python3.10/site-packages (from streamrip) (1.5.2)
Requirement already satisfied: pylev<2.0.0,>=1.3.0 in ./.local/lib/python3.10/site-packages (from cleo==1.0.0a4->streamrip) (1.4.0)
Requirement already satisfied: crashtest<0.4.0,>=0.3.1 in ./.local/lib/python3.10/site-packages (from cleo==1.0.0a4->streamrip) (0.3.1)
Requirement already satisfied: pycares>=4.0.0 in ./.local/lib/python3.10/site-packages (from aiodns<4.0.0,>=3.0.0->streamrip) (4.2.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.7.4->streamrip) (4.0.2)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.7.4->streamrip) (2.0.11)
Requirement already satisfied: frozenlist>=1.1.1 in ./.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.7.4->streamrip) (1.3.3)
Requirement already satisfied: yarl<2.0,>=1.0 in ./.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.7.4->streamrip) (1.8.2)
Requirement already satisfied: aiosignal>=1.1.2 in ./.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.7.4->streamrip) (1.3.1)
Requirement already satisfied: multidict<7.0,>=4.5 in ./.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.7.4->streamrip) (6.0.3)
Requirement already satisfied: attrs>=17.3.0 in ./.local/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.7.4->streamrip) (22.1.0)
Requirement already satisfied: iso8601 in ./.local/lib/python3.10/site-packages (from m3u8<0.10.0,>=0.9.0->streamrip) (1.1.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.10/site-packages (from requests<3.0.0,>=2.25.1->streamrip) (1.26.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.10/site-packages (from requests<3.0.0,>=2.25.1->streamrip) (3.3)
Requirement already satisfied: cffi>=1.5.0 in /usr/lib64/python3.10/site-packages (from pycares>=4.0.0->aiodns<4.0.0,>=3.0.0->streamrip) (1.15.0)
Requirement already satisfied: pycparser in /usr/lib/python3.10/site-packages (from cffi>=1.5.0->pycares>=4.0.0->aiodns<4.0.0,>=3.0.0->streamrip) (2.20)
Requirement already satisfied: ply==3.11 in /usr/lib/python3.10/site-packages (from pycparser->cffi>=1.5.0->pycares>=4.0.0->aiodns<4.0.0,>=3.0.0->streamrip) (3.11)
Building wheels for collected packages: cchardet
  Building wheel for cchardet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5si3pwh1/cchardet_75e76b090d924ae6a28478b9c2cbcee8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5si3pwh1/cchardet_75e76b090d924ae6a28478b9c2cbcee8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-w3s07ev7
       cwd: /tmp/pip-install-5si3pwh1/cchardet_75e76b090d924ae6a28478b9c2cbcee8/
  Complete output (22 lines):
  cythonize: ['src/cchardet/_cchardet.pyx']
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.10
  creating build/lib.linux-x86_64-3.10/cchardet
  copying src/cchardet/version.py -> build/lib.linux-x86_64-3.10/cchardet
  copying src/cchardet/__init__.py -> build/lib.linux-x86_64-3.10/cchardet
  running build_ext
  building 'cchardet._cchardet' extension
  creating build/temp.linux-x86_64-3.10
  creating build/temp.linux-x86_64-3.10/src
  creating build/temp.linux-x86_64-3.10/src/cchardet
  creating build/temp.linux-x86_64-3.10/src/ext
  creating build/temp.linux-x86_64-3.10/src/ext/uchardet
  creating build/temp.linux-x86_64-3.10/src/ext/uchardet/src
  creating build/temp.linux-x86_64-3.10/src/ext/uchardet/src/LangModels
  gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/ext/uchardet/src -I/usr/include/python3.10 -c src/cchardet/_cchardet.cpp -o build/temp.linux-x86_64-3.10/src/cchardet/_cchardet.o
  gcc: fatal error: cannot execute ‘cc1plus’: execvp: Ficheiro ou pasta inexistente
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for cchardet
  Running setup.py clean for cchardet
Failed to build cchardet
Installing collected packages: cchardet, appdirs, aiohttp, aiofiles, aiodns, streamrip
    Running setup.py install for cchardet ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5si3pwh1/cchardet_75e76b090d924ae6a28478b9c2cbcee8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5si3pwh1/cchardet_75e76b090d924ae6a28478b9c2cbcee8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-o_yco8no/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/{my user name}/.local/include/python3.10/cchardet
         cwd: /tmp/pip-install-5si3pwh1/cchardet_75e76b090d924ae6a28478b9c2cbcee8/
    Complete output (24 lines):
    cythonize: ['src/cchardet/_cchardet.pyx']
    running install
    /usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.10
    creating build/lib.linux-x86_64-3.10/cchardet
    copying src/cchardet/version.py -> build/lib.linux-x86_64-3.10/cchardet
    copying src/cchardet/__init__.py -> build/lib.linux-x86_64-3.10/cchardet
    running build_ext
    building 'cchardet._cchardet' extension
    creating build/temp.linux-x86_64-3.10
    creating build/temp.linux-x86_64-3.10/src
    creating build/temp.linux-x86_64-3.10/src/cchardet
    creating build/temp.linux-x86_64-3.10/src/ext
    creating build/temp.linux-x86_64-3.10/src/ext/uchardet
    creating build/temp.linux-x86_64-3.10/src/ext/uchardet/src
    creating build/temp.linux-x86_64-3.10/src/ext/uchardet/src/LangModels
    gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/ext/uchardet/src -I/usr/include/python3.10 -c src/cchardet/_cchardet.cpp -o build/temp.linux-x86_64-3.10/src/cchardet/_cchardet.o
    gcc: fatal error: cannot execute ‘cc1plus’: execvp: Ficheiro ou pasta inexistente
    compilation terminated.
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5si3pwh1/cchardet_75e76b090d924ae6a28478b9c2cbcee8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5si3pwh1/cchardet_75e76b090d924ae6a28478b9c2cbcee8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-o_yco8no/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/{my user name}/.local/include/python3.10/cchardet Check the logs for full command output.
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = ""
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.
[database.downloads]
enabled = true
path = ""

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
[database.failed_downloads]
enabled = true
path = ""

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true

[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false


# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"

[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"

[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.2"
```

### Operating System

Linux

### streamrip version

1.9.5
