### ISSUE TITLE
[BUG] <Some commands add blank lines to config.toml>

### ISSUE THREAD

**Issue by fuzxi** [nathom/streamrip#408]
### Describe the bug

This is very odd, but running some commands, such as `rip search` and `rip url`, adds one empty line immediately before each [Bracketed heading] in the config.toml file, for a total of 16 lines each time the command is run. `search` does this even if nothing is downloaded. `url` does not do this if the specified item is already in the downloads database and the download is skipped.

### Command Used

```bash
$ wc -l .config/streamrip/config.toml
> 174 .config/streamrip/config.toml

174 lines to begin with.

rip url https://tidal.com/track/35691379

$ wc -l .config/streamrip/config.toml
>190 .config/streamrip/config.toml

190 lines afterwards.
```

### Debug Traceback

```text
$ rip url https://tidal.com/track/35691379 -vvv

Config loaded
executing CREATE TABLE downloads (id TEXT UNIQUE NOT NULL)
Parsed urls: [('tidal', 'track', '35691379')]
Searching for {'id': '35691379'} in database
Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)
{'quality': 2, 'download_videos': False, 'user_id': redacted, 'country_code': 'US', 'access_token': 'redacted>
Logging in with access token
Config saved: /home/user/.config/streamrip/config.toml
{'id': '35691379'}
{'downloads': {'folder': '/data/media/streamrip', 'source_subdirectories': False, 'concurrency': {'enabled': True, 'max_connections': 3}}, 'qobuz': {'quality': 3, 'download_booklets': True, '>
Arguments from config: {'restrict_filenames': False, 'truncate_filenames': True, 'parent_folder': '/data/media/streamrip', 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{b>
Loading metadata
{'id': 35691379, 'title': "Enjoy Yourself (It's Later Than You Think)", 'duration': 156, 'replayGain': -4.32, 'peak': 0.841611, 'allowStreaming': True, 'streamReady': True, 'streamStartDate':>
{'id': 35691379, 'title': "Enjoy Yourself (It's Later Than You Think)", 'duration': 156, 'replayGain': -4.32, 'peak': 0.841611, 'allowStreaming': True, 'streamReady': True, 'streamStartDate':>
Formatter keys: {albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]
'albumartist'
None
'title'
Enjoy Yourself (It's Later Than You Think)
1
'year'
None
'container'
FLAC
1
'bit_depth'
16
2
'sampling_rate'
44.1
1
Track meta formatter {'tracknumber': 7, 'artist': 'Louis Prima', 'albumartist': None, 'composer': None, 'title': "Enjoy Yourself (It's Later Than You Think)", 'albumcomposer': None, 'explicit>
Formatter keys: {tracknumber}. {artist} - {title}
'tracknumber'
7
2
'artist'
Louis Prima
1
'title'
Enjoy Yourself (It's Later Than You Think)
1
Formatted path: /data/media/streamrip/Unknown - Enjoy Yourself (It's Later Than You Think) (Unknown) [FLAC] [16B-44.1kHz]/07. Louis Prima - Enjoy Yourself (It's Later Than You Think).flac
Downloading cover from https://resources.tidal.com/images/5f05a750/7b94/45fa/854d/f7387d1e4ac6/640x640.jpg
{'mimeType': 'audio/flac', 'codecs': 'flac', 'encryptionType': 'NONE', 'urls': ['https://sp-pr-cf.audio.tidal.com/mediatracks/CAEaKRInMDU3YjQ0ODRmYjRiN2U1MDU1Mzg2ODIwMzUyYTk5YmFfNjEubXA0/0.fl>
Downloadable URL found: https://sp-pr-cf.audio.tidal.com/mediatracks/CAEaKRInMDU3YjQ0ODRmYjRiN2U1MDU1Mzg2ODIwMzUyYTk5YmFfNjEubXA0/0.flac?Expires=1681380853&Signature=aAPfY51ScFrVah~zmp6LRRlIL>
Downloaded: /data/media/streamrip/Unknown - Enjoy Yourself (It's Later Than You Think) (Unknown) [FLAC] [16B-44.1kHz]/07. Louis Prima - Enjoy Yourself (It's Later Than You Think).flac -> /dat>
Executing INSERT INTO downloads (id) VALUES (?)
Items to add: ('35691379',)
Tagging file with FLAC container
Excluded tags: set()
attr: title
Adding tag TITLE: Enjoy Yourself (It's Later Than You Think)
Setting TITLE tag to Enjoy Yourself (It's Later Than You Think)
attr: artist
Adding tag ARTIST: Louis Prima
Setting ARTIST tag to Louis Prima
attr: album
Adding tag ALBUM: Beepin' & Boppin'
Setting ALBUM tag to Beepin' & Boppin'
attr: albumartist
attr: composer
attr: year
attr: comment
attr: description
attr: purchase_date
attr: grouping
attr: genre
attr: lyrics
attr: encoder
attr: copyright
attr: compilation
attr: cover
attr: tracknumber
Adding tag TRACKNUMBER: 07
Setting TRACKNUMBER tag to 07
attr: discnumber
Adding tag DISCNUMBER: 01
Setting DISCNUMBER tag to 01
attr: tracktotal
Adding tag TRACKTOTAL: 01
Setting TRACKTOTAL tag to 01
attr: disctotal
Adding tag DISCTOTAL: 01
Setting DISCTOTAL tag to 01
attr: date
```

### Config File

```toml
Before running `rip url https://tidal.com/track/35691379`:
[downloads]
# Folder where tracks are downloaded to
folder = "/data/media/streamrip"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true
email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 2
# This will download videos included in Video Albums.
download_videos = false

# Do not change any of the fields below
user_id = redacted
country_code = "US"
access_token = "redacted"
refresh_token = "redacted"
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = redacted

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.
[database.downloads]
enabled = true
path = "/home/user/.config/streamrip/downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
[database.failed_downloads]
enabled = true
path = "/home/user/.config/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true

[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = true
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than 120 characters
# Setting this to false may cause downloads to fail on some systems
truncate = true


# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"

[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"

[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.6"

After running `rip url https://tidal.com/track/35691379`:
[downloads]
# Folder where tracks are downloaded to
folder = "/data/media/streamrip"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false


[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3


[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true
email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []


[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 2
# This will download videos included in Video Albums.
download_videos = false

# Do not change any of the fields below
user_id = redacted
country_code = "US"
access_token = "redacted"
refresh_token = "redacted"
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = redacted


[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true


[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""


[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.

[database.downloads]
enabled = true
path = "/home/user/.config/streamrip/downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads

[database.failed_downloads]
enabled = true
path = "/home/user/.config/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.

[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.

[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false


[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.

[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = true
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than 120 characters
# Setting this to false may cause downloads to fail on some systems
truncate = true


# Last.fm playlists are downloaded by searching for the titles of the tracks

[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"


[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"


[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.6"
```

### Operating System

Linux

### streamrip version

1.9.7
