### ISSUE TITLE
[BUG] error when trying to add ARL

### ISSUE THREAD

**Issue by I-G-1-1** [nathom/streamrip#417]
### Describe the bug

streamrip was working the past week. This week instead when I try to add a new ARL I get the error attached below.
I also tried to manually add the arl to the config file and then use "rip url [theulr] --max-quality 2" but it didn't work.
Is this a bug or am I doing something wrong? thanks

### Command Used

```bash
rip config --deezer
```

### Debug Traceback

```text
rip config --deezer

DEBUG:streamrip:Config loaded
Follow the instructions at https://github.com/nathom/streamrip/wiki/Finding-your-Deezer-ARL-Cookie
Paste your ARL here:  [ REDACTED ]
Validating arl...

  StopIteration

  0

  at /usr/local/lib/python3.8/json/decoder.py:353 in raw_decode
      349│         have extraneous data at the end.
      350│ 
      351│         """
      352│         try:
    → 353│             obj, end = self.scan_once(s, idx)
      354│         except StopIteration as err:
      355│             raise JSONDecodeError("Expecting value", s, err.value) from None
      356│         return obj, end
      357│ 

The following error occurred when trying to handle this error:


  Stack trace:

  3  /srv/streamrip/lib/python3.8/site-packages/requests/models.py:971 in json
       969│ 
       970│         try:
    →  971│             return complexjson.loads(self.text, **kwargs)
       972│         except JSONDecodeError as e:
       973│             # Catch JSON-related errors and raise as requests.JSONDecodeError

  2  /usr/local/lib/python3.8/json/__init__.py:357 in loads
      355│             parse_int is None and parse_float is None and
      356│             parse_constant is None and object_pairs_hook is None and not kw):
    → 357│         return _default_decoder.decode(s)
      358│     if cls is None:
      359│         cls = JSONDecoder

  1  /usr/local/lib/python3.8/json/decoder.py:337 in decode
      335│ 
      336│         """
    → 337│         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      338│         end = _w(s, end).end()
      339│         if end != len(s):

  JSONDecodeError

  Expecting value: line 1 column 1 (char 0)

  at /usr/local/lib/python3.8/json/decoder.py:355 in raw_decode
      351│         """
      352│         try:
      353│             obj, end = self.scan_once(s, idx)
      354│         except StopIteration as err:
    → 355│             raise JSONDecodeError("Expecting value", s, err.value) from None
      356│         return obj, end
      357│ 

The following error occurred when trying to handle this error:


  Stack trace:

  11  /srv/streamrip/lib/python3.8/site-packages/cleo/application.py:330 in run
       328│ 
       329│             try:
     → 330│                 exit_code = self._run(io)
       331│             except Exception as e:
       332│                 if not self._catch_exceptions:

  10  /srv/streamrip/lib/python3.8/site-packages/rip/cli.py:762 in _run
       760│             logger.addHandler(fh)
       761│ 
     → 762│         super()._run(io)
       763│ 
       764│     def create_io(self, input=None, output=None, error_output=None):

   9  /srv/streamrip/lib/python3.8/site-packages/cleo/application.py:425 in _run
       423│                 io.set_input(ArgvInput(argv))
       424│ 
     → 425│         exit_code = self._run_command(command, io)
       426│         self._running_command = None
       427│ 

   8  /srv/streamrip/lib/python3.8/site-packages/cleo/application.py:432 in _run_command
       430│     def _run_command(self, command: Command, io: IO) -> int:
       431│         if self._event_dispatcher is None:
     → 432│             return command.run(io)
       433│ 
       434│         # Bind before the console.command event,

   7  /srv/streamrip/lib/python3.8/site-packages/cleo/commands/base_command.py:118 in run
       116│         io.input.validate()
       117│ 
     → 118│         status_code = self.execute(io)
       119│ 
       120│         if status_code is None:

   6  /srv/streamrip/lib/python3.8/site-packages/cleo/commands/command.py:85 in execute
        83│ 
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

   5  /srv/streamrip/lib/python3.8/site-packages/rip/cli.py:470 in handle
       468│ 
       469│             try:
     → 470│                 DeezerClient().login(arl=given_arl)
       471│                 self._config.file["deezer"]["arl"] = given_arl
       472│                 self._config.save()

   4  /srv/streamrip/lib/python3.8/site-packages/streamrip/clients.py:506 in login
        504│             raise MissingCredentials
        505│ 
     →  506│         success = self.client.login_via_arl(arl)
        507│         if not success:
        508│             raise AuthenticationError

   3  /srv/streamrip/lib/python3.8/site-packages/deezer/__init__.py:98 in login_via_arl
        96│         )
        97│         self.session.cookies.set_cookie(cookie_obj)
     →  98│         user_data = self.gw.get_user_data()
        99│         # Check if user logged in
       100│         if not user_data or user_data and len(user_data.keys()) == 0:

   2  /srv/streamrip/lib/python3.8/site-packages/deezer/gw.py:72 in get_user_data
        70│ 
        71│     def get_user_data(self):
     →  72│         return self.api_call('deezer.getUserData')
        73│ 
        74│     def get_user_profile_page(self, user_id, tab, limit=10):

   1  /srv/streamrip/lib/python3.8/site-packages/deezer/gw.py:42 in api_call
        40│         p.update(params)
        41│         try:
     →  42│             result_json = self.session.post(
        43│                 "http://www.deezer.com/ajax/gw-light.php",
        44│                 params=p,

  JSONDecodeError

  Expecting value: line 1 column 1 (char 0)

  at /srv/streamrip/lib/python3.8/site-packages/requests/models.py:975 in json
       971│             return complexjson.loads(self.text, **kwargs)
       972│         except JSONDecodeError as e:
       973│             # Catch JSON-related errors and raise as requests.JSONDecodeError
       974│             # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
    →  975│             raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
       976│ 
       977│     @property
       978│     def links(self):
       979│         """Returns the parsed header links of the response, if any."""

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose



rip url [ REDACTED ] --max-quality 2 -vvv

DEBUG:streamrip:Config loaded
Extracting IDs from Deezer dynamic link. Use urls of the form https://www.deezer.com/{country}/{type}/{id} for faster processing.

  Stack trace:

  10  /srv/streamrip/lib/python3.8/site-packages/cleo/application.py:330 in run
       328│ 
       329│             try:
     → 330│                 exit_code = self._run(io)
       331│             except Exception as e:
       332│                 if not self._catch_exceptions:

   9  /srv/streamrip/lib/python3.8/site-packages/rip/cli.py:762 in _run
       760│             logger.addHandler(fh)
       761│ 
     → 762│         super()._run(io)
       763│ 
       764│     def create_io(self, input=None, output=None, error_output=None):

   8  /srv/streamrip/lib/python3.8/site-packages/cleo/application.py:425 in _run
       423│                 io.set_input(ArgvInput(argv))
       424│ 
     → 425│         exit_code = self._run_command(command, io)
       426│         self._running_command = None
       427│ 

   7  /srv/streamrip/lib/python3.8/site-packages/cleo/application.py:432 in _run_command
       430│     def _run_command(self, command: Command, io: IO) -> int:
       431│         if self._event_dispatcher is None:
     → 432│             return command.run(io)
       433│ 
       434│         # Bind before the console.command event,

   6  /srv/streamrip/lib/python3.8/site-packages/cleo/commands/base_command.py:118 in run
       116│         io.input.validate()
       117│ 
     → 118│         status_code = self.execute(io)
       119│ 
       120│         if status_code is None:

   5  /srv/streamrip/lib/python3.8/site-packages/cleo/commands/command.py:85 in execute
        83│ 
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

   4  /srv/streamrip/lib/python3.8/site-packages/rip/cli.py:122 in handle
       120│ 
       121│         if urls:
     → 122│             core.handle_urls(";".join(urls))
       123│ 
       124│         if len(core) > 0:

   3  /srv/streamrip/lib/python3.8/site-packages/rip/core.py:163 in handle_urls
       161│             self.extend(YoutubeVideo(u) for u in youtube_urls)
       162│ 
     → 163│         parsed = self.parse_urls(url)
       164│         if not parsed and len(self) == 0:
       165│             if "last.fm" in url:

   2  /srv/streamrip/lib/python3.8/site-packages/rip/core.py:463 in parse_urls
       461│                 fg="yellow",
       462│             )
     → 463│             parsed.extend(
       464│                 ("deezer", *extract_deezer_dynamic_link(url)) for url in dynamic_urls
       465│             )

   1  /srv/streamrip/lib/python3.8/site-packages/rip/core.py:464 in <genexpr>
       462│             )
       463│             parsed.extend(
     → 464│                 ("deezer", *extract_deezer_dynamic_link(url)) for url in dynamic_urls
       465│             )
       466│ 

  Exception

  Unable to extract Deezer dynamic link.

  at /srv/streamrip/lib/python3.8/site-packages/rip/utils.py:49 in extract_deezer_dynamic_link
       45│     match = deezer_id_link_regex.search(r.text)
       46│     if match:
       47│         return match.group(1), match.group(2)
       48│ 
    →  49│     raise Exception("Unable to extract Deezer dynamic link.")
       50│ 

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "[ REDACTED ]"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false



[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3



[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []



[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""



[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = "[ REDACTED ]"
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true



[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""



[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.


[database.downloads]
enabled = true
path = "/home/pi/.config/streamrip/downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads


[database.failed_downloads]
enabled = true
path = "/home/pi/.config/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.


[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.


[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false



[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true



[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.


[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than 120 characters
# Setting this to false may cause downloads to fail on some systems
truncate = true


# Last.fm playlists are downloaded by searching for the titles of the tracks


[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"



[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"



[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.6"
```

### Operating System

Debian 9.13

### streamrip version

Rip (version 1.9.7)

### Additional context

streamrip installed in a python venv using python3.8 (tried also with python3.9 with same result)
