### ISSUE TITLE
[BUG] TIDAL Login error

### ISSUE THREAD

**Issue by Batmanx86** [nathom/streamrip#446]
### Describe the bug

Unable to login TIDAL on beta version and token also not refreshes automatically, when filled TIDAL credentials manually in config.toml

### Command Used

```bash
rip config --tidal
```

### Debug Traceback

```text
DEBUG:streamrip:Config loaded
DEBUG:streamrip:Logging in as a new user

  Stack trace:

  10  /usr/local/lib/python3.10/dist-packages/cleo/application.py:330 in run
       328│ 
       329│             try:
     → 330│                 exit_code = self._run(io)
       331│             except Exception as e:
       332│                 if not self._catch_exceptions:

   9  /usr/local/lib/python3.10/dist-packages/rip/cli.py:754 in _run
       752│             logger.addHandler(fh)
       753│ 
     → 754│         super()._run(io)
       755│ 
       756│     def create_io(self, input=None, output=None, error_output=None):

   8  /usr/local/lib/python3.10/dist-packages/cleo/application.py:425 in _run
       423│                 io.set_input(ArgvInput(argv))
       424│ 
     → 425│         exit_code = self._run_command(command, io)
       426│         self._running_command = None
       427│ 

   7  /usr/local/lib/python3.10/dist-packages/cleo/application.py:432 in _run_command
       430│     def _run_command(self, command: Command, io: IO) -> int:
       431│         if self._event_dispatcher is None:
     → 432│             return command.run(io)
       433│ 
       434│         # Bind before the console.command event,

   6  /usr/local/lib/python3.10/dist-packages/cleo/commands/base_command.py:118 in run
       116│         io.input.validate()
       117│ 
     → 118│         status_code = self.execute(io)
       119│ 
       120│         if status_code is None:

   5  /usr/local/lib/python3.10/dist-packages/cleo/commands/command.py:85 in execute
        83│ 
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

   4  /usr/local/lib/python3.10/dist-packages/rip/cli.py:437 in handle
       435│ 
       436│             client = TidalClient()
     → 437│             client.login()
       438│             self._config.file["tidal"].update(client.get_tokens())
       439│             self._config.save()

   3  /usr/local/lib/python3.10/dist-packages/streamrip/clients.py:777 in login
        775│         else:
        776│             logger.debug("Logging in as a new user")
     →  777│             self._login_new_user()
        778│ 
        779│         self.logged_in = True
        
   2  /usr/local/lib/python3.10/dist-packages/streamrip/clients.py:862 in _login_new_user
        860│         :type launch: bool
        861│         """
     →  862│         login_link = f"https://{self._get_device_code()}"
        863│ 
        864│         secho(

   1  /usr/local/lib/python3.10/dist-packages/streamrip/clients.py:894 in _get_device_code
        892│             "scope": "r_usr+w_usr+w_sub",
        893│         }
     →  894│         resp = self._api_post(f"{TIDAL_AUTH_URL}/device_authorization", data)
        895│ 
        896│         if resp.get("status", 200) != 200:

  AttributeError

  'NoneType' object has no attribute 'json'

  at /usr/local/lib/python3.10/dist-packages/streamrip/clients.py:1103 in _api_post
      1099│         :param url:
      1100│         :param data:
      1101│         :param auth:
      1102│         """
    → 1103│         return self.session.post(url, data=data, auth=auth, verify=False).json()
      1104│ 
      1105│ 
      1106│ class SoundCloudClient(Client):
      1107│     """SoundCloudClient."""
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/root/Streamrip"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

















[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3
# Max number of API requests to handle per minute
# Set to -1 for no limit
requests_per_minute = -1

















[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 4
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = "950096963"
# Do not change
secrets = ["10b251c286cfbf64d6b7105f253d9a2e", "979549437fcc4a3faad4867b5cd25dcb"]
use_auth_token = false
email_or_userid = ""
password_or_token = ""


























































[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = 
country_code = "NZ"
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = 


























































[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true


























































[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

















[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.
















[database.downloads]
enabled = false
path = ""

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
















[database.failed_downloads]
enabled = false
path = ""

# Convert tracks to a codec after downloading them.
















[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
















[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

















[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "original"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true

















[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
















[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than 120 characters
# Setting this to false may cause downloads to fail on some systems
truncate = true

# Last.fm playlists are downloaded by searching for the titles of the tracks
















[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"

















[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"

















[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.8"
```

### Operating System

Ubuntu 22.04.2 LTS x86_64

### streamrip version

1.9.7
