### ISSUE TITLE
[BUG] Error in specific album/track download, can't continue after.

### ISSUE THREAD

**Issue by AKL55** [nathom/streamrip#449]
### Describe the bug

Streamrip gives error in specific track/album "https://www.deezer.com/en/album/48332102" it only downloads the cover.

### Command Used

```bash
rip url https://www.deezer.com/en/album/48332102
```

### Debug Traceback

```text
(venv) F:\QBDLX\rip\rip>rip url https://www.deezer.com/en/album/48332102 -vvv
DEBUG:streamrip:Config loaded
DEBUG:streamrip:Parsed urls: [('deezer', 'album', '48332102')]
DEBUG:streamrip:Searching for {'id': '48332102'} in database
DEBUG:streamrip:Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)
DEBUG:streamrip:{'downloads': {'folder': 'F:\\QBDLX\\rip\\download', 'source_subdirectories': False, 'concurrency': {'enabled': False, 'max_connections': 1}}, 'qobuz': {'quality': 2, 'download_booklets': True, 'email': '', 'password': '', 'app_id': '', 'secrets': []}, 'tidal': {'quality': 3, 'download_videos': True}, 'deezer': {'quality': 2, 'arl': '', 'use_deezloader': True, 'deezloader_warnings': True}, 'soundcloud': {'quality': 0, 'client_id': '', 'app_version': ''}, 'youtube': {'quality': 0, 'download_videos': False, 'video_downloads_folder': ''}, 'database': {'downloads': {'enabled': True, 'path': 'F:\\QBDLX\\rip\\db\\downloads.db'}, 'failed_downloads': {'enabled': True, 'path': 'F:\\QBDLX\\rip\\db\\downloads_failed.db'}}, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'filters': {'extras': False, 'repeats': False, 'non_albums': False, 'features': False, 'non_studio_albums': False, 'non_remaster': False}, 'artwork': {'embed': True, 'size': 'original', 'max_width': -1, 'max_height': -1, 'keep_hires_cover': True}, 'metadata': {'set_playlist_to_album': True, 'new_playlist_tracknumbers': True, 'exclude': ['genre', 'lyrics', 'comment']}, 'filepaths': {'add_singles_to_folder': False, 'folder_format': '{albumartist} - {title}', 'track_format': '{tracknumber}. {artist} - {title}', 'restrict_characters': False, 'truncate': True}, 'lastfm': {'source': 'qobuz', 'fallback_source': 'deezer'}, 'theme': {'progress_bar': 'dainty'}, 'misc': {'version': '1.9.6'}}
DEBUG:streamrip:Arguments from config: {'restrict_filenames': False, 'truncate_filenames': True, 'parent_folder': 'F:\\QBDLX\\rip\\download', 'folder_format': '{albumartist} - {title}', 'track_format': '{tracknumber}. {artist} - {title}', 'embed_cover': True, 'embed_cover_size': 'original', 'keep_hires_cover': True, 'set_playlist_to_album': True, 'stay_temp': False, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'concurrent_downloads': False, 'max_connections': 1, 'new_tracknumbers': True, 'download_videos': True, 'download_booklets': True, 'download_youtube_videos': False, 'youtube_video_downloads_folder': '', 'add_singles_to_folder': False, 'max_artwork_width': -1, 'max_artwork_height': -1, 'exclude_tags': ['genre', 'lyrics', 'comment']}
DEBUG:streamrip:Loading metadata
DEBUG:streamrip:{'id': 48332102, 'title': 'SBL (with Boskipo)', 'upc': '5057302549824', 'link': 'https://www.deezer.com/album/48332102', 'share': 'https://www.deezer.com/album/48332102?utm_source=deezer&utm_content=album-48332102&utm_term=0_1693271322&utm_medium=web', 'cover': 'https://api.deezer.com/album/48332102/image', 'cover_small': 'https://e-cdns-images.dzcdn.net/images/cover/52e47712869c4c88d88eba6ccbdfbabb/56x56-000000-80-0-0.jpg', 'cover_medium': 'https://e-cdns-images.dzcdn.net/images/cover/52e47712869c4c88d88eba6ccbdfbabb/250x250-000000-80-0-0.jpg', 'cover_big': 'https://e-cdns-images.dzcdn.net/images/cover/52e47712869c4c88d88eba6ccbdfbabb/500x500-000000-80-0-0.jpg', 'cover_xl': 'https://e-cdns-images.dzcdn.net/images/cover/52e47712869c4c88d88eba6ccbdfbabb/1000x1000-000000-80-0-0.jpg', 'md5_image': '52e47712869c4c88d88eba6ccbdfbabb', 'genre_id': 106, 'genres': {'data': [{'id': 106, 'name': 'Electro', 'picture': 'https://api.deezer.com/genre/106/image', 'type': 'genre'}, {'id': 113, 'name': 'Dance', 'picture': 'https://api.deezer.com/genre/113/image', 'type': 'genre'}]}, 'label': 'OHM Records Indonesia', 'nb_tracks': 1, 'duration': 212, 'fans': 1, 'release_date': '2017-09-14', 'record_type': 'single', 'available': True, 'tracklist': 'https://api.deezer.com/album/48332102/tracks', 'explicit_lyrics': False, 'explicit_content_lyrics': 0, 'explicit_content_cover': 2, 'contributors': [{'id': 13182311, 'name': 'MQX', 'link': 'https://www.deezer.com/artist/13182311', 'share': 'https://www.deezer.com/artist/13182311?utm_source=deezer&utm_content=artist-13182311&utm_term=0_1693271322&utm_medium=web', 'picture': 'https://api.deezer.com/artist/13182311/image', 'picture_small': 'https://e-cdns-images.dzcdn.net/images/artist//56x56-000000-80-0-0.jpg', 'picture_medium': 'https://e-cdns-images.dzcdn.net/images/artist//250x250-000000-80-0-0.jpg', 'picture_big': 'https://e-cdns-images.dzcdn.net/images/artist//500x500-000000-80-0-0.jpg', 'picture_xl': 'https://e-cdns-images.dzcdn.net/images/artist//1000x1000-000000-80-0-0.jpg', 'radio': True, 'tracklist': 'https://api.deezer.com/artist/13182311/top?limit=50', 'type': 'artist', 'role': 'Main'}], 'artist': {'id': 13182311, 'name': 'MQX', 'picture': 'https://api.deezer.com/artist/13182311/image', 'picture_small': 'https://e-cdns-images.dzcdn.net/images/artist//56x56-000000-80-0-0.jpg', 'picture_medium': 'https://e-cdns-images.dzcdn.net/images/artist//250x250-000000-80-0-0.jpg', 'picture_big': 'https://e-cdns-images.dzcdn.net/images/artist//500x500-000000-80-0-0.jpg', 'picture_xl': 'https://e-cdns-images.dzcdn.net/images/artist//1000x1000-000000-80-0-0.jpg', 'tracklist': 'https://api.deezer.com/artist/13182311/top?limit=50', 'type': 'artist'}, 'type': 'album', 'tracks': [{'id': 407837062, 'readable': True, 'title': 'SBL (with Boskipo)', 'title_short': 'SBL (with Boskipo)', 'title_version': '', 'isrc': 'GBSMU4162733', 'link': 'https://www.deezer.com/track/407837062', 'duration': 212, 'track_position': 1, 'disk_number': 1, 'rank': 0, 'explicit_lyrics': False, 'explicit_content_lyrics': 0, 'explicit_content_cover': 2, 'preview': 'https://cdns-preview-c.dzcdn.net/stream/c-c64e0a8d7b8cba5dcce3e6e17452f04e-2.mp3', 'md5_image': '52e47712869c4c88d88eba6ccbdfbabb', 'artist': {'id': 13182311, 'name': 'MQX', 'tracklist': 'https://api.deezer.com/artist/13182311/top?limit=50', 'type': 'artist'}, 'type': 'track'}], 'track_total': 1}
DEBUG:streamrip:{'meta': <TrackMetadata object -0xf82046f7464160a>, 'id': 407837062, 'part_of_tracklist': True}
DEBUG:streamrip:Sampling rate, bit depth = (16, 44100)
DEBUG:streamrip:Formatter: {'albumartist': 'MQX', 'title': 'SBL (with Boskipo)', 'year': '2017', 'bit_depth': 16, 'sampling_rate': 44.1, 'container': 'FLAC', 'albumcomposer': None, 'id': 48332102}
DEBUG:streamrip:Formatter keys: {albumartist} - {title}
DEBUG:streamrip:'albumartist'
DEBUG:streamrip:MQX
DEBUG:streamrip:1
DEBUG:streamrip:'title'
DEBUG:streamrip:SBL (with Boskipo)
DEBUG:streamrip:1


Downloading SBL (with Boskipo) (Album)

Downloading cover art (original)
DEBUG:streamrip:Chosen cover url: https://e-cdns-images.dzcdn.net/images/cover/52e47712869c4c88d88eba6ccbdfbabb/1000x1000-000000-80-0-0.jpg
DEBUG:streamrip:Getting cover_obj from C:\Users\ullia\AppData\Local\Temp\cover_4f46056023f97651b48107b708bfc601.jpg

Downloading "MQX - SBL (with Boskipo)"
DEBUG:streamrip:Downloading track to F:\QBDLX\rip\download\MQX - SBL (with Boskipo)
DEBUG:streamrip:Track meta formatter {'tracknumber': 1, 'artist': 'MQX', 'albumartist': 'MQX', 'composer': None, 'title': 'SBL (with Boskipo)', 'albumcomposer': None, 'explicit': False}
DEBUG:streamrip:Formatter keys: {tracknumber}. {artist} - {title}
DEBUG:streamrip:'tracknumber'
DEBUG:streamrip:1
DEBUG:streamrip:2
DEBUG:streamrip:'artist'
DEBUG:streamrip:MQX
DEBUG:streamrip:1
DEBUG:streamrip:'title'
DEBUG:streamrip:SBL (with Boskipo)
DEBUG:streamrip:1
DEBUG:streamrip:Formatted path: F:\QBDLX\rip\download\MQX - SBL (with Boskipo)\01. MQX - SBL (with Boskipo).flac
DEBUG:streamrip:Track info: {'ALB_ID': '48332102', 'ALB_PICTURE': '52e47712869c4c88d88eba6ccbdfbabb', 'ALB_TITLE': 'SBL (with Boskipo)', 'ARTISTS': [{'ART_ID': '13182311', 'ROLE_ID': '0', 'ARTISTS_SONGS_ORDER': '1', 'ART_NAME': 'MQX', 'ARTIST_IS_DUMMY': False, 'ART_PICTURE': 'b5095bf241d45a79af0987cf1dba9dee', 'RANK': '491642', 'LOCALES': [], '__TYPE__': 'artist'}], 'ART_ID': '13182311', 'ART_NAME': 'MQX', 'ARTIST_IS_DUMMY': False, 'DIGITAL_RELEASE_DATE': '2017-09-14', 'DISK_NUMBER': '1', 'DURATION': '212', 'EXPLICIT_LYRICS': '0', 'EXPLICIT_TRACK_CONTENT': {'EXPLICIT_LYRICS_STATUS': 0, 'EXPLICIT_COVER_STATUS': 2}, 'GENRE_ID': '0', 'HIERARCHICAL_TITLE': '', 'ISRC': 'GBSMU4162733', 'LYRICS_ID': 0, 'PHYSICAL_RELEASE_DATE': '2017-09-14', 'PROVIDER_ID': '48', 'RANK': '0', 'SMARTRADIO': 0, 'SNG_CONTRIBUTORS': {'main_artist': ['MQX'], 'secondary': ['Boskipo']}, 'SNG_ID': '407837062', 'SNG_TITLE': 'SBL (with Boskipo)', 'STATUS': 1, 'TRACK_NUMBER': '1', 'USER_ID': 0, 'VERSION': '', 'MD5_ORIGIN': 'f1d080105f64c172ef2aa9faa961781d', 'FILESIZE_AAC_64': '0', 'FILESIZE_MP3_64': '0', 'FILESIZE_MP3_128': '417', 'FILESIZE_MP3_256': '0', 'FILESIZE_MP3_320': '1044', 'FILESIZE_FLAC': '276', 'FILESIZE': '417', 'MEDIA_VERSION': '2', 'TRACK_TOKEN': 'AAAAAWTtRRtk7l5b-2prGbKBceUrhCiZzgH1dD9KwtQBZ5SQqRAxKfiCvua9ev6WjrtYTex9sC78rkWyby6lcQ-0UxPT6CcMnYJOC1Gh4lUmiN3sOHxjo2quJS_Hg-Nw-0PaG22P6tu-SOa7NDg', 'TRACK_TOKEN_EXPIRE': 1693343323, 'MEDIA': [{'TYPE': 'preview', 'HREF': 'http://cdn-preview-c.deezer.com/stream/c-c64e0a8d7b8cba5dcce3e6e17452f04e-2.mp3'}], 'RIGHTS': {'STREAM_ADS_AVAILABLE': True, 'STREAM_ADS': '2000-01-01', 'STREAM_SUB_AVAILABLE': True, 'STREAM_SUB': '2000-01-01'}, '__TYPE__': 'song'}
DEBUG:streamrip:dl_info {'quality': 2, 'fallback_id': None, 'size_to_quality': {417: 0, 276: 2, 0: None, 1044: 1}, 'url': 'https://e-cdnt-proxy-f.dzcdn.net/media/1/f640329b0ce3bd985035fa5ed4e19cee1564f4908ae4100433e8f8571ac7bdfe7d072d242ca4c1fe1a2b09130a5833153680e9c78ffe01fa5a274621b53767a9dcdf26b0bb19be4cd0318c4738581bd0?3YAq-RNFMNO4ErzVPTICTvXNldcl194piIqgm0wEnxvq3XG6UUwDN3AmW2kenTrfbX82Bcg2O-PpBBW7jSXn5zqAo9PQZdUgj67zfKkvcVe3QhSo91YVdPI3vP00Lhiva4MdtoYNRPXtmbkRpqFIi719iwYJb-zinGqFrrnqLi8iDV840ngs_Rh0jOzxu95zIIkHc8v6oBf4MRuR72CF7E4TAD8LEpW_lxeg6R_dJO4_mZzPwZc7YTjzsLTWPbF1rA0YK5OwnNsbfjWjFV66sX955Gv69lF4YOjSlLaZ3_vdf3SEVM9daQXEMToS0pbm0abOfRgvqRGs'}

  StopIteration

  0

  at ~\AppData\Local\Programs\Python\Python310\lib\json\decoder.py:353 in raw_decode
      349│         have extraneous data at the end.
      350│
      351│         """
      352│         try:
    → 353│             obj, end = self.scan_once(s, idx)
      354│         except StopIteration as err:
      355│             raise JSONDecodeError("Expecting value", s, err.value) from None
      356│         return obj, end
      357│

The following error occurred when trying to handle this error:


  Stack trace:

  3  venv\lib\site-packages\requests\models.py:971 in json
       969│
       970│         try:
    →  971│             return complexjson.loads(self.text, **kwargs)
       972│         except JSONDecodeError as e:
       973│             # Catch JSON-related errors and raise as requests.JSONDecodeError

  2  ~\AppData\Local\Programs\Python\Python310\lib\json\__init__.py:346 in loads
      344│             parse_int is None and parse_float is None and
      345│             parse_constant is None and object_pairs_hook is None and not kw):
    → 346│         return _default_decoder.decode(s)
      347│     if cls is None:
      348│         cls = JSONDecoder

  1  ~\AppData\Local\Programs\Python\Python310\lib\json\decoder.py:337 in decode
      335│
      336│         """
    → 337│         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      338│         end = _w(s, end).end()
      339│         if end != len(s):

  JSONDecodeError

  Expecting value: line 1 column 1 (char 0)

  at ~\AppData\Local\Programs\Python\Python310\lib\json\decoder.py:355 in raw_decode
      351│         """
      352│         try:
      353│             obj, end = self.scan_once(s, idx)
      354│         except StopIteration as err:
    → 355│             raise JSONDecodeError("Expecting value", s, err.value) from None
      356│         return obj, end
      357│

The following error occurred when trying to handle this error:


  Stack trace:

  1  venv\lib\site-packages\streamrip\downloadtools.py:74 in __init__
       72│
       73│             try:
    →  74│                 info = self.request.json()
       75│                 try:
       76│                     # Usually happens with deezloader downloads

  JSONDecodeError

  Expecting value: line 1 column 1 (char 0)

  at venv\lib\site-packages\requests\models.py:975 in json
       971│             return complexjson.loads(self.text, **kwargs)
       972│         except JSONDecodeError as e:
       973│             # Catch JSON-related errors and raise as requests.JSONDecodeError
       974│             # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
    →  975│             raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
       976│
       977│     @property
       978│     def links(self):
       979│         """Returns the parsed header links of the response, if any."""

The following error occurred when trying to handle this error:


  Stack trace:

  1  venv\lib\site-packages\streamrip\media.py:336 in download
       334│
       335│             try:
    →  336│                 stream = DownloadStream(
       337│                     dl_info["url"], source="deezer", item_id=self.id
       338│                 )

  NonStreamable

  File not found.

  at venv\lib\site-packages\streamrip\downloadtools.py:82 in __init__
       78│                 except KeyError:
       79│                     raise NonStreamable(info)
       80│
       81│             except json.JSONDecodeError:
    →  82│                 raise NonStreamable("File not found.")
       83│
       84│     def __iter__(self) -> Iterable:
       85│         """Iterate through chunks of the stream.
       86│

The following error occurred when trying to handle this error:


  Stack trace:

  13  venv\lib\site-packages\cleo\application.py:330 in run
       328│
       329│             try:
     → 330│                 exit_code = self._run(io)
       331│             except Exception as e:
       332│                 if not self._catch_exceptions:

  12  venv\lib\site-packages\rip\cli.py:762 in _run
       760│             logger.addHandler(fh)
       761│
     → 762│         super()._run(io)
       763│
       764│     def create_io(self, input=None, output=None, error_output=None):

  11  venv\lib\site-packages\cleo\application.py:425 in _run
       423│                 io.set_input(ArgvInput(argv))
       424│
     → 425│         exit_code = self._run_command(command, io)
       426│         self._running_command = None
       427│

  10  venv\lib\site-packages\cleo\application.py:432 in _run_command
       430│     def _run_command(self, command: Command, io: IO) -> int:
       431│         if self._event_dispatcher is None:
     → 432│             return command.run(io)
       433│
       434│         # Bind before the console.command event,

   9  venv\lib\site-packages\cleo\commands\base_command.py:118 in run
       116│         io.input.validate()
       117│
     → 118│         status_code = self.execute(io)
       119│
       120│         if status_code is None:

   8  venv\lib\site-packages\cleo\commands\command.py:85 in execute
        83│
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

   7  venv\lib\site-packages\rip\cli.py:125 in handle
       123│
       124│         if len(core) > 0:
     → 125│             core.download()
       126│         elif not urls and path is None:
       127│             self.line("Must pass arguments. See rip url -h.")

   6  venv\lib\site-packages\rip\core.py:314 in download
       312│
       313│             try:
     → 314│                 item.download(**arguments)
       315│                 for item_id in item.downloaded_ids:
       316│                     # Add items row by row

   5  venv\lib\site-packages\streamrip\media.py:1195 in download
       1193│                     secho(f'\nDownloading "{item!s}"', bold=True, fg="green")
       1194│                 try:
     → 1195│                     target(item, **kwargs)
       1196│                 except ItemExists:
       1197│                     secho(f"{item!s} exists. Skipping.", fg="yellow")

   4  venv\lib\site-packages\streamrip\media.py:1572 in _download_item
       1570│
       1571│         quality = kwargs.pop("quality", 3)
     → 1572│         item.download(quality=min(self.quality, quality), **kwargs)
       1573│
       1574│         logger.debug("tagging tracks")

   3  venv\lib\site-packages\streamrip\media.py:341 in download
        339│             except NonStreamable:
        340│                 self.id = dl_info["fallback_id"]
     →  341│                 dl_info = self.client.get_file_url(self.id, self.quality)
        342│                 assert isinstance(dl_info, dict)
        343│                 stream = DownloadStream(

   2  venv\lib\site-packages\streamrip\clients.py:553 in get_file_url
        551│         dl_info: Dict[str, Any] = {"quality": quality}
        552│
     →  553│         track_info = self.client.gw.get_track(meta_id)
        554│         logger.debug("Track info: %s", track_info)
        555│

   1  venv\lib\site-packages\deezer\gw.py:84 in get_track
        82│
        83│     def get_track(self, sng_id):
     →  84│         return self.api_call('song.getData', {'SNG_ID': sng_id})
        85│
        86│     def get_track_page(self, sng_id):

  GWAPIError

  {"MISSING_PARAMETER_SNG_ID": "Parameter SNG_ID is missing"}

  at venv\lib\site-packages\deezer\gw.py:63 in api_call
       59│             if result_json.get('payload', {}) and result_json['payload'].get('FALLBACK', {}):
       60│                 for key in result_json['payload']['FALLBACK'].keys():
       61│                     args[key] = result_json['payload']['FALLBACK'][key]
       62│                 return self.api_call(method, args, params)
    →  63│             raise GWAPIError(json.dumps(result_json['error']))
       64│         if not self.api_token and method == 'deezer.getUserData': self.api_token = result_json['results']['checkForm']
       65│         return result_json['results']
       66│
       67│     def _get_token(self):
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "F:\\QBDLX\\rip\\download"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false




[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = false
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 1




[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 2
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []


[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true





[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true





[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

# This stores a list of item IDs so that repeats are not downloaded.



[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.

[database.downloads]
enabled = true
path = "F:\\QBDLX\\rip\\db\\downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads



[database.failed_downloads]
enabled = true
path = "F:\\QBDLX\\rip\\db\\downloads_failed.db"

# Convert tracks to a codec after downloading them.



[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.



[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false




[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "original"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true




[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = ["genre", "lyrics", "comment"]

# Changes the folder and file names generated by streamrip.



[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title}"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than 120 characters
# Setting this to false may cause downloads to fail on some systems
truncate = true


# Last.fm playlists are downloaded by searching for the titles of the tracks



[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"




[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"




[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.6"
```

### Operating System

Windows 10 Pro

### streamrip version

1.9.7

### Additional context

Running on python 3.10.10 virtual environment. `python -m venv venv`
