### ISSUE TITLE
[BUG] tidal  Download failed

### ISSUE THREAD

**Issue by sky8282** [nathom/streamrip#453]
### Describe the bug

A download failure occurred for a specific album

https://tidal.com/browse/album/3826955

### Command Used

```bash
rip url https://tidal.com/browse/album/3826955
```

### Debug Traceback

```text
Stack trace:

  12  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cleo/application.py:330 in run
       328│ 
       329│             try:
     → 330│                 exit_code = self._run(io)
       331│             except Exception as e:
       332│                 if not self._catch_exceptions:

  11  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rip/cli.py:762 in _run
       760│             logger.addHandler(fh)
       761│ 
     → 762│         super()._run(io)
       763│ 
       764│     def create_io(self, input=None, output=None, error_output=None):

  10  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cleo/application.py:425 in _run
       423│                 io.set_input(ArgvInput(argv))
       424│ 
     → 425│         exit_code = self._run_command(command, io)
       426│         self._running_command = None
       427│ 

   9  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cleo/application.py:432 in _run_command
       430│     def _run_command(self, command: Command, io: IO) -> int:
       431│         if self._event_dispatcher is None:
     → 432│             return command.run(io)
       433│ 
       434│         # Bind before the console.command event,

   8  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cleo/commands/base_command.py:118 in run
       116│         io.input.validate()
       117│ 
     → 118│         status_code = self.execute(io)
       119│ 
       120│         if status_code is None:

   7  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cleo/commands/command.py:85 in execute
        83│ 
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

   6  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rip/cli.py:125 in handle
       123│ 
       124│         if len(core) > 0:
     → 125│             core.download()
       126│         elif not urls and path is None:
       127│             self.line("Must pass arguments. See rip url -h.")

   5  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/rip/core.py:307 in download
       305│                 logger.debug("Loading metadata")
       306│                 try:
     → 307│                     item.load_meta(**arguments)
       308│                 except NonStreamable:
       309│                     self.failed_db.add((item.client.source, item.type, item.id))

   4  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/media.py:1456 in load_meta
       1454│         """Load detailed metadata from API using the id."""
       1455│         assert hasattr(self, "id"), "id must be set to load metadata"
     → 1456│         resp = self.client.get(self.id, media_type="album")
       1457│ 
       1458│         # update attributes based on response

   3  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/clients.py:772 in get
        770│         :param media_type:
        771│         """
     →  772│         resp = self._api_get(item_id, media_type)
        773│         logger.debug(resp)
        774│         return resp

   2  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/clients.py:1006 in _api_get
       1004│         """
       1005│         url = f"{media_type}s/{item_id}"
     → 1006│         item = self._api_request(url)
       1007│         if media_type in ("playlist", "album"):
       1008│ 

   1  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/streamrip/clients.py:1047 in _api_request
       1045│         params["limit"] = 100
       1046│         r = self.session.get(f"{TIDAL_BASE}/{path}", params=params)
     → 1047│         r.raise_for_status()
       1048│         return r.json()
       1049│ 

  HTTPError

  404 Client Error: Not Found for url: https://api.tidalhifi.com/v1/albums/3826955?countryCode=US&limit=100

  at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py:1021 in raise_for_status
      1017│                 f"{self.status_code} Server Error: {reason} for url: {self.url}"
      1018│             )
      1019│ 
      1020│         if http_error_msg:
    → 1021│             raise HTTPError(http_error_msg, response=self)
      1022│ 
      1023│     def close(self):
      1024│         """Releases the connection back to the pool. Once this method has been
      1025│         called the underlying ``raw`` object must not be accessed again.

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/Volumes/机械硬盘/Tidal/Album"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3


[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []


[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true
# Do not change any of the fields below
user_id = 194211737
country_code = "US"
access_token = 
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = 

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.

[database.downloads]
enabled = true
path = "/Users/sky/Library/Application Support/streamrip/downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads

[database.failed_downloads]
enabled = true
path = "/Users/sky/Library/Application Support/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.

[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.


[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false


[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true

[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.

[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist}/ {title} [{bit_depth}B] [{sampling_rate}Khz] [{year}]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber} - {artist} - {title} {explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than 120 characters
# Setting this to false may cause downloads to fail on some systems
truncate = true


# Last.fm playlists are downloaded by searching for the titles of the tracks

[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"

[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"

[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.6"
```

### Operating System

macOS

### streamrip version

1.9.6

### Screenshots and recordings

![1](https://github.com/nathom/streamrip/assets/99399889/e2e5ba24-d559-46ba-96cf-2baecc7ecf46)
