### ISSUE TITLE
[BUG] <title>Qobuz Login

### ISSUE THREAD

**Issue by weexisttocease** [nathom/streamrip#461]
### Describe the bug

Hi there.

I have a Qobuz streaming account bur for some reason it's saying I have a free account, which is not true. 

### Command Used

```bash
IneligibleError

  Free accounts are not eligible to download tracks.

  at AppData\Local\Programs\Python\Python39\lib\site-packages\streamrip\clients.py:370 in _api_login
       366│         else:
       367│             logger.info("Logged in to Qobuz")
       368│
       369│         if not resp["user"]["credential"]["parameters"]:
    →  370│             raise IneligibleError("Free accounts are not eligible to download tracks.")
       371│
       372│         self.uat = resp["user_auth_token"]
       373│         self.session.headers.update({"X-User-Auth-Token": self.uat})
       374│         self.label = resp["user"]["credential"]["parameters"]["short_label"]
```

### Debug Traceback

```text
C:\Users\Jorge>rip url --max-quality 4 https://open.qobuz.com/album/mtekpseobyhxb -vvv
DEBUG:streamrip:Config loaded
DEBUG:streamrip:Parsed urls: [('qobuz', 'album', 'mtekpseobyhxb')]
DEBUG:streamrip:Searching for {'id': 'mtekpseobyhxb'} in database
DEBUG:streamrip:Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)
Logging into qobuz
DEBUG:streamrip:Raw request signature: trackgetFileUrlformat_id7intentstreamtrack_id195125741695676770.408889810b251c286cfbf64d6b7105f253d9a2e
DEBUG:streamrip:Raw request signature: trackgetFileUrlformat_id7intentstreamtrack_id195125741695676770.4088898979549437fcc4a3faad4867b5cd25dcb
DEBUG:streamrip:Hashed request signature: 8579478aeacecbe5454aaa6834e082ea
DEBUG:streamrip:Hashed request signature: bbe0accd642429bd8b5572b4e9ad8d46
DEBUG:streamrip:{"track_id":19512574,"duration":30,"url":"https:\/\/streaming-qobuz-std.akamaized.net\/file?eid=19512574&fmt=7&profile=raw&range=20-30&app_id=814460817&etsp=1695680273&hmac=jIEGV_RaHZnY0UjXQM7YAovwanA","format_id":7,"mime_type":"audio\/flac","sample":true,"restrictions":[{"code":"UserUnauthenticated"}],"sampling_rate":96,"bit_depth":24}
DEBUG:streamrip:{"status":"error","code":400,"message":"Invalid Request Signature parameter (request_sig) (Root=1-6511f901-10f6748c415c449b3175fd5c)"}
DEBUG:streamrip:Test for 979549437fcc4a3faad4867b5cd25dcb secret didn't work: Invalid app secret from params {'request_ts': 1695676770.4088898, 'request_sig': 'bbe0accd642429bd8b5572b4e9ad8d46', 'track_id': '19512574', 'format_id': 7, 'intent': 'stream'}
DEBUG:streamrip:{"user":{"id":1243036,"publicId":"qobuz:user:A4oTmujodD6Kl","email":"","login":"","firstname":null,"lastname":null,"display_name":"Jorge Costa","country_code":"ES","language_code":"es","zone":"ES","store":"ES-es","country":"ES","avatar":"https:\/\/www.gravatar.com\/avatar\/85d6dd2fd16383c53f4717fa6dda4d47?s=50&d=mm","genre":"male","age":44,"creation_date":"2020-01-02","subscription":{"offer":"studio","periodicity":"monthly","start_date":"2021-12-19","end_date":"2023-08-18","is_canceled":true,"household_size_max":1},"credential":{"id":null,"label":null,"description":"Miembro de Qobuz","parameters":null},"last_update":{"favorite":1685649717,"favorite_album":1577958852,"favorite_artist":1685649717,"favorite_track":1577958852,"playlist":1577958852,"purchase":1639871925},"store_features":{"download":true,"streaming":true,"editorial":true,"club":true,"wallet":false,"weeklyq":true,"autoplay":true,"inapp_purchase_subscripton":true,"opt_in":true,"music_import":true},"player_settings":[],"externals":{}},"user_auth_token":"3ftaS-5azVYjK8WaNAVojJ6h8qYU33eSdaEvS1MXfcYVLO7RQt8CgABPiV11NL6H6qVzwzHqJPgZGN-Y5qJqvQ"}
INFO:streamrip:Logged in to Qobuz

  Stack trace:

  12  AppData\Local\Programs\Python\Python39\lib\site-packages\cleo\application.py:330 in run
       328│
       329│             try:
     → 330│                 exit_code = self._run(io)
       331│             except Exception as e:
       332│                 if not self._catch_exceptions:

  11  AppData\Local\Programs\Python\Python39\lib\site-packages\rip\cli.py:762 in _run
       760│             logger.addHandler(fh)
       761│
     → 762│         super()._run(io)
       763│
       764│     def create_io(self, input=None, output=None, error_output=None):

  10  AppData\Local\Programs\Python\Python39\lib\site-packages\cleo\application.py:425 in _run
       423│                 io.set_input(ArgvInput(argv))
       424│
     → 425│         exit_code = self._run_command(command, io)
       426│         self._running_command = None
       427│

   9  AppData\Local\Programs\Python\Python39\lib\site-packages\cleo\application.py:432 in _run_command
       430│     def _run_command(self, command: Command, io: IO) -> int:
       431│         if self._event_dispatcher is None:
     → 432│             return command.run(io)
       433│
       434│         # Bind before the console.command event,

   8  AppData\Local\Programs\Python\Python39\lib\site-packages\cleo\commands\base_command.py:118 in run
       116│         io.input.validate()
       117│
     → 118│         status_code = self.execute(io)
       119│
       120│         if status_code is None:

   7  AppData\Local\Programs\Python\Python39\lib\site-packages\cleo\commands\command.py:85 in execute
        83│
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

   6  AppData\Local\Programs\Python\Python39\lib\site-packages\rip\cli.py:122 in handle
       120│
       121│         if urls:
     → 122│             core.handle_urls(";".join(urls))
       123│
       124│         if len(core) > 0:

   5  AppData\Local\Programs\Python\Python39\lib\site-packages\rip\core.py:183 in handle_urls
       181│                 continue
       182│
     → 183│             self.handle_item(source, url_type, item_id)
       184│
       185│     def handle_item(self, source: str, media_type: str, item_id: str):

   4  AppData\Local\Programs\Python\Python39\lib\site-packages\rip\core.py:195 in handle_item
       193│         :type item_id: str
       194│         """
     → 195│         client = self.get_client(source)
       196│
       197│         if media_type not in MEDIA_TYPES:

   3  AppData\Local\Programs\Python\Python39\lib\site-packages\rip\core.py:359 in get_client
       357│         if not client.logged_in:
       358│             try:
     → 359│                 self.login(client)
       360│             except DeezloaderFallback:
       361│                 client = self.clients["deezloader"]

   2  AppData\Local\Programs\Python\Python39\lib\site-packages\rip\core.py:384 in login
       382│         while True:
       383│             try:
     → 384│                 client.login(**creds)
       385│                 break
       386│             except AuthenticationError:

   1  AppData\Local\Programs\Python\Python39\lib\site-packages\streamrip\clients.py:141 in login
        139│             self._validate_secrets()
        140│
     →  141│         self._api_login(email, pwd)
        142│         logger.debug("Logged into Qobuz")
        143│         logger.debug("Qobuz client is ready to use")

  IneligibleError

  Free accounts are not eligible to download tracks.

  at AppData\Local\Programs\Python\Python39\lib\site-packages\streamrip\clients.py:370 in _api_login
       366│         else:
       367│             logger.info("Logged in to Qobuz")
       368│
       369│         if not resp["user"]["credential"]["parameters"]:
    →  370│             raise IneligibleError("Free accounts are not eligible to download tracks.")
       371│
       372│         self.uat = resp["user_auth_token"]
       373│         self.session.headers.update({"X-User-Auth-Token": self.uat})
       374│         self.label = resp["user"]["credential"]["parameters"]["short_label"]

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "C:\\Users\\Jorge\\StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false




[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3




[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = "0b73757e9d7bd318680111eef049edcc"
# Do not change
app_id = "814460817"
# Do not change
secrets = ["10b251c286cfbf64d6b7105f253d9a2e", "979549437fcc4a3faad4867b5cd25dcb"]
```

### Operating System

Windows

### streamrip version

1.9.7
