### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by multidrago11** [nathom/streamrip#483]
### Describe the bug

It runs as normal before stating [WinError 2] the system cannot find the specified file. Nothing is then downloaded despite stating further up in the log otherwise.
![blach](https://github.com/nathom/streamrip/assets/128261572/a06f48e3-5691-4341-9d3a-ae636f685b2a)

### Command Used

```bash
rip url https://soundcloud.com/kikai-the-maid/sins
```

### Debug Traceback

```text
PS C:\Windows\system32> rip url https://soundcloud.com/kikai-the-maid/sins -vvv
DEBUG:streamrip:Config loaded
DEBUG:streamrip:client_id: MBDHKk9QaRZMLAtaGC7nnigKRz66I2Bc, app_version: 1687252420
DEBUG:streamrip:Fetching url https://api-v2.soundcloud.com/announcements with params {'client_id': 'MBDHKk9QaRZMLAtaGC7nnigKRz66I2Bc', 'app_version': '1687252420', 'app_locale': 'en'}
DEBUG:streamrip:Refreshing client_id=MBDHKk9QaRZMLAtaGC7nnigKRz66I2Bc and app_version=1687252420
DEBUG:streamrip:Fetching url https://api-v2.soundcloud.com/resolve?url=https://soundcloud.com/kikai-the-maid/sins with params {'client_id': '9jJYDKHcEdy3IbZHsTAooey6e3VYbZ6G', 'app_version': '1699627789', 'app_locale': 'en'}
DEBUG:streamrip:{'artwork_url': 'https://i1.sndcdn.com/artworks-1wD0cROXOJ4zVd6G-SNdyNQ-large.jpg',
 'caption': None,
 'comment_count': 1,
 'commentable': True,
 'created_at': '2023-07-08T13:32:15Z',
 'description': '',
 'display_date': '2023-07-08T13:32:15Z',
 'download_count': 21,
 'downloadable': True,
 'duration': 192026,
 'embeddable_by': 'all',
 'full_duration': 192026,
 'genre': 'breakcore',
 'has_downloads_left': True,
 'id': 1559332987,
 'kind': 'track',
 'label_name': None,
 'last_modified': '2023-07-08T14:00:02Z',
 'license': 'all-rights-reserved',
 'likes_count': 40,
 'media': {'transcodings': [{'duration': 192026,
                             'format': {'mime_type': 'audio/mpeg',
                                        'protocol': 'hls'},
                             'preset': 'mp3_1_0',
                             'quality': 'sq',
                             'snipped': False,
                             'url': 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1559332987/389e69ff-b9a1-4c13-9d4e-6f2cdd32e7ec/stream/hls'},
                            {'duration': 192026,
                             'format': {'mime_type': 'audio/mpeg',
                                        'protocol': 'progressive'},
                             'preset': 'mp3_1_0',
                             'quality': 'sq',
                             'snipped': False,
                             'url': 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1559332987/389e69ff-b9a1-4c13-9d4e-6f2cdd32e7ec/stream/progressive'},
                            {'duration': 192007,
                             'format': {'mime_type': 'audio/ogg; codecs="opus"',
                                        'protocol': 'hls'},
                             'preset': 'opus_0_0',
                             'quality': 'sq',
                             'snipped': False,
                             'url': 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1559332987/79dec43e-7aa3-417a-8894-445d2bd3fb36/stream/hls'}]},
 'monetization_model': 'NOT_APPLICABLE',
 'permalink': 'sins',
 'permalink_url': 'https://soundcloud.com/kikai-the-maid/sins',
 'playback_count': 652,
 'policy': 'ALLOW',
 'public': True,
 'publisher_metadata': {'contains_music': True,
                        'id': 1559332987,
                        'urn': 'soundcloud:tracks:1559332987'},
 'purchase_title': None,
 'purchase_url': None,
 'release_date': None,
 'reposts_count': 5,
 'secret_token': None,
 'sharing': 'public',
 'state': 'finished',
 'station_permalink': 'track-stations:1559332987',
 'station_urn': 'soundcloud:system-playlists:track-stations:1559332987',
 'streamable': True,
 'tag_list': '"Drum & Bass" Experimental Atmospheric Electronic',
 'title': 'sins',
 'track_authorization': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJUVCIsInN1YiI6IiIsInJpZCI6ImM1MmIxMGZhLWZiYmItNDY3OS1hODA2LWQzNjUzYzAxY2E0MiIsImlhdCI6MTY5OTcxMTM3Mn0.bi3JotprEyrihKf0UhfTQXuRI6mGDoR5lGA1ZTxuUm4',
 'track_format': 'single-track',
 'uri': 'https://api.soundcloud.com/tracks/1559332987',
 'urn': 'soundcloud:tracks:1559332987',
 'user': {'avatar_url': 'https://i1.sndcdn.com/avatars-oMJhtj7ELQboGN6D-CGohkA-large.jpg',
          'badges': {'pro': False, 'pro_unlimited': False, 'verified': False},
          'city': None,
          'comments_count': 0,
          'country_code': None,
          'created_at': '2022-09-01T17:24:14Z',
          'creator_subscription': {'product': {'id': 'free'}},
          'creator_subscriptions': [{'product': {'id': 'free'}}],
          'description': None,
          'first_name': '',
          'followers_count': 57,
          'followings_count': 0,
          'full_name': '',
          'groups_count': 0,
          'id': 1159799083,
          'kind': 'user',
          'last_modified': '2022-09-03T15:04:10Z',
          'last_name': '',
          'likes_count': 0,
          'permalink': 'kikai-the-maid',
          'permalink_url': 'https://soundcloud.com/kikai-the-maid',
          'playlist_count': 0,
          'playlist_likes_count': 0,
          'reposts_count': None,
          'station_permalink': 'artist-stations:1159799083',
          'station_urn': 'soundcloud:system-playlists:artist-stations:1159799083',
          'track_count': 3,
          'uri': 'https://api.soundcloud.com/users/1159799083',
          'urn': 'soundcloud:users:1159799083',
          'username': 'Kikai The Maid',
          'verified': False,
          'visuals': {'enabled': True,
                      'tracking': None,
                      'urn': 'soundcloud:users:1159799083',
                      'visuals': [{'entry_time': 0,
                                   'urn': 'soundcloud:visuals:174256857',
                                   'visual_url': 'https://i1.sndcdn.com/visuals-001159799083-sVHCkk-original.jpg'}]}},
 'user_id': 1159799083,
 'visuals': None,
 'waveform_url': 'https://wave.sndcdn.com/C5hEktAb5pCF_m.json'}
DEBUG:streamrip:Parsed urls: [('soundcloud', 'track', '1559332987')]
DEBUG:streamrip:Searching for {'id': '1559332987'} in database
DEBUG:streamrip:Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)
DEBUG:streamrip:{'id': '1559332987'}
DEBUG:streamrip:{'downloads': {'folder': 'C:\\Users\\Admin\\StreamripDownloads', 'source_subdirectories': False, 'concurrency': {'enabled': True, 'max_connections': 3}}, 'qobuz': {'quality': 3, 'download_booklets': True, 'email': '', 'password': '', 'app_id': '', 'secrets': []}, 'tidal': {'quality': 3, 'download_videos': True, 'user_id': '', 'country_code': '', 'access_token': '', 'refresh_token': '', 'token_expiry': ''}, 'deezer': {'quality': 2, 'arl': '', 'use_deezloader': True, 'deezloader_warnings': True}, 'soundcloud': {'quality': 0, 'client_id': 'MBDHKk9QaRZMLAtaGC7nnigKRz66I2Bc', 'app_version': '1687252420'}, 'youtube': {'quality': 0, 'download_videos': False, 'video_downloads_folder': ''}, 'database': {'downloads': {'enabled': True, 'path': 'C:\\Users\\Admin\\AppData\\Local\\streamrip\\streamrip\\downloads.db'}, 'failed_downloads': {'enabled': True, 'path': 'C:\\Users\\Admin\\AppData\\Local\\streamrip\\streamrip\\failed_downloads.db'}}, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'filters': {'extras': False, 'repeats': False, 'non_albums': False, 'features': False, 'non_studio_albums': False, 'non_remaster': False}, 'artwork': {'embed': True, 'size': 'large', 'max_width': -1, 'max_height': -1, 'keep_hires_cover': True}, 'metadata': {'set_playlist_to_album': True, 'new_playlist_tracknumbers': True, 'exclude': []}, 'filepaths': {'add_singles_to_folder': False, 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}{explicit}', 'restrict_characters': False, 'truncate': True}, 'lastfm': {'source': 'qobuz', 'fallback_source': 'deezer'}, 'theme': {'progress_bar': 'dainty'}, 'misc': {'version': '1.9.6'}}
DEBUG:streamrip:Arguments from config: {'restrict_filenames': False, 'truncate_filenames': True, 'parent_folder': 'C:\\Users\\Admin\\StreamripDownloads', 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}{explicit}', 'embed_cover': True, 'embed_cover_size': 'large', 'keep_hires_cover': True, 'set_playlist_to_album': True, 'stay_temp': False, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'concurrent_downloads': True, 'max_connections': 3, 'new_tracknumbers': True, 'download_videos': True, 'download_booklets': True, 'download_youtube_videos': False, 'youtube_video_downloads_folder': '', 'add_singles_to_folder': False, 'max_artwork_width': -1, 'max_artwork_height': -1, 'exclude_tags': []}
DEBUG:streamrip:Loading metadata
DEBUG:streamrip:Fetching url https://api-v2.soundcloud.com/tracks/1559332987 with params {'client_id': '9jJYDKHcEdy3IbZHsTAooey6e3VYbZ6G', 'app_version': '1699627789', 'app_locale': 'en'}
DEBUG:streamrip:{'artwork_url': 'https://i1.sndcdn.com/artworks-1wD0cROXOJ4zVd6G-SNdyNQ-large.jpg', 'caption': None, 'commentable': True, 'comment_count': 1, 'created_at': '2023-07-08T13:32:15Z', 'description': '', 'downloadable': True, 'download_count': 21, 'duration': 192026, 'full_duration': 192026, 'embeddable_by': 'all', 'genre': 'breakcore', 'has_downloads_left': True, 'id': 1559332987, 'kind': 'track', 'label_name': None, 'last_modified': '2023-07-08T14:00:02Z', 'license': 'all-rights-reserved', 'likes_count': 40, 'permalink': 'sins', 'permalink_url': 'https://soundcloud.com/kikai-the-maid/sins', 'playback_count': 652, 'public': True, 'publisher_metadata': {'id': 1559332987, 'urn': 'soundcloud:tracks:1559332987', 'contains_music': True}, 'purchase_title': None, 'purchase_url': None, 'release_date': None, 'reposts_count': 5, 'secret_token': None, 'sharing': 'public', 'state': 'finished', 'streamable': True, 'tag_list': '"Drum & Bass" Experimental Atmospheric Electronic', 'title': 'sins', 'track_format': 'single-track', 'uri': 'https://api.soundcloud.com/tracks/1559332987', 'urn': 'soundcloud:tracks:1559332987', 'user_id': 1159799083, 'visuals': None, 'waveform_url': 'https://wave.sndcdn.com/C5hEktAb5pCF_m.json', 'display_date': '2023-07-08T13:32:15Z', 'media': {'transcodings': [{'url': 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1559332987/389e69ff-b9a1-4c13-9d4e-6f2cdd32e7ec/stream/hls', 'preset': 'mp3_1_0', 'duration': 192026, 'snipped': False, 'format': {'protocol': 'hls', 'mime_type': 'audio/mpeg'}, 'quality': 'sq'}, {'url': 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1559332987/389e69ff-b9a1-4c13-9d4e-6f2cdd32e7ec/stream/progressive', 'preset': 'mp3_1_0', 'duration': 192026, 'snipped': False, 'format': {'protocol': 'progressive', 'mime_type': 'audio/mpeg'}, 'quality': 'sq'}, {'url': 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1559332987/79dec43e-7aa3-417a-8894-445d2bd3fb36/stream/hls', 'preset': 'opus_0_0', 'duration': 192007, 'snipped': False, 'format': {'protocol': 'hls', 'mime_type': 'audio/ogg; codecs="opus"'}, 'quality': 'sq'}]}, 'station_urn': 'soundcloud:system-playlists:track-stations:1559332987', 'station_permalink': 'track-stations:1559332987', 'track_authorization': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJUVCIsInN1YiI6IiIsInJpZCI6ImM1MmIxMGZhLWZiYmItNDY3OS1hODA2LWQzNjUzYzAxY2E0MiIsImlhdCI6MTY5OTcxMTM3Mn0.bi3JotprEyrihKf0UhfTQXuRI6mGDoR5lGA1ZTxuUm4', 'monetization_model': 'NOT_APPLICABLE', 'policy': 'ALLOW', 'user': {'avatar_url': 'https://i1.sndcdn.com/avatars-oMJhtj7ELQboGN6D-CGohkA-large.jpg', 'first_name': '', 'followers_count': 57, 'full_name': '', 'id': 1159799083, 'kind': 'user', 'last_modified': '2022-09-03T15:04:10Z', 'last_name': '', 'permalink': 'kikai-the-maid', 'permalink_url': 'https://soundcloud.com/kikai-the-maid', 'uri': 'https://api.soundcloud.com/users/1159799083', 'urn': 'soundcloud:users:1159799083', 'username': 'Kikai The Maid', 'verified': False, 'city': None, 'country_code': None, 'badges': {'pro': False, 'pro_unlimited': False, 'verified': False}, 'station_urn': 'soundcloud:system-playlists:artist-stations:1159799083', 'station_permalink': 'artist-stations:1159799083'}}
DEBUG:streamrip:Track meta formatter {'tracknumber': 0, 'artist': 'Kikai The Maid', 'albumartist': 'Kikai The Maid', 'composer': None, 'title': 'sins', 'albumcomposer': None, 'explicit': False}
DEBUG:streamrip:Formatter keys: {tracknumber}. {artist} - {title}{explicit}
DEBUG:streamrip:'tracknumber'
DEBUG:streamrip:0
DEBUG:streamrip:2
DEBUG:streamrip:'artist'
DEBUG:streamrip:Kikai The Maid
DEBUG:streamrip:1
DEBUG:streamrip:'title'
DEBUG:streamrip:sins
DEBUG:streamrip:1
DEBUG:streamrip:'explicit'
DEBUG:streamrip:False
DEBUG:streamrip:3
DEBUG:streamrip:Formatted path: C:\Users\Admin\StreamripDownloads\00. Kikai The Maid - sins.mp3
DEBUG:streamrip:Downloading cover from https://i1.sndcdn.com/artworks-1wD0cROXOJ4zVd6G-SNdyNQ-t500x500.jpg
Cover |███████████████████████████████████████████████████████████████████████████████████████| 00:00 left at 1.22MB/s
DEBUG:streamrip:Fetching url https://api-v2.soundcloud.com/tracks/1559332987/download with params {'client_id': '9jJYDKHcEdy3IbZHsTAooey6e3VYbZ6G', 'app_version': '1699627789', 'app_locale': 'en'}
Track 00 |████████████████████████████████████████████████████████████████████████████████████| 00:00 left at 21.8MB/s
DEBUG:streamrip:{'self': <streamrip.converter.FLAC object at 0x0000019B3770B2B0>, 'filename': 'C:\\Users\\Admin\\AppData\\Local\\Temp\\-2855082973980803905_0.tmp', 'ffmpeg_arg': None, 'sampling_rate': None, 'bit_depth': None, 'copy_art': True, 'remove_source': False, 'show_progress': False}
DEBUG:streamrip:No arguments provided. Codec defaults will be used
DEBUG:streamrip:FFmpeg codec extra argument:
DEBUG:streamrip:['ffmpeg', '-i', 'C:\\Users\\Admin\\AppData\\Local\\Temp\\-2855082973980803905_0.tmp', '-c:a', 'flac', '-c:v', 'copy', '-y', 'C:\\Users\\Admin\\AppData\\Local\\Temp\\-2855082973980803905_0.flac']
DEBUG:streamrip:Generated conversion command: ['ffmpeg', '-i', 'C:\\Users\\Admin\\AppData\\Local\\Temp\\-2855082973980803905_0.tmp', '-c:a', 'flac', '-c:v', 'copy', '-y', 'C:\\Users\\Admin\\AppData\\Local\\Temp\\-2855082973980803905_0.flac']

  Stack trace:

  12  ~\AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\application.py:330 in run
       328│
       329│             try:
     → 330│                 exit_code = self._run(io)
       331│             except Exception as e:
       332│                 if not self._catch_exceptions:

  11  ~\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py:762 in _run
       760│             logger.addHandler(fh)
       761│
     → 762│         super()._run(io)
       763│
       764│     def create_io(self, input=None, output=None, error_output=None):

  10  ~\AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\application.py:425 in _run
       423│                 io.set_input(ArgvInput(argv))
       424│
     → 425│         exit_code = self._run_command(command, io)
       426│         self._running_command = None
       427│

   9  ~\AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\application.py:432 in _run_command
       430│     def _run_command(self, command: Command, io: IO) -> int:
       431│         if self._event_dispatcher is None:
     → 432│             return command.run(io)
       433│
       434│         # Bind before the console.command event,

   8  ~\AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\commands\base_command.py:118 in run
       116│         io.input.validate()
       117│
     → 118│         status_code = self.execute(io)
       119│
       120│         if status_code is None:

   7  ~\AppData\Local\Programs\Python\Python310\lib\site-packages\cleo\commands\command.py:85 in execute
        83│
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

   6  ~\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\cli.py:125 in handle
       123│
       124│         if len(core) > 0:
     → 125│             core.download()
       126│         elif not urls and path is None:
       127│             self.line("Must pass arguments. See rip url -h.")

   5  ~\AppData\Local\Programs\Python\Python310\lib\site-packages\rip\core.py:314 in download
       312│
       313│             try:
     → 314│                 item.download(**arguments)
       315│                 for item_id in item.downloaded_ids:
       316│                     # Add items row by row

   4  ~\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\media.py:361 in download
        359│
        360│         elif self.client.source == "soundcloud":
     →  361│             self._soundcloud_download(dl_info)
        362│
        363│         else:

   3  ~\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\media.py:460 in _soundcloud_download
        458│             engine = converter.FLAC(self.path)
        459│             self.path = f"{self.path}.flac"
     →  460│             engine.convert(custom_fn=self.path)
        461│
        462│             self.final_path = self.final_path.replace(".mp3", ".flac")

   2  ~\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\converter.py:84 in convert
        82│         logger.debug("Generated conversion command: %s", self.command)
        83│
     →  84│         process = subprocess.Popen(self.command, stderr=subprocess.PIPE)
        85│         process.wait()
        86│         if process.returncode == 0 and os.path.isfile(self.tempfile):

   1  ~\AppData\Local\Programs\Python\Python310\lib\subprocess.py:971 in __init__
        969│                             encoding=encoding, errors=errors)
        970│
     →  971│             self._execute_child(args, executable, preexec_fn, close_fds,
        972│                                 pass_fds, cwd, env,
        973│                                 startupinfo, creationflags, shell,

  FileNotFoundError

  [WinError 2] The system cannot find the file specified

  at ~\AppData\Local\Programs\Python\Python310\lib\subprocess.py:1440 in _execute_child
      1436│             sys.audit("subprocess.Popen", executable, args, cwd, env)
      1437│
      1438│             # Start the process
      1439│             try:
    → 1440│                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      1441│                                          # no special security
      1442│                                          None, None,
      1443│                                          int(not close_fds),
      1444│                                          creationflags,

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "C:\\Users\\Admin\\StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false



[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3



[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []



[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""



[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true



[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = "MBDHKk9QaRZMLAtaGC7nnigKRz66I2Bc"
app_version = "1687252420"



[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.


[database.downloads]
enabled = true
path = "C:\\Users\\Admin\\AppData\\Local\\streamrip\\streamrip\\downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads


[database.failed_downloads]
enabled = true
path = "C:\\Users\\Admin\\AppData\\Local\\streamrip\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.


[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.


[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false



[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true



[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.


[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than 120 characters
# Setting this to false may cause downloads to fail on some systems
truncate = true


# Last.fm playlists are downloaded by searching for the titles of the tracks


[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"



[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"



[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.6"
```

### Operating System

Windows

### streamrip version

1.9.7

### Additional context

I've installed it as normal with pip. I have several other programs installed with pip as well, such as mangadex-dl and gallery-dl. I do not believe these should pose any issue though.
