### ISSUE TITLE
[BUG] Suddenly getting a ParseError and subsequent Exception when running most non-help/list commands (I think commands referencing config.toml?), despite it working flawlessly last time.

### ISSUE THREAD

**Issue by SKDemon820** [nathom/streamrip#489]
### Describe the bug

When running most non-help/list commands, the command fails with the reason:
```
ParseError

Empty key found at line 1 col 0
```

And:
```
The following error occurred when trying to handle this error:

Exception

Error parsing config file with error Empty key found at line 1 col 0. Make sure you escape backslashes (\) in Windows paths. Example: "E:\\StreamripDownloads\\" 
```

This didn't happen the last time I used the script about a week ago (which was the first time I used it) and I didn't change anything between then and now.  More details in the Debug Traceback and Additional Context

### Command Used

```bash
Most of the non-help/list commands.  Such as:

rip config
rip url
rip db test
```

### Debug Traceback

```text
[Censored-Name]-MacBook-Air ~ % rip config -vvv

  Stack trace:

  7  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/rip/config.py:137 in load
      135│         with open(self._path) as cfg:
      136│             try:
    → 137│                 toml = tomlkit.loads(cfg.read().strip()).items()
      138│             except Exception as e:
      139│                 raise Exception(

  6  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tomlkit/api.py:34 in loads
       32│     Alias for parse().
       33│     """
    →  34│     return parse(string)
       35│ 
       36│ 

  5  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tomlkit/api.py:51 in parse
       49│     Parses a string into a TOMLDocument.
       50│     """
    →  51│     return Parser(string).parse()
       52│ 
       53│ 

  4  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tomlkit/parser.py:146 in parse
       144│ 
       145│             # Otherwise, take and append one KV
    →  146│             item = self._parse_item()
       147│             if not item:
       148│                 break

  3  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tomlkit/parser.py:306 in _parse_item
       304│                     break
       305│ 
    →  306│         return self._parse_key_value(True)
       307│ 
       308│     def _parse_comment_trail(self):  # type: () -> Tuple[str, str, str]

  2  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tomlkit/parser.py:378 in _parse_key_value
       376│ 
       377│         # Key
    →  378│         key = self._parse_key()
       379│ 
       380│         self.mark()

  1  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tomlkit/parser.py:422 in _parse_key
       420│             return self._parse_quoted_key()
       421│         else:
    →  422│             return self._parse_bare_key()
       423│ 
       424│     def _parse_quoted_key(self):  # type: () -> Key

  ParseError

  Empty key found at line 1 col 0

  at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tomlkit/parser.py:474 in _parse_bare_key
       470│         original = self.extract()
       471│         key = original.strip()
       472│         if not key:
       473│             # Empty key
    →  474│             raise self.parse_error(ParseError, "Empty key found")
       475│ 
       476│         if " " in key:
       477│             # Bare key with spaces in it
       478│             raise self.parse_error(ParseError, 'Invalid key "{}"'.format(key))

The following error occurred when trying to handle this error:


  Stack trace:

  8  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cleo/application.py:330 in run
      328│ 
      329│             try:
    → 330│                 exit_code = self._run(io)
      331│             except Exception as e:
      332│                 if not self._catch_exceptions:

  7  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/rip/cli.py:754 in _run
      752│             logger.addHandler(fh)
      753│ 
    → 754│         super()._run(io)
      755│ 
      756│     def create_io(self, input=None, output=None, error_output=None):

  6  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cleo/application.py:425 in _run
      423│                 io.set_input(ArgvInput(argv))
      424│ 
    → 425│         exit_code = self._run_command(command, io)
      426│         self._running_command = None
      427│ 

  5  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cleo/application.py:432 in _run_command
      430│     def _run_command(self, command: Command, io: IO) -> int:
      431│         if self._event_dispatcher is None:
    → 432│             return command.run(io)
      433│ 
      434│         # Bind before the console.command event,

  4  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cleo/commands/base_command.py:118 in run
      116│         io.input.validate()
      117│ 
    → 118│         status_code = self.execute(io)
      119│ 
      120│         if status_code is None:

  3  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cleo/commands/command.py:85 in execute
       83│ 
       84│         try:
    →  85│             return self.handle()
       86│         except KeyboardInterrupt:
       87│             return 1

  2  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/rip/cli.py:408 in handle
      406│         from .constants import CONFIG_DIR, CONFIG_PATH
      407│ 
    → 408│         self._config = Config()
      409│ 
      410│         if self.option("path"):

  1  /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/rip/config.py:57 in __init__
       55│ 
       56│         if os.path.isfile(self._path):
    →  57│             self.load()
       58│             if self.file["misc"]["version"] != self.defaults["misc"]["version"]:
       59│                 secho(

  Exception

  Error parsing config file with error Empty key found at line 1 col 0. Make sure you escape backslashes (\) in Windows paths. Example: "E:\\StreamripDownloads\\" 

  at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/rip/config.py:139 in load
      135│         with open(self._path) as cfg:
      136│             try:
      137│                 toml = tomlkit.loads(cfg.read().strip()).items()
      138│             except Exception as e:
    → 139│                 raise Exception(
      140│                     f"Error parsing config file with error {e}. Make sure you escape "
      141│                     r'backslashes (\) in Windows paths. Example: "E:\\StreamripDownloads\\" '
      142│                 )
      143│ 

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = ""
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3
# Max number of API requests to handle per minute
# Set to -1 for no limit
requests_per_minute = -1

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = false
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = ""
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.
[database.downloads]
enabled = true
path = ""

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
[database.failed_downloads]
enabled = true
path = ""

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true

[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than 120 characters
# Setting this to false may cause downloads to fail on some systems
truncate = true

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"

[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"

[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.8"
```

### Operating System

macOS Ventura 13.5

### streamrip version

1.9.7

### Additional context

When I first installed streamrip about a week ago, everything worked fine.  I ran the `rip url [Qobuz artist url]` command and it behaved as intended, downloading all the songs to the default directory.  After that I ended the terminal instance and didn't touch anything until today, when I tried running the same command and encountered the issue.  I know almost nothing about code but it seems like it's an issue with the config.toml file, and only seems to affects commands referencing it (Ex. `rip config` doesn't work but `rip config -h does`).  I tried completely reinstalling streamrip and tomlkit but it still happens on a fresh install, which is confusing me because there of course shouldn't be an error with the default blank config file.
