### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by RobertjanTuit** [nathom/streamrip#491]
### Describe the bug

rip from coundcloud fails: [WinError 2] The system cannot find the file specified

### Command Used

```bash
rip url https://soundcloud.com/dj-pippi/dj-pippi-destino-d-lounge-august-2023
```


### Debug Traceback

```text
rip url https://soundcloud.com/dj-pippi/dj-pippi-destino-d-lounge-august-2023 -vvv
DEBUG:streamrip:Config loaded
DEBUG:streamrip:client_id: 3lrgRJqrM65nUmQzObbOjJTczVQZcnsk, app_version: 1701096691
DEBUG:streamrip:Fetching url https://api-v2.soundcloud.com/announcements with params {'client_id': '3lrgRJqrM65nUmQzObbOjJTczVQZcnsk', 'app_version': '1701096691', 'app_locale': 'en'}
DEBUG:streamrip:Fetching url https://api-v2.soundcloud.com/resolve?url=https://soundcloud.com/dj-pippi/dj-pippi-destino-d-lounge-august-2023 with params {'client_id': '3lrgRJqrM65nUmQzObbOjJTczVQZcnsk', 'app_version': '1701096691', 'app_locale': 'en'}
DEBUG:streamrip:{'artwork_url': 'https://i1.sndcdn.com/artworks-WFemszZQPzjVS7Nx-emk1ng-large.jpg',
 'caption': None,
 'comment_count': 2,
 'commentable': True,
 'created_at': '2023-08-28T10:23:02Z',
 'description': '',
 'display_date': '2023-08-28T10:23:02Z',
 'download_count': 0,
 'downloadable': False,
 'duration': 7198250,
 'embeddable_by': 'all',
 'full_duration': 7198250,
 'genre': '',
 'has_downloads_left': False,
 'id': 1602667896,
 'kind': 'track',
 'label_name': None,
 'last_modified': '2023-08-28T10:23:05Z',
 'license': 'all-rights-reserved',
 'likes_count': 54,
 'media': {'transcodings': [{'duration': 7198250,
                             'format': {'mime_type': 'audio/mpeg',
                                        'protocol': 'hls'},
                             'preset': 'mp3_1_0',
                             'quality': 'sq',
                             'snipped': False,
                             'url': 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1602667896/71237dde-1b38-470b-9479-3c3b52250582/stream/hls'},
                            {'duration': 7198230,
                             'format': {'mime_type': 'audio/ogg; codecs="opus"',
                                        'protocol': 'hls'},
                             'preset': 'opus_0_0',
                             'quality': 'sq',
                             'snipped': False,
                             'url': 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1602667896/c533430a-6975-446a-8ab0-fbfa707a53af/stream/hls'}]},
 'monetization_model': 'NOT_APPLICABLE',
 'permalink': 'dj-pippi-destino-d-lounge-august-2023',
 'permalink_url': 'https://soundcloud.com/dj-pippi/dj-pippi-destino-d-lounge-august-2023',
 'playback_count': 1007,
 'policy': 'ALLOW',
 'public': True,
 'publisher_metadata': {'contains_music': True,
                        'id': 1602667896,
                        'urn': 'soundcloud:tracks:1602667896'},
 'purchase_title': None,
 'purchase_url': None,
 'release_date': None,
 'reposts_count': 8,
 'secret_token': None,
 'sharing': 'public',
 'state': 'finished',
 'station_permalink': 'track-stations:1602667896',
 'station_urn': 'soundcloud:system-playlists:track-stations:1602667896',
 'streamable': True,
 'tag_list': 'Houseibiza2023 housemusic ibizasound summer2023',
 'title': 'Dj Pippi @ Destino D - Lounge August 2023',
 'track_authorization': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJVUyIsInN1YiI6IiIsInJpZCI6ImY1YzU0YTY3LWMzYzItNDA4Ny1iMzk5LWQwNzQzYTk2ZGY4MiIsImlhdCI6MTcwMTEzMTg3OH0.vgsmyoVga3h-pkAYQjd-wFQFKM_KVuBb0zAjYtLHSb8',
 'track_format': 'single-track',
 'uri': 'https://api.soundcloud.com/tracks/1602667896',
 'urn': 'soundcloud:tracks:1602667896',
 'user': {'avatar_url': 'https://i1.sndcdn.com/avatars-94QLA7H5ctWviUbo-y6Egzg-large.jpg',
          'badges': {'pro': False, 'pro_unlimited': True, 'verified': False},
          'city': 'Ibiza',
          'comments_count': 0,
          'country_code': 'ES',
          'created_at': '2010-01-15T16:34:42Z',
          'creator_subscription': {'product': {'id': 'creator-pro-unlimited'}},
          'creator_subscriptions': [{'product': {'id': 'creator-pro-unlimited'}}],
          'description': 'dj pippi\n'
                         ' Legendary Ibiza Dj Pippi as one of the very first '
                         'Ibiza residents he managed to claim a prominent spot '
                         'in the global house scene. He truly is one of the '
                         'creators of that distinct Ibiza sound that is loved '
                         'and respected worldwide\n'
                         '\n'
                         'A musical ambassador and a veteran of acid house, a '
                         'champion of , a dance music pioneer, label owner, '
                         "Legend of Ibiza – you name it, Carl's been there and "
                         'done it, never losing sight of his passions."\n'
                         'www.djpippi.com',
          'first_name': '',
          'followers_count': 6741,
          'followings_count': 21,
          'full_name': '',
          'groups_count': 0,
          'id': 527439,
          'kind': 'user',
          'last_modified': '2020-05-25T22:43:37Z',
          'last_name': '',
          'likes_count': 48,
          'permalink': 'dj-pippi',
          'permalink_url': 'https://soundcloud.com/dj-pippi',
          'playlist_count': 16,
          'playlist_likes_count': 7,
          'reposts_count': None,
          'station_permalink': 'artist-stations:527439',
          'station_urn': 'soundcloud:system-playlists:artist-stations:527439',
          'track_count': 160,
          'uri': 'https://api.soundcloud.com/users/527439',
          'urn': 'soundcloud:users:527439',
          'username': 'Dj Pippi Ibiza',
          'verified': False,
          'visuals': {'enabled': True,
                      'tracking': None,
                      'urn': 'soundcloud:users:527439',
                      'visuals': [{'entry_time': 0,
                                   'urn': 'soundcloud:visuals:86968995',
                                   'visual_url': 'https://i1.sndcdn.com/visuals-000000527439-TkklOw-original.jpg'}]}},
 'user_id': 527439,
 'visuals': None,
 'waveform_url': 'https://wave.sndcdn.com/z2qphX0fJq2w_m.json'}
DEBUG:streamrip:Parsed urls: [('soundcloud', 'track', '1602667896')]
DEBUG:streamrip:Searching for {'id': '1602667896'} in database
DEBUG:streamrip:Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)
DEBUG:streamrip:{'id': '1602667896'}
DEBUG:streamrip:{'downloads': {'folder': 'C:\\Users\\r_tui\\StreamripDownloads', 'source_subdirectories': False, 'concurrency': {'enabled': True, 'max_connections': 3, 'requests_per_minute': -1}}, 'qobuz': {'quality': 3, 'download_booklets': True, 'email': '', 'password': '', 'app_id': '', 'secrets': []}, 'tidal': {'quality': 3, 'download_videos': True, 'user_id': '', 'country_code': '', 'access_token': '', 'refresh_token': '', 'token_expiry': ''}, 'deezer': {'quality': 2, 'arl': '', 'use_deezloader': True, 'deezloader_warnings': True}, 'soundcloud': {'quality': 0, 'client_id': '3lrgRJqrM65nUmQzObbOjJTczVQZcnsk', 'app_version': '1701096691'}, 'youtube': {'quality': 0, 'download_videos': False, 'video_downloads_folder': ''}, 'database': {'downloads': {'enabled': True, 'path': 'C:\\Users\\r_tui\\AppData\\Local\\streamrip\\streamrip\\downloads.db'}, 'failed_downloads': {'enabled': True, 'path': 'C:\\Users\\r_tui\\AppData\\Local\\streamrip\\streamrip\\failed_downloads.db'}}, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'filters': {'extras': False, 'repeats': False, 'non_albums': False, 'features': False, 'non_studio_albums': False, 'non_remaster': False}, 'artwork': {'embed': True, 'size': 'large', 'max_width': -1, 'max_height': -1, 'keep_hires_cover': True}, 'metadata': {'set_playlist_to_album': True, 'new_playlist_tracknumbers': True, 'exclude': []}, 'filepaths': {'add_singles_to_folder': False, 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}{explicit}', 'restrict_characters': False, 'truncate': True}, 'lastfm': {'source': 'qobuz', 'fallback_source': 'deezer'}, 'theme': {'progress_bar': 'dainty'}, 'misc': {'version': '1.9.8'}}
DEBUG:streamrip:Arguments from config: {'restrict_filenames': False, 'truncate_filenames': True, 'parent_folder': 'C:\\Users\\r_tui\\StreamripDownloads', 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}{explicit}', 'embed_cover': True, 'embed_cover_size': 'large', 'keep_hires_cover': True, 'set_playlist_to_album': True, 'stay_temp': False, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'concurrent_downloads': True, 'max_connections': 3, 'new_tracknumbers': True, 'download_videos': True, 'download_booklets': True, 'download_youtube_videos': False, 'youtube_video_downloads_folder': '', 'add_singles_to_folder': False, 'max_artwork_width': -1, 'max_artwork_height': -1, 'exclude_tags': []}
DEBUG:streamrip:Loading metadata
DEBUG:streamrip:Fetching url https://api-v2.soundcloud.com/tracks/1602667896 with params {'client_id': '3lrgRJqrM65nUmQzObbOjJTczVQZcnsk', 'app_version': '1701096691', 'app_locale': 'en'}
DEBUG:streamrip:{'artwork_url': 'https://i1.sndcdn.com/artworks-WFemszZQPzjVS7Nx-emk1ng-large.jpg', 'caption': None, 'commentable': True, 'comment_count': 2, 'created_at': '2023-08-28T10:23:02Z', 'description': '', 'downloadable': False, 'download_count': 0, 'duration': 7198250, 'full_duration': 7198250, 'embeddable_by': 'all', 'genre': '', 'has_downloads_left': False, 'id': 1602667896, 'kind': 'track', 'label_name': None, 'last_modified': '2023-08-28T10:23:05Z', 'license': 'all-rights-reserved', 'likes_count': 54, 'permalink': 'dj-pippi-destino-d-lounge-august-2023', 'permalink_url': 'https://soundcloud.com/dj-pippi/dj-pippi-destino-d-lounge-august-2023', 'playback_count': 1007, 'public': True, 'publisher_metadata': {'id': 1602667896, 'urn': 'soundcloud:tracks:1602667896', 'contains_music': True}, 'purchase_title': None, 'purchase_url': None, 'release_date': None, 'reposts_count': 8, 'secret_token': None, 'sharing': 'public', 'state': 'finished', 'streamable': True, 'tag_list': 'Houseibiza2023 housemusic ibizasound summer2023', 'title': 'Dj Pippi @ Destino D - Lounge August 2023', 'track_format': 'single-track', 'uri': 'https://api.soundcloud.com/tracks/1602667896', 'urn': 'soundcloud:tracks:1602667896', 'user_id': 527439, 'visuals': None, 'waveform_url': 'https://wave.sndcdn.com/z2qphX0fJq2w_m.json', 'display_date': '2023-08-28T10:23:02Z', 'media': {'transcodings': [{'url': 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1602667896/71237dde-1b38-470b-9479-3c3b52250582/stream/hls', 'preset': 'mp3_1_0', 'duration': 7198250, 'snipped': False, 'format': {'protocol': 'hls', 'mime_type': 'audio/mpeg'}, 'quality': 'sq'}, {'url': 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1602667896/c533430a-6975-446a-8ab0-fbfa707a53af/stream/hls', 'preset': 'opus_0_0', 'duration': 7198230, 'snipped': False, 'format': {'protocol': 'hls', 'mime_type': 'audio/ogg; codecs="opus"'}, 'quality': 'sq'}]}, 'station_urn': 'soundcloud:system-playlists:track-stations:1602667896', 'station_permalink': 'track-stations:1602667896', 'track_authorization': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJVUyIsInN1YiI6IiIsInJpZCI6ImY1YzU0YTY3LWMzYzItNDA4Ny1iMzk5LWQwNzQzYTk2ZGY4MiIsImlhdCI6MTcwMTEzMTg3OH0.vgsmyoVga3h-pkAYQjd-wFQFKM_KVuBb0zAjYtLHSb8', 'monetization_model': 'NOT_APPLICABLE', 'policy': 'ALLOW', 'user': {'avatar_url': 'https://i1.sndcdn.com/avatars-94QLA7H5ctWviUbo-y6Egzg-large.jpg', 'first_name': '', 'followers_count': 6741, 'full_name': '', 'id': 527439, 'kind': 'user', 'last_modified': '2020-05-25T22:43:37Z', 'last_name': '', 'permalink': 'dj-pippi', 'permalink_url': 'https://soundcloud.com/dj-pippi', 'uri': 'https://api.soundcloud.com/users/527439', 'urn': 'soundcloud:users:527439', 'username': 'Dj Pippi Ibiza', 'verified': False, 'city': 'Ibiza', 'country_code': 'ES', 'badges': {'pro': False, 'pro_unlimited': True, 'verified': False}, 'station_urn': 'soundcloud:system-playlists:artist-stations:527439', 'station_permalink': 'artist-stations:527439'}}
DEBUG:streamrip:Track meta formatter {'tracknumber': 0, 'artist': 'Dj Pippi Ibiza', 'albumartist': 'Dj Pippi Ibiza', 'composer': None, 'title': 'Dj Pippi @ Destino D - Lounge August 2023', 'albumcomposer': None, 'explicit': False}
DEBUG:streamrip:Formatter keys: {tracknumber}. {artist} - {title}{explicit}
DEBUG:streamrip:'tracknumber'
DEBUG:streamrip:0
DEBUG:streamrip:2
DEBUG:streamrip:'artist'
DEBUG:streamrip:Dj Pippi Ibiza
DEBUG:streamrip:1
DEBUG:streamrip:'title'
DEBUG:streamrip:Dj Pippi @ Destino D - Lounge August 2023
DEBUG:streamrip:1
DEBUG:streamrip:'explicit'
DEBUG:streamrip:False
DEBUG:streamrip:3
DEBUG:streamrip:Formatted path: C:\Users\r_tui\StreamripDownloads\00. Dj Pippi Ibiza - Dj Pippi @ Destino D - Lounge August 2023.mp3
DEBUG:streamrip:Downloading cover from https://i1.sndcdn.com/artworks-WFemszZQPzjVS7Nx-emk1ng-t500x500.jpg
Cover |                                                                                                                                                                                                                                                               | ? left at ?B/s
DEBUG:streamrip:Fetching url https://api-v2.soundcloud.com/media/soundcloud:tracks:1602667896/71237dde-1b38-470b-9479-3c3b52250582/stream/hls with params {'client_id': '3lrgRJqrM65nUmQzObbOjJTczVQZcnsk', 'app_version': '1701096691', 'app_locale': 'en'}
}

  Stack trace:

  13  AppData\Local\Programs\Python\Python312\Lib\site-packages\cleo\application.py:330 in run
       328│
       329│             try:
     → 330│                 exit_code = self._run(io)
       331│             except Exception as e:
       332│                 if not self._catch_exceptions:

  12  AppData\Local\Programs\Python\Python312\Lib\site-packages\rip\cli.py:754 in _run
       752│             logger.addHandler(fh)
       753│
     → 754│         super()._run(io)
       755│
       756│     def create_io(self, input=None, output=None, error_output=None):

  11  AppData\Local\Programs\Python\Python312\Lib\site-packages\cleo\application.py:425 in _run
       423│                 io.set_input(ArgvInput(argv))
       424│
     → 425│         exit_code = self._run_command(command, io)
       426│         self._running_command = None
       427│

  10  AppData\Local\Programs\Python\Python312\Lib\site-packages\cleo\application.py:432 in _run_command
       430│     def _run_command(self, command: Command, io: IO) -> int:
       431│         if self._event_dispatcher is None:
     → 432│             return command.run(io)
       433│
       434│         # Bind before the console.command event,

   9  AppData\Local\Programs\Python\Python312\Lib\site-packages\cleo\commands\base_command.py:118 in run
       116│         io.input.validate()
       117│
     → 118│         status_code = self.execute(io)
       119│
       120│         if status_code is None:

   8  AppData\Local\Programs\Python\Python312\Lib\site-packages\cleo\commands\command.py:85 in execute
        83│
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

   7  AppData\Local\Programs\Python\Python312\Lib\site-packages\rip\cli.py:125 in handle
       123│
       124│         if len(core) > 0:
     → 125│             core.download()
       126│         elif not urls and path is None:
       127│             self.line("Must pass arguments. See rip url -h.")

   6  AppData\Local\Programs\Python\Python312\Lib\site-packages\rip\core.py:314 in download
       312│
       313│             try:
     → 314│                 item.download(**arguments)
       315│                 for item_id in item.downloaded_ids:
       316│                     # Add items row by row

   5  AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\media.py:361 in download
        359│
        360│         elif self.client.source == "soundcloud":
     →  361│             self._soundcloud_download(dl_info)
        362│
        363│         else:

   4  AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\media.py:452 in _soundcloud_download
        450│                 pool.download(callback=update_tqdm_bar)
        451│
     →  452│                 concat_audio_files(pool.files, self.path, "mp3")
        453│
        454│         elif dl_info["type"] == "original":

   3  AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\utils.py:61 in concat_audio_files
        59│     for i in range(num_batches):
        60│         logger.debug("Batch %d", i)
     →  61│         proc = subprocess.run(
        62│             (
        63│                 "ffmpeg",

   2  AppData\Local\Programs\Python\Python312\Lib\subprocess.py:548 in run
        546│         kwargs['stderr'] = PIPE
        547│
     →  548│     with Popen(*popenargs, **kwargs) as process:
        549│         try:
        550│             stdout, stderr = process.communicate(input, timeout=timeout)

   1  AppData\Local\Programs\Python\Python312\Lib\subprocess.py:1026 in __init__
       1024│                             encoding=encoding, errors=errors)
       1025│
     → 1026│             self._execute_child(args, executable, preexec_fn, close_fds,
       1027│                                 pass_fds, cwd, env,
       1028│                                 startupinfo, creationflags, shell,

  FileNotFoundError

  [WinError 2] The system cannot find the file specified

  at AppData\Local\Programs\Python\Python312\Lib\subprocess.py:1538 in _execute_child
      1534│             sys.audit("subprocess.Popen", executable, args, cwd, env)
      1535│
      1536│             # Start the process
      1537│             try:
    → 1538│                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      1539│                                          # no special security
      1540│                                          None, None,
      1541│                                          int(not close_fds),
      1542│                                          creationflags,

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose
Track 00 |██████████| 00:00 left at 267Chunk/s
```


### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "C:\\Users\\r_tui\\StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false



[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3
# Max number of API requests to handle per minute
# Set to -1 for no limit
requests_per_minute = -1



[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []





[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""





[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true





[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = "3lrgRJqrM65nUmQzObbOjJTczVQZcnsk"
app_version = "1701096691"



[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.


[database.downloads]
enabled = true
path = "C:\\Users\\r_tui\\AppData\\Local\\streamrip\\streamrip\\downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads


[database.failed_downloads]
enabled = true
path = "C:\\Users\\r_tui\\AppData\\Local\\streamrip\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.


[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.


[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false



[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true



[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.


[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than 120 characters
# Setting this to false may cause downloads to fail on some systems
truncate = true

# Last.fm playlists are downloaded by searching for the titles of the tracks


[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"



[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"



[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.8"
```


### Operating System

Windows 11

### streamrip version

Rip (version 1.9.7) (But same problem on stable)

### Screenshots and recordings

_No response_

### Additional context

_No response_
