### ISSUE TITLE
[BUG] <AttributeError>

### ISSUE THREAD

**Issue by weyasey** [nathom/streamrip#499]
### Describe the bug

Streamrip been working for months until recently and with no changes a search now errors with the following command:

  AttributeError

  'NoneType' object has no attribute 'json'

  at .local/lib/python3.12/site-packages/streamrip/clients.py:1103 in _api_post
      1099│         :param url:
      1100│         :param data:
      1101│         :param auth:
      1102│         """
    → 1103│         return self.session.post(url, data=data, auth=auth, verify=False).json()
      1104│ 
      1105│ 
      1106│ class SoundCloudClient(Client):
      1107│     """SoundCloudClient."""

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose

### Command Used

```bash
rip search --source tidal 'Rick James'
```

### Debug Traceback

```text
rip search --source tidal 'Rick James' -vvvvv
DEBUG:streamrip:Config loaded
DEBUG:streamrip:searching for Rick James
DEBUG:streamrip:{'quality': 3, 'download_videos': True, 'user_id': 183986298, 'country_code': 'GB', 'access_token': 'eyJXNyIHdfdXNyIiwiY2lkIjozMjM1LCJzVmVyIjowLCJnVmVyIjowLCJpc3MiOiJodHRwczovL2F1dGgudGlkYWwuY29tL3YxIn0.AXw5-b0vOBdJ', 'token_expiry': 1701178043.9870553}
DEBUG:streamrip:Refreshing access token

  Stack trace:

  13  .local/lib/python3.12/site-packages/cleo/application.py:330 in run
       328│ 
       329│             try:
     → 330│                 exit_code = self._run(io)
       331│             except Exception as e:
       332│                 if not self._catch_exceptions:

  12  .local/lib/python3.12/site-packages/rip/cli.py:754 in _run
       752│             logger.addHandler(fh)
       753│ 
     → 754│         super()._run(io)
       755│ 
       756│     def create_io(self, input=None, output=None, error_output=None):

  11  .local/lib/python3.12/site-packages/cleo/application.py:425 in _run
       423│                 io.set_input(ArgvInput(argv))
       424│ 
     → 425│         exit_code = self._run_command(command, io)
       426│         self._running_command = None
       427│ 

  10  .local/lib/python3.12/site-packages/cleo/application.py:432 in _run_command
       430│     def _run_command(self, command: Command, io: IO) -> int:
       431│         if self._event_dispatcher is None:
     → 432│             return command.run(io)
       433│ 
       434│         # Bind before the console.command event,

   9  .local/lib/python3.12/site-packages/cleo/commands/base_command.py:118 in run
       116│         io.input.validate()
       117│ 
     → 118│         status_code = self.execute(io)
       119│ 
       120│         if status_code is None:

   8  .local/lib/python3.12/site-packages/cleo/commands/command.py:85 in execute
        83│ 
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

   7  .local/lib/python3.12/site-packages/rip/cli.py:205 in handle
       203│         core = RipCore(config)
       204│ 
     → 205│         if core.interactive_search(query, source, type):
       206│             core.download()
       207│         else:

   6  .local/lib/python3.12/site-packages/rip/core.py:735 in interactive_search
       733│         :type media_type: str
       734│         """
     → 735│         results = tuple(self.search(source, query, media_type, limit=limit))
       736│ 
       737│         def title(res):

   5  .local/lib/python3.12/site-packages/rip/core.py:643 in search
       641│         logger.debug("searching for %s", query)
       642│ 
     → 643│         client = self.get_client(source)
       644│ 
       645│         if isinstance(client, DeezloaderClient) and media_type == "featured":

   4  .local/lib/python3.12/site-packages/rip/core.py:359 in get_client
       357│         if not client.logged_in:
       358│             try:
     → 359│                 self.login(client)
       360│             except DeezloaderFallback:
       361│                 client = self.clients["deezloader"]

   3  .local/lib/python3.12/site-packages/rip/core.py:384 in login
       382│         while True:
       383│             try:
     → 384│                 client.login(**creds)
       385│                 break
       386│             except AuthenticationError:

   2  .local/lib/python3.12/site-packages/streamrip/clients.py:771 in login
        769│             if self.token_expiry - time.time() < 86400:  # 1 day
        770│                 logger.debug("Refreshing access token")
     →  771│                 self._refresh_access_token()
        772│             else:
        773│                 logger.debug("Logging in with access token")

   1  .local/lib/python3.12/site-packages/streamrip/clients.py:963 in _refresh_access_token
        961│             "scope": "r_usr+w_usr+w_sub",
        962│         }
     →  963│         resp = self._api_post(
        964│             f"{TIDAL_AUTH_URL}/token",
        965│             data,

  AttributeError

  'NoneType' object has no attribute 'json'

  at .local/lib/python3.12/site-packages/streamrip/clients.py:1103 in _api_post
      1099│         :param url:
      1100│         :param data:
      1101│         :param auth:
      1102│         """
    → 1103│         return self.session.post(url, data=data, auth=auth, verify=False).json()
      1104│ 
      1105│ 
      1106│ class SoundCloudClient(Client):
      1107│     """SoundCloudClient."""
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/DATA/Tunes"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false




[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3
# Max number of API requests to handle per minute
# Set to -1 for no limit
requests_per_minute = -1




[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []







[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = 183986298
country_code = "GB"
access_token = "eyJraWQiOiJ2OU1GbFhq Do not change any of the fields below
user_id = 183986298
country_code = "GB"
access_token = "oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo_P7Fw77g"
refresh_token = "ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooOBdJ"
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = 1701178043.9870553







[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true








[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = "rKvLzheaEV2CItTrBrB3vSnqOoo2bFvM"
app_version = "1701944487"




[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.



[database.downloads]
enabled = true
path = "/home/weyasey/.config/streamrip/downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads



[database.failed_downloads]
enabled = true
path = "/home/weyasey/.config/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.



[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.



[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
:


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.



[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than 120 characters
# Setting this to false may cause downloads to fail on some systems
truncate = true

# Last.fm playlists are downloaded by searching for the titles of the tracks



[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"




[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"




[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.8"
(END)
```

### Operating System

Linux

### streamrip version

Rip (version 1.9.7)
