### ISSUE TITLE
[BUG] [Tidal] Failed to download single track - AttributeError  - 'Track' object has no attribute 'folder'

### ISSUE THREAD

**Issue by tiagodj** [nathom/streamrip#500]
### Describe the bug

Hi,

When trying to download a single track, I get this error:

```shell
user@local:~/download/tidal$ rip url https://tidal.com/browse/track/120929272
Logged into Tidal
Downloading T. Rex - Debora

  AttributeError

  'Track' object has no attribute 'folder'

  at ~/.local/share/virtualenvs/user-2kl7PhDV/lib/python3.8/site-packages/streamrip/media.py:233 in _prepare_download
       229│         self.quality = min(
       230│             kwargs["quality"], self.client.max_quality, self.meta.quality
       231│         )
       232│
    →  233│         self.folder = kwargs["parent_folder"] or self.folder
       234│
       235│         if not self.part_of_tracklist and kwargs["add_singles_to_folder"]:
       236│             self.folder = os.path.join(
       237│                 self.folder,
```

### Command Used

```bash
rip url https://tidal.com/browse/track/120929272
```

### Debug Traceback

```text
user@local:~/download/tidal$ rip url https://tidal.com/browse/track/120929272 -vvv
DEBUG:streamrip:Config loaded
DEBUG:streamrip:Parsed urls: [('tidal', 'track', '120929272')]
DEBUG:streamrip:Searching for {'id': '120929272'} in database
DEBUG:streamrip:Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)
DEBUG:streamrip:{'quality': 3, 'download_videos': False, 'user_id': 182919873, 'country_code': 'BR', 'access_token': '<redacted>', 'refresh_token': '<redacted>', 'token_expiry': 1703166571.9940212}
DEBUG:streamrip:Logging in with access token
Logged into Tidal
DEBUG:streamrip:Config saved: /var/services/homes/user/.config/streamrip/config.toml
DEBUG:streamrip:{'id': '120929272'}
DEBUG:streamrip:{'downloads': {'folder': '', 'source_subdirectories': False, 'concurrency': {'enabled': True, 'max_connections': 3}}, 'qobuz': {'quality': 3, 'download_booklets': True, 'email': '', 'password': '', 'app_id': '', 'secrets': []}, 'tidal': {'quality': 3, 'download_videos': False, 'user_id': 182919873, 'country_code': 'BR', 'access_token': '<redacted>', 'refresh_token': '<redacted>', 'token_expiry': 1703166571.9940212}, 'deezer': {'quality': 2, 'arl': '', 'use_deezloader': True, 'deezloader_warnings': True}, 'soundcloud': {'quality': 0, 'client_id': '', 'app_version': ''}, 'youtube': {'quality': 0, 'download_videos': False, 'video_downloads_folder': ''}, 'database': {'downloads': {'enabled': True, 'path': '/var/services/homes/user/.config/streamrip/downloads.db'}, 'failed_downloads': {'enabled': True, 'path': '/var/services/homes/user/.config/streamrip/failed_downloads.db'}}, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'filters': {'extras': False, 'repeats': False, 'non_albums': False, 'features': False, 'non_studio_albums': False, 'non_remaster': False}, 'artwork': {'embed': True, 'size': 'large', 'max_width': -1, 'max_height': -1, 'keep_hires_cover': True}, 'metadata': {'set_playlist_to_album': True, 'new_playlist_tracknumbers': True, 'exclude': []}, 'filepaths': {'add_singles_to_folder': False, 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}{explicit}', 'restrict_characters': False, 'truncate': True}, 'lastfm': {'source': 'qobuz', 'fallback_source': 'deezer'}, 'theme': {'progress_bar': 'dainty'}, 'misc': {'version': '1.9.6'}}
DEBUG:streamrip:Arguments from config: {'restrict_filenames': False, 'truncate_filenames': True, 'parent_folder': '', 'folder_format': '{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]', 'track_format': '{tracknumber}. {artist} - {title}{explicit}', 'embed_cover': True, 'embed_cover_size': 'large', 'keep_hires_cover': True, 'set_playlist_to_album': True, 'stay_temp': False, 'conversion': {'enabled': False, 'codec': 'ALAC', 'sampling_rate': 48000, 'bit_depth': 24, 'lossy_bitrate': 320}, 'concurrent_downloads': True, 'max_connections': 3, 'new_tracknumbers': True, 'download_videos': False, 'download_booklets': True, 'download_youtube_videos': False, 'youtube_video_downloads_folder': '', 'add_singles_to_folder': False, 'max_artwork_width': -1, 'max_artwork_height': -1, 'exclude_tags': []}
DEBUG:streamrip:Loading metadata
DEBUG:streamrip:{'id': 120929272, 'title': 'Debora', 'duration': 188, 'replayGain': -8.94, 'peak': 0.998932, 'allowStreaming': True, 'streamReady': True, 'adSupportedStreamReady': True, 'djReady': True, 'stemReady': False, 'streamStartDate': '2019-10-18T00:00:00.000+0000', 'premiumStreamingOnly': False, 'trackNumber': 7, 'volumeNumber': 1, 'version': None, 'popularity': 5, 'copyright': 'An A&M Records Release; ℗ 1968 Straight Ahead Productions Ltd., under exclusive license to A&M Records, Inc.', 'url': 'http://www.tidal.com/track/120929272', 'isrc': 'GBCHM0000023', 'editable': False, 'explicit': False, 'audioQuality': 'LOSSLESS', 'audioModes': ['STEREO'], 'mediaMetadata': {'tags': ['LOSSLESS']}, 'artist': {'id': 62165, 'name': 'T. Rex', 'type': 'MAIN', 'picture': '8316c037-1b51-49b9-b87c-da09ef4ef736'}, 'artists': [{'id': 62165, 'name': 'T. Rex', 'type': 'MAIN', 'picture': '8316c037-1b51-49b9-b87c-da09ef4ef736'}], 'album': {'id': 120929265, 'title': 'Get It On: The Collection', 'cover': 'c5cd8caf-a396-4eb9-b4f7-e7f32b332879', 'vibrantColor': '#f04423', 'videoCover': None}, 'mixes': {'TRACK_MIX': '001ffcd2d5c502cabeb913c5ca8fdf'}}
DEBUG:streamrip:{'id': 120929272, 'title': 'Debora', 'duration': 188, 'replayGain': -8.94, 'peak': 0.998932, 'allowStreaming': True, 'streamReady': True, 'adSupportedStreamReady': True, 'djReady': True, 'stemReady': False, 'streamStartDate': '2019-10-18T00:00:00.000+0000', 'premiumStreamingOnly': False, 'trackNumber': 7, 'volumeNumber': 1, 'version': None, 'popularity': 5, 'copyright': 'An A&M Records Release; ℗ 1968 Straight Ahead Productions Ltd., under exclusive license to A&M Records, Inc.', 'url': 'http://www.tidal.com/track/120929272', 'isrc': 'GBCHM0000023', 'editable': False, 'explicit': False, 'audioQuality': 'LOSSLESS', 'audioModes': ['STEREO'], 'mediaMetadata': {'tags': ['LOSSLESS']}, 'artist': {'id': 62165, 'name': 'T. Rex', 'type': 'MAIN', 'picture': '8316c037-1b51-49b9-b87c-da09ef4ef736'}, 'artists': [{'id': 62165, 'name': 'T. Rex', 'type': 'MAIN', 'picture': '8316c037-1b51-49b9-b87c-da09ef4ef736'}], 'album': {'id': 120929265, 'title': 'Get It On: The Collection', 'cover': 'c5cd8caf-a396-4eb9-b4f7-e7f32b332879', 'vibrantColor': '#f04423', 'videoCover': None}, 'mixes': {'TRACK_MIX': '001ffcd2d5c502cabeb913c5ca8fdf'}}
Downloading T. Rex - Debora


  Stack trace:

  9  ~/.local/share/virtualenvs/user-2kl7PhDV/lib/python3.8/site-packages/cleo/application.py:330 in run
      328│
      329│             try:
    → 330│                 exit_code = self._run(io)
      331│             except Exception as e:
      332│                 if not self._catch_exceptions:

  8  ~/.local/share/virtualenvs/user-2kl7PhDV/lib/python3.8/site-packages/rip/cli.py:762 in _run
      760│             logger.addHandler(fh)
      761│
    → 762│         super()._run(io)
      763│
      764│     def create_io(self, input=None, output=None, error_output=None):

  7  ~/.local/share/virtualenvs/user-2kl7PhDV/lib/python3.8/site-packages/cleo/application.py:425 in _run
      423│                 io.set_input(ArgvInput(argv))
      424│
    → 425│         exit_code = self._run_command(command, io)
      426│         self._running_command = None
      427│

  6  ~/.local/share/virtualenvs/user-2kl7PhDV/lib/python3.8/site-packages/cleo/application.py:432 in _run_command
      430│     def _run_command(self, command: Command, io: IO) -> int:
      431│         if self._event_dispatcher is None:
    → 432│             return command.run(io)
      433│
      434│         # Bind before the console.command event,

  5  ~/.local/share/virtualenvs/user-2kl7PhDV/lib/python3.8/site-packages/cleo/commands/base_command.py:118 in run
      116│         io.input.validate()
      117│
    → 118│         status_code = self.execute(io)
      119│
      120│         if status_code is None:

  4  ~/.local/share/virtualenvs/user-2kl7PhDV/lib/python3.8/site-packages/cleo/commands/command.py:85 in execute
       83│
       84│         try:
    →  85│             return self.handle()
       86│         except KeyboardInterrupt:
       87│             return 1

  3  ~/.local/share/virtualenvs/user-2kl7PhDV/lib/python3.8/site-packages/rip/cli.py:125 in handle
      123│
      124│         if len(core) > 0:
    → 125│             core.download()
      126│         elif not urls and path is None:
      127│             self.line("Must pass arguments. See rip url -h.")

  2  ~/.local/share/virtualenvs/user-2kl7PhDV/lib/python3.8/site-packages/rip/core.py:314 in download
      312│
      313│             try:
    → 314│                 item.download(**arguments)
      315│                 for item_id in item.downloaded_ids:
      316│                     # Add items row by row

  1  ~/.local/share/virtualenvs/user-2kl7PhDV/lib/python3.8/site-packages/streamrip/media.py:284 in download
       282│             secho(f"Downloading {self!s}\n", bold=True)
       283│
    →  284│         self._prepare_download(
       285│             quality=quality,
       286│             parent_folder=parent_folder,

  AttributeError

  'Track' object has no attribute 'folder'

  at ~/.local/share/virtualenvs/user-2kl7PhDV/lib/python3.8/site-packages/streamrip/media.py:233 in _prepare_download
       229│         self.quality = min(
       230│             kwargs["quality"], self.client.max_quality, self.meta.quality
       231│         )
       232│
    →  233│         self.folder = kwargs["parent_folder"] or self.folder
       234│
       235│         if not self.part_of_tracklist and kwargs["add_singles_to_folder"]:
       236│             self.folder = os.path.join(
       237│                 self.folder,
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = ""
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false








[downloads.concurrency]
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
enabled = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
max_connections = 3








[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

email = ""
# This is an md5 hash of the plaintext password
password = ""
# Do not change
app_id = ""
# Do not change
secrets = []








[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = false

# Do not change any of the fields below
user_id = 182919873
country_code = "BR"
access_token = "<redacted>"
refresh_token = "<redacted>"
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = 1703166571.9940212








[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true








[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""








[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

# This stores a list of item IDs so that repeats are not downloaded.







[database.downloads]
enabled = true
path = "/var/services/homes/user/.config/streamrip/downloads.db"

# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads







[database.failed_downloads]
enabled = true
path = "/var/services/homes/user/.config/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.







[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.







[filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false








[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
size = "large"
# Both of these options limit the size of the embedded artwork. If their values
# are larger than the actual dimensions of the image, they will be ignored.
# If either value is -1, the image is left untouched.
max_width = -1
max_height = -1
# Save the cover image at the highest quality as a seperate jpg file
keep_hires_cover = true








[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# Replaces the original track's tracknumber with it's position in the playlist
new_playlist_tracknumbers = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.







[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "container", "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than 120 characters
# Setting this to false may cause downloads to fail on some systems
truncate = true


# Last.fm playlists are downloaded by searching for the titles of the tracks







[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "deezer"








[theme]
# Options: "dainty" or "plain"
progress_bar = "dainty"








[misc]
# Metadata to identify this config file. Do not change.
version = "1.9.6"
```

### Operating System

Linux (Synology DSM 7)

### streamrip version

1.9.7
