### ISSUE TITLE
[BUG] config-path not a valid option

### ISSUE THREAD

**Issue by mon5termatt** [nathom/streamrip#502]
### Describe the bug

`rip url` doesn't want to take the "--config-path" argument.

### Command Used

```bash
rip url https://www.deezer.com/us/artist/4244987 --config-path=/plex/streamrip/Configs/artist.toml
```

<details open>
<summary>Bash Script Used.</summary>
<br>

```bash
#!/bin/bash

# Function to check if a string is numeric
is_numeric() {
  local input=$1
  if [[ $input =~ ^[0-9]+$ ]]; then
    return 0  # Numeric
  else
    return 1  # Not numeric
  fi
}

# Check if an argument is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <artist_name_or_id>"
  exit 1
fi

# Get the artist name or ID from the command line arguments
input=$1

# Determine if the input is numeric (artist ID) or a string (artist name)
if is_numeric "$input"; then
  # Input is numeric, treat it as an artist ID
  id=$input

  # Use the artist ID to fetch additional details
  output=$(curl -s "https://api.deezer.com/artist/$id")

  # Check if the artist with the given ID exists
  if [ "$(echo "$output" | jq -r '.error.code')" == "800" ]; then
    echo "Artist not found"
    exit 1
  fi

  # Extract name using jq
  name=$(echo "$output" | jq -r '.name')

  echo "ID: $id corresponds to Artist: $name"
else
  # Input is a string, treat it as an artist name
  artist="$*"

  # URL encode the artist name for the API request
  encoded_artist=$(echo "$artist" | sed 's/ /%20/g')

  # Use jq to parse JSON response (assuming jq is installed)
  output=$(curl -s "https://api.deezer.com/search/artist?q=$encoded_artist" | jq -r '.data[0]')

  # Check if the artist was found
  if [ "$output" == "null" ]; then
    echo "Artist not found"
    exit 1
  fi

  # Extract name and id using jq
  name=$(echo "$output" | jq -r '.name')
  id=$(echo "$output" | jq -r '.id')

  echo "Name: $name, ID: $id"
fi

# Ask for user confirmation
read -p "Do you want to download content (y/n)? " -n 1 -r
echo    # move to a new line after the user input

if [[ $REPLY =~ ^[Yy]$ ]]; then
  # Rip content using the obtained artist ID
  rip url "https://www.deezer.com/us/artist/$id" --config-path /plex/streamrip/configs/artist.toml
  echo "Download completed."
else
  echo "Download canceled."
fi
```

</details>

### Debug Traceback

```text
root@d-fi:/plex/scripts# rip url https://www.deezer.com/us/artist/4244987 --config-path=/plex/streamrip/Configs/artist.toml -vvv
Usage: rip url [OPTIONS] URLS...
Try 'rip url --help' for help.

Error: No such option: --config-path
```

### Config File

<details open>
<summary>Config</summary>
<br>

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/plex/MUSIC"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially.
# If you are converting the tracks, or have fast internet, this will
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 10
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = -1

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = true
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = "REDACTED"
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = "REDACTED"
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = "REDACTED"
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = false
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "/root/StreamripDownloads/YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database
downloads_path = "/plex/streamrip/db/downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "/plex/streamrip/db/incomplete.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "FLAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this.
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding.
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name.
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = true
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
#folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
folder_format = "{year} - {title}"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber} - {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = true
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for
# on this one.
fallback_source = "deezer"

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0"
```

</details>

### Operating System

Debian 12

### streamrip version

2.0
