### ISSUE TITLE
[BUG] embed_max_width option in config file not working?

### ISSUE THREAD

**Issue by Tom4tot** [nathom/streamrip#538]
### Describe the bug

If I change the -1 value to something like 1500, the setting gets ignored and the full cover is downloaded. Am i using the option wrongly or is not working

### Command Used

```bash
rip url
```

### Debug Traceback

```text
rip url
```

### Config File

```toml
[artwork]
# Write the image to the audio file
embed = false
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = 1500
```

### Operating System

Windows 11

### streamrip version

2.0.2
