### ISSUE TITLE
[BUG] source_subdirectories does not use subfolders any more

### ISSUE THREAD

**Issue by AllKind** [nathom/streamrip#551]
### Describe the bug

Using `source_subdirectories = true` does not create / honour the respective folders any more (tested Qobuz and Tidal).

### Command Used

```bash
rip url https://play.qobuz.com/artist/XXXXX
rip url https://tidal.com/browse/track/XXXXX
```

### Debug Traceback

```text
No traceback as download works.
```

### Config File

```toml
downloads]
# Folder where tracks are downloaded to
folder = "/storage/pub/tmp/stream_dl/streamrip"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = true

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 3
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60
```

### Operating System

Linux (Mint 21.3)

### streamrip version

2.0.2

### Additional context

python 3.10
btw: had to uninstall (after upgrade to 2.0.2) and reinstall streamrip (pip3) to get the login (email) working with Qobuz. Else it would fail with invalid secrets error.
