### ISSUE TITLE
[BUG] ClientConnectorError: Cannot connect to host play.qobuz.com even though I can connect to Qobuz via any other way

### ISSUE THREAD

**Issue by jieweix** [nathom/streamrip#552]
### Describe the bug

I need a proxy to connect to Qobuz, and I do have a working proxy which does that. After I set the proxy for the terminal shell, I can load the Qobuz webpage using `w3m`, get HTTP 200 from `curl` and `requests.get` in Python environment, and download an image file from Qobuz server using `wget`. However, when I try to search on Qobuz or download from a Qobuz URL using `streamrip`, it failed to connect.

### Command Used

```bash
rip --verbose url https://play.qobuz.com/album/f3quv31a87xya
```

### Debug Traceback

```text
GitHub says "Comment is too long (maximum is 65536 characters)", so see this pastebin: https://pastebin.ubuntu.com/p/FwXKV4fkhv/
```

### Config File

```toml
Default, except:

# Folder where tracks are downloaded to
folder = "/mnt/f/qobuz"

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 4

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = true
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = "*userid*"
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = "*token*"
```

### Operating System

I've tried this on Windows, WSL Ubuntu and WSL Arch

### streamrip version

2.0.2
