### ISSUE TITLE
[BUG] PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by rpuls** [nathom/streamrip#566]
### Describe the bug

Failing to download playlist from tidal. Tried running command again, this time it skips some items and fails immediately.
I tried deleting the folder with the downloaded files, however, th db still think they are there, so it is still skipping them, and goes straight to the failing item.

I would like to be able to reset db, but this doesn't seem to have a commend?

It seems to me that track with id: 323123591 is problematic. Maybe we could skip problematic items and continue instead of terminating the program? 🙏

### Command Used

```bash
rip url https://tidal.com/browse/playlist/a3738798-a613-4e88-93aa-7e34a3de94cc
```

### Debug Traceback

```text
[21:19:47] INFO     Track (311253571) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (321635714) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (251481746) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (318443301) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (321522195) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (320434340) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (306964785) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (327558528) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (325880000) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (310685952) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (323008120) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (315074120) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (326421183) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (311189703) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (319372398) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (307170434) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (330933034) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (295411261) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (307068793) already logged in database. Skipping.                               playlist.py:46
           INFO     Track (322306673) already logged in database. Skipping.                               playlist.py:46
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\username\miniconda3\Lib\site-packages\streamrip\rip\cli.py:158 in url                      │
│                                                                                                  │
│   155 │   │   async with Main(cfg) as main:                                                      │
│   156 │   │   │   await main.add_all(urls)                                                       │
│   157 │   │   │   await main.resolve()                                                           │
│ ❱ 158 │   │   │   await main.rip()                                                               │
│   159                                                                                            │
│   160                                                                                            │
│   161 @rip.command()                                                                             │
│                                                                                                  │
│ C:\Users\username\miniconda3\Lib\site-packages\streamrip\rip\main.py:165 in rip                     │
│                                                                                                  │
│   162 │                                                                                          │
│   163 │   async def rip(self):                                                                   │
│   164 │   │   """Download all resolved items."""                                                 │
│ ❱ 165 │   │   await asyncio.gather(*[item.rip() for item in self.media])                         │
│   166 │                                                                                          │
│   167 │   async def search_interactive(self, source: str, media_type: str, query: str):          │
│   168 │   │   client = await self.get_logged_in_client(source)                                   │
│                                                                                                  │
│                                     ... 5 frames hidden ...                                      │
│                                                                                                  │
│ C:\Users\username\miniconda3\Lib\site-packages\streamrip\client\tidal.py:322 in _api_request        │
│                                                                                                  │
│   319 │   │                                                                                      │
│   320 │   │   async with self.rate_limiter:                                                      │
│   321 │   │   │   async with self.session.get(f"{BASE}/{path}", params=params) as resp:          │
│ ❱ 322 │   │   │   │   resp.raise_for_status()                                                    │
│   323 │   │   │   │   return await resp.json()                                                   │
│   324                                                                                            │
│                                                                                                  │
│ C:\Users\username\miniconda3\Lib\site-packages\aiohttp\client_reqrep.py:1059 in raise_for_status    │
│                                                                                                  │
│   1056 │   │   │   # reason should always be not None for a started response                     │
│   1057 │   │   │   assert self.reason is not None                                                │
│   1058 │   │   │   self.release()                                                                │
│ ❱ 1059 │   │   │   raise ClientResponseError(                                                    │
│   1060 │   │   │   │   self.request_info,                                                        │
│   1061 │   │   │   │   self.history,                                                             │
│   1062 │   │   │   │   status=self.status,                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ClientResponseError: 404, message='Not Found',
url=URL('https://api.tidalhifi.com/v1/tracks/323123591?countryCode=NL&limit=100')

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in _run_module_as_main:198                                                                       │
│ in _run_code:88                                                                                  │
│                                                                                                  │
│                                     ... 15 frames hidden ...                                     │
│                                                                                                  │
│ C:\Users\username\miniconda3\Lib\shutil.py:622 in _rmtree_unsafe                                    │
│                                                                                                  │
│    619 │   │   │   try:                                                                          │
│    620 │   │   │   │   os.unlink(fullname)                                                       │
│    621 │   │   │   except OSError:                                                               │
│ ❱  622 │   │   │   │   onerror(os.unlink, fullname, sys.exc_info())                              │
│    623 │   try:                                                                                  │
│    624 │   │   os.rmdir(path)                                                                    │
│    625 │   except OSError:                                                                       │
│                                                                                                  │
│ C:\Users\username\miniconda3\Lib\shutil.py:620 in _rmtree_unsafe                                    │
│                                                                                                  │
│    617 │   │   │   _rmtree_unsafe(fullname, onerror)                                             │
│    618 │   │   else:                                                                             │
│    619 │   │   │   try:                                                                          │
│ ❱  620 │   │   │   │   os.unlink(fullname)                                                       │
│    621 │   │   │   except OSError:                                                               │
│    622 │   │   │   │   onerror(os.unlink, fullname, sys.exc_info())                              │
│    623 │   try:                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process:
"C:\\Users\\username\\StreamripDownloads\\Winter '23 curated\\__artwork\\cover3231172209921221889.jpg"
sys:1: RuntimeWarning: coroutine 'Playlist.download.<locals>._resolve_download' was never awaited
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "C:\\Users\\username\\StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = false
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = ""
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = private....
country_code = "NL"
access_token = "removed for privacy reasons"
refresh_token = "removed for privacy reasons"
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = 1705773592.8340158

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "C:\\Users\\username\\StreamripDownloads\\YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "C:\\Users\\username\\AppData\\Roaming\\streamrip\\downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "C:\\Users\\username\\AppData\\Roaming\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0"
```

### Operating System

window 11

### streamrip version

2.0.2
