### ISSUE TITLE
[REGRESS] using \\ in folder_format

### ISSUE THREAD

**Issue by benzekat75** [nathom/streamrip#573]
### Describe the bug

in previous version rip allowed creating subfolders through the folder_format
now when trying the same, the \\ are removed from the folder_format and the values are concatenated

before: path_to_ripfolder\Artist\Album
after: path_to_ripfolder\ArtistAlbum

### Command Used

```bash
rip url whatever
```

### Debug Traceback

```text
no logs
```

### Config File

```toml
[filepaths]
folder_format = "{albumartist}\\{title} ({year}) [{container}]"
```

### Operating System

Windows

### streamrip version

2.0.3
