### ISSUE TITLE
[REGRESS] "Disc" subfolders ?

### ISSUE THREAD

**Issue by benzekat75** [nathom/streamrip#577]
### Describe the bug

in previous versions there was a sub folder created per disc
now it seems all tracks are located in the same folder

### Command Used

```bash
rip url http://whatever

(was a Qobuz rip)
```

### Debug Traceback

```text
n/a
```

### Config File

```toml
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
#folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
folder_format = "{albumartist} - {title} ({year}) [{container}]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120
```

### Operating System

Windows

### streamrip version

2.0.3
