### ISSUE TITLE
[BUG] <title> IndexError: list index out of range (downloading a lastfm playlist)

### ISSUE THREAD

**Issue by goauld2001** [nathom/streamrip#579]
### Describe the bug

I can donwload ablums from Deezer without any problem.
I have several playlist in my last.fm portal and when I tried to download it with "rip lastfm --source deezer https://www.last.fm/user/goauld2/playlists/12878537", I got the error: "IndexError: list index out of range".

Each playlist I tried to download from last.fm comes to same error.

Python versión: Python 3.11.2 ( running on a python virtual environment)
rip, version 2.0.3

### Command Used

```bash
rip lastfm --source deezer https://www.last.fm/user/goauld2/playlists/12878537
```

### Debug Traceback

```text
(entorno_virtual_python) orangepi@orangepizero2w:~$ rip -vvv lastfm --source deezer https://www.last.fm/user/goauld2/playlists/12878537 
[18:11:37] DEBUG    Showing all debug logs                                                                      cli.py:102
[18:11:40] DEBUG    Fetching lastfm playlist                                                               playlist.py:314
🌗  Searching for last.fm tracks (0 found, 0 failed, 25 total)[18:11:41] DEBUG    Found result for Nemesis Shriekback on deezer                                          playlist.py:269
🌘  Searching for last.fm tracks (1 found, 0 failed, 25 total)           DEBUG    Found result for Hollow Eyes Red Lorry Yellow Lorry on deezer                          playlist.py:269
🌑  Searching for last.fm tracks (2 found, 0 failed, 25 total)           DEBUG    Found result for Careering Public Image Ltd. on deezer                                 playlist.py:269
🌒  Searching for last.fm tracks (3 found, 0 failed, 25 total)           DEBUG    Found result for Probability Blackouts on deezer                                       playlist.py:269
🌓  Searching for last.fm tracks (4 found, 0 failed, 25 total)           DEBUG    Found result for Tarantula - 12" Version 1 Remastered Colourbox on deezer              playlist.py:269
🌔  Searching for last.fm tracks (5 found, 0 failed, 25 total)           DEBUG    Found result for Beautiful Losers Clock DVA on deezer                                  playlist.py:269
🌖  Searching for last.fm tracks (6 found, 0 failed, 25 total)[18:11:42] DEBUG    Found result for Anti-glory Horsegirl on deezer                                        playlist.py:269
🌘  Searching for last.fm tracks (7 found, 0 failed, 25 total)           DEBUG    Found result for Shadow Dance - 12" Version Eyes of the Nightmare Jungle on deezer     playlist.py:269
🌑  Searching for last.fm tracks (8 found, 0 failed, 25 total)           DEBUG    Found result for I Don't Owe You Anything - 2011 Remaster The Smiths on deezer         playlist.py:269
🌒  Searching for last.fm tracks (9 found, 0 failed, 25 total)           DEBUG    Found result for Winning - Live The Sound on deezer                                    playlist.py:269
🌔  Searching for last.fm tracks (10 found, 0 failed, 25 total)           DEBUG    Found result for I Don't Believe in You - 1997 Remaster Talk Talk on deezer            playlist.py:269
🌕  Searching for last.fm tracks (11 found, 0 failed, 25 total)           DEBUG    Found result for Kill the Sexplayer Girls Against Boys on deezer                       playlist.py:269
🌘  Searching for last.fm tracks (12 found, 0 failed, 25 total)           DEBUG    Found result for Allein Xmal Deutschland on deezer                                     playlist.py:269
🌑  Searching for last.fm tracks (13 found, 0 failed, 25 total)[18:11:43] DEBUG    Found result for Joy Division Oven Gloves Half Man Half Biscuit on deezer              playlist.py:269
🌔  Searching for last.fm tracks (14 found, 0 failed, 25 total)           DEBUG    Found result for Brave New World The Cultural Decay on deezer                          playlist.py:269
🌕  Searching for last.fm tracks (15 found, 0 failed, 25 total)           DEBUG    Found result for Falling Quarter Life on deezer                                        playlist.py:269
🌗  Searching for last.fm tracks (16 found, 0 failed, 25 total)           DEBUG    Found result for Expose Tragic Figures on deezer                                       playlist.py:269
🌒  Searching for last.fm tracks (17 found, 0 failed, 25 total)           DEBUG    Found result for Empire Song Killing Joke on deezer                                    playlist.py:269
🌓  Searching for last.fm tracks (18 found, 0 failed, 25 total)           DEBUG    Found result for M.E. Wand on deezer                                                   playlist.py:269
🌔  Searching for last.fm tracks (19 found, 0 failed, 25 total)           DEBUG    Found result for Rose of Flesh and Blood Plastique Noir on deezer                      playlist.py:269
🌖  Searching for last.fm tracks (20 found, 0 failed, 25 total)[18:11:44] DEBUG    Found result for In The Nighttime Death in June on deezer                              playlist.py:269
🌘  Searching for last.fm tracks (21 found, 0 failed, 25 total)           DEBUG    Found result for Unconscious Melody Preoccupations on deezer                           playlist.py:269
           DEBUG    Found result for Dreamsickle Wombo on deezer                                           playlist.py:269
🌒  Searching for last.fm tracks (23 found, 0 failed, 25 total)           DEBUG    Found result for Paper And Iron (Notes And Coins) - 2001 Remaster XTC on deezer        playlist.py:269
🌔  Searching for last.fm tracks (24 found, 0 failed, 25 total)           DEBUG    Found result for Revenge Ministry on deezer                                            playlist.py:269
           DEBUG    Removing dirs set()                                                                      artwork.py:19
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/orangepi/entorno_virtual_python/bin/rip:8 in <module>                                      │
│                                                                                                  │
│   5 from streamrip.rip import rip                                                                │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(rip())                                                                          │
│   9                                                                                              │
│                                                                                                  │
│ ╭─────────────────────────── locals ────────────────────────────╮                                │
│ │  re = <module 're' from '/usr/lib/python3.11/re/__init__.py'> │                                │
│ │ rip = <HelpColorsGroup rip>                                   │                                │
│ │ sys = <module 'sys' (built-in)>                               │                                │
│ ╰───────────────────────────────────────────────────────────────╯                                │
│                                                                                                  │
│ /home/orangepi/entorno_virtual_python/lib/python3.11/site-packages/click/core.py:1157 in         │
│ __call__                                                                                         │
│                                                                                                  │
│ /home/orangepi/entorno_virtual_python/lib/python3.11/site-packages/click/core.py:1078 in main    │
│                                                                                                  │
│ /home/orangepi/entorno_virtual_python/lib/python3.11/site-packages/click/core.py:1688 in invoke  │
│                                                                                                  │
│ /home/orangepi/entorno_virtual_python/lib/python3.11/site-packages/click/core.py:1434 in invoke  │
│                                                                                                  │
│ /home/orangepi/entorno_virtual_python/lib/python3.11/site-packages/click/core.py:783 in invoke   │
│                                                                                                  │
│ /home/orangepi/entorno_virtual_python/lib/python3.11/site-packages/click/decorators.py:33 in     │
│ new_func                                                                                         │
│                                                                                                  │
│ /home/orangepi/entorno_virtual_python/lib/python3.11/site-packages/streamrip/rip/cli.py:28 in    │
│ wrapper                                                                                          │
│                                                                                                  │
│    25 def coro(f):                                                                               │
│    26 │   @wraps(f)                                                                              │
│    27 │   def wrapper(*args, **kwargs):                                                          │
│ ❱  28 │   │   return asyncio.run(f(*args, **kwargs))                                             │
│    29 │                                                                                          │
│    30 │   return wrapper                                                                         │
│    31                                                                                            │
│                                                                                                  │
│ ╭────────────────────────────────── locals ──────────────────────────────────╮                   │
│ │   args = (<click.core.Context object at 0xffff960b5810>,)                  │                   │
│ │      f = <function lastfm at 0xffff9357b4c0>                               │                   │
│ │ kwargs = {                                                                 │                   │
│ │          │   'source': 'deezer',                                           │                   │
│ │          │   'url': 'https://www.last.fm/user/goauld2/playlists/12878537', │                   │
│ │          │   'fallback_source': None                                       │                   │
│ │          }                                                                 │                   │
│ ╰────────────────────────────────────────────────────────────────────────────╯                   │
│                                                                                                  │
│ /usr/lib/python3.11/asyncio/runners.py:190 in run                                                │
│                                                                                                  │
│   187 │   │   │   "asyncio.run() cannot be called from a running event loop")                    │
│   188 │                                                                                          │
│   189 │   with Runner(debug=debug) as runner:                                                    │
│ ❱ 190 │   │   return runner.run(main)                                                            │
│   191                                                                                            │
│   192                                                                                            │
│   193 def _cancel_all_tasks(loop):                                                               │
│                                                                                                  │
│ ╭────────────────────────── locals ──────────────────────────╮                                   │
│ │  debug = None                                              │                                   │
│ │   main = <coroutine object lastfm at 0xffff934e1c60>       │                                   │
│ │ runner = <asyncio.runners.Runner object at 0xffff935626d0> │                                   │
│ ╰────────────────────────────────────────────────────────────╯                                   │
│                                                                                                  │
│ /usr/lib/python3.11/asyncio/runners.py:118 in run                                                │
│                                                                                                  │
│   115 │   │                                                                                      │
│   116 │   │   self._interrupt_count = 0                                                          │
│   117 │   │   try:                                                                               │
│ ❱ 118 │   │   │   return self._loop.run_until_complete(task)                                     │
│   119 │   │   except exceptions.CancelledError:                                                  │
│   120 │   │   │   if self._interrupt_count > 0:                                                  │
│   121 │   │   │   │   uncancel = getattr(task, "uncancel", None)                                 │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │        context = <_contextvars.Context object at 0xffff9337e700>                             │ │
│ │           coro = <coroutine object lastfm at 0xffff934e1c60>                                 │ │
│ │           self = <asyncio.runners.Runner object at 0xffff935626d0>                           │ │
│ │ sigint_handler = functools.partial(<bound method Runner._on_sigint of                        │ │
│ │                  <asyncio.runners.Runner object at 0xffff935626d0>>, main_task=<Task         │ │
│ │                  finished name='Task-1' coro=<lastfm() done, defined at                      │ │
│ │                  /home/orangepi/entorno_virtual_python/lib/python3.11/site-packages/streamr… │ │
│ │                  exception=IndexError('list index out of range')>)                           │ │
│ │           task = <Task finished name='Task-1' coro=<lastfm() done, defined at                │ │
│ │                  /home/orangepi/entorno_virtual_python/lib/python3.11/site-packages/streamr… │ │
│ │                  exception=IndexError('list index out of range')>                            │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /usr/lib/python3.11/asyncio/base_events.py:653 in run_until_complete                             │
│                                                                                                  │
│    650 │   │   if not future.done():                                                             │
│    651 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')             │
│    652 │   │                                                                                     │
│ ❱  653 │   │   return future.result()                                                            │
│    654 │                                                                                         │
│    655 │   def stop(self):                                                                       │
│    656 │   │   """Stop running the event loop.                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   future = <Task finished name='Task-1' coro=<lastfm() done, defined at                      │ │
│ │            /home/orangepi/entorno_virtual_python/lib/python3.11/site-packages/streamrip/rip… │ │
│ │            exception=IndexError('list index out of range')>                                  │ │
│ │ new_task = False                                                                             │ │
│ │     self = <_UnixSelectorEventLoop running=False closed=True debug=False>                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/orangepi/entorno_virtual_python/lib/python3.11/site-packages/streamrip/rip/cli.py:395 in   │
│ lastfm                                                                                           │
│                                                                                                  │
│   392 │   │   config.session.lastfm.fallback_source = fallback_source                            │
│   393 │   with config as cfg:                                                                    │
│   394 │   │   async with Main(cfg) as main:                                                      │
│ ❱ 395 │   │   │   await main.resolve_lastfm(url)                                                 │
│   396 │   │   │   await main.rip()                                                               │
│   397                                                                                            │
│   398                                                                                            │
│                                                                                                  │
│ ╭──────────────────────────────── locals ─────────────────────────────────╮                      │
│ │             cfg = <streamrip.config.Config object at 0xffff94b43250>    │                      │
│ │          config = <streamrip.config.Config object at 0xffff94b43250>    │                      │
│ │             ctx = <click.core.Context object at 0xffff960b5810>         │                      │
│ │ fallback_source = None                                                  │                      │
│ │            main = <streamrip.rip.main.Main object at 0xffff9337d250>    │                      │
│ │          source = 'deezer'                                              │                      │
│ │             url = 'https://www.last.fm/user/goauld2/playlists/12878537' │                      │
│ ╰─────────────────────────────────────────────────────────────────────────╯                      │
│                                                                                                  │
│ /home/orangepi/entorno_virtual_python/lib/python3.11/site-packages/streamrip/rip/main.py:270 in  │
│ resolve_lastfm                                                                                   │
│                                                                                                  │
│   267 │   │   │   self.config,                                                                   │
│   268 │   │   │   self.database,                                                                 │
│   269 │   │   )                                                                                  │
│ ❱ 270 │   │   playlist = await pending_playlist.resolve()                                        │
│   271 │   │                                                                                      │
│   272 │   │   if playlist is not None:                                                           │
│   273 │   │   │   self.media.append(playlist)                                                    │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                c = LastFmConfig(source='deezer', fallback_source='')                         │ │
│ │           client = <streamrip.client.deezer.DeezerClient object at 0xffff9337dd10>           │ │
│ │  fallback_client = None                                                                      │ │
│ │ pending_playlist = PendingLastfmPlaylist(                                                    │ │
│ │                    │   lastfm_url='https://www.last.fm/user/goauld2/playlists/12878537',     │ │
│ │                    │   client=<streamrip.client.deezer.DeezerClient object at                │ │
│ │                    0xffff9337dd10>,                                                          │ │
│ │                    │   fallback_client=None,                                                 │ │
│ │                    │   config=<streamrip.config.Config object at 0xffff94b43250>,            │ │
│ │                    │   db=Database(                                                          │ │
│ │                    │   │   downloads=<streamrip.db.Downloads object at 0xffff947329d0>,      │ │
│ │                    │   │   failed=<streamrip.db.Failed object at 0xffff934ddd10>             │ │
│ │                    │   )                                                                     │ │
│ │                    )                                                                         │ │
│ │     playlist_url = 'https://www.last.fm/user/goauld2/playlists/12878537'                     │ │
│ │             self = <streamrip.rip.main.Main object at 0xffff9337d250>                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/orangepi/entorno_virtual_python/lib/python3.11/site-packages/streamrip/media/playlist.py:2 │
│ 15 in resolve                                                                                    │
│                                                                                                  │
│   212 │   │   │   │                                                                              │
│   213 │   │   │   │   for title, artist in titles_artists:                                       │
│   214 │   │   │   │   │   requests.append(self._make_query(f"{title} {artist}", s, callback))    │
│ ❱ 215 │   │   │   │   results: list[tuple[str | None, bool]] = await asyncio.gather(*requests)   │
│   216 │   │   else:                                                                              │
│   217 │   │   │                                                                                  │
│   218 │   │   │   def callback():                                                                │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │         artist = 'Ministry'                                                                  │ │
│ │       callback = <function PendingLastfmPlaylist.resolve.<locals>.callback at                │ │
│ │                  0xffff935aff60>                                                             │ │
│ │ playlist_title = 'r/PostPunk | Top weekly posts'                                             │ │
│ │       requests = [                                                                           │ │
│ │                  │   <coroutine object PendingLastfmPlaylist._make_query at 0xffff933ffab0>, │ │
│ │                  │   <coroutine object PendingLastfmPlaylist._make_query at 0xffff933ff890>, │ │
│ │                  │   <coroutine object PendingLastfmPlaylist._make_query at 0xffff933ff9a0>, │ │
│ │                  │   <coroutine object PendingLastfmPlaylist._make_query at 0xffff933ff670>, │ │
│ │                  │   <coroutine object PendingLastfmPlaylist._make_query at 0xffff933ff560>, │ │
│ │                  │   <coroutine object PendingLastfmPlaylist._make_query at 0xffff933ff780>, │ │
│ │                  │   <coroutine object PendingLastfmPlaylist._make_query at 0xffff933ff450>, │ │
│ │                  │   <coroutine object PendingLastfmPlaylist._make_query at 0xffff933fe350>, │ │
│ │                  │   <coroutine object PendingLastfmPlaylist._make_query at 0xffff933ff230>, │ │
│ │                  │   <coroutine object PendingLastfmPlaylist._make_query at 0xffff933fdbe0>, │ │
│ │                  │   ... +15                                                                 │ │
│ │                  ]                                                                           │ │
│ │              s = Status(found=25, failed=0, total=25)                                        │ │
│ │           self = PendingLastfmPlaylist(                                                      │ │
│ │                  │   lastfm_url='https://www.last.fm/user/goauld2/playlists/12878537',       │ │
│ │                  │   client=<streamrip.client.deezer.DeezerClient object at 0xffff9337dd10>, │ │
│ │                  │   fallback_client=None,                                                   │ │
│ │                  │   config=<streamrip.config.Config object at 0xffff94b43250>,              │ │
│ │                  │   db=Database(                                                            │ │
│ │                  │   │   downloads=<streamrip.db.Downloads object at 0xffff947329d0>,        │ │
│ │                  │   │   failed=<streamrip.db.Failed object at 0xffff934ddd10>               │ │
│ │                  │   )                                                                       │ │
│ │                  )                                                                           │ │
│ │         status = <rich.status.Status object at 0xffff934dd450>                               │ │
│ │          title = 'Revenge'                                                                   │ │
│ │ titles_artists = [                                                                           │ │
│ │                  │   ('Nemesis', 'Shriekback'),                                              │ │
│ │                  │   ('Hollow Eyes', 'Red Lorry Yellow Lorry'),                              │ │
│ │                  │   ('Careering', 'Public Image Ltd.'),                                     │ │
│ │                  │   ('Probability', 'Blackouts'),                                           │ │
│ │                  │   ('Tarantula - 12" Version 1 Remastered', 'Colourbox'),                  │ │
│ │                  │   ('Beautiful Losers', 'Clock DVA'),                                      │ │
│ │                  │   ('Anti-glory', 'Horsegirl'),                                            │ │
│ │                  │   ('Shadow Dance - 12" Version', 'Eyes of the Nightmare Jungle'),         │ │
│ │                  │   ("I Don't Owe You Anything - 2011 Remaster", 'The Smiths'),             │ │
│ │                  │   ('Winning - Live', 'The Sound'),                                        │ │
│ │                  │   ... +15                                                                 │ │
│ │                  ]                                                                           │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/orangepi/entorno_virtual_python/lib/python3.11/site-packages/streamrip/media/playlist.py:2 │
│ 72 in _make_query                                                                                │
│                                                                                                  │
│   269 │   │   │   │   logger.debug(f"Found result for {query} on {self.client.source}")          │
│   270 │   │   │   │   s.found += 1                                                               │
│   271 │   │   │   │   return (                                                                   │
│ ❱ 272 │   │   │   │   │   SearchResults.from_pages(self.client.source, "track", pages)           │
│   273 │   │   │   │   │   .results[0]                                                            │
│   274 │   │   │   │   │   .id                                                                    │
│   275 │   │   │   │   ), False                                                                   │
│                                                                                                  │
│ ╭──────────────────────────────────────── locals ─────────────────────────────────────────╮      │
│ │ callback = <function PendingLastfmPlaylist.resolve.<locals>.callback at 0xffff935aff60> │      │
│ │    pages = [{'data': [], 'total': 0}]                                                   │      │
│ │    query = 'In The Nighttime Death in June'                                             │      │
│ │        s = Status(found=25, failed=0, total=25)                                         │      │
│ │     self = PendingLastfmPlaylist(                                                       │      │
│ │            │   lastfm_url='https://www.last.fm/user/goauld2/playlists/12878537',        │      │
│ │            │   client=<streamrip.client.deezer.DeezerClient object at 0xffff9337dd10>,  │      │
│ │            │   fallback_client=None,                                                    │      │
│ │            │   config=<streamrip.config.Config object at 0xffff94b43250>,               │      │
│ │            │   db=Database(                                                             │      │
│ │            │   │   downloads=<streamrip.db.Downloads object at 0xffff947329d0>,         │      │
│ │            │   │   failed=<streamrip.db.Failed object at 0xffff934ddd10>                │      │
│ │            │   )                                                                        │      │
│ │            )                                                                            │      │
│ │    stack = <contextlib.ExitStack object at 0xffff93fb5b10>                              │      │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────╯      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
IndexError: list index out of range
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/home/orangepi/StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = false
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = ""
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 1
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = "dxxxxxxxxxx257144057c76210c83517dee7fd72c824cb9c0cc2ecd6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "/home/orangepi/StreamripDownloads/YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "/home/orangepi/.config/streamrip/downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "/home/orangepi/.config/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Debian 12 ((entorno_virtual_python) orangepi@orangepiDebian 12 (6.1.31-sun50iw9 #1.0.0 SMP Thu Sep  7 17:39:46 CST 2023 aarch64 GNU/Linux)

### streamrip version

rip, version 2.0.3
