### ISSUE TITLE
[BUG] set_playlist_to_album = false dont works

### ISSUE THREAD

**Issue by WMP** [nathom/streamrip#605]
### Describe the bug

I have a playlist on deezer with various tracks and bands, I want them to download as: {Artist}/{Album}/{Artist} - {Track}.mp3 . Unfortunately, when I use the option `set_playlist_to_album = false` they still download to {Playlist}/{Artist} - {Track}.mp3 

### Command Used

```bash
rip url https://deezer.page.link/wJ7pC2wZLLZ4GLhv8
```

### Debug Traceback

```text
Nothing interested
```

### Config File

```toml
[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = false
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = false
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
#folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
folder_format = "{albumartist}"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
#track_format = "{tracknumber}. {artist} - {title}{explicit}"
track_format = "{albumartist} - {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = true
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120
```

### Operating System

Linux

### streamrip version

2.0.3
