### ISSUE TITLE
[BUG] 2.0.5: corrupted downloads

### ISSUE THREAD

**Issue by valefrox** [nathom/streamrip#607]
### Describe the bug

With version 2.0.5 FLAC tracks downloaded from Deezer are corrupted, the last byte of the file is missing.
The same track downloaded with version 2.0.3 from Deezer or with version 2.0.5 from Qobuz is fine.

### Command Used

```bash
rip url https://www.deezer.com/en/album/445985195
```

### Debug Traceback

```text
rip url https://www.deezer.com/en/album/445985195

[19:48:35] DEBUG    Showing all debug logs                                                                   cli.py:102
⠸ Resolving URLs...[19:48:38] DEBUG    Pending tracks: [PendingTrack(id=2299465995,                                            album.py:92
                    album=AlbumMetadata(info=AlbumInfo(id='445985195', quality=2, container='FLAC',
                    label='The Hit House', explicit=False, sampling_rate=44100, bit_depth=16,
                    booklets=None), album='Ordinary World', albumartist='William August Hunt', year='2023',
                    genre=['Rock'], covers=Covers(('original',
                    'https://e-cdns-images.dzcdn.net/images/cover/4405d32117f739541a0f31eba922f40e/1000x100
                    0-000000-80-0-0.jpg', 'F:\\Downloads\\streamrip\\.new\\William August Hunt - Ordinary
                    World\\__artwork\\cover5827721833094463554.jpg')
                    ('large',
                    'https://e-cdns-images.dzcdn.net/images/cover/4405d32117f739541a0f31eba922f40e/500x500-
                    000000-80-0-0.jpg', None)
                    ('small',
                    'https://e-cdns-images.dzcdn.net/images/cover/4405d32117f739541a0f31eba922f40e/250x250-
                    000000-80-0-0.jpg', None)
                    ('thumbnail',
                    'https://e-cdns-images.dzcdn.net/images/cover/4405d32117f739541a0f31eba922f40e/56x56-00
                    0000-80-0-0.jpg', None)), tracktotal=1, disctotal=1, albumcomposer=None, comment=None,
                    compilation=None, copyright=None, date='2023-05-25', description=None, encoder=None,
                    grouping=None, lyrics=None, purchase_date=None),
                    client=<streamrip.client.deezer.DeezerClient object at 0x000001076221E190>,
                    config=<streamrip.config.Config object at 0x000001075DF4B890>,
                    folder='F:\\Downloads\\streamrip\\.new\\William August Hunt - Ordinary World',

           ⠼         failed Resolving URLs...=<streamrip.db.Dummy object at 0x0000010762185B50>),                       
                    cover_path='F:\\Downloads\\streamrip\\.new\\William August Hunt - Ordinary
                    World\\__artwork\\cover5827721833094463554.jpg')]
           DEBUG    Fetching deezer url with token                                                        deezer.py:167
                    AAAAAWW38xNluQxTMSfILtULv2vJzJ-83wI84IVgPnLniGYQHWW3pbGM4uqiI77O1DXylmigzRM9bEXgPihDP
                    fW1xc5rNDprugwCXnYWSZnUlrby2eN3AKN52LEjDkdPeiGCc7nCFlreqb-FvFw
[19:48:39] DEBUG    dz track info: {'ALB_ID': '445985195', 'ALB_PICTURE':                                 deezer.py:190
                    '4405d32117f739541a0f31eba922f40e', 'ALB_TITLE': 'Ordinary World', 'ARTISTS':
                    [{'ART_ID': '76290102', 'ROLE_ID': '0', 'ARTISTS_SONGS_ORDER': '1', 'ART_NAME':
                    'William August Hunt', 'ARTIST_IS_DUMMY': False, 'ART_PICTURE':
                    '2642b0612eb55b0772d562944be4839a', 'RANK': '112395', 'LOCALES': [], '__TYPE__':
                    'artist'}, {'ART_ID': '76290092', 'ROLE_ID': '0', 'ARTISTS_SONGS_ORDER': '2',
                    'ART_NAME': 'Scott Lee Miller', 'ARTIST_IS_DUMMY': False, 'ART_PICTURE':
                    '2deaca1a33863e9f05feb1a5d997a645', 'RANK': '106047', 'LOCALES': [], '__TYPE__':
                    'artist'}, {'ART_ID': '4527305', 'ROLE_ID': '0', 'ARTISTS_SONGS_ORDER': '3',
                    'ART_NAME': 'The Hit House', 'ARTIST_IS_DUMMY': False, 'ART_PICTURE':
                    'dd123256049e0722f67a092f72d3c4c0', 'RANK': '182267', 'LOCALES': [], '__TYPE__':
                    'artist'}], 'ART_ID': '76290102', 'ART_NAME': 'William August Hunt',
                    'ARTIST_IS_DUMMY': False, 'DIGITAL_RELEASE_DATE': '2023-05-25', 'DISK_NUMBER': '1',
                    'DURATION': '293', 'EXPLICIT_LYRICS': '0', 'EXPLICIT_TRACK_CONTENT':
                    {'EXPLICIT_LYRICS_STATUS': 0, 'EXPLICIT_COVER_STATUS': 2}, 'GENRE_ID': '0',
                    'HIERARCHICAL_TITLE': '', 'ISRC': 'QZHNB2318073', 'LYRICS_ID': 0,
                    'PHYSICAL_RELEASE_DATE': '2023-05-27', 'PROVIDER_ID': '452', 'RANK': '105067',
                    'SMARTRADIO': 0, 'SNG_CONTRIBUTORS': {'main_artist': ['William August Hunt', 'Scott
                    Lee Miller', 'The Hit House'], 'composer': ['Duran Duran']}, 'SNG_ID': '2299465995',
                    'SNG_TITLE': 'Ordinary World', 'STATUS': 1, 'TRACK_NUMBER': '1', 'USER_ID': 0,
                    'VERSION': '', 'MD5_ORIGIN': '6a1cd53623e8375b3b06464cdbae68da', 'FILESIZE_AAC_64':
                    '0', 'FILESIZE_MP3_64': '0', 'FILESIZE_MP3_128': '4703711', 'FILESIZE_MP3_256': '0',
                    'FILESIZE_MP3_320': '11759280', 'FILESIZE_FLAC': '29261625', 'FILESIZE': '4703711',
                    'GAIN': '-9.1', 'MEDIA_VERSION': '3', 'TRACK_TOKEN':
                    'AAAAAWW38xNluQxTMSfILtULv2vJzJ-83wI84IVgPnLniGYQHWW3pbGM4uqiI77O1DXylmigzRM9bEXgPihD
                    PfW1xc5rNDprugwCXnYWSZnUlrby2eN3AKN52LEjDkdPeiGCc7nCFlreqb-FvFw',
                    'TRACK_TOKEN_EXPIRE': 1706626131, 'MEDIA': [{'TYPE': 'preview', 'HREF':
                    'http://cdn-preview-7.deezer.com/stream/c-727fa129388bb70bf8eaf9bd6191e375-3.mp3'}],
                    'RIGHTS': {'STREAM_ADS_AVAILABLE': True, 'STREAM_ADS': '2000-01-01',
                    'STREAM_SUB_AVAILABLE': True, 'STREAM_SUB': '2000-01-01'}, '__TYPE__': 'song'}
           DEBUG    Deezer info for downloadable: {'quality': 2, 'id': 2299465995,                   downloadable.py:89
                    'quality_to_size': [4703711, 11759280, 29261625], 'url':
                    'https://cdnt-proxy-6.dzcdn.net/media/1/7dd469131f389fac201b161016010622b8973410
                    03460d6c4473629b22267a19dfb8be78e219d19743e484a24e58f449ced1e3d68f52473a2bd05fdb
                    d47e98322c2750aaa2dcbabb278509d5ac4d91eb?hdnea=exp=1706626131~acl=/media/1/7dd46
                    9131f389fac201b161016010622b897341003460d6c4473629b22267a19dfb8be78e219d19743e48
                    4a24e58f449ced1e3d68f52473a2bd05fdbd47e98322c2750aaa2dcbabb278509d5ac4d91eb*~dat
                    a=user_id=5706048851~hmac=def34e4fe53801cbe9ec2f5afcc0813ff5d4ac9f33290b943ab3a2
                    1dc34445e9'}
           DEBUG    Deezer file (id 2299465995) at                                                  downloadable.py:129
                    https://cdnt-proxy-6.dzcdn.net/media/1/7dd469131f389fac201b161016010622b8973410
                    03460d6c4473629b22267a19dfb8be78e219d19743e484a24e58f449ced1e3d68f52473a2bd05fd
                    bd47e98322c2750aaa2dcbabb278509d5ac4d91eb?hdnea=exp=1706626131~acl=/media/1/7dd
                    469131f389fac201b161016010622b897341003460d6c4473629b22267a19dfb8be78e219d19743
                    e484a24e58f449ced1e3d68f52473a2bd05fdbd47e98322c2750aaa2dcbabb278509d5ac4d91eb*
                    ~data=user_id=5706048851~hmac=def34e4fe53801cbe9ec2f5afcc0813ff5d4ac9f33290b943
                    ab3a21dc34445e9 is encrypted. Decrypting with b'ac1o`o\x7f11-qd=i2g'
[19:48:45] DEBUG    Tagging with [('TITLE', 'Ordinary World'), ('ARTIST', 'William August Hunt'),         tagger.py:253
                    ('ALBUM', 'Ordinary World'), ('ALBUMARTIST', 'William August Hunt'), ('YEAR',
                    '2023'), ('GENRE', 'Rock'), ('TRACKNUMBER', '01'), ('DISCNUMBER', '01'),
                    ('TRACKTOTAL', '01'), ('DISCTOTAL', '01'), ('DATE', '2023-05-25'), ('ISRC',
                    'QZHNB2318073')]
───────────────────────────────────────────── Downloading Ordinary World ──────────────────────────────────────────────
           DEBUG    Removing dirs {'F:\\Downloads\\streamrip\\.new\\William August Hunt - Ordinary        artwork.py:19
                    World\\__artwork'}

rip
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "F:\\Downloads\\streamrip\\.new"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 5
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 2
# This will download booklet pdfs that are included with some albums
download_booklets = false

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = true
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = ""
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = ""
# Do not change
app_id = ""
# Do not change
secrets = ["", ""]

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 2
# This will download videos included in Video Albums.
download_videos = false

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = false
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = false

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "F:\\Downloads\\streamrip\\.new"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = false
# Path to the downloads database 
downloads_path = "C:\\Temp\\downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = false
failed_downloads_path = "C:\\Temp\\failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "FLAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 44100
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 16
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "original"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = false
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = false
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = false
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = true
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title}"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = false

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "deezer"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "qobuz"

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Windows 10

### streamrip version

2.0.5
