### ISSUE TITLE
[BUG] lastfm option does not download tracks using filepath format 

### ISSUE THREAD

**Issue by devlocalhost** [nathom/streamrip#630]
### Describe the bug

When you download a lastfm playlist, streamrip will not follow the file path format, for example:
```
track_format = "{title}"
folder_format = "{albumartist}/{title}"
```
Instead, it'll just put all the tracks in one single location 

### Command Used

```bash
rip lastfm https://www.last.fm/user/dev64/playlists/12906263
```

### Debug Traceback

```text
Output too long
```

### Config File

```toml
[downloads]
folder = "/sdcard/Music"
...
...
[filepaths]
folder_format = "{albumartist}/{title}"
track_format = "{title}"
```

### Operating System

Android 

### streamrip version

2.0.5
