### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by MisterEco** [nathom/streamrip#631]
### Describe the bug

Hello, I want to report an issue that appears in versions  greater than 2.0. The ID tag is not extracting the correct Qobuz album ID. In 1,9,7 version the ID retrieved was = fb97xad16z1wb. In 2.0.4 / 2.0.5 the ID is = 95951056 , which does not correspond with the original ID.

Please repair this issue.

Thank you!

### Command Used

```bash
rip url https://www.qobuz.com/us-en/album/quiet-places-andreas-vollenweider/fb97xad16z1wb
```

### Debug Traceback

```text
C:\Users\azviz>rip -vvv url https://www.qobuz.com/us-en/album/quiet-places-andreas-vollenweider/fb97xad16z1wb
[19:24:54] DEBUG    Showing all debug logs                                                                                                                                                                               cli.py:102
           DEBUG    Raw request signature: trackgetFileUrlformat_id27intentstreamtrack_id195125741708277094.238807410b251c286cfbf64d6b7105f253d9a2e                                                                   .py:414
           DEBUG    Hashed request signature: 31782247f67edf2e62fa23356b60f99e                                                                                                                                        .py:416
           DEBUG    api_request: endpoint=track/getFileUrl, params={'request_ts': 1708277094.2388074, 'request_sig': '31782247f67edf2e62fa23356b60f99e', 'track_id': '19512574', 'format_id': 27, 'intent': 'stream'} .py:431
           DEBUG    Raw request signature: trackgetFileUrlformat_id27intentstreamtrack_id195125741708277094.243807979549437fcc4a3faad4867b5cd25dcb                                                                    .py:414
           DEBUG    Hashed request signature: 429b081693224e75e716fcd409a619eb                                                                                                                                        .py:416
           DEBUG    api_request: endpoint=track/getFileUrl, params={'request_ts': 1708277094.243807, 'request_sig': '429b081693224e75e716fcd409a619eb', 'track_id': '19512574', 'format_id': 27, 'intent': 'stream'}  .py:431
⠸ Logging into[19:24:55] DEBUG    Request params {'email': ' ', 'password': ' ', 'app_id': ' '}
       .py:181
           DEBUG    api_request: endpoint=user/login, params={'email': ' ', 'password': ' ', 'app_id': ' '}                                               .py:431
⠧ Logging into           DEBUG    Login resp: {'user': {'id': 2176837, 'publicId': 'qobuz:user: ', 'email': ' ', 'login': '', 'firstname': None, 'lastname': None,
       .py:183
                    'display_name': '', 'country_code': 'GB', 'language_code': 'en', 'zone': 'GB', 'store': 'GB-en', 'country': 'GB', 'avatar':
                    'https://www.gravatar.com/avatar/bc4a6bdc8225078cbd6be964a3be62f3?s=50&d=mm', 'genre': 'male', 'age': 31, 'creation_date': '', 'subscription': None, 'credential': {'id': ,
                    'label': 'streaming-studio', 'description': 'Subscriber Studio', 'parameters': {'lossy_streaming': True, 'lossless_streaming': True, 'hires_streaming': True, 'hires_purchases_streaming':
                    True, 'mobile_streaming': True, 'offline_streaming': True, 'hfp_purchase': False, 'included_format_group_ids': [1, 2, 3, 4], 'color_scheme': {'logo': '#B8D729'}, 'label': 'Qobuz Studio',
                    'short_label': 'Studio', 'source': 'household'}}, 'last_update': {'favorite': 1707734036, 'favorite_album': 1707734036, 'favorite_artist': 1663409954, 'favorite_track': 1696102249, 'playlist':
                    1677572353, 'purchase': 1663409954}, 'store_features': {'download': True, 'streaming': True, 'editorial': True, 'club': True, 'wallet': True, 'weeklyq': True, 'autoplay': True,
                    'inapp_purchase_subscripton': True, 'opt_in': True, 'music_import': True, 'radio': True}, 'player_settings': {'sonos_audio_format': 7}, 'externals': {}}, 'user_auth_token':
                    'gIO5zBa1wg1n_ka-PT25RPrKt6b2LpupICflFAHGIhz3xyBUvAiGZ38VtvxVc5g6X8jTlLUDBva3WZVZA7FG8w'}
           DEBUG    Logged in to                                                                                                                                                                                .py:190
           DEBUG    request params: {'app_id': ' ', 'album_id': 'fb97xad16z1wb', 'limit': 500, 'offset': 0}                                                                                                   .py:222
           DEBUG    api_request: endpoint=album/get, params={'app_id': ' ', 'album_id': 'fb97xad16z1wb', 'limit': 500, 'offset': 0}                                                                           .py:431
⠧ Resolving URLs...[19:24:57] DEBUG    Pending tracks: [PendingTrack(id=95951057, album=AlbumMetadata(info=AlbumInfo(id='95951056', quality=3, container='FLAC', label='AVAF Music', explicit=False, sampling_rate=44.1, bit_depth=24,     album.py:92
                    booklets=None), album='Quiet Places', albumartist='Andreas Vollenweider', year='2020', genre=['Électronique', 'New Age'], covers=Covers(('original',
                    'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_org.jpg', 'D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg')
                    ('large', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_600.jpg', None)
                    ('small', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_230.jpg', None)
                    ('thumbnail', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_50.jpg', None)), tracktotal=10, disctotal=1, albumcomposer='Various Composers', comment=None, compilation=None,
                    copyright='2020 AVAF Music, Switzerland 2020 AVAF Music, Switzerland', date='2020-10-02', description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None),
                    client=<streamrip.client.qobuz.QobuzClient object at 0x0000013CF7C1AE30>, config=<streamrip.config.Config object at 0x0000013CF7B56DA0>, folder='D:\\Andreas Vollenweider - Quiet Places
                    (2020) [24-44.1] [95951056]', db=Database(downloads=<streamrip.db.Downloads object at 0x0000013CF7C1B400>, failed=<streamrip.db.Failed object at 0x0000013CF7C1B4F0>),
                    cover_path='D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg'), PendingTrack(id=95951058,
                    album=AlbumMetadata(info=AlbumInfo(id='95951056', quality=3, container='FLAC', label='AVAF Music', explicit=False, sampling_rate=44.1, bit_depth=24, booklets=None), album='Quiet Places',
                    albumartist='Andreas Vollenweider', year='2020', genre=['Électronique', 'New Age'], covers=Covers(('original', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_org.jpg',
                    'D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg')
                    ('large', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_600.jpg', None)
                    ('small', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_230.jpg', None)
                    ('thumbnail', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_50.jpg', None)), tracktotal=10, disctotal=1, albumcomposer='Various Composers', comment=None, compilation=None,
                    copyright='2020 AVAF Music, Switzerland 2020 AVAF Music, Switzerland', date='2020-10-02', description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None),
                    client=<streamrip.client.qobuz.QobuzClient object at 0x0000013CF7C1AE30>, config=<streamrip.config.Config object at 0x0000013CF7B56DA0>, folder='D:\\Andreas Vollenweider - Quiet Places
                    (2020) [24-44.1] [95951056]', db=Database(downloads=<streamrip.db.Downloads object at 0x0000013CF7C1B400>, failed=<streamrip.db.Failed object at 0x0000013CF7C1B4F0>),
                    cover_path='D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg'), PendingTrack(id=95951059,
                    album=AlbumMetadata(info=AlbumInfo(id='95951056', quality=3, container='FLAC', label='AVAF Music', explicit=False, sampling_rate=44.1, bit_depth=24, booklets=None), album='Quiet Places',
                    albumartist='Andreas Vollenweider', year='2020', genre=['Électronique', 'New Age'], covers=Covers(('original', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_org.jpg',
                    'D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg')
                    ('large', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_600.jpg', None)
                    ('small', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_230.jpg', None)
                    ('thumbnail', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_50.jpg', None)), tracktotal=10, disctotal=1, albumcomposer='Various Composers', comment=None, compilation=None,
                    copyright='2020 AVAF Music, Switzerland 2020 AVAF Music, Switzerland', date='2020-10-02', description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None),
                    client=<streamrip.client.qobuz.QobuzClient object at 0x0000013CF7C1AE30>, config=<streamrip.config.Config object at 0x0000013CF7B56DA0>, folder='D:\\Andreas Vollenweider - Quiet Places
                    (2020) [24-44.1] [95951056]', db=Database(downloads=<streamrip.db.Downloads object at 0x0000013CF7C1B400>, failed=<streamrip.db.Failed object at 0x0000013CF7C1B4F0>),
                    cover_path='D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg'), PendingTrack(id=95951060,
                    album=AlbumMetadata(info=AlbumInfo(id='95951056', quality=3, container='FLAC', label='AVAF Music', explicit=False, sampling_rate=44.1, bit_depth=24, booklets=None), album='Quiet Places',
                    albumartist='Andreas Vollenweider', year='2020', genre=['Électronique', 'New Age'], covers=Covers(('original', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_org.jpg',
                    'D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg')
                    ('large', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_600.jpg', None)
                    ('small', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_230.jpg', None)
                    ('thumbnail', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_50.jpg', None)), tracktotal=10, disctotal=1, albumcomposer='Various Composers', comment=None, compilation=None,
                    copyright='2020 AVAF Music, Switzerland 2020 AVAF Music, Switzerland', date='2020-10-02', description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None),
                    client=<streamrip.client.qobuz.QobuzClient object at 0x0000013CF7C1AE30>, config=<streamrip.config.Config object at 0x0000013CF7B56DA0>, folder='D:\\Andreas Vollenweider - Quiet Places
                    (2020) [24-44.1] [95951056]', db=Database(downloads=<streamrip.db.Downloads object at 0x0000013CF7C1B400>, failed=<streamrip.db.Failed object at 0x0000013CF7C1B4F0>),
                    cover_path='D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg'), PendingTrack(id=95951061,
                    album=AlbumMetadata(info=AlbumInfo(id='95951056', quality=3, container='FLAC', label='AVAF Music', explicit=False, sampling_rate=44.1, bit_depth=24, booklets=None), album='Quiet Places',
                    albumartist='Andreas Vollenweider', year='2020', genre=['Électronique', 'New Age'], covers=Covers(('original', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_org.jpg',
                    'D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg')
                    ('large', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_600.jpg', None)
                    ('small', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_230.jpg', None)
                    ('thumbnail', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_50.jpg', None)), tracktotal=10, disctotal=1, albumcomposer='Various Composers', comment=None, compilation=None,
                    copyright='2020 AVAF Music, Switzerland 2020 AVAF Music, Switzerland', date='2020-10-02', description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None),
                    client=<streamrip.client.qobuz.QobuzClient object at 0x0000013CF7C1AE30>, config=<streamrip.config.Config object at 0x0000013CF7B56DA0>, folder='D:\\Andreas Vollenweider - Quiet Places
                    (2020) [24-44.1] [95951056]', db=Database(downloads=<streamrip.db.Downloads object at 0x0000013CF7C1B400>, failed=<streamrip.db.Failed object at 0x0000013CF7C1B4F0>),
                    cover_path='D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg'), PendingTrack(id=95951062,
                    album=AlbumMetadata(info=AlbumInfo(id='95951056', quality=3, container='FLAC', label='AVAF Music', explicit=False, sampling_rate=44.1, bit_depth=24, booklets=None), album='Quiet Places',
                    albumartist='Andreas Vollenweider', year='2020', genre=['Électronique', 'New Age'], covers=Covers(('original', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_org.jpg',
                    'D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg')
                    ('large', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_600.jpg', None)
                    ('small', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_230.jpg', None)
                    ('thumbnail', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_50.jpg', None)), tracktotal=10, disctotal=1, albumcomposer='Various Composers', comment=None, compilation=None,
                    copyright='2020 AVAF Music, Switzerland 2020 AVAF Music, Switzerland', date='2020-10-02', description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None),
                    client=<streamrip.client.qobuz.QobuzClient object at 0x0000013CF7C1AE30>, config=<streamrip.config.Config object at 0x0000013CF7B56DA0>, folder='D:\\Andreas Vollenweider - Quiet Places
                    (2020) [24-44.1] [95951056]', db=Database(downloads=<streamrip.db.Downloads object at 0x0000013CF7C1B400>, failed=<streamrip.db.Failed object at 0x0000013CF7C1B4F0>),
                    cover_path='D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg'), PendingTrack(id=95951063,
                    album=AlbumMetadata(info=AlbumInfo(id='95951056', quality=3, container='FLAC', label='AVAF Music', explicit=False, sampling_rate=44.1, bit_depth=24, booklets=None), album='Quiet Places',
                    albumartist='Andreas Vollenweider', year='2020', genre=['Électronique', 'New Age'], covers=Covers(('original', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_org.jpg',
                    'D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg')
                    ('large', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_600.jpg', None)
                    ('small', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_230.jpg', None)
                    ('thumbnail', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_50.jpg', None)), tracktotal=10, disctotal=1, albumcomposer='Various Composers', comment=None, compilation=None,
                    copyright='2020 AVAF Music, Switzerland 2020 AVAF Music, Switzerland', date='2020-10-02', description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None),
                    client=<streamrip.client.qobuz.QobuzClient object at 0x0000013CF7C1AE30>, config=<streamrip.config.Config object at 0x0000013CF7B56DA0>, folder='D:\\Andreas Vollenweider - Quiet Places
                    (2020) [24-44.1] [95951056]', db=Database(downloads=<streamrip.db.Downloads object at 0x0000013CF7C1B400>, failed=<streamrip.db.Failed object at 0x0000013CF7C1B4F0>),
                    cover_path='D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg'), PendingTrack(id=95951064,
                    album=AlbumMetadata(info=AlbumInfo(id='95951056', quality=3, container='FLAC', label='AVAF Music', explicit=False, sampling_rate=44.1, bit_depth=24, booklets=None), album='Quiet Places',
                    albumartist='Andreas Vollenweider', year='2020', genre=['Électronique', 'New Age'], covers=Covers(('original', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_org.jpg',
                    'D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg')
                    ('large', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_600.jpg', None)
                    ('small', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_230.jpg', None)
                    ('thumbnail', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_50.jpg', None)), tracktotal=10, disctotal=1, albumcomposer='Various Composers', comment=None, compilation=None,
                    copyright='2020 AVAF Music, Switzerland 2020 AVAF Music, Switzerland', date='2020-10-02', description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None),
                    client=<streamrip.client.qobuz.QobuzClient object at 0x0000013CF7C1AE30>, config=<streamrip.config.Config object at 0x0000013CF7B56DA0>, folder='D:\\Andreas Vollenweider - Quiet Places
                    (2020) [24-44.1] [95951056]', db=Database(downloads=<streamrip.db.Downloads object at 0x0000013CF7C1B400>, failed=<streamrip.db.Failed object at 0x0000013CF7C1B4F0>),
                    cover_path='D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg'), PendingTrack(id=95951065,
                    album=AlbumMetadata(info=AlbumInfo(id='95951056', quality=3, container='FLAC', label='AVAF Music', explicit=False, sampling_rate=44.1, bit_depth=24, booklets=None), album='Quiet Places',
                    albumartist='Andreas Vollenweider', year='2020', genre=['Électronique', 'New Age'], covers=Covers(('original', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_org.jpg',
                    'D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg')
                    ('large', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_600.jpg', None)
                    ('small', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_230.jpg', None)
                    ('thumbnail', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_50.jpg', None)), tracktotal=10, disctotal=1, albumcomposer='Various Composers', comment=None, compilation=None,
                    copyright='2020 AVAF Music, Switzerland 2020 AVAF Music, Switzerland', date='2020-10-02', description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None),
                    client=<streamrip.client.qobuz.QobuzClient object at 0x0000013CF7C1AE30>, config=<streamrip.config.Config object at 0x0000013CF7B56DA0>, folder='D:\\Andreas Vollenweider - Quiet Places
                    (2020) [24-44.1] [95951056]', db=Database(downloads=<streamrip.db.Downloads object at 0x0000013CF7C1B400>, failed=<streamrip.db.Failed object at 0x0000013CF7C1B4F0>),
                    cover_path='D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg'), PendingTrack(id=95951066,
                    album=AlbumMetadata(info=AlbumInfo(id='95951056', quality=3, container='FLAC', label='AVAF Music', explicit=False, sampling_rate=44.1, bit_depth=24, booklets=None), album='Quiet Places',
                    albumartist='Andreas Vollenweider', year='2020', genre=['Électronique', 'New Age'], covers=Covers(('original', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_org.jpg',
                    'D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg')
                    ('large', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_600.jpg', None)
                    ('small', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_230.jpg', None)
                    ('thumbnail', 'https://static.qobuz.com/images/covers/wb/z1/fb97xad16z1wb_50.jpg', None)), tracktotal=10, disctotal=1, albumcomposer='Various Composers', comment=None, compilation=None,
                    copyright='2020 AVAF Music, Switzerland 2020 AVAF Music, Switzerland', date='2020-10-02', description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None),
                    client=<streamrip.client.qobuz.QobuzClient object at 0x0000013CF7C1AE30>, config=<streamrip.config.Config object at 0x0000013CF7B56DA0>, folder='D:\\Andreas Vollenweider - Quiet Places
                    (2020) [24-44.1] [95951056]', db=Database(downloads=<streamrip.db.Downloads object at 0x0000013CF7C1B400>, failed=<streamrip.db.Failed object at 0x0000013CF7C1B4F0>),
                    cover_path='D:\\Andreas Vollenweider - Quiet Places (2020) [24-44.1] [95951056]\ArtWork\Cover.jpg')]
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "D:\\Qobuz"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 4
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = false
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = ""
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = ""
# Do not change
app_id = ""
# Do not change
secrets = 

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "C:\\Users\\xxxxx\\StreamripDownloads\\YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "C:\\Users\\xxxxx\\AppData\\Roaming\\streamrip\\downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "C:\\Users\\xxxxx\\AppData\\Roaming\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "original"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
#folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"

folder_format = "{albumartist} - {title} ({year}) [{container} ({bit_depth}Bit-{sampling_rate}kHz)] [{id}]"
#folder_format = "-{title} ({year}) [{container} ({bit_depth}Bit-{sampling_rate}kHz)] [{id}]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 180

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Windows 11

### streamrip version

2.0.5
