### ISSUE TITLE
[BUG] Can't download dolby atmos tracks

### ISSUE THREAD

**Issue by chicco-carone** [nathom/streamrip#695]
### Describe the bug

I was trying to download some dolby music from tidal but after downloading the track and running ffprobe it was only stereo. 

### Command Used

```bash
rip -vvv  --no-db -q 3 url https://tidal.com/track/281055338?u
```

### Debug Traceback

```text
[22:51:02] DEBUG    Showing all debug logs                                                                                                                                                                                      cli.py:102
⠋ Resolving URLs...           DEBUG    {'id': 281055338, 'title': 'Stayin\' Alive (From "Saturday Night Fever" Soundtrack)', 'duration': 284, 'replayGain': 0.0, 'peak': 0.0, 'allowStreaming': True, 'streamReady': True,                       tidal.py:104
                    'adSupportedStreamReady': True, 'djReady': True, 'stemReady': False, 'streamStartDate': '2023-03-10T00:00:00.000+0000', 'premiumStreamingOnly': False, 'trackNumber': 1, 'volumeNumber': 1, 'version':
                    None, 'popularity': 12, 'copyright': '℗ 1977 Barry Gibb, The Estate of Robin Gibb and Yvonne Gibb, under exclusive license to Capitol Music Group', 'bpm': None, 'url':
                    'http://www.tidal.com/track/281055338', 'isrc': 'USUG12301809', 'editable': False, 'explicit': False, 'audioQuality': 'LOW', 'audioModes': ['DOLBY_ATMOS'], 'mediaMetadata': {'tags': ['DOLBY_ATMOS']},
                    'artist': {'id': 15096, 'name': 'Bee Gees', 'type': 'MAIN', 'picture': '80beb0ec-c9e0-4a66-af11-06d5c22a0426'}, 'artists': [{'id': 15096, 'name': 'Bee Gees', 'type': 'MAIN', 'picture':
                    '80beb0ec-c9e0-4a66-af11-06d5c22a0426'}], 'album': {'id': 281055336, 'title': 'Staying Alive', 'cover': '9adfe393-bb77-435c-ad29-ecd751f28f1f', 'vibrantColor': '#dacca5', 'videoCover': None}, 'mixes':
                    {'TRACK_MIX': '001d057e4dda78c89383f47bdc851f'}}
⠸ Resolving URLs...           DEBUG    {'trackId': 294512597, 'assetPresentation': 'FULL', 'audioMode': 'STEREO', 'audioQuality': 'LOSSLESS', 'manifestMimeType': 'application/vnd.tidal.bts', 'manifestHash':                                   tidal.py:137
                    '68Cin9Rsyoi1uBPuxxZSSUFHkkoQfYezhyNN6EBHTkM=', 'manifest':
                    'eyJtaW1lVHlwZSI6ImF1ZGlvL2ZsYWMiLCJjb2RlY3MiOiJmbGFjIiwiZW5jcnlwdGlvblR5cGUiOiJOT05FIiwidXJscyI6WyJodHRwczovL3NwLXByLWZhLmF1ZGlvLnRpZGFsLmNvbS9tZWRpYXRyYWNrcy9DQUVhS1JJbk4yVTNNelZrT0RsaE5qTXdOREF5TlRV
                    elpqWmlNMkV3WlRZeU5HUTRaVFpmTmpFdWJYQTAvMC5mbGFjP3Rva2VuPTE3MTczNjUwNjJ+WkRoaU4yTmpNVFZtWTJVNU1HSXlaRFpoTURCa1lUVTFZV1kzTnpZM1pUTXhaamxsTkRSbE9BPT0iXX0=', 'albumReplayGain': -11.08,
                    'albumPeakAmplitude': 0.999969, 'trackReplayGain': -8.46, 'trackPeakAmplitude': 0.988708, 'bitDepth': 16, 'sampleRate': 44100}
           DEBUG    {'mimeType': 'audio/flac', 'codecs': 'flac', 'encryptionType': 'NONE', 'urls':                                                                                                                            tidal.py:143
                    ['https://sp-pr-fa.audio.tidal.com/mediatracks/CAEaKRInN2U3MzVkODlhNjMwNDAyNTUzZjZiM2EwZTYyNGQ4ZTZfNjEubXA0/0.flac?token=1717365062~ZDhiN2NjMTVmY2U5MGIyZDZhMDBkYTU1YWY3NzY3ZTMxZjllNDRlOA==']}
[22:51:11] DEBUG    Tagging with [('TITLE', 'Stayin\' Alive (From "Saturday Night Fever" Soundtrack)'), ('ARTIST', 'Bee Gees'), ('ALBUM', 'Staying Alive'), ('ALBUMARTIST', 'Bee Gees'), ('YEAR', '2023'), ('COPYRIGHT', '℗  tagger.py:253
                    1977 Barry Gibb, The Estate of Robin Gibb and Yvonne Gibb, under exclusive license to Capitol Music Group'), ('TRACKNUMBER', '01'), ('DISCNUMBER', '01'), ('TRACKTOTAL', '01'), ('DISCTOTAL', '01'),
                    ('DATE', '2023-03-10T00:00:00.000+0000'), ('ISRC', 'USUG12301809')]
─────────────────────────────────────────────────────────────────────────────────── Downloading Stayin' Alive (From "Saturday Night Fever" Soundtrack) ───────────────────────────────────────────────────────────────────────────────────
           DEBUG    Removing dirs {'/home/chicco/StreamripDownloads/__artwork'}
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/home/chicco/StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = false

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = false
# Do not change
app_id = "950096963"
# Do not change
secrets = ["10b251c286cfbf64d6b7105f253d9a2e", "979549437fcc4a3faad4867b5cd25dcb"]

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true


[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "/home/chicco/StreamripDownloads/YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "/home/chicco/.config/streamrip/downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "/home/chicco/.config/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "FLAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = false
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Arch Linux

### streamrip version

rip, version 2.0.5

### Additional context

The song link was grabbed from the android application which supports dolby and shows dolby tracks
