### ISSUE TITLE
[BUG] Cover not being embedded with [artwork] embed = true

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [nathom/streamrip#702]
### Describe the bug

Downloading from Deezer, cover is not embedded. The separate .jpg file downloads OK if I enable the option.

### Command Used

```bash
rip url
```


### Debug Traceback

```text
Last login: Fri Jun 14 07:52:14 on ttys000
redacteds-iMac:~ redacted$ rip --version
rip, version 2.0.5
redacteds-iMac:~ redacted$ rip -vvv url https://www.deezer.com/en/album/329906
[07:58:56] DEBUG    Showing all debug logs                            cli.py:102
⠧ Resolving URLs...[07:58:58] DEBUG    Pending tracks: [PendingTrack(id=3480312, album=AlbumMetadata(info=AlbumInfo(id='329906', quality=2, container='FLAC', label='Parlophone Sweden', explicit=False, sampling_rate=44100, bit_depth=16, booklets=None), album='Gyllene Tider',       album.py:92
                    albumartist='Gyllene Tider', year='2006', genre=['Pop'], covers=Covers(('original', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/1000x1000-000000-80-0-0.jpg', None)                                                       
                    ('large', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/500x500-000000-80-0-0.jpg', '/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg')                               
                    ('small', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/250x250-000000-80-0-0.jpg', None)                                                                                                                                   
                    ('thumbnail', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/56x56-000000-80-0-0.jpg', None)), tracktotal=11, disctotal=1, albumcomposer=None, comment=None, compilation=None, copyright=None, date='2006-05-26',            
                    description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None), client=<streamrip.client.deezer.DeezerClient object at 0x106086390>, config=<streamrip.config.Config object at 0x1055971a0>,                                                
                    folder='/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)', db=Database(downloads=<streamrip.db.Dummy object at 0x106086750>, failed=<streamrip.db.Failed object at 0x106086780>), cover_path='/Users/redacted/Downloads/Gyllene                
                    Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg'), PendingTrack(id=3480313, album=AlbumMetadata(info=AlbumInfo(id='329906', quality=2, container='FLAC', label='Parlophone Sweden', explicit=False, sampling_rate=44100,                
                    bit_depth=16, booklets=None), album='Gyllene Tider', albumartist='Gyllene Tider', year='2006', genre=['Pop'], covers=Covers(('original',                                                                                                                     
                    'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/1000x1000-000000-80-0-0.jpg', None)                                                                                                                                           
                    ('large', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/500x500-000000-80-0-0.jpg', '/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg')                               
                    ('small', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/250x250-000000-80-0-0.jpg', None)                                                                                                                                   
                    ('thumbnail', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/56x56-000000-80-0-0.jpg', None)), tracktotal=11, disctotal=1, albumcomposer=None, comment=None, compilation=None, copyright=None, date='2006-05-26',            
                    description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None), client=<streamrip.client.deezer.DeezerClient object at 0x106086390>, config=<streamrip.config.Config object at 0x1055971a0>,                                                
                    folder='/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)', db=Database(downloads=<streamrip.db.Dummy object at 0x106086750>, failed=<streamrip.db.Failed object at 0x106086780>), cover_path='/Users/redacted/Downloads/Gyllene                
                    Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg'), PendingTrack(id=3480314, album=AlbumMetadata(info=AlbumInfo(id='329906', quality=2, container='FLAC', label='Parlophone Sweden', explicit=False, sampling_rate=44100,                
                    bit_depth=16, booklets=None), album='Gyllene Tider', albumartist='Gyllene Tider', year='2006', genre=['Pop'], covers=Covers(('original',                                                                                                                     
                    'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/1000x1000-000000-80-0-0.jpg', None)                                                                                                                                           
                    ('large', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/500x500-000000-80-0-0.jpg', '/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg')                               
                    ('small', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/250x250-000000-80-0-0.jpg', None)                                                                                                                                   
                    ('thumbnail', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/56x56-000000-80-0-0.jpg', None)), tracktotal=11, disctotal=1, albumcomposer=None, comment=None, compilation=None, copyright=None, date='2006-05-26',            
                    description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None), client=<streamrip.client.deezer.DeezerClient object at 0x106086390>, config=<streamrip.config.Config object at 0x1055971a0>,                                                
                    folder='/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)', db=Database(downloads=<streamrip.db.Dummy object at 0x106086750>, failed=<streamrip.db.Failed object at 0x106086780>), cover_path='/Users/redacted/Downloads/Gyllene                
                    Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg'), PendingTrack(id=3480315, album=AlbumMetadata(info=AlbumInfo(id='329906', quality=2, container='FLAC', label='Parlophone Sweden', explicit=False, sampling_rate=44100,                
                    bit_depth=16, booklets=None), album='Gyllene Tider', albumartist='Gyllene Tider', year='2006', genre=['Pop'], covers=Covers(('original',                                                                                                                     
                    'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/1000x1000-000000-80-0-0.jpg', None)                                                                                                                                           
                    ('large', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/500x500-000000-80-0-0.jpg', '/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg')                               
                    ('small', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/250x250-000000-80-0-0.jpg', None)                                                                                                                                   
                    ('thumbnail', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/56x56-000000-80-0-0.jpg', None)), tracktotal=11, disctotal=1, albumcomposer=None, comment=None, compilation=None, copyright=None, date='2006-05-26',            
                    description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None), client=<streamrip.client.deezer.DeezerClient object at 0x106086390>, config=<streamrip.config.Config object at 0x1055971a0>,                                                
                    folder='/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)', db=Database(downloads=<streamrip.db.Dummy object at 0x106086750>, failed=<streamrip.db.Failed object at 0x106086780>), cover_path='/Users/redacted/Downloads/Gyllene                
                    Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg'), PendingTrack(id=3480316, album=AlbumMetadata(info=AlbumInfo(id='329906', quality=2, container='FLAC', label='Parlophone Sweden', explicit=False, sampling_rate=44100,                
                    bit_depth=16, booklets=None), album='Gyllene Tider', albumartist='Gyllene Tider', year='2006', genre=['Pop'], covers=Covers(('original',                                                                                                                     
                    'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/1000x1000-000000-80-0-0.jpg', None)                                                                                                                                           
                    ('large', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/500x500-000000-80-0-0.jpg', '/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg')                               
                    ('small', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/250x250-000000-80-0-0.jpg', None)                                                                                                                                   
                    ('thumbnail', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/56x56-000000-80-0-0.jpg', None)), tracktotal=11, disctotal=1, albumcomposer=None, comment=None, compilation=None, copyright=None, date='2006-05-26',            
                    description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None), client=<streamrip.client.deezer.DeezerClient object at 0x106086390>, config=<streamrip.config.Config object at 0x1055971a0>,                                                
                    folder='/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)', db=Database(downloads=<streamrip.db.Dummy object at 0x106086750>, failed=<streamrip.db.Failed object at 0x106086780>), cover_path='/Users/redacted/Downloads/Gyllene                
                    Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg'), PendingTrack(id=3480317, album=AlbumMetadata(info=AlbumInfo(id='329906', quality=2, container='FLAC', label='Parlophone Sweden', explicit=False, sampling_rate=44100,                
                    bit_depth=16, booklets=None), album='Gyllene Tider', albumartist='Gyllene Tider', year='2006', genre=['Pop'], covers=Covers(('original',                                                                                                                     
                    'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/1000x1000-000000-80-0-0.jpg', None)                                                                                                                                           
                    ('large', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/500x500-000000-80-0-0.jpg', '/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg')                               
                    ('small', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/250x250-000000-80-0-0.jpg', None)                                                                                                                                   
                    ('thumbnail', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/56x56-000000-80-0-0.jpg', None)), tracktotal=11, disctotal=1, albumcomposer=None, comment=None, compilation=None, copyright=None, date='2006-05-26',            
                    description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None), client=<streamrip.client.deezer.DeezerClient object at 0x106086390>, config=<streamrip.config.Config object at 0x1055971a0>,                                                
                    folder='/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)', db=Database(downloads=<streamrip.db.Dummy object at 0x106086750>, failed=<streamrip.db.Failed object at 0x106086780>), cover_path='/Users/redacted/Downloads/Gyllene                
                    Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg'), PendingTrack(id=3480318, album=AlbumMetadata(info=AlbumInfo(id='329906', quality=2, container='FLAC', label='Parlophone Sweden', explicit=False, sampling_rate=44100,                
                    bit_depth=16, booklets=None), album='Gyllene Tider', albumartist='Gyllene Tider', year='2006', genre=['Pop'], covers=Covers(('original',                                                                                                                     
                    'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/1000x1000-000000-80-0-0.jpg', None)                                                                                                                                           
                    ('large', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/500x500-000000-80-0-0.jpg', '/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg')                               
                    ('small', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/250x250-000000-80-0-0.jpg', None)                                                                                                                                   
                    ('thumbnail', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/56x56-000000-80-0-0.jpg', None)), tracktotal=11, disctotal=1, albumcomposer=None, comment=None, compilation=None, copyright=None, date='2006-05-26',            
                    description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None), client=<streamrip.client.deezer.DeezerClient object at 0x106086390>, config=<streamrip.config.Config object at 0x1055971a0>,                                                
                    folder='/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)', db=Database(downloads=<streamrip.db.Dummy object at 0x106086750>, failed=<streamrip.db.Failed object at 0x106086780>), cover_path='/Users/redacted/Downloads/Gyllene                
                    Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg'), PendingTrack(id=3480319, album=AlbumMetadata(info=AlbumInfo(id='329906', quality=2, container='FLAC', label='Parlophone Sweden', explicit=False, sampling_rate=44100,                
                    bit_depth=16, booklets=None), album='Gyllene Tider', albumartist='Gyllene Tider', year='2006', genre=['Pop'], covers=Covers(('original',                                                                                                                     
                    'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/1000x1000-000000-80-0-0.jpg', None)                                                                                                                                           
                    ('large', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/500x500-000000-80-0-0.jpg', '/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg')                               
                    ('small', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/250x250-000000-80-0-0.jpg', None)                                                                                                                                   
                    ('thumbnail', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/56x56-000000-80-0-0.jpg', None)), tracktotal=11, disctotal=1, albumcomposer=None, comment=None, compilation=None, copyright=None, date='2006-05-26',            
                    description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None), client=<streamrip.client.deezer.DeezerClient object at 0x106086390>, config=<streamrip.config.Config object at 0x1055971a0>,                                                
                    folder='/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)', db=Database(downloads=<streamrip.db.Dummy object at 0x106086750>, failed=<streamrip.db.Failed object at 0x106086780>), cover_path='/Users/redacted/Downloads/Gyllene                
                    Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg'), PendingTrack(id=3480320, album=AlbumMetadata(info=AlbumInfo(id='329906', quality=2, container='FLAC', label='Parlophone Sweden', explicit=False, sampling_rate=44100,                
                    bit_depth=16, booklets=None), album='Gyllene Tider', albumartist='Gyllene Tider', year='2006', genre=['Pop'], covers=Covers(('original',                                                                                                                     
                    'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/1000x1000-000000-80-0-0.jpg', None)                                                                                                                                           
                    ('large', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/500x500-000000-80-0-0.jpg', '/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg')                               
                    ('small', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/250x250-000000-80-0-0.jpg', None)                                                                                                                                   
                    ('thumbnail', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/56x56-000000-80-0-0.jpg', None)), tracktotal=11, disctotal=1, albumcomposer=None, comment=None, compilation=None, copyright=None, date='2006-05-26',            
                    description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None), client=<streamrip.client.deezer.DeezerClient object at 0x106086390>, config=<streamrip.config.Config object at 0x1055971a0>,                                                
                    folder='/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)', db=Database(downloads=<streamrip.db.Dummy object at 0x106086750>, failed=<streamrip.db.Failed object at 0x106086780>), cover_path='/Users/redacted/Downloads/Gyllene                
                    Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg'), PendingTrack(id=3480321, album=AlbumMetadata(info=AlbumInfo(id='329906', quality=2, container='FLAC', label='Parlophone Sweden', explicit=False, sampling_rate=44100,                
                    bit_depth=16, booklets=None), album='Gyllene Tider', albumartist='Gyllene Tider', year='2006', genre=['Pop'], covers=Covers(('original',                                                                                                                     
                    'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/1000x1000-000000-80-0-0.jpg', None)                                                                                                                                           
                    ('large', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/500x500-000000-80-0-0.jpg', '/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg')                               
                    ('small', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/250x250-000000-80-0-0.jpg', None)                                                                                                                                   
                    ('thumbnail', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/56x56-000000-80-0-0.jpg', None)), tracktotal=11, disctotal=1, albumcomposer=None, comment=None, compilation=None, copyright=None, date='2006-05-26',            
                    description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None), client=<streamrip.client.deezer.DeezerClient object at 0x106086390>, config=<streamrip.config.Config object at 0x1055971a0>,                                                
                    folder='/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)', db=Database(downloads=<streamrip.db.Dummy object at 0x106086750>, failed=<streamrip.db.Failed object at 0x106086780>), cover_path='/Users/redacted/Downloads/Gyllene                
                    Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg'), PendingTrack(id=3480322, album=AlbumMetadata(info=AlbumInfo(id='329906', quality=2, container='FLAC', label='Parlophone Sweden', explicit=False, sampling_rate=44100,                
                    bit_depth=16, booklets=None), album='Gyllene Tider', albumartist='Gyllene Tider', year='2006', genre=['Pop'], covers=Covers(('original',                                                                                                                     
                    'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/1000x1000-000000-80-0-0.jpg', None)                                                                                                                                           
                    ('large', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/500x500-000000-80-0-0.jpg', '/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg')                               
                    ('small', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/250x250-000000-80-0-0.jpg', None)                                                                                                                                   
                    ('thumbnail', 'https://e-cdns-images.dzcdn.net/images/cover/aa78d673fa73854410e16a1e8c5239df/56x56-000000-80-0-0.jpg', None)), tracktotal=11, disctotal=1, albumcomposer=None, comment=None, compilation=None, copyright=None, date='2006-05-26',            
                    description=None, encoder=None, grouping=None, lyrics=None, purchase_date=None), client=<streamrip.client.deezer.DeezerClient object at 0x106086390>, config=<streamrip.config.Config object at 0x1055971a0>,                                                
                    folder='/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)', db=Database(downloads=<streamrip.db.Dummy object at 0x106086750>, failed=<streamrip.db.Failed object at 0x106086780>), cover_path='/Users/redacted/Downloads/Gyllene                
                    Tider - Gyllene Tider (2006)/__artwork/cover-6600634237270320085.jpg')]                                                                                                                                                                                      
[07:58:59] DEBUG    Fetching deezer url with token                                                                                                                                                                                                                  deezer.py:167
                    AAAAAWZsMINmbUnDR4Yo034KguJF8MbZBXBl0bJxSyHnKDqlSheuk0OGSSgEKCPdaugHM7AobNtde1YHYKnSC2NpwSuQ7kkI1ShBcNLwFbor0ycrE52EssOCWCCR0skDvHQ-_VOpzTzQwH8-K2H1CUsXhQft9ReUXCXb-kg1i1pdDNGAxFJt2IgU3MvE0ntiRUfg8fErbeMN72VfSVGJGXHS_BDA-K7-1XGU6a6fc4rvsuR              
                    TykyMf-FI8kKOAT4r4oEaRSdvaYpDJQjfdrhZPFgANaggBqm8XOvhWZnoEcCufYPptXLIalpITTpt3dop9i4vhixZzBGQB884SWt9lGoSVIVbaPzNaZYWcPg6Jz_YGrSsD71KbYNJK0nbcjNGyg                                                                                                          
[07:59:00] DEBUG    dz track info: {'ALB_ID': '329906', 'ALB_PICTURE': 'aa78d673fa73854410e16a1e8c5239df', 'ALB_TITLE': 'Gyllene Tider', 'ARTISTS': [{'ART_ID': '13048', 'ROLE_ID': '0', 'ARTISTS_SONGS_ORDER': '1', 'ART_NAME': 'Gyllene Tider',                   deezer.py:190
                    'ARTIST_IS_DUMMY': False, 'ART_PICTURE': '60aaceaa65a9cb81be1ed4e0df410786', 'RANK': '310716', 'LOCALES': [], '__TYPE__': 'artist'}], 'ART_ID': '13048', 'ART_NAME': 'Gyllene Tider', 'ARTIST_IS_DUMMY': False, 'DIGITAL_RELEASE_DATE':                      
                    '2006-05-26', 'DISK_NUMBER': '1', 'DURATION': '150', 'EXPLICIT_LYRICS': '0', 'EXPLICIT_TRACK_CONTENT': {'EXPLICIT_LYRICS_STATUS': 0, 'EXPLICIT_COVER_STATUS': 2}, 'GENRE_ID': '7', 'HIERARCHICAL_TITLE': '', 'ISRC': 'SEAME7900043',                         
                    'LYRICS_ID': 74730847, 'PHYSICAL_RELEASE_DATE': '2006-05-26', 'PROVIDER_ID': '3', 'RANK': '20963', 'SMARTRADIO': 0, 'SNG_CONTRIBUTORS': {'main_artist': ['Gyllene Tider'], 'recordingengineer': ['Björn Boström'], 'author': ['Per Gessle'],                 
                    'composer': ['Robert Van Leeuven']}, 'SNG_ID': '3480312', 'SNG_TITLE': 'Skicka ett vykort, älskling', 'STATUS': 1, 'TRACK_NUMBER': '1', 'USER_ID': 0, 'VERSION': '', 'MD5_ORIGIN': '5cd48d5f4d4479c5d03f205e287b4dd8', 'FILESIZE_AAC_64': '0',               
                    'FILESIZE_MP3_64': '0', 'FILESIZE_MP3_128': '2412877', 'FILESIZE_MP3_256': '0', 'FILESIZE_MP3_320': '6032195', 'FILESIZE_FLAC': '18925175', 'FILESIZE': '2412877', 'GAIN': '-8.5', 'MEDIA_VERSION': '4', 'TRACK_TOKEN':                                      
               





... ETC                                                                                                                                






─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Downloading Gyllene Tider ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
           DEBUG    Removing dirs {'/Users/redacted/Downloads/Gyllene Tider - Gyllene Tider (2006)/__artwork'}                                                                                                                                                      artwork.py:19
redacteds-iMac:~ redacted$
```


### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/Users/redacted/Downloads/"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 1
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = false
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = ""
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 1
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 1
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "/Users/redacted/StreamripDownloads/YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = false
# Path to the downloads database 
downloads_path = "/Users/redacted/Library/Application Support/streamrip/downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "/Users/redacted/Library/Application Support/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = false
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1

[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year})"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```


### Operating System

macOS

### streamrip version

2.0.5

### Screenshots and recordings

_No response_

### Additional context

First time trying. Config is almost default.
