### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by cy920820** [nathom/streamrip#706]
### Describe the bug

Interrupted midway through each download and displayed ClientPayloadError

### Command Used

```bash
rip url https://www.qobuz.com/us-en/album/-/rg3nmvkllhjvc
```

### Debug Traceback

```text
rip url https://www.qobuz.com/us-en/album/-/rg3nmvkllhjvc
───────────────────────────────────── Downloading Fantasy ─────────────────────────────────────
Track 1  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━ 92.0% • 155.2 kB/s • 0:00:26
Track 3  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━ 75.6% • 168.3 kB/s • 0:01:22
Track 8  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━ 71.9% • 226.0 kB/s • 0:01:02
Track 10 ━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8% • 114.8 kB/s • 0:05:20
Track 6  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━ 88.5% • 139.1 kB/s • 0:00:33
╭───────────────────────────── Traceback (most recent call last) ─────────────────────────────╮
│ /opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/aiohttp/client_proto.py: │
│ 94 in connection_lost                                                                       │
│                                                                                             │
│    91 │   │   uncompleted = None                                                            │
│    92 │   │   if self._parser is not None:                                                  │
│    93 │   │   │   try:                                                                      │
│ ❱  94 │   │   │   │   uncompleted = self._parser.feed_eof()                                 │
│    95 │   │   │   except Exception as underlying_exc:                                       │
│    96 │   │   │   │   if self._payload is not None:                                         │
│    97 │   │   │   │   │   client_payload_exc_msg = (                                        │
│                                                                                             │
│ in aiohttp._http_parser.HttpParser.feed_eof:510                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
ContentLengthError: 400, message:
  Not enough data for satisfy content length header.

The above exception was the direct cause of the following exception:

╭───────────────────────────── Traceback (most recent call last) ─────────────────────────────╮
│ /opt/homebrew/Caskroom/miniconda/base/bin/rip:8 in <module>                                 │
│                                                                                             │
│   5 from streamrip.rip import rip                                                           │
│   6 if __name__ == '__main__':                                                              │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                    │
│ ❱ 8 │   sys.exit(rip())                                                                     │
│   9                                                                                         │
│                                                                                             │
│ /opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/click/core.py:1157 in    │
│ __call__                                                                                    │
│                                                                                             │
│                                  ... 17 frames hidden ...                                   │
│                                                                                             │
│ /opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/aiohttp/streams.py:50 in │
│ __anext__                                                                                   │
│                                                                                             │
│    47 │                                                                                     │
│    48 │   async def __anext__(self) -> _T:                                                  │
│    49 │   │   try:                                                                          │
│ ❱  50 │   │   │   rv = await self.read_func()                                               │
│    51 │   │   except EofStream:                                                             │
│    52 │   │   │   raise StopAsyncIteration                                                  │
│    53 │   │   if rv == b"":                                                                 │
│                                                                                             │
│ /opt/homebrew/Caskroom/miniconda/base/lib/python3.10/site-packages/aiohttp/streams.py:357   │
│ in read                                                                                     │
│                                                                                             │
│   354 │                                                                                     │
│   355 │   async def read(self, n: int = -1) -> bytes:                                       │
│   356 │   │   if self._exception is not None:                                               │
│ ❱ 357 │   │   │   raise self._exception                                                     │
│   358 │   │                                                                                 │
│   359 │   │   # migration problem; with DataQueue you have to catch                         │
│   360 │   │   # EofStream exception, so common way is to run payload.read() inside          │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
ClientPayloadError: Response payload is not completed: <ContentLengthError: 400, message='Not
enough data for satisfy content length header.'>
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/Users/cy920820/StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = true
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = "2738067"
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = "LnW5pfpKbK5DwHwDXRUav36sd2warFexZ4BcIttG7H_QTiNmAUwglbyKm9irZv579OsTJV056bOXsu9dlfSvvA"
# Do not change
app_id = "950096963"
# Do not change
secrets = ["10b251c286cfbf64d6b7105f253d9a2e", "979549437fcc4a3faad4867b5cd25dcb"]

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "/Users/cy920820/StreamripDownloads/YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "/Users/cy920820/Library/Application Support/streamrip/downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "/Users/cy920820/Library/Application Support/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

MacOS 14.5

### streamrip version

2.0.5
