### ISSUE TITLE
[BUG] OSError: filename too long

### ISSUE THREAD

**Issue by owhyy** [nathom/streamrip#712]
### Describe the bug

Some album names are longer than 255 characters (the general limit on filenames). If this happens, the program crashes, as the directory is not created.

For example, see [this](https://www.qobuz.com/us-en/album/scelsi-quattro-pezzi-per-orchestra-pranam-zender-5-haiku-for-flute-and-strings-zeitstrome-kantate-hans-zender/0761203948529) album, which has a name longer than 255 characters.

### Command Used

```bash
rip -vvv search qobuz album 0761203948529
```

### Debug Traceback

```text
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/<redated>/venv/bin/rip:8 in <module>                                                          │
│                                                                                                  │
│   5 from streamrip.rip import rip                                                                │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(rip())                                                                          │
│   9                                                                                              │
│                                                                                                  │
│ ╭─────────────────────── locals ───────────────────────╮                                         │
│ │  re = <module 're' from '/usr/lib/python3.10/re.py'> │                                         │
│ │ rip = <HelpColorsGroup rip>                          │                                         │
│ │ sys = <module 'sys' (built-in)>                      │                                         │
│ ╰──────────────────────────────────────────────────────╯                                         │
│                                                                                                  │
│ /home/<redacted>/venv/lib/python3.10/site-packages/click/core.py:1157 in __call__                    │
│                                                                                                  │
│ /home/<redacted>/venv/lib/python3.10/site-packages/click/core.py:1078 in main                        │
│                                                                                                  │
│ /home/<redacted>/venv/lib/python3.10/site-packages/click/core.py:1688 in invoke                      │
│                                                                                                  │
│ /home/<redacted>/venv/lib/python3.10/site-packages/click/core.py:1434 in invoke                      │
│                                                                                                  │
│ /home/<redacted>/venv/lib/python3.10/site-packages/click/core.py:783 in invoke                       │
│                                                                                                  │
│ /home/<redacted>/venv/lib/python3.10/site-packages/click/decorators.py:33 in new_func                │
│                                                                                                  │
│ /home/<redacted>/venv/lib/python3.10/site-packages/streamrip/rip/cli.py:28 in wrapper                │
│                                                                                                  │
│    25 def coro(f):                                                                               │
│    26 │   @wraps(f)                                                                              │
│    27 │   def wrapper(*args, **kwargs):                                                          │
│ ❱  28 │   │   return asyncio.run(f(*args, **kwargs))                                             │
│    29 │                                                                                          │
│    30 │   return wrapper                                                                         │
│    31                                                                                            │
│                                                                                                  │
│ ╭───────────────────────── locals ──────────────────────────╮                                    │
│ │   args = (<click.core.Context object at 0x7b9dff1004f0>,) │                                    │
│ │      f = <function search at 0x7b9dfcc44940>              │                                    │
│ │ kwargs = {                                                │                                    │
│ │          │   'source': 'qobuz',                           │                                    │
│ │          │   'media_type': 'album',                       │                                    │
│ │          │   'query': '0761203948529',                    │                                    │
│ │          │   'first': False,                              │                                    │
│ │          │   'output_file': None,                         │                                    │
│ │          │   'num_results': 100                           │                                    │
│ │          }                                                │                                    │
│ ╰───────────────────────────────────────────────────────────╯                                    │
│                                                                                                  │
│ /usr/lib/python3.10/asyncio/runners.py:44 in run                                                 │
│                                                                                                  │
│   41 │   │   events.set_event_loop(loop)                                                         │
│   42 │   │   if debug is not None:                                                               │
│   43 │   │   │   loop.set_debug(debug)                                                           │
│ ❱ 44 │   │   return loop.run_until_complete(main)                                                │
│   45 │   finally:                                                                                │
│   46 │   │   try:                                                                                │
│   47 │   │   │   _cancel_all_tasks(loop)                                                         │
│                                                                                                  │
│ ╭──────────────────────────────── locals ────────────────────────────────╮                       │
│ │ debug = None                                                           │                       │
│ │  loop = <_UnixSelectorEventLoop running=False closed=True debug=False> │                       │
│ │  main = <coroutine object search at 0x7b9dfcc35070>                    │                       │
│ ╰────────────────────────────────────────────────────────────────────────╯                       │
│                                                                                                  │
│ /usr/lib/python3.10/asyncio/base_events.py:649 in run_until_complete                             │
│                                                                                                  │
│    646 │   │   if not future.done():                                                             │
│    647 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')             │
│    648 │   │                                                                                     │
│ ❱  649 │   │   return future.result()                                                            │
│    650 │                                                                                         │
│    651 │   def stop(self):                                                                       │
│    652 │   │   """Stop running the event loop.                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   future = <Task finished name='Task-1' coro=<search() done, defined at                      │ │
│ │            /home/<redacted>/venv/lib/python3.10/site-packages/streamrip/rip/cli.py:327>          │ │
│ │            exception=OSError(36, 'File name too long')>                                      │ │
│ │ new_task = True                                                                              │ │
│ │     self = <_UnixSelectorEventLoop running=False closed=True debug=False>                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/<redacted>/venv/lib/python3.10/site-packages/streamrip/rip/cli.py:372 in search                │
│                                                                                                  │
│   369 │   │   │   │   )                                                                          │
│   370 │   │   │   else:                                                                          │
│   371 │   │   │   │   await main.search_interactive(source, media_type, query)                   │
│ ❱ 372 │   │   │   await main.resolve()                                                           │
│   373 │   │   │   await main.rip()                                                               │
│   374                                                                                            │
│   375                                                                                            │
│                                                                                                  │
│ ╭───────────────────────────── locals ─────────────────────────────╮                             │
│ │         cfg = <streamrip.config.Config object at 0x7b9dfcc17070> │                             │
│ │         ctx = <click.core.Context object at 0x7b9dff1004f0>      │                             │
│ │       first = False                                              │                             │
│ │        main = <streamrip.rip.main.Main object at 0x7b9dfcce3f40> │                             │
│ │  media_type = 'album'                                            │                             │
│ │ num_results = 100                                                │                             │
│ │ output_file = None                                               │                             │
│ │       query = '0761203948529'                                    │                             │
│ │      source = 'qobuz'                                            │                             │
│ ╰──────────────────────────────────────────────────────────────────╯                             │
│                                                                                                  │
│ /home/<redacted>/venv/lib/python3.10/site-packages/streamrip/rip/main.py:157 in resolve              │
│                                                                                                  │
│   154 │   │   with console.status("Resolving URLs...", spinner="dots"):                          │
│   155 │   │   │   coros = [p.resolve() for p in self.pending]                                    │
│   156 │   │   │   new_media: list[Media] = [                                                     │
│ ❱ 157 │   │   │   │   m for m in await asyncio.gather(*coros) if m is not None                   │
│   158 │   │   │   ]                                                                              │
│   159 │   │                                                                                      │
│   160 │   │   self.media.extend(new_media)                                                       │
│                                                                                                  │
│ ╭────────────────────────────── locals ───────────────────────────────╮                          │
│ │ coros = [<coroutine object PendingAlbum.resolve at 0x7b9dfcc368f0>] │                          │
│ │  self = <streamrip.rip.main.Main object at 0x7b9dfcce3f40>          │                          │
│ ╰─────────────────────────────────────────────────────────────────────╯                          │
│                                                                                                  │
│ /home/<redacted>/venv/lib/python3.10/site-packages/streamrip/media/album.py:72 in resolve            │
│                                                                                                  │
│    69 │   │   tracklist = get_album_track_ids(self.client.source, resp)                          │
│    70 │   │   folder = self.config.session.downloads.folder                                      │
│    71 │   │   album_folder = self._album_folder(folder, meta)                                    │
│ ❱  72 │   │   os.makedirs(album_folder, exist_ok=True)                                           │
│    73 │   │   embed_cover, _ = await download_artwork(                                           │
│    74 │   │   │   self.client.session,                                                           │
│    75 │   │   │   album_folder,                                                                  │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ album_folder = '/home/<redacted>/StreamripDownloads/Rundfunk-Sinfonieorchester Saarbrücken,      │ │
│ │                Michiko '+207                                                                 │ │
│ │       folder = '/home/<redacted>/StreamripDownloads'                                             │ │
│ │         meta = AlbumMetadata(                                                                │ │
│ │                │   info=AlbumInfo(                                                           │ │
│ │                │   │   id='8896397',                                                         │ │
│ │                │   │   quality=2,                                                            │ │
│ │                │   │   container='FLAC',                                                     │ │
│ │                │   │   label='CPO',                                                          │ │
│ │                │   │   explicit=False,                                                       │ │
│ │                │   │   sampling_rate=44.1,                                                   │ │
│ │                │   │   bit_depth=16,                                                         │ │
│ │                │   │   booklets=None                                                         │ │
│ │                │   ),                                                                        │ │
│ │                │   album='Scelsi: Quattro pezzi per orchestra - Pranam - Zender: 5 Haiku for │ │
│ │                Flute and Str'+27,                                                            │ │
│ │                │   albumartist='Rundfunk-Sinfonieorchester Saarbrücken, Michiko Hirayama,    │ │
│ │                Roswitha Staege, Hanna'+57,                                                   │ │
│ │                │   year='2000',                                                              │ │
│ │                │   genre=['Classique'],                                                      │ │
│ │                │   covers=Covers(('original',                                                │ │
│ │                'https://static.qobuz.com/images/covers/29/85/0761203948529_org.jpg', None)   │ │
│ │                ('large',                                                                     │ │
│ │                'https://static.qobuz.com/images/covers/29/85/0761203948529_600.jpg', None)   │ │
│ │                ('small',                                                                     │ │
│ │                'https://static.qobuz.com/images/covers/29/85/0761203948529_230.jpg', None)   │ │
│ │                ('thumbnail',                                                                 │ │
│ │                'https://static.qobuz.com/images/covers/29/85/0761203948529_50.jpg', None)),  │ │
│ │                │   tracktotal=15,                                                            │ │
│ │                │   disctotal=1,                                                              │ │
│ │                │   albumcomposer='Giacinto Scelsi',                                          │ │
│ │                │   comment=None,                                                             │ │
│ │                │   compilation=None,                                                         │ │
│ │                │   copyright='(C) 2000 CPO (P) 2000 CPO',                                    │ │
│ │                │   date='2000-01-01',                                                        │ │
│ │                │   description=None,                                                         │ │
│ │                │   encoder=None,                                                             │ │
│ │                │   grouping=None,                                                            │ │
│ │                │   lyrics=None,                                                              │ │
│ │                │   purchase_date=None                                                        │ │
│ │                )                                                                             │ │
│ │         resp = {                                                                             │ │
│ │                │   'maximum_bit_depth': 16,                                                  │ │
│ │                │   'image': {                                                                │ │
│ │                │   │   'small':                                                              │ │
│ │                'https://static.qobuz.com/images/covers/29/85/0761203948529_230.jpg',         │ │
│ │                │   │   'thumbnail':                                                          │ │
│ │                'https://static.qobuz.com/images/covers/29/85/0761203948529_50.jpg',          │ │
│ │                │   │   'large':                                                              │ │
│ │                'https://static.qobuz.com/images/covers/29/85/0761203948529_600.jpg',         │ │
│ │                │   │   'back': None                                                          │ │
│ │                │   },                                                                        │ │
│ │                │   'media_count': 1,                                                         │ │
│ │                │   'artist': {                                                               │ │
│ │                │   │   'image': None,                                                        │ │
│ │                │   │   'name': 'Rundfunk-Sinfonieorchester Saarbrücken',                     │ │
│ │                │   │   'id': 63139,                                                          │ │
│ │                │   │   'albums_count': 38,                                                   │ │
│ │                │   │   'slug': 'rundfunk-sinfonieorchester-saarbrucken',                     │ │
│ │                │   │   'picture': None                                                       │ │
│ │                │   },                                                                        │ │
│ │                │   'artists': [                                                              │ │
│ │                │   │   {                                                                     │ │
│ │                │   │   │   'id': 63139,                                                      │ │
│ │                │   │   │   'name': 'Rundfunk-Sinfonieorchester Saarbrücken',                 │ │
│ │                │   │   │   'roles': ['main-artist']                                          │ │
│ │                │   │   },                                                                    │ │
│ │                │   │   {                                                                     │ │
│ │                │   │   │   'id': 1098070,                                                    │ │
│ │                │   │   │   'name': 'Michiko Hirayama',                                       │ │
│ │                │   │   │   'roles': ['main-artist']                                          │ │
│ │                │   │   },                                                                    │ │
│ │                │   │   {'id': 771869, 'name': 'Roswitha Staege', 'roles': ['main-artist']},  │ │
│ │                │   │   {'id': 245940, 'name': 'Hanna Aurbacher', 'roles': ['main-artist']},  │ │
│ │                │   │   {'id': 22479, 'name': 'Hans Zender', 'roles': ['main-artist']},       │ │
│ │                │   │   {                                                                     │ │
│ │                │   │   │   'id': 8058678,                                                    │ │
│ │                │   │   │   'name': 'Saarbrucken Integration Ensemble',                       │ │
│ │                │   │   │   'roles': ['main-artist']                                          │ │
│ │                │   │   }                                                                     │ │
│ │                │   ],                                                                        │ │
│ │                │   'upc': '0761203948529',                                                   │ │
│ │                │   'released_at': 946681200,                                                 │ │
│ │                │   'label': {                                                                │ │
│ │                │   │   'name': 'CPO',                                                        │ │
│ │                │   │   'id': 6286,                                                           │ │
│ │                │   │   'albums_count': 2364,                                                 │ │
│ │                │   │   'supplier_id': 24,                                                    │ │
│ │                │   │   'slug': 'cpo'                                                         │ │
│ │                │   },                                                                        │ │
│ │                │   'title': 'Scelsi: Quattro pezzi per orchestra - Pranam - Zender: 5 Haiku  │ │
│ │                for Flute and Str'+27,                                                        │ │
│ │                │   'qobuz_id': 8896397,                                                      │ │
│ │                │   ... +48                                                                   │ │
│ │                }                                                                             │ │
│ │         self = PendingAlbum(                                                                 │ │
│ │                │   id='0761203948529',                                                       │ │
│ │                │   client=<streamrip.client.qobuz.QobuzClient object at 0x7b9dfcb00070>,     │ │
│ │                │   config=<streamrip.config.Config object at 0x7b9dfcc17070>,                │ │
│ │                │   db=Database(                                                              │ │
│ │                │   │   downloads=<streamrip.db.Downloads object at 0x7b9dfcb00640>,          │ │
│ │                │   │   failed=<streamrip.db.Failed object at 0x7b9dfcb00730>                 │ │
│ │                │   )                                                                         │ │
│ │                )                                                                             │ │
│ │    tracklist = [                                                                             │ │
│ │                │   8896398,                                                                  │ │
│ │                │   8896400,                                                                  │ │
│ │                │   8896401,                                                                  │ │
│ │                │   8896402,                                                                  │ │
│ │                │   8896403,                                                                  │ │
│ │                │   8896405,                                                                  │ │
│ │                │   8896407,                                                                  │ │
│ │                │   8896408,                                                                  │ │
│ │                │   8896409,                                                                  │ │
│ │                │   8896410,                                                                  │ │
│ │                │   ... +5                                                                    │ │
│ │                ]                                                                             │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /usr/lib/python3.10/os.py:225 in makedirs                                                        │
│                                                                                                  │
│    222 │   │   if tail == cdir:           # xxx/newdir/. exists if xxx/newdir exists             │
│    223 │   │   │   return                                                                        │
│    224 │   try:                                                                                  │
│ ❱  225 │   │   mkdir(name, mode)                                                                 │
│    226 │   except OSError:                                                                       │
│    227 │   │   # Cannot rely on checking for EEXIST, since the operating system                  │
│    228 │   │   # could give priority to other errors like EACCES or EROFS                        │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ exist_ok = True                                                                              │ │
│ │     head = '/home/<redacted>/StreamripDownloads'                                                 │ │
│ │     mode = 511                                                                               │ │
│ │     name = '/home/<redacted>/StreamripDownloads/Rundfunk-Sinfonieorchester Saarbrücken, Michiko  │ │
│ │            '+207                                                                             │ │
│ │     tail = 'Rundfunk-Sinfonieorchester Saarbrücken, Michiko Hirayama, Roswitha Staege,       │ │
│ │            Hanna'+175                                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: [Errno 36] File name too long: '/home/<redacted>/StreamripDownloads/Rundfunk-Sinfonieorchester Saarbrücken, Michiko Hirayama, Roswitha Staege, Hanna Aurbacher, Hans Zender, Saarbrucken Integration Ensemble - Scelsi Quattro pezzi per orchestra - Pranam - Zender 5 Haiku 
for Flute and Strings - Zeitstrome - Kantate (2000) [F'
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/home/<redacted>StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 4
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = true
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = "<redacted>"
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = "<redacted>"
# Do not change
app_id = "<redacted>"
# Do not change
secrets = [<redacted>]

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "/home/snooze/StreamripDownloads/YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "/home/snooze/.config/streamrip/downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "/home/snooze/.config/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Linux

### streamrip version

2.0.5
