### ISSUE TITLE
Cannot download songs in a Playlist in TIDAL

### ISSUE THREAD

**Issue by baumaeschi** [nathom/streamrip#723]
### Describe the bug

The title says everything: Cannot download songs in a Playlist in TIDAL

### Command Used

```bash
rip url https://tidal.com/browse/playlist/c84617f6-613a-453a-ade2-36efd2965fa3
```

### Debug Traceback

```text
C:\Windows\System32>rip -vvv url https://tidal.com/browse/playlist/c84617f6-613a-453a-ade2-36efd2965fa3

...
Sorry, had to remover lines because it's too long!
....
But hope you can reproduce yourself :)
....

                     │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │   _w = <built-in method match of re.Pattern object at 0x000001F473D98E10>                    │ │
│ │    s = '<?xml version=\'1.0\' encoding=\'UTF-8\'?><MPD                                       │ │
│ │        xmlns="urn:mpeg:dash:schema:mpd:2011"'+1510                                           │ │
│ │ self = <json.decoder.JSONDecoder object at 0x000001F473DB4250>                               │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py:355 in raw_decode     │
│                                                                                                  │
│   352 │   │   try:                                                                               │
│   353 │   │   │   obj, end = self.scan_once(s, idx)                                              │
│   354 │   │   except StopIteration as err:                                                       │
│ > 355 │   │   │   raise JSONDecodeError("Expecting value", s, err.value) from None               │
│   356 │   │   return obj, end                                                                    │
│   357                                                                                            │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │  idx = 0                                                                                     │ │
│ │    s = '<?xml version=\'1.0\' encoding=\'UTF-8\'?><MPD                                       │ │
│ │        xmlns="urn:mpeg:dash:schema:mpd:2011"'+1510                                           │ │
│ │ self = <json.decoder.JSONDecoder object at 0x000001F473DB4250>                               │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ in _run_module_as_main:198                                                                       │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │   alter_argv = False                                                                         │ │
│ │         code = <code object <module> at 0x000001F471146140, file                             │ │
│ │                "C:\Users\aesch\AppData\Local\Programs\Python\Python311\Scripts\rip.exe\__ma… │ │
│ │                line 1>                                                                       │ │
│ │ main_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\aesch\AppData\Local\Programs\Python\Python311\Scripts\rip.exe\">,   │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\aesch\AppData\Local\Programs\Python\Python311\Scripts\rip.exe\">,   │ │
│ │                origin='C:\\Users\\aesch\\AppData\\Local\\Programs\\Python\\Python311\\Scrip… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\aesch\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\rip… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\aesch\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\rip… │ │
│ │                │   're': <module 're' from                                                   │ │
│ │                'C:\\Users\\aesch\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\re\\__i… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\aesch\AppData\Local\Programs\Python\Python311\Scripts\rip.exe\">,   │ │
│ │                origin='C:\\Users\\aesch\\AppData\\Local\\Programs\\Python\\Python311\\Scrip… │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│ in _run_code:88                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │       cached = 'C:\\Users\\aesch\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\rip… │ │
│ │         code = <code object <module> at 0x000001F471146140, file                             │ │
│ │                "C:\Users\aesch\AppData\Local\Programs\Python\Python311\Scripts\rip.exe\__ma… │ │
│ │                line 1>                                                                       │ │
│ │        fname = 'C:\\Users\\aesch\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\rip… │ │
│ │ init_globals = None                                                                          │ │
│ │       loader = <zipimporter object                                                           │ │
│ │                "C:\Users\aesch\AppData\Local\Programs\Python\Python311\Scripts\rip.exe\">    │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\aesch\AppData\Local\Programs\Python\Python311\Scripts\rip.exe\">,   │ │
│ │                origin='C:\\Users\\aesch\\AppData\\Local\\Programs\\Python\\Python311\\Scrip… │ │
│ │     pkg_name = ''                                                                            │ │
│ │  run_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\aesch\AppData\Local\Programs\Python\Python311\Scripts\rip.exe\">,   │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\aesch\AppData\Local\Programs\Python\Python311\Scripts\rip.exe\">,   │ │
│ │                origin='C:\\Users\\aesch\\AppData\\Local\\Programs\\Python\\Python311\\Scrip… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\aesch\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\rip… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\aesch\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\rip… │ │
│ │                │   're': <module 're' from                                                   │ │
│ │                'C:\\Users\\aesch\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\re\\__i… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │  script_name = None                                                                          │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│ C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py:1157 in   │
│ __call__                                                                                         │
│                                                                                                  │
│ C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py:1078 in   │
│ main                                                                                             │
│                                                                                                  │
│ C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py:1688 in   │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py:1434 in   │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py:783 in    │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py:33  │
│ in new_func                                                                                      │
│                                                                                                  │
│ C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamrip\rip\cli.py:28 │
│ in wrapper                                                                                       │
│                                                                                                  │
│    25 def coro(f):                                                                               │
│    26 │   @wraps(f)                                                                              │
│    27 │   def wrapper(*args, **kwargs):                                                          │
│ >  28 │   │   return asyncio.run(f(*args, **kwargs))                                             │
│    29 │                                                                                          │
│    30 │   return wrapper                                                                         │
│    31                                                                                            │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │   args = (<click.core.Context object at 0x000001F4716C2A50>,)                                │ │
│ │      f = <function url at 0x000001F475497F60>                                                │ │
│ │ kwargs = {                                                                                   │ │
│ │          │   'urls': (                                                                       │ │
│ │          │   │   'https://tidal.com/browse/playlist/c84617f6-613a-453a-ade2-36efd2965fa3',   │ │
│ │          │   )                                                                               │ │
│ │          }                                                                                   │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py:190 in run         │
│                                                                                                  │
│   187 │   │   │   "asyncio.run() cannot be called from a running event loop")                    │
│   188 │                                                                                          │
│   189 │   with Runner(debug=debug) as runner:                                                    │
│ > 190 │   │   return runner.run(main)                                                            │
│   191                                                                                            │
│   192                                                                                            │
│   193 def _cancel_all_tasks(loop):                                                               │
│                                                                                                  │
│ ┌──────────────────────────── locals ────────────────────────────┐                               │
│ │  debug = None                                                  │                               │
│ │   main = <coroutine object url at 0x000001F4753A7760>          │                               │
│ │ runner = <asyncio.runners.Runner object at 0x000001F4754BF810> │                               │
│ └────────────────────────────────────────────────────────────────┘                               │
│                                                                                                  │
│ C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py:118 in run         │
│                                                                                                  │
│   115 │   │                                                                                      │
│   116 │   │   self._interrupt_count = 0                                                          │
│   117 │   │   try:                                                                               │
│ > 118 │   │   │   return self._loop.run_until_complete(task)                                     │
│   119 │   │   except exceptions.CancelledError:                                                  │
│   120 │   │   │   if self._interrupt_count > 0:                                                  │
│   121 │   │   │   │   uncancel = getattr(task, "uncancel", None)                                 │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │        context = <_contextvars.Context object at 0x000001F4756DB780>                         │ │
│ │           coro = <coroutine object url at 0x000001F4753A7760>                                │ │
│ │           self = <asyncio.runners.Runner object at 0x000001F4754BF810>                       │ │
│ │ sigint_handler = functools.partial(<bound method Runner._on_sigint of                        │ │
│ │                  <asyncio.runners.Runner object at 0x000001F4754BF810>>, main_task=<Task     │ │
│ │                  finished name='Task-1' coro=<url() done, defined at                         │ │
│ │                  C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\site-packages\s… │ │
│ │                  exception=PermissionError(13, 'Der Prozess kann nicht auf die Datei         │ │
│ │                  zugreifen, da sie von einem anderen Prozess verwendet wird')>)              │ │
│ │           task = <Task finished name='Task-1' coro=<url() done, defined at                   │ │
│ │                  C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\site-packages\s… │ │
│ │                  exception=PermissionError(13, 'Der Prozess kann nicht auf die Datei         │ │
│ │                  zugreifen, da sie von einem anderen Prozess verwendet wird')>               │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py:654 in         │
│ run_until_complete                                                                               │
│                                                                                                  │
│    651 │   │   if not future.done():                                                             │
│    652 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')             │
│    653 │   │                                                                                     │
│ >  654 │   │   return future.result()                                                            │
│    655 │                                                                                         │
│    656 │   def stop(self):                                                                       │
│    657 │   │   """Stop running the event loop.                                                   │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │   future = <Task finished name='Task-1' coro=<url() done, defined at                         │ │
│ │            C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamr… │ │
│ │            exception=PermissionError(13, 'Der Prozess kann nicht auf die Datei zugreifen, da │ │
│ │            sie von einem anderen Prozess verwendet wird')>                                   │ │
│ │ new_task = False                                                                             │ │
│ │     self = <ProactorEventLoop running=False closed=True debug=False>                         │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamrip\rip\cli.py:16 │
│ 5 in url                                                                                         │
│                                                                                                  │
│   162 │   │   else:                                                                              │
│   163 │   │   │   version_coro = None                                                            │
│   164 │   │                                                                                      │
│ > 165 │   │   async with Main(cfg) as main:                                                      │
│   166 │   │   │   await main.add_all(urls)                                                       │
│   167 │   │   │   await main.resolve()                                                           │
│   168 │   │   │   await main.rip()                                                               │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │          cfg = <streamrip.config.Config object at 0x000001F47138BCD0>                        │ │
│ │          ctx = <click.core.Context object at 0x000001F4716C2A50>                             │ │
│ │         main = <streamrip.rip.main.Main object at 0x000001F4756DA310>                        │ │
│ │      updates = True                                                                          │ │
│ │         urls = ('https://tidal.com/browse/playlist/c84617f6-613a-453a-ade2-36efd2965fa3',)   │ │
│ │ version_coro = <Task finished name='Task-2' coro=<latest_streamrip_version() done, defined   │ │
│ │                at                                                                            │ │
│ │                C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\site-packages\str… │ │
│ │                result=('2.0.5', None)>                                                       │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamrip\rip\main.py:2 │
│ 89 in __aexit__                                                                                  │
│                                                                                                  │
│   286 │   │   # We remove artwork tempdirs here because multiple singles                         │
│   287 │   │   # may be able to share downloaded artwork in the same `rip` session                │
│   288 │   │   # We don't know that a cover will not be used again until end of execution         │
│ > 289 │   │   remove_artwork_tempdirs()                                                          │
│   290                                                                                            │
│                                                                                                  │
│ ┌─────────────────────────────────────── locals ───────────────────────────────────────┐         │
│ │      _ = (                                                                           │         │
│ │          │   <class 'json.decoder.JSONDecodeError'>,                                 │         │
│ │          │   JSONDecodeError('Expecting value: line 1 column 1 (char 0)'),           │         │
│ │          │   <traceback object at 0x000001F4772ADBC0>                                │         │
│ │          )                                                                           │         │
│ │ client = <streamrip.client.soundcloud.SoundcloudClient object at 0x000001F475635C90> │         │
│ │   self = <streamrip.rip.main.Main object at 0x000001F4756DA310>                      │         │
│ └──────────────────────────────────────────────────────────────────────────────────────┘         │
│                                                                                                  │
│ C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamrip\media\artwork │
│ .py:22 in remove_artwork_tempdirs                                                                │
│                                                                                                  │
│    19 │   logger.debug("Removing dirs %s", _artwork_tempdirs)                                    │
│    20 │   for path in _artwork_tempdirs:                                                         │
│    21 │   │   try:                                                                               │
│ >  22 │   │   │   shutil.rmtree(path)                                                            │
│    23 │   │   except FileNotFoundError:                                                          │
│    24 │   │   │   pass                                                                           │
│    25                                                                                            │
│                                                                                                  │
│ ┌─────────────────────────────── locals ────────────────────────────────┐                        │
│ │ path = 'C:\\Users\\aesch\\StreamripDownloads\\My Playlist\\__artwork' │                        │
│ └───────────────────────────────────────────────────────────────────────┘                        │
│                                                                                                  │
│ C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\shutil.py:787 in rmtree               │
│                                                                                                  │
│    784 │   │   │   onerror(os.path.islink, path, sys.exc_info())                                 │
│    785 │   │   │   # can't continue even if onerror hook returns                                 │
│    786 │   │   │   return                                                                        │
│ >  787 │   │   return _rmtree_unsafe(path, onerror)                                              │
│    788                                                                                           │
│    789 # Allow introspection of whether or not the hardening against symlink                     │
│    790 # attacks is supported on the current platform                                            │
│                                                                                                  │
│ ┌──────────────────────────────────── locals ────────────────────────────────────┐               │
│ │        dir_fd = None                                                           │               │
│ │ ignore_errors = False                                                          │               │
│ │       onerror = <function rmtree.<locals>.onerror at 0x000001F47733D940>       │               │
│ │          path = 'C:\\Users\\aesch\\StreamripDownloads\\My Playlist\\__artwork' │               │
│ └────────────────────────────────────────────────────────────────────────────────┘               │
│                                                                                                  │
│ C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\shutil.py:634 in _rmtree_unsafe       │
│                                                                                                  │
│    631 │   │   │   try:                                                                          │
│    632 │   │   │   │   os.unlink(fullname)                                                       │
│    633 │   │   │   except OSError:                                                               │
│ >  634 │   │   │   │   onerror(os.unlink, fullname, sys.exc_info())                              │
│    635 │   try:                                                                                  │
│    636 │   │   os.rmdir(path)                                                                    │
│    637 │   except OSError:                                                                       │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │    entries = [                                                                               │ │
│ │              │   <DirEntry 'cover-261416483009202801.jpg'>,                                  │ │
│ │              │   <DirEntry 'cover-3124090416951585672.jpg'>,                                 │ │
│ │              │   <DirEntry 'cover-5243581039136752896.jpg'>,                                 │ │
│ │              │   <DirEntry 'cover-568571260974952196.jpg'>,                                  │ │
│ │              │   <DirEntry 'cover-6988460102585340994.jpg'>,                                 │ │
│ │              │   <DirEntry 'cover-8480247214541953545.jpg'>,                                 │ │
│ │              │   <DirEntry 'cover-8494340896248920898.jpg'>,                                 │ │
│ │              │   <DirEntry 'cover-8693239332584085643.jpg'>,                                 │ │
│ │              │   <DirEntry 'cover1743778640886175201.jpg'>,                                  │ │
│ │              │   <DirEntry 'cover1907354135813867032.jpg'>,                                  │ │
│ │              │   ... +7                                                                      │ │
│ │              ]                                                                               │ │
│ │      entry = <DirEntry 'cover-261416483009202801.jpg'>                                       │ │
│ │   fullname = 'C:\\Users\\aesch\\StreamripDownloads\\My                                       │ │
│ │              Playlist\\__artwork\\cover-261416483009202801'+4                                │ │
│ │    onerror = <function rmtree.<locals>.onerror at 0x000001F47733D940>                        │ │
│ │       path = 'C:\\Users\\aesch\\StreamripDownloads\\My Playlist\\__artwork'                  │ │
│ │ scandir_it = <nt.ScandirIterator object at 0x000001F4760CBA70>                               │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\aesch\AppData\Local\Programs\Python\Python311\Lib\shutil.py:632 in _rmtree_unsafe       │
│                                                                                                  │
│    629 │   │   │   _rmtree_unsafe(fullname, onerror)                                             │
│    630 │   │   else:                                                                             │
│    631 │   │   │   try:                                                                          │
│ >  632 │   │   │   │   os.unlink(fullname)                                                       │
│    633 │   │   │   except OSError:                                                               │
│    634 │   │   │   │   onerror(os.unlink, fullname, sys.exc_info())                              │
│    635 │   try:                                                                                  │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │    entries = [                                                                               │ │
│ │              │   <DirEntry 'cover-261416483009202801.jpg'>,                                  │ │
│ │              │   <DirEntry 'cover-3124090416951585672.jpg'>,                                 │ │
│ │              │   <DirEntry 'cover-5243581039136752896.jpg'>,                                 │ │
│ │              │   <DirEntry 'cover-568571260974952196.jpg'>,                                  │ │
│ │              │   <DirEntry 'cover-6988460102585340994.jpg'>,                                 │ │
│ │              │   <DirEntry 'cover-8480247214541953545.jpg'>,                                 │ │
│ │              │   <DirEntry 'cover-8494340896248920898.jpg'>,                                 │ │
│ │              │   <DirEntry 'cover-8693239332584085643.jpg'>,                                 │ │
│ │              │   <DirEntry 'cover1743778640886175201.jpg'>,                                  │ │
│ │              │   <DirEntry 'cover1907354135813867032.jpg'>,                                  │ │
│ │              │   ... +7                                                                      │ │
│ │              ]                                                                               │ │
│ │      entry = <DirEntry 'cover-261416483009202801.jpg'>                                       │ │
│ │   fullname = 'C:\\Users\\aesch\\StreamripDownloads\\My                                       │ │
│ │              Playlist\\__artwork\\cover-261416483009202801'+4                                │ │
│ │    onerror = <function rmtree.<locals>.onerror at 0x000001F47733D940>                        │ │
│ │       path = 'C:\\Users\\aesch\\StreamripDownloads\\My Playlist\\__artwork'                  │ │
│ │ scandir_it = <nt.ScandirIterator object at 0x000001F4760CBA70>                               │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess
verwendet wird: 'C:\\Users\\aesch\\StreamripDownloads\\My Playlist\\__artwork\\cover-261416483009202801.jpg'
sys:1: RuntimeWarning: coroutine 'Playlist.download.<locals>._resolve_download' was never awaited

C:\Windows\System32>
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "C:\\Users\\aesch\\StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = false
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = ""
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = 113122291
country_code = "CH"
access_token = "eyJraWQiOiJ2OU1GbFhqWSIsImFsZyI6IkVTMjU2In0.eyJ0eXBlIjoibzJfYWNjZXNzIiwidWlkIjoxMTMxMjIyOTEsInNjb3BlIjoid191c3Igd19zdWIgcl91c3IiLCJnVmVyIjowLCJzVmVyIjoxLCJjaWQiOjMyMzUsImV4cCI6MTcyMjY4MTc5OSwic2lkIjoiYzM5Y2MyYTctMzg3YS00MzIwLWJlMGEtNTIyNWY4NTE2ODMyIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLnRpZGFsLmNvbS92MSJ9.Ceah18LcUNXLuuG8pn-IOHuijax-xFqIWj2tFJMeVxXap1rlI1llSPo3UKcJhDoqKNTJCe-KexmxYFpIY2eHFA"
refresh_token = "eyJraWQiOiJoUzFKYTdVMCIsImFsZyI6IkVTNTEyIn0.eyJ0eXBlIjoibzJfcmVmcmVzaCIsInVpZCI6MTEzMTIyMjkxLCJzY29wZSI6IndfdXNyIHdfc3ViIHJfdXNyIiwiY2lkIjozMjM1LCJzVmVyIjoxLCJnVmVyIjowLCJpc3MiOiJodHRwczovL2F1dGgudGlkYWwuY29tL3YxIn0.AKQuclJDRrBO_0UxCcbJ_i9GYBeeNTnkPTysuzC-68XOPmQgEpfc47F9V3nuQYLbXZRWanBgEDSw5QYIuS0w_AsTAEhW2jNlIIwc3a-MH0zqn1z7zvue6zkIgptB8zXhEveW51t-bhKGIncs5Q_Pmv4pI4_Et_1647ye_y1K9de87jcZ"
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = 1722681799.7733693

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "C:\\Users\\aesch\\StreamripDownloads\\YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "C:\\Users\\aesch\\AppData\\Roaming\\streamrip\\downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "C:\\Users\\aesch\\AppData\\Roaming\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Windows 10

### streamrip version

C:\Windows\System32>rip --version rip, version 2.0.5

### Screenshots and recordings

![streamrip_errors_playlist_download](https://github.com/user-attachments/assets/9c024e4b-c28c-4fcf-bb81-afd7cbc2b6e4)
