### ISSUE TITLE
[BUG] AssertionError when downloading some files in Tidal

### ISSUE THREAD

**Issue by khchow222** [nathom/streamrip#728]
### Describe the bug

Some titles give me an error when do the rip in Tidal

### Command Used

```bash
rip url https://tidal.com/browse/track/207278424?u
```

### Debug Traceback

```text
C:\Users\abcdefg\Downloads\stream>rip -vvv url https://tidal.com/browse/track/207278424?u
[21:10:27] DEBUG    Showing all debug logs                                                                                          cli.py:102
           DEBUG    Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)                                                      db.py:108
⠹ Resolving URLs...           DEBUG    {'id': 207278424, 'title': '神奇的糊塗魔藥', 'duration': 203, 'replayGain': -9.61, 'peak': 0.991646,          tidal.py:104
                    'allowStreaming': True, 'streamReady': True, 'adSupportedStreamReady': True, 'djReady': True, 'stemReady':
                    False, 'streamStartDate': '2021-12-02T11:00:00.000+0000', 'premiumStreamingOnly': False, 'trackNumber': 3,
                    'volumeNumber': 1, 'version': None, 'popularity': 14, 'copyright': None, 'bpm': None, 'url':
                    'http://www.tidal.com/track/207278424', 'isrc': 'HKC991900014', 'editable': False, 'explicit': False,
                    'audioQuality': 'LOSSLESS', 'audioModes': ['STEREO', 'DOLBY_ATMOS'], 'mediaMetadata': {'tags': ['LOSSLESS',
                    'HIRES_LOSSLESS', 'DOLBY_ATMOS']}, 'artist': {'id': 10797314, 'name': 'Terence Lam', 'type': 'MAIN',
                    'picture': '0d76778f-77fa-44c6-a811-3adf79b26833'}, 'artists': [{'id': 10797314, 'name': 'Terence Lam',
                    'type': 'MAIN', 'picture': '0d76778f-77fa-44c6-a811-3adf79b26833'}], 'album': {'id': 207278421, 'title':
                    'SEVEN', 'cover': '47b9024c-4065-4794-a337-593d3d353fea', 'vibrantColor': '#FFFFFF', 'videoCover': None},
                    'mixes': {'TRACK_MIX': '001f87222314f3c14158e1baab15fa'}}
[21:10:28] DEBUG    Removing dirs set()                                                                                          artwork.py:19
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ in _run_module_as_main:198                                                                       │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │   alter_argv = False                                                                         │ │
│ │         code = <code object <module> at 0x0000020D166E16B0, file                             │ │
│ │                "C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\__mai… │ │
│ │                line 1>                                                                       │ │
│ │ main_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,    │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,    │ │
│ │                origin='C:\\Users\\abcdefg\\AppData\\Local\\Programs\\Python\\Python312\\Script… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\abcdefg\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip.… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\abcdefg\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip.… │ │
│ │                │   're': <module 're' from                                                   │ │
│ │                'C:\\Users\\abcdefg\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\re\\__in… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,    │ │
│ │                origin='C:\\Users\\abcdefg\\AppData\\Local\\Programs\\Python\\Python312\\Script… │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│ in _run_code:88                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │       cached = 'C:\\Users\\abcdefg\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip.… │ │
│ │         code = <code object <module> at 0x0000020D166E16B0, file                             │ │
│ │                "C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\__mai… │ │
│ │                line 1>                                                                       │ │
│ │        fname = 'C:\\Users\\abcdefg\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip.… │ │
│ │ init_globals = None                                                                          │ │
│ │       loader = <zipimporter object                                                           │ │
│ │                "C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">     │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,    │ │
│ │                origin='C:\\Users\\abcdefg\\AppData\\Local\\Programs\\Python\\Python312\\Script… │ │
│ │     pkg_name = ''                                                                            │ │
│ │  run_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,    │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,    │ │
│ │                origin='C:\\Users\\abcdefg\\AppData\\Local\\Programs\\Python\\Python312\\Script… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\abcdefg\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip.… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\abcdefg\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip.… │ │
│ │                │   're': <module 're' from                                                   │ │
│ │                'C:\\Users\\abcdefg\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\re\\__in… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │  script_name = None                                                                          │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│ C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py:1157 in    │
│ __call__                                                                                         │
│                                                                                                  │
│ C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py:1078 in    │
│ main                                                                                             │
│                                                                                                  │
│ C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py:1688 in    │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py:1434 in    │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py:783 in     │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\decorators.py:33   │
│ in new_func                                                                                      │
│                                                                                                  │
│ C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\rip\cli.py:28  │
│ in wrapper                                                                                       │
│                                                                                                  │
│    25 def coro(f):                                                                               │
│    26 │   @wraps(f)                                                                              │
│    27 │   def wrapper(*args, **kwargs):                                                          │
│ >  28 │   │   return asyncio.run(f(*args, **kwargs))                                             │
│    29 │                                                                                          │
│    30 │   return wrapper                                                                         │
│    31                                                                                            │
│                                                                                                  │
│ ┌────────────────────────────── locals ──────────────────────────────┐                           │
│ │   args = (<click.core.Context object at 0x0000020D1A6125A0>,)      │                           │
│ │      f = <function url at 0x0000020D1A6E37E0>                      │                           │
│ │ kwargs = {'urls': ('https://tidal.com/browse/track/207278424?u',)} │                           │
│ └────────────────────────────────────────────────────────────────────┘                           │
│                                                                                                  │
│ C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py:194 in run          │
│                                                                                                  │
│   191 │   │   │   "asyncio.run() cannot be called from a running event loop")                    │
│   192 │                                                                                          │
│   193 │   with Runner(debug=debug, loop_factory=loop_factory) as runner:                         │
│ > 194 │   │   return runner.run(main)                                                            │
│   195                                                                                            │
│   196                                                                                            │
│   197 def _cancel_all_tasks(loop):                                                               │
│                                                                                                  │
│ ┌─────────────────────────────── locals ───────────────────────────────┐                         │
│ │        debug = None                                                  │                         │
│ │ loop_factory = None                                                  │                         │
│ │         main = <coroutine object url at 0x0000020D1A6C0DC0>          │                         │
│ │       runner = <asyncio.runners.Runner object at 0x0000020D1A6EAF00> │                         │
│ └──────────────────────────────────────────────────────────────────────┘                         │
│                                                                                                  │
│ C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py:118 in run          │
│                                                                                                  │
│   115 │   │                                                                                      │
│   116 │   │   self._interrupt_count = 0                                                          │
│   117 │   │   try:                                                                               │
│ > 118 │   │   │   return self._loop.run_until_complete(task)                                     │
│   119 │   │   except exceptions.CancelledError:                                                  │
│   120 │   │   │   if self._interrupt_count > 0:                                                  │
│   121 │   │   │   │   uncancel = getattr(task, "uncancel", None)                                 │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │        context = <_contextvars.Context object at 0x0000020D1A714D80>                         │ │
│ │           coro = <coroutine object url at 0x0000020D1A6C0DC0>                                │ │
│ │           self = <asyncio.runners.Runner object at 0x0000020D1A6EAF00>                       │ │
│ │ sigint_handler = functools.partial(<bound method Runner._on_sigint of                        │ │
│ │                  <asyncio.runners.Runner object at 0x0000020D1A6EAF00>>, main_task=<Task     │ │
│ │                  finished name='Task-1' coro=<url() done, defined at                         │ │
│ │                  C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\site-packages\st… │ │
│ │                  exception=AssertionError()>)                                                │ │
│ │           task = <Task finished name='Task-1' coro=<url() done, defined at                   │ │
│ │                  C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\site-packages\st… │ │
│ │                  exception=AssertionError()>                                                 │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:687 in          │
│ run_until_complete                                                                               │
│                                                                                                  │
│    684 │   │   if not future.done():                                                             │
│    685 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')             │
│    686 │   │                                                                                     │
│ >  687 │   │   return future.result()                                                            │
│    688 │                                                                                         │
│    689 │   def stop(self):                                                                       │
│    690 │   │   """Stop running the event loop.                                                   │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │   future = <Task finished name='Task-1' coro=<url() done, defined at                         │ │
│ │            C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamri… │ │
│ │            exception=AssertionError()>                                                       │ │
│ │ new_task = False                                                                             │ │
│ │     self = <_WindowsSelectorEventLoop running=False closed=True debug=False>                 │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\rip\cli.py:167 │
│ in url                                                                                           │
│                                                                                                  │
│   164 │   │                                                                                      │
│   165 │   │   async with Main(cfg) as main:                                                      │
│   166 │   │   │   await main.add_all(urls)                                                       │
│ > 167 │   │   │   await main.resolve()                                                           │
│   168 │   │   │   await main.rip()                                                               │
│   169 │   │                                                                                      │
│   170 │   │   if version_coro is not None:                                                       │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │          cfg = <streamrip.config.Config object at 0x0000020D1A6EAC30>                        │ │
│ │          ctx = <click.core.Context object at 0x0000020D1A6125A0>                             │ │
│ │         main = <streamrip.rip.main.Main object at 0x0000020D1A774410>                        │ │
│ │      updates = True                                                                          │ │
│ │         urls = ('https://tidal.com/browse/track/207278424?u',)                               │ │
│ │ version_coro = <Task finished name='Task-2' coro=<latest_streamrip_version() done, defined   │ │
│ │                at                                                                            │ │
│ │                C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\site-packages\stre… │ │
│ │                result=('2.0.5', None)>                                                       │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\rip\main.py:15 │
│ 7 in resolve                                                                                     │
│                                                                                                  │
│   154 │   │   with console.status("Resolving URLs...", spinner="dots"):                          │
│   155 │   │   │   coros = [p.resolve() for p in self.pending]                                    │
│   156 │   │   │   new_media: list[Media] = [                                                     │
│ > 157 │   │   │   │   m for m in await asyncio.gather(*coros) if m is not None                   │
│   158 │   │   │   ]                                                                              │
│   159 │   │                                                                                      │
│   160 │   │   self.media.extend(new_media)                                                       │
│                                                                                                  │
│ ┌───────────────────────────────── locals ─────────────────────────────────┐                     │
│ │ coros = [<coroutine object PendingSingle.resolve at 0x0000020D1A55BB00>] │                     │
│ │  self = <streamrip.rip.main.Main object at 0x0000020D1A774410>           │                     │
│ └──────────────────────────────────────────────────────────────────────────┘                     │
│                                                                                                  │
│ C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\media\track.py │
│ :157 in resolve                                                                                  │
│                                                                                                  │
│   154 │   │   │   logger.error(f"Error fetching track {self.id}: {e}")                           │
│   155 │   │   │   return None                                                                    │
│   156 │   │   # Patch for soundcloud                                                             │
│ > 157 │   │   album = AlbumMetadata.from_track_resp(resp, self.client.source)                    │
│   158 │   │   if album is None:                                                                  │
│   159 │   │   │   self.db.set_failed(self.client.source, "track", self.id)                       │
│   160 │   │   │   logger.error(                                                                  │
│                                                                                                  │
│ ┌─────────────────────────────────────── locals ───────────────────────────────────────┐         │
│ │ resp = {                                                                             │         │
│ │        │   'id': 207278424,                                                          │         │
│ │        │   'title': '神奇的糊塗魔藥',                                                │         │
│ │        │   'duration': 203,                                                          │         │
│ │        │   'replayGain': -9.61,                                                      │         │
│ │        │   'peak': 0.991646,                                                         │         │
│ │        │   'allowStreaming': True,                                                   │         │
│ │        │   'streamReady': True,                                                      │         │
│ │        │   'adSupportedStreamReady': True,                                           │         │
│ │        │   'djReady': True,                                                          │         │
│ │        │   'stemReady': False,                                                       │         │
│ │        │   ... +19                                                                   │         │
│ │        }                                                                             │         │
│ │ self = PendingSingle(                                                                │         │
│ │        │   id='207278424',                                                           │         │
│ │        │   client=<streamrip.client.tidal.TidalClient object at 0x0000020D1A774470>, │         │
│ │        │   config=<streamrip.config.Config object at 0x0000020D1A6EAC30>,            │         │
│ │        │   db=Database(                                                              │         │
│ │        │   │   downloads=<streamrip.db.Downloads object at 0x0000020D1A774800>,      │         │
│ │        │   │   failed=<streamrip.db.Failed object at 0x0000020D1A774830>             │         │
│ │        │   )                                                                         │         │
│ │        )                                                                             │         │
│ └──────────────────────────────────────────────────────────────────────────────────────┘         │
│                                                                                                  │
│ C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\metadata\album │
│ .py:498 in from_track_resp                                                                       │
│                                                                                                  │
│   495 │   │   if source == "qobuz":                                                              │
│   496 │   │   │   return cls.from_qobuz(resp["album"])                                           │
│   497 │   │   if source == "tidal":                                                              │
│ > 498 │   │   │   return cls.from_tidal_playlist_track_resp(resp)                                │
│   499 │   │   if source == "soundcloud":                                                         │
│   500 │   │   │   return cls.from_soundcloud(resp)                                               │
│   501 │   │   if source == "deezer":                                                             │
│                                                                                                  │
│ ┌───────────────────────── locals ──────────────────────────┐                                    │
│ │    cls = <class 'streamrip.metadata.album.AlbumMetadata'> │                                    │
│ │   resp = {                                                │                                    │
│ │          │   'id': 207278424,                             │                                    │
│ │          │   'title': '神奇的糊塗魔藥',                   │                                    │
│ │          │   'duration': 203,                             │                                    │
│ │          │   'replayGain': -9.61,                         │                                    │
│ │          │   'peak': 0.991646,                            │                                    │
│ │          │   'allowStreaming': True,                      │                                    │
│ │          │   'streamReady': True,                         │                                    │
│ │          │   'adSupportedStreamReady': True,              │                                    │
│ │          │   'djReady': True,                             │                                    │
│ │          │   'stemReady': False,                          │                                    │
│ │          │   ... +19                                      │                                    │
│ │          }                                                │                                    │
│ │ source = 'tidal'                                          │                                    │
│ └───────────────────────────────────────────────────────────┘                                    │
│                                                                                                  │
│ C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\metadata\album │
│ .py:386 in from_tidal_playlist_track_resp                                                        │
│                                                                                                  │
│   383 │   │   else:                                                                              │
│   384 │   │   │   year = "Unknown Year"                                                          │
│   385 │   │                                                                                      │
│ > 386 │   │   _copyright = typed(resp.get("copyright"), str)                                     │
│   387 │   │   artists = typed(resp.get("artists", []), list)                                     │
│   388 │   │   albumartist = ", ".join(a["name"] for a in artists)                                │
│   389 │   │   if not albumartist:                                                                │
│                                                                                                  │
│ ┌───────────────────────────── locals ──────────────────────────────┐                            │
│ │      album = 'SEVEN'                                              │                            │
│ │ album_resp = {                                                    │                            │
│ │              │   'id': 207278421,                                 │                            │
│ │              │   'title': 'SEVEN',                                │                            │
│ │              │   'cover': '47b9024c-4065-4794-a337-593d3d353fea', │                            │
│ │              │   'vibrantColor': '#FFFFFF',                       │                            │
│ │              │   'videoCover': None                               │                            │
│ │              }                                                    │                            │
│ │        cls = <class 'streamrip.metadata.album.AlbumMetadata'>     │                            │
│ │       date = '2021-12-02T11:00:00.000+0000'                       │                            │
│ │    item_id = '207278424'                                          │                            │
│ │       resp = {                                                    │                            │
│ │              │   'id': 207278424,                                 │                            │
│ │              │   'title': '神奇的糊塗魔藥',                       │                            │
│ │              │   'duration': 203,                                 │                            │
│ │              │   'replayGain': -9.61,                             │                            │
│ │              │   'peak': 0.991646,                                │                            │
│ │              │   'allowStreaming': True,                          │                            │
│ │              │   'streamReady': True,                             │                            │
│ │              │   'adSupportedStreamReady': True,                  │                            │
│ │              │   'djReady': True,                                 │                            │
│ │              │   'stemReady': False,                              │                            │
│ │              │   ... +19                                          │                            │
│ │              }                                                    │                            │
│ │ streamable = True                                                 │                            │
│ │ tracktotal = 1                                                    │                            │
│ │       year = '2021'                                               │                            │
│ └───────────────────────────────────────────────────────────────────┘                            │
│                                                                                                  │
│ C:\Users\abcdefg\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\metadata\util. │
│ py:24 in typed                                                                                   │
│                                                                                                  │
│   21                                                                                             │
│   22                                                                                             │
│   23 def typed(thing, expected_type: Type[T]) -> T:                                              │
│ > 24 │   assert isinstance(thing, expected_type)                                                 │
│   25 │   return thing                                                                            │
│   26                                                                                             │
│   27                                                                                             │
│                                                                                                  │
│ ┌─────────── locals ────────────┐                                                                │
│ │ expected_type = <class 'str'> │                                                                │
│ │         thing = None          │                                                                │
│ └───────────────────────────────┘                                                                │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
AssertionError
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = ""
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = false
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = ""
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = ""
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = ""

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Windows 11

### streamrip version

2.0.5
