### ISSUE TITLE
[BUG] Error when ripping from Deezer

### ISSUE THREAD

**Issue by KazooBoye** [nathom/streamrip#731]
### Describe the bug

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Issue newly encountered, i was able to run the command fine until today.

### Command Used

```bash
rip --quality 2 -vvv url https://www.deezer.com/en/artist/13277279
```

### Debug Traceback

```text
[04:07:45] DEBUG    Showing all debug logs                                                                    cli.py:102
[04:07:48] DEBUG    Removing dirs set()                                                                    artwork.py:19
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/py312venv/lib/python3.12/site-packages/requests/models.py:974 in json                      │
│                                                                                                  │
│    971 │   │   │   │   │   raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)                    │
│    972 │   │                                                                                     │
│    973 │   │   try:                                                                              │
│ ❱  974 │   │   │   return complexjson.loads(self.text, **kwargs)                                 │
│    975 │   │   except JSONDecodeError as e:                                                      │
│    976 │   │   │   # Catch JSON-related errors and raise as requests.JSONDecodeError             │
│    977 │   │   │   # This aliases json.JSONDecodeError and simplejson.JSONDecodeError            │
│                                                                                                  │
│ ╭───────── locals ──────────╮                                                                    │
│ │ kwargs = {}               │                                                                    │
│ │   self = <Response [200]> │                                                                    │
│ ╰───────────────────────────╯                                                                    │
│                                                                                                  │
│ /root/.pyenv/versions/3.12.5/lib/python3.12/json/__init__.py:346 in loads                        │
│                                                                                                  │
│   343 │   if (cls is None and object_hook is None and                                            │
│   344 │   │   │   parse_int is None and parse_float is None and                                  │
│   345 │   │   │   parse_constant is None and object_pairs_hook is None and not kw):              │
│ ❱ 346 │   │   return _default_decoder.decode(s)                                                  │
│   347 │   if cls is None:                                                                        │
│   348 │   │   cls = JSONDecoder                                                                  │
│   349 │   if object_hook is not None:                                                            │
│                                                                                                  │
│ ╭───────── locals ─────────╮                                                                     │
│ │               cls = None │                                                                     │
│ │                kw = {}   │                                                                     │
│ │       object_hook = None │                                                                     │
│ │ object_pairs_hook = None │                                                                     │
│ │    parse_constant = None │                                                                     │
│ │       parse_float = None │                                                                     │
│ │         parse_int = None │                                                                     │
│ │                 s = ''   │                                                                     │
│ ╰──────────────────────────╯                                                                     │
│                                                                                                  │
│ /root/.pyenv/versions/3.12.5/lib/python3.12/json/decoder.py:337 in decode                        │
│                                                                                                  │
│   334 │   │   containing a JSON document).                                                       │
│   335 │   │                                                                                      │
│   336 │   │   """                                                                                │
│ ❱ 337 │   │   obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                  │
│   338 │   │   end = _w(s, end).end()                                                             │
│   339 │   │   if end != len(s):                                                                  │
│   340 │   │   │   raise JSONDecodeError("Extra data", s, end)                                    │
│                                                                                                  │
│ ╭─────────────────────────────── locals ────────────────────────────────╮                        │
│ │   _w = <built-in method match of re.Pattern object at 0x7f06bfbd9630> │                        │
│ │    s = ''                                                             │                        │
│ │ self = <json.decoder.JSONDecoder object at 0x7f06c00dae40>            │                        │
│ ╰───────────────────────────────────────────────────────────────────────╯                        │
│                                                                                                  │
│ /root/.pyenv/versions/3.12.5/lib/python3.12/json/decoder.py:355 in raw_decode                    │
│                                                                                                  │
│   352 │   │   try:                                                                               │
│   353 │   │   │   obj, end = self.scan_once(s, idx)                                              │
│   354 │   │   except StopIteration as err:                                                       │
│ ❱ 355 │   │   │   raise JSONDecodeError("Expecting value", s, err.value) from None               │
│   356 │   │   return obj, end                                                                    │
│   357                                                                                            │
│                                                                                                  │
│ ╭────────────────────────── locals ──────────────────────────╮                                   │
│ │  idx = 0                                                   │                                   │
│ │    s = ''                                                  │                                   │
│ │ self = <json.decoder.JSONDecoder object at 0x7f06c00dae40> │                                   │
│ ╰────────────────────────────────────────────────────────────╯                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/py312venv/bin/rip:8 in <module>                                                            │
│                                                                                                  │
│   5 from streamrip.rip import rip                                                                │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(rip())                                                                          │
│   9                                                                                              │
│                                                                                                  │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮        │
│ │  re = <module 're' from '/root/.pyenv/versions/3.12.5/lib/python3.12/re/__init__.py'> │        │
│ │ rip = <HelpColorsGroup rip>                                                           │        │
│ │ sys = <module 'sys' (built-in)>                                                       │        │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯        │
│                                                                                                  │
│ /root/py312venv/lib/python3.12/site-packages/click/core.py:1157 in __call__                      │
│                                                                                                  │
│ /root/py312venv/lib/python3.12/site-packages/click/core.py:1078 in main                          │
│                                                                                                  │
│ /root/py312venv/lib/python3.12/site-packages/click/core.py:1688 in invoke                        │
│                                                                                                  │
│ /root/py312venv/lib/python3.12/site-packages/click/core.py:1434 in invoke                        │
│                                                                                                  │
│ /root/py312venv/lib/python3.12/site-packages/click/core.py:783 in invoke                         │
│                                                                                                  │
│ /root/py312venv/lib/python3.12/site-packages/click/decorators.py:33 in new_func                  │
│                                                                                                  │
│ /root/py312venv/lib/python3.12/site-packages/streamrip/rip/cli.py:28 in wrapper                  │
│                                                                                                  │
│    25 def coro(f):                                                                               │
│    26 │   @wraps(f)                                                                              │
│    27 │   def wrapper(*args, **kwargs):                                                          │
│ ❱  28 │   │   return asyncio.run(f(*args, **kwargs))                                             │
│    29 │                                                                                          │
│    30 │   return wrapper                                                                         │
│    31                                                                                            │
│                                                                                                  │
│ ╭───────────────────────────── locals ──────────────────────────────╮                            │
│ │   args = (<click.core.Context object at 0x7f06bec0ea80>,)         │                            │
│ │      f = <function url at 0x7f06be46b600>                         │                            │
│ │ kwargs = {'urls': ('https://www.deezer.com/en/album/550173122',)} │                            │
│ ╰───────────────────────────────────────────────────────────────────╯                            │
│                                                                                                  │
│ /root/.pyenv/versions/3.12.5/lib/python3.12/asyncio/runners.py:194 in run                        │
│                                                                                                  │
│   191 │   │   │   "asyncio.run() cannot be called from a running event loop")                    │
│   192 │                                                                                          │
│   193 │   with Runner(debug=debug, loop_factory=loop_factory) as runner:                         │
│ ❱ 194 │   │   return runner.run(main)                                                            │
│   195                                                                                            │
│   196                                                                                            │
│   197 def _cancel_all_tasks(loop):                                                               │
│                                                                                                  │
│ ╭───────────────────────────── locals ─────────────────────────────╮                             │
│ │        debug = None                                              │                             │
│ │ loop_factory = None                                              │                             │
│ │         main = <coroutine object url at 0x7f06be59ee60>          │                             │
│ │       runner = <asyncio.runners.Runner object at 0x7f06be5b1910> │                             │
│ ╰──────────────────────────────────────────────────────────────────╯                             │
│                                                                                                  │
│ /root/.pyenv/versions/3.12.5/lib/python3.12/asyncio/runners.py:118 in run                        │
│                                                                                                  │
│   115 │   │                                                                                      │
│   116 │   │   self._interrupt_count = 0                                                          │
│   117 │   │   try:                                                                               │
│ ❱ 118 │   │   │   return self._loop.run_until_complete(task)                                     │
│   119 │   │   except exceptions.CancelledError:                                                  │
│   120 │   │   │   if self._interrupt_count > 0:                                                  │
│   121 │   │   │   │   uncancel = getattr(task, "uncancel", None)                                 │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │        context = <_contextvars.Context object at 0x7f06be217340>                             │ │
│ │           coro = <coroutine object url at 0x7f06be59ee60>                                    │ │
│ │           self = <asyncio.runners.Runner object at 0x7f06be5b1910>                           │ │
│ │ sigint_handler = functools.partial(<bound method Runner._on_sigint of                        │ │
│ │                  <asyncio.runners.Runner object at 0x7f06be5b1910>>, main_task=<Task         │ │
│ │                  finished name='Task-1' coro=<url() done, defined at                         │ │
│ │                  /root/py312venv/lib/python3.12/site-packages/streamrip/rip/cli.py:150>      │ │
│ │                  exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>)    │ │
│ │           task = <Task finished name='Task-1' coro=<url() done, defined at                   │ │
│ │                  /root/py312venv/lib/python3.12/site-packages/streamrip/rip/cli.py:150>      │ │
│ │                  exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>     │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /root/.pyenv/versions/3.12.5/lib/python3.12/asyncio/base_events.py:687 in run_until_complete     │
│                                                                                                  │
│    684 │   │   if not future.done():                                                             │
│    685 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')             │
│    686 │   │                                                                                     │
│ ❱  687 │   │   return future.result()                                                            │
│    688 │                                                                                         │
│    689 │   def stop(self):                                                                       │
│    690 │   │   """Stop running the event loop.                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   future = <Task finished name='Task-1' coro=<url() done, defined at                         │ │
│ │            /root/py312venv/lib/python3.12/site-packages/streamrip/rip/cli.py:150>            │ │
│ │            exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>           │ │
│ │ new_task = False                                                                             │ │
│ │     self = <_UnixSelectorEventLoop running=False closed=True debug=False>                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /root/py312venv/lib/python3.12/site-packages/streamrip/rip/cli.py:166 in url                     │
│                                                                                                  │
│   163 │   │   │   version_coro = None                                                            │
│   164 │   │                                                                                      │
│   165 │   │   async with Main(cfg) as main:                                                      │
│ ❱ 166 │   │   │   await main.add_all(urls)                                                       │
│   167 │   │   │   await main.resolve()                                                           │
│   168 │   │   │   await main.rip()                                                               │
│   169                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │          cfg = <streamrip.config.Config object at 0x7f06be40fb30>                            │ │
│ │          ctx = <click.core.Context object at 0x7f06bec0ea80>                                 │ │
│ │         main = <streamrip.rip.main.Main object at 0x7f06be444740>                            │ │
│ │      updates = True                                                                          │ │
│ │         urls = ('https://www.deezer.com/en/album/550173122',)                                │ │
│ │ version_coro = <Task cancelled name='Task-2' coro=<latest_streamrip_version() done, defined  │ │
│ │                at /root/py312venv/lib/python3.12/site-packages/streamrip/rip/cli.py:414>>    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /root/py312venv/lib/python3.12/site-packages/streamrip/rip/main.py:121 in add_all                │
│                                                                                                  │
│   118 │   │   │   │   │   f"[red]Found invalid url [cyan]{urls[i]}[/cyan], skipping.",           │
│   119 │   │   │   │   )                                                                          │
│   120 │   │   │   │   continue                                                                   │
│ ❱ 121 │   │   │   url_client_pairs.append((p, await self.get_logged_in_client(p.source)))        │
│   122 │   │                                                                                      │
│   123 │   │   pendings = await asyncio.gather(                                                   │
│   124 │   │   │   *[                                                                             │
│                                                                                                  │
│ ╭────────────────────────────────────── locals ──────────────────────────────────────╮           │
│ │                i = 0                                                               │           │
│ │                p = <streamrip.rip.parse_url.GenericURL object at 0x7f06be4d6f60>   │           │
│ │           parsed = [<streamrip.rip.parse_url.GenericURL object at 0x7f06be4d6f60>] │           │
│ │             self = <streamrip.rip.main.Main object at 0x7f06be444740>              │           │
│ │ url_client_pairs = []                                                              │           │
│ │             urls = ('https://www.deezer.com/en/album/550173122',)                  │           │
│ ╰────────────────────────────────────────────────────────────────────────────────────╯           │
│                                                                                                  │
│ /root/py312venv/lib/python3.12/site-packages/streamrip/rip/main.py:147 in get_logged_in_client   │
│                                                                                                  │
│   144 │   │   │   else:                                                                          │
│   145 │   │   │   │   with console.status(f"[cyan]Logging into {source}", spinner="dots"):       │
│   146 │   │   │   │   │   # Log into client using credentials from config                        │
│ ❱ 147 │   │   │   │   │   await client.login()                                                   │
│   148 │   │                                                                                      │
│   149 │   │   assert client.logged_in                                                            │
│   150 │   │   return client                                                                      │
│                                                                                                  │
│ ╭────────────────────────────────── locals ───────────────────────────────────╮                  │
│ │   client = <streamrip.client.deezer.DeezerClient object at 0x7f06be4d6b10>  │                  │
│ │ prompter = <streamrip.rip.prompter.DeezerPrompter object at 0x7f06be4d6f30> │                  │
│ │     self = <streamrip.rip.main.Main object at 0x7f06be444740>               │                  │
│ │   source = 'deezer'                                                         │                  │
│ ╰─────────────────────────────────────────────────────────────────────────────╯                  │
│                                                                                                  │
│ /root/py312venv/lib/python3.12/site-packages/streamrip/client/deezer.py:49 in login              │
│                                                                                                  │
│    46 │   │   arl = self.config.arl                                                              │
│    47 │   │   if not arl:                                                                        │
│    48 │   │   │   raise MissingCredentialsError                                                  │
│ ❱  49 │   │   success = self.client.login_via_arl(arl)                                           │
│    50 │   │   if not success:                                                                    │
│    51 │   │   │   raise AuthenticationError                                                      │
│    52 │   │   self.logged_in = True                                                              │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │  arl = 'a679e677a2b891410b052988ba8d96cb57d0efa3778a45a74db5f6aefeb14922083daecd4697b8fb'+1… │ │
│ │ self = <streamrip.client.deezer.DeezerClient object at 0x7f06be4d6b10>                       │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /root/py312venv/lib/python3.12/site-packages/deezer/__init__.py:98 in login_via_arl              │
│                                                                                                  │
│    95 │   │   │   rest={'HttpOnly': True}                                                        │
│    96 │   │   )                                                                                  │
│    97 │   │   self.session.cookies.set_cookie(cookie_obj)                                        │
│ ❱  98 │   │   user_data = self.gw.get_user_data()                                                │
│    99 │   │   # Check if user logged in                                                          │
│   100 │   │   if not user_data or user_data and len(user_data.keys()) == 0:                      │
│   101 │   │   │   self.logged_in = False                                                         │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │        arl = 'a679e677a2b891410b052988ba8d96cb57d0efa3778a45a74db5f6aefeb14922083daecd4697b… │ │
│ │      child = 0                                                                               │ │
│ │ cookie_obj = Cookie(version=0, name='arl',                                                   │ │
│ │              value='a679e677a2b891410b052988ba8d96cb57d0efa3778a45a74db5f6aefeb14922083daec… │ │
│ │              port=None, port_specified=False, domain='.deezer.com', domain_specified=True,   │ │
│ │              domain_initial_dot=True, path='/', path_specified=True, secure=False,           │ │
│ │              expires=None, discard=True, comment=None, comment_url=None, rest={'HttpOnly':   │ │
│ │              True}, rfc2109=False)                                                           │ │
│ │       self = <deezer.Deezer object at 0x7f06be4d6b70>                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /root/py312venv/lib/python3.12/site-packages/deezer/gw.py:72 in get_user_data                    │
│                                                                                                  │
│    69 │   │   return token_data['checkForm']                                                     │
│    70 │                                                                                          │
│    71 │   def get_user_data(self):                                                               │
│ ❱  72 │   │   return self.api_call('deezer.getUserData')                                         │
│    73 │                                                                                          │
│    74 │   def get_user_profile_page(self, user_id, tab, limit=10):                               │
│    75 │   │   return self.api_call('deezer.pageProfile', {'USER_ID': user_id, 'tab': tab, 'nb'   │
│                                                                                                  │
│ ╭──────────────────── locals ────────────────────╮                                               │
│ │ self = <deezer.gw.GW object at 0x7f06be4d6e10> │                                               │
│ ╰────────────────────────────────────────────────╯                                               │
│                                                                                                  │
│ /root/py312venv/lib/python3.12/site-packages/deezer/gw.py:48 in api_call                         │
│                                                                                                  │
│    45 │   │   │   │   timeout=30,                                                                │
│    46 │   │   │   │   json=args,                                                                 │
│    47 │   │   │   │   headers=self.http_headers                                                  │
│ ❱  48 │   │   │   ).json()                                                                       │
│    49 │   │   except (requests.ConnectionError, requests.Timeout):                               │
│    50 │   │   │   sleep(2)                                                                       │
│    51 │   │   │   return self.api_call(method, args, params)                                     │
│                                                                                                  │
│ ╭───────────────────── locals ─────────────────────╮                                             │
│ │   args = {}                                      │                                             │
│ │ method = 'deezer.getUserData'                    │                                             │
│ │      p = {                                       │                                             │
│ │          │   'api_version': '1.0',               │                                             │
│ │          │   'api_token': 'null',                │                                             │
│ │          │   'input': '3',                       │                                             │
│ │          │   'method': 'deezer.getUserData'      │                                             │
│ │          }                                       │                                             │
│ │ params = {}                                      │                                             │
│ │   self = <deezer.gw.GW object at 0x7f06be4d6e10> │                                             │
│ ╰──────────────────────────────────────────────────╯                                             │
│                                                                                                  │
│ /root/py312venv/lib/python3.12/site-packages/requests/models.py:978 in json                      │
│                                                                                                  │
│    975 │   │   except JSONDecodeError as e:                                                      │
│    976 │   │   │   # Catch JSON-related errors and raise as requests.JSONDecodeError             │
│    977 │   │   │   # This aliases json.JSONDecodeError and simplejson.JSONDecodeError            │
│ ❱  978 │   │   │   raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)                            │
│    979 │                                                                                         │
│    980 │   @property                                                                             │
│    981 │   def links(self):                                                                      │
│                                                                                                  │
│ ╭───────── locals ──────────╮                                                                    │
│ │ kwargs = {}               │                                                                    │
│ │   self = <Response [200]> │                                                                    │
│ ╰───────────────────────────╯                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Exception ignored in: <bound method BaseEventLoop.call_exception_handler of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.12.5/lib/python3.12/asyncio/base_events.py", line 1853, in call_exception_handler
  File "/root/.pyenv/versions/3.12.5/lib/python3.12/logging/__init__.py", line 1568, in error
  File "/root/.pyenv/versions/3.12.5/lib/python3.12/logging/__init__.py", line 1684, in _log
  File "/root/.pyenv/versions/3.12.5/lib/python3.12/logging/__init__.py", line 1700, in handle
  File "/root/.pyenv/versions/3.12.5/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
  File "/root/.pyenv/versions/3.12.5/lib/python3.12/logging/__init__.py", line 1028, in handle
  File "/root/py312venv/lib/python3.12/site-packages/rich/logging.py", line 160, in emit
  File "/root/py312venv/lib/python3.12/site-packages/rich/logging.py", line 221, in render
  File "/root/py312venv/lib/python3.12/site-packages/rich/_log_render.py", line 43, in __call__
ImportError: sys.meta_path is None, Python is likely shutting down
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/mnt/y/Plex/Music"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 10
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = false
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = ""
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = "a679e677a2b891410b052988ba8d96cb57d0efa3778a45a74db5f6aefeb14922083daecd4697b8fbcffd59cdb7c6538de544b862a0a80727e2ce7e80141599c9544ecd8874ae718e663196eac2f5ffb454c7e3911543b17eb936a8e05fb693da"
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "/Users/caoducanh/StreamripDownloads/YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "/root/.config/streamrip/downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "/root/.config/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Ubuntu 22 LTS on Windows WSL

### streamrip version

2.0.5

### Additional context

Issue newly encountered, i was able to run the command fine until today.
