### ISSUE TITLE
[BUG] folder_format tag isn't able to create new directory

### ISSUE THREAD

**Issue by niessenty** [nathom/streamrip#742]
### Describe the bug

I use the following as my folder format, so that I can have albums sorted into folders by artist

folder_format = "{albumartist}/{year} - {title} [{container}]-[{bit_depth}B-{sampling_rate}kHz] [{id}]"

When I run this on my computer (Windows), it correctly creates a new folder at the slash. When I run this on my NAS (inside a docker container), it ignores the slash, so I end up with a folder such as "Nothing But Thieves2018 - Lover, You Should Have Come Over [FLAC]-[24B-44.1kHz] [48306500]"

I have tried both a double backslash as well as a single forward slash in the NAS Config to get it to work, but to no avail.

### Command Used

```bash
rip file links.txt
```

### Debug Traceback

```text
streamrip-streamrip-web-1  |                     True, 'pre_register_zipcode': False,                        
streamrip-streamrip-web-1  |                     'music_import': True, 'radio': True},                       
streamrip-streamrip-web-1  |                     'player_settings': {'sonos_audio_format': 7},               
streamrip-streamrip-web-1  |                     'externals': {}}, 'user_auth_token':                        
streamrip-streamrip-web-1  |                     'REDACTED'}                  
streamrip-streamrip-web-1  |            DEBUG    Logged in to Qobuz                              qobuz.py:190
streamrip-streamrip-web-1  |            DEBUG    request params: {'app_id': 'REDACTED',         qobuz.py:222
streamrip-streamrip-web-1  |                     'album_id': 'ntgi63wv4n1rc', 'limit': 500,                  
streamrip-streamrip-web-1  |                     'offset': 0}                                                
streamrip-streamrip-web-1  |            DEBUG    api_request: endpoint=album/get,                qobuz.py:429
streamrip-streamrip-web-1  |                     params={'app_id': 'REDACTED', 'album_id':                  
streamrip-streamrip-web-1  |                     'ntgi63wv4n1rc', 'limit': 500, 'offset': 0}                 
streamrip-streamrip-web-1  | [12:07:40] DEBUG    Pending tracks: [PendingTrack(id=48306501,       album.py:97
streamrip-streamrip-web-1  |                     album=AlbumMetadata(info=AlbumInfo(id='48306500'            
streamrip-streamrip-web-1  |                     , quality=3, container='FLAC', label='RCA                   
streamrip-streamrip-web-1  |                     Records Label', explicit=False,                             
streamrip-streamrip-web-1  |                     sampling_rate=44.1, bit_depth=24,                           
streamrip-streamrip-web-1  |                     booklets=None), album='Lover, You Should Have               
streamrip-streamrip-web-1  |                     Come Over ', albumartist='Nothing But Thieves',             
streamrip-streamrip-web-1  |                     year='2018', genre=['Pop', 'Rock', 'Alternatif              
streamrip-streamrip-web-1  |                     et Indé'], covers=Covers(('original',                       
streamrip-streamrip-web-1  |                     'https://static.qobuz.com/images/covers/rc/n1/nt            
streamrip-streamrip-web-1  |                     gi63wv4n1rc_org.jpg',                                       
streamrip-streamrip-web-1  |                     '/root/StreamripDownloads/Nothing But                       
streamrip-streamrip-web-1  |                     Thieves2018 - Lover, You Should Have Come Over              
streamrip-streamrip-web-1  |                     [FLAC]-[24B-44.1kHz] [48306500]/cover.jpg')                 
streamrip-streamrip-web-1  |                     ('large',                                                   
streamrip-streamrip-web-1  |                     'https://static.qobuz.com/images/covers/rc/n1/nt            
streamrip-streamrip-web-1  |                     gi63wv4n1rc_600.jpg',                                       
streamrip-streamrip-web-1  |                     '/root/StreamripDownloads/Nothing But                       
streamrip-streamrip-web-1  |                     Thieves2018 - Lover, You Should Have Come Over              
streamrip-streamrip-web-1  |                     [FLAC]-[24B-44.1kHz]                                        
streamrip-streamrip-web-1  |                     [48306500]/__artwork/cover1767714330684783972.jp            
streamrip-streamrip-web-1  |                     g')                                                         
streamrip-streamrip-web-1  |                     ('small',                                                   
streamrip-streamrip-web-1  |                     'https://static.qobuz.com/images/covers/rc/n1/nt            
streamrip-streamrip-web-1  |                     gi63wv4n1rc_230.jpg', None)                                 
streamrip-streamrip-web-1  |                     ('thumbnail',                                               
streamrip-streamrip-web-1  |                     'https://static.qobuz.com/images/covers/rc/n1/nt            
streamrip-streamrip-web-1  |                     gi63wv4n1rc_50.jpg', None)), tracktotal=1,                  
streamrip-streamrip-web-1  |                     disctotal=1, albumcomposer='Jeff Buckley',                  
streamrip-streamrip-web-1  |                     comment=None, compilation=None, copyright='(P)              
streamrip-streamrip-web-1  |                     2018 BBC', date='2018-04-27', description='',               
streamrip-streamrip-web-1  |                     encoder=None, grouping=None, lyrics=None,                   
streamrip-streamrip-web-1  |                     purchase_date=None),                                        
streamrip-streamrip-web-1  |                     client=<streamrip.client.qobuz.QobuzClient                  
streamrip-streamrip-web-1  |                     object at 0x7fd73605abc0>,                                  
streamrip-streamrip-web-1  |                     config=<streamrip.config.Config object at                   
streamrip-streamrip-web-1  |                     0x7fd73619e6e0>,                                            
streamrip-streamrip-web-1  |                     folder='/root/StreamripDownloads/Nothing But                
streamrip-streamrip-web-1  |                     Thieves2018 - Lover, You Should Have Come Over              
streamrip-streamrip-web-1  |                     [FLAC]-[24B-44.1kHz] [48306500]',                           
streamrip-streamrip-web-1  |                     db=Database(downloads=<streamrip.db.Downloads               
streamrip-streamrip-web-1  |                     object at 0x7fd73605b220>,                                  
streamrip-streamrip-web-1  |                     failed=<streamrip.db.Failed object at                       
streamrip-streamrip-web-1  |                     0x7fd73605b310>),                                           
streamrip-streamrip-web-1  |                     cover_path='/root/StreamripDownloads/Nothing But            
streamrip-streamrip-web-1  |                     Thieves2018 - Lover, You Should Have Come Over              
streamrip-streamrip-web-1  |                     [FLAC]-[24B-44.1kHz]                                        
streamrip-streamrip-web-1  |                     [48306500]/__artwork/cover1767714330684783972.jp            
streamrip-streamrip-web-1  |                     g')]                                                        
streamrip-streamrip-web-1  |            DEBUG    Executing SELECT EXISTS(SELECT 1 FROM downloads    db.py:108
streamrip-streamrip-web-1  |                     WHERE id=?)                                                 
streamrip-streamrip-web-1  |            DEBUG    request params: {'app_id': '950096963',         qobuz.py:222
streamrip-streamrip-web-1  |                     'track_id': 48306501, 'limit': 500, 'offset':               
streamrip-streamrip-web-1  |                     0}                                                          
streamrip-streamrip-web-1  |            DEBUG    api_request: endpoint=track/get,                qobuz.py:429
streamrip-streamrip-web-1  |                     params={'app_id': '950096963', 'track_id':                  
streamrip-streamrip-web-1  |                     48306501, 'limit': 500, 'offset': 0}                        
streamrip-streamrip-web-1  |            DEBUG    Raw request signature:                          qobuz.py:412
streamrip-streamrip-web-1  |                     trackgetFileUrlformat_id7intentstreamtrack_id48             
streamrip-streamrip-web-1  |                     3065011726661260.6560507979549437fcc4a3faad4867             
streamrip-streamrip-web-1  |                     b5cd25dcb                                                   
streamrip-streamrip-web-1  |            DEBUG    Hashed request signature:                       qobuz.py:414
streamrip-streamrip-web-1  |                     beea665735b3530e10ee2ebc4b1050a0                            
streamrip-streamrip-web-1  |            DEBUG    api_request: endpoint=track/getFileUrl,         qobuz.py:429
streamrip-streamrip-web-1  |                     params={'request_ts': 1726661260.6560507,                   
streamrip-streamrip-web-1  |                     'request_sig':                                              
streamrip-streamrip-web-1  |                     'beea665735b3530e10ee2ebc4b1050a0', 'track_id':             
streamrip-streamrip-web-1  |                     48306501, 'format_id': 7, 'intent': 'stream'}               
streamrip-streamrip-web-1  | [12:07:59] DEBUG    Tagging with [('TITLE', 'Lover, You Should     tagger.py:253
streamrip-streamrip-web-1  |                     Have Come Over (Live at BBC Maida Vale                      
streamrip-streamrip-web-1  |                     Studios)'), ('ARTIST', 'Nothing But Thieves'),              
streamrip-streamrip-web-1  |                     ('ALBUM', 'Lover, You Should Have Come Over                 
streamrip-streamrip-web-1  |                     '), ('ALBUMARTIST', 'Nothing But Thieves'),                 
streamrip-streamrip-web-1  |                     ('COMPOSER', 'Jeff Buckley'), ('YEAR',                      
streamrip-streamrip-web-1  |                     '2018'), ('GENRE', 'Pop, Rock, Alternatif et                
streamrip-streamrip-web-1  |                     Indé'), ('COPYRIGHT', '℗ 2018 BBC'),                        
streamrip-streamrip-web-1  |                     ('TRACKNUMBER', '01'), ('DISCNUMBER', '01'),                
streamrip-streamrip-web-1  |                     ('TRACKTOTAL', '01'), ('DISCTOTAL', '01'),                  
streamrip-streamrip-web-1  |                     ('DATE', '2018-04-27'), ('ISRC',                            
streamrip-streamrip-web-1  |                     'GBCAD1700994')]                                            
streamrip-streamrip-web-1  |            DEBUG    Executing INSERT INTO downloads (id) VALUES (?)    db.py:124
streamrip-streamrip-web-1  |            DEBUG    Items to add: ('48306501',)                        db.py:125
streamrip-streamrip-web-1  | ───────────────── Downloading Lover, You Should Have Come Over ─────────────────           DEBUG    Removing dirs                                  artwork.py:19
streamrip-streamrip-web-1  |                     {'/root/StreamripDownloads/Nothing But                      
streamrip-streamrip-web-1  |                     Thieves2018 - Lover, You Should Have Come Over              
streamrip-streamrip-web-1  |                     [FLAC]-[24B-44.1kHz] [48306500]/__artwork'}
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/root/StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false
# Put tracks in an album with 2 or more discs into a subfolder named `Disc N` 
disc_subdirectories = true
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 1
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = true
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = "REDACTED"
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = "REDACTED"
# Do not change
app_id = "REDACTED"
# Do not change
secrets = ["REDACTED"]

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "/root/StreamripDownloads/YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "/root/.config/streamrip/downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "/root/.config/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = true
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist}/{year} - {title} [{container}]-[{bit_depth}B-{sampling_rate}kHz] [{id}]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{albumartist} - {tracknumber} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.6"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Linux

### streamrip version

2.0.5 (use beta version)
