### ISSUE TITLE
[BUG] Qobuz InvalidAppSecretError

### ISSUE THREAD

**Issue by bokkaebi** [nathom/streamrip#744]
### Describe the bug

Encounters InvalidAppSecretError whenever using Qobuz, even though valid userid and token is in config

### Command Used

```bash
rip search qobuz playlist chill
```

### Debug Traceback

```text
[22:52:16] DEBUG    Showing all debug logs                                         cli.py:102
[22:52:17] DEBUG    Raw request signature:                                       qobuz.py:414
                    trackgetFileUrlformat_id27intentstreamtrack_id19512574172770
                    7937.029917210b251c286cfbf64d6b7105f253d9a2e
           DEBUG    Hashed request signature: 549bc98ae806bd398b210c027b269f11   qobuz.py:416
           DEBUG    api_request: endpoint=track/getFileUrl,                      qobuz.py:431
                    params={'request_ts': 1727707937.0299172, 'request_sig':
                    '549bc98ae806bd398b210c027b269f11', 'track_id': '19512574',
                    'format_id': 27, 'intent': 'stream'}
           DEBUG    Raw request signature:                                       qobuz.py:414
                    trackgetFileUrlformat_id27intentstreamtrack_id19512574172770
                    7937.0349874979549437fcc4a3faad4867b5cd25dcb
           DEBUG    Hashed request signature: c65b17e9124b7a7e256eab8bb71de2b3   qobuz.py:416
           DEBUG    api_request: endpoint=track/getFileUrl,                      qobuz.py:431
                    params={'request_ts': 1727707937.0349874, 'request_sig':
                    'c65b17e9124b7a7e256eab8bb71de2b3', 'track_id': '19512574',
                    'format_id': 27, 'intent': 'stream'}
⠴ Logging into qobuz           WARNING  Got status 401 when testing secret
        qobuz.py:402
           DEBUG    Removing dirs set()                                         artwork.py:19
╭──────────────────────────── Traceback (most recent call last) ────────────────────────────╮
│ /home/zjm/.local/bin/rip:8 in <module>                                                    │
│                                                                                           │
│   5 from streamrip.rip import rip                                                         │
│   6 if __name__ == '__main__':                                                            │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                  │
│ ❱ 8 │   sys.exit(rip())                                                                   │
│   9                                                                                       │
│                                                                                           │
│ ╭─────────────────────────── locals ────────────────────────────╮                         │
│ │  re = <module 're' from '/usr/lib/python3.11/re/__init__.py'> │                         │
│ │ rip = <HelpColorsGroup rip>                                   │                         │
│ │ sys = <module 'sys' (built-in)>                               │                         │
│ ╰───────────────────────────────────────────────────────────────╯                         │
│                                                                                           │
│ /home/zjm/.local/lib/python3.11/site-packages/click/core.py:1157 in __call__              │
│                                                                                           │
│ /home/zjm/.local/lib/python3.11/site-packages/click/core.py:1078 in main                  │
│                                                                                           │
│ /home/zjm/.local/lib/python3.11/site-packages/click/core.py:1688 in invoke                │
│                                                                                           │
│ /home/zjm/.local/lib/python3.11/site-packages/click/core.py:1434 in invoke                │
│                                                                                           │
│ /home/zjm/.local/lib/python3.11/site-packages/click/core.py:783 in invoke                 │
│                                                                                           │
│ /home/zjm/.local/lib/python3.11/site-packages/click/decorators.py:33 in new_func          │
│                                                                                           │
│ /home/zjm/.local/lib/python3.11/site-packages/streamrip/rip/cli.py:28 in wrapper          │
│                                                                                           │
│    25 def coro(f):                                                                        │
│    26 │   @wraps(f)                                                                       │
│    27 │   def wrapper(*args, **kwargs):                                                   │
│ ❱  28 │   │   return asyncio.run(f(*args, **kwargs))                                      │
│    29 │                                                                                   │
│    30 │   return wrapper                                                                  │
│    31                                                                                     │
│                                                                                           │
│ ╭───────────────────────── locals ──────────────────────────╮                             │
│ │   args = (<click.core.Context object at 0x7f3dd2bab890>,) │                             │
│ │      f = <function search at 0x7f3dd035e5c0>              │                             │
│ │ kwargs = {                                                │                             │
│ │          │   'source': 'qobuz',                           │                             │
│ │          │   'media_type': 'playlist',                    │                             │
│ │          │   'query': 'chill',                            │                             │
│ │          │   'first': False,                              │                             │
│ │          │   'output_file': None,                         │                             │
│ │          │   'num_results': 100                           │                             │
│ │          }                                                │                             │
│ ╰───────────────────────────────────────────────────────────╯                             │
│                                                                                           │
│ /usr/lib/python3.11/asyncio/runners.py:188 in run                                         │
│                                                                                           │
│   185 │   │   │   "asyncio.run() cannot be called from a running event loop")             │
│   186 │                                                                                   │
│   187 │   with Runner(debug=debug) as runner:                                             │
│ ❱ 188 │   │   return runner.run(main)                                                     │
│   189                                                                                     │
│   190                                                                                     │
│   191 def _cancel_all_tasks(loop):                                                        │
│                                                                                           │
│ ╭────────────────────────── locals ──────────────────────────╮                            │
│ │  debug = None                                              │                            │
│ │   main = <coroutine object search at 0x7f3dd06620c0>       │                            │
│ │ runner = <asyncio.runners.Runner object at 0x7f3dd036dc90> │                            │
│ ╰────────────────────────────────────────────────────────────╯                            │
│                                                                                           │
│ /usr/lib/python3.11/asyncio/runners.py:120 in run                                         │
│                                                                                           │
│   117 │   │   try:                                                                        │
│   118 │   │   │   if self._set_event_loop:                                                │
│   119 │   │   │   │   events.set_event_loop(self._loop)                                   │
│ ❱ 120 │   │   │   return self._loop.run_until_complete(task)                              │
│   121 │   │   except exceptions.CancelledError:                                           │
│   122 │   │   │   if self._interrupt_count > 0:                                           │
│   123 │   │   │   │   uncancel = getattr(task, "uncancel", None)                          │
│                                                                                           │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮ │
│ │        context = <_contextvars.Context object at 0x7f3dd0192540>                      │ │
│ │           coro = <coroutine object search at 0x7f3dd06620c0>                          │ │
│ │           self = <asyncio.runners.Runner object at 0x7f3dd036dc90>                    │ │
│ │ sigint_handler = functools.partial(<bound method Runner._on_sigint of                 │ │
│ │                  <asyncio.runners.Runner object at 0x7f3dd036dc90>>, main_task=<Task  │ │
│ │                  finished name='Task-1' coro=<search() done, defined at               │ │
│ │                  /home/zjm/.local/lib/python3.11/site-packages/streamrip/rip/cli.py:… │ │
│ │                  exception=InvalidAppSecretError(['10b251c286cfbf64d6b7105f253d9a2e', │ │
│ │                  '979549437fcc4a3faad4867b5cd25dcb'])>)                               │ │
│ │           task = <Task finished name='Task-1' coro=<search() done, defined at         │ │
│ │                  /home/zjm/.local/lib/python3.11/site-packages/streamrip/rip/cli.py:… │ │
│ │                  exception=InvalidAppSecretError(['10b251c286cfbf64d6b7105f253d9a2e', │ │
│ │                  '979549437fcc4a3faad4867b5cd25dcb'])>                                │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                           │
│ /usr/lib/python3.11/asyncio/base_events.py:650 in run_until_complete                      │
│                                                                                           │
│    647 │   │   if not future.done():                                                      │
│    648 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')      │
│    649 │   │                                                                              │
│ ❱  650 │   │   return future.result()                                                     │
│    651 │                                                                                  │
│    652 │   def stop(self):                                                                │
│    653 │   │   """Stop running the event loop.                                            │
│                                                                                           │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮ │
│ │   future = <Task finished name='Task-1' coro=<search() done, defined at               │ │
│ │            /home/zjm/.local/lib/python3.11/site-packages/streamrip/rip/cli.py:327>    │ │
│ │            exception=InvalidAppSecretError(['10b251c286cfbf64d6b7105f253d9a2e',       │ │
│ │            '979549437fcc4a3faad4867b5cd25dcb'])>                                      │ │
│ │ new_task = False                                                                      │ │
│ │     self = <_UnixSelectorEventLoop running=False closed=True debug=False>             │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                           │
│ /home/zjm/.local/lib/python3.11/site-packages/streamrip/rip/cli.py:371 in search          │
│                                                                                           │
│   368 │   │   │   │   │   source, media_type, query, output_file, num_results             │
│   369 │   │   │   │   )                                                                   │
│   370 │   │   │   else:                                                                   │
│ ❱ 371 │   │   │   │   await main.search_interactive(source, media_type, query)            │
│   372 │   │   │   await main.resolve()                                                    │
│   373 │   │   │   await main.rip()                                                        │
│   374                                                                                     │
│                                                                                           │
│ ╭───────────────────────────── locals ─────────────────────────────╮                      │
│ │         cfg = <streamrip.config.Config object at 0x7f3dd15929d0> │                      │
│ │         ctx = <click.core.Context object at 0x7f3dd2bab890>      │                      │
│ │       first = False                                              │                      │
│ │        main = <streamrip.rip.main.Main object at 0x7f3dd0191fd0> │                      │
│ │  media_type = 'playlist'                                         │                      │
│ │ num_results = 100                                                │                      │
│ │ output_file = None                                               │                      │
│ │       query = 'chill'                                            │                      │
│ │      source = 'qobuz'                                            │                      │
│ ╰──────────────────────────────────────────────────────────────────╯                      │
│                                                                                           │
│ /home/zjm/.local/lib/python3.11/site-packages/streamrip/rip/main.py:168 in                │
│ search_interactive                                                                        │
│                                                                                           │
│   165 │   │   await asyncio.gather(*[item.rip() for item in self.media])                  │
│   166 │                                                                                   │
│   167 │   async def search_interactive(self, source: str, media_type: str, query: str):   │
│ ❱ 168 │   │   client = await self.get_logged_in_client(source)                            │
│   169 │   │                                                                               │
│   170 │   │   with console.status(f"[bold]Searching {source}", spinner="dots"):           │
│   171 │   │   │   pages = await client.search(media_type, query, limit=100)               │
│                                                                                           │
│ ╭──────────────────────────── locals ─────────────────────────────╮                       │
│ │ media_type = 'playlist'                                         │                       │
│ │      query = 'chill'                                            │                       │
│ │       self = <streamrip.rip.main.Main object at 0x7f3dd0191fd0> │                       │
│ │     source = 'qobuz'                                            │                       │
│ ╰─────────────────────────────────────────────────────────────────╯                       │
│                                                                                           │
│ /home/zjm/.local/lib/python3.11/site-packages/streamrip/rip/main.py:147 in                │
│ get_logged_in_client                                                                      │
│                                                                                           │
│   144 │   │   │   else:                                                                   │
│   145 │   │   │   │   with console.status(f"[cyan]Logging into {source}", spinner="dots") │
│   146 │   │   │   │   │   # Log into client using credentials from config                 │
│ ❱ 147 │   │   │   │   │   await client.login()                                            │
│   148 │   │                                                                               │
│   149 │   │   assert client.logged_in                                                     │
│   150 │   │   return client                                                               │
│                                                                                           │
│ ╭────────────────────────────────── locals ──────────────────────────────────╮            │
│ │   client = <streamrip.client.qobuz.QobuzClient object at 0x7f3dd036d510>   │            │
│ │ prompter = <streamrip.rip.prompter.QobuzPrompter object at 0x7f3dd0f7bcd0> │            │
│ │     self = <streamrip.rip.main.Main object at 0x7f3dd0191fd0>              │            │
│ │   source = 'qobuz'                                                         │            │
│ ╰────────────────────────────────────────────────────────────────────────────╯            │
│                                                                                           │
│ /home/zjm/.local/lib/python3.11/site-packages/streamrip/client/qobuz.py:166 in login      │
│                                                                                           │
│   163 │   │   │   f.set_modified()                                                        │
│   164 │   │                                                                               │
│   165 │   │   self.session.headers.update({"X-App-Id": c.app_id})                         │
│ ❱ 166 │   │   self.secret = await self._get_valid_secret(c.secrets)                       │
│   167 │   │                                                                               │
│   168 │   │   if c.use_auth_token:                                                        │
│   169 │   │   │   params = {                                                              │
│                                                                                           │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮ │
│ │    c = QobuzConfig(                                                                   │ │
│ │        │   use_auth_token=True,                                                       │ │
│ │        │   email_or_userid='3228063',                                                 │ │
│ │        │                                                                              │ │
│ │        password_or_token='**********************************************************… │ │
│ │        │   app_id='*********',                                                        │ │
│ │        │   quality=3,                                                                 │ │
│ │        │   download_booklets=True,                                                    │ │
│ │        │   secrets=['10b251c286cfbf64d6b7105f253d9a2e',                               │ │
│ │        '979549437fcc4a3faad4867b5cd25dcb']                                            │ │
│ │        )                                                                              │ │
│ │ self = <streamrip.client.qobuz.QobuzClient object at 0x7f3dd036d510>                  │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                           │
│ /home/zjm/.local/lib/python3.11/site-packages/streamrip/client/qobuz.py:392 in            │
│ _get_valid_secret                                                                         │
│                                                                                           │
│   389 │   │   working_secrets = [r for r in results if r is not None]                     │
│   390 │   │                                                                               │
│   391 │   │   if len(working_secrets) == 0:                                               │
│ ❱ 392 │   │   │   raise InvalidAppSecretError(secrets)                                    │
│   393 │   │                                                                               │
│   394 │   │   return working_secrets[0]                                                   │
│   395                                                                                     │
│                                                                                           │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮ │
│ │         results = [None, None]                                                        │ │
│ │         secrets = ['10b251c286cfbf64d6b7105f253d9a2e',                                │ │
│ │                   '979549437fcc4a3faad4867b5cd25dcb']                                 │ │
│ │            self = <streamrip.client.qobuz.QobuzClient object at 0x7f3dd036d510>       │ │
│ │ working_secrets = []                                                                  │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
InvalidAppSecretError: ['10b251c286cfbf64d6b7105f253d9a2e',
'979549437fcc4a3faad4867b5cd25dcb']
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/home/**/StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = true
# enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = "***"
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = "***_De4lkbCDaj21fDNXg"
# Do not change
app_id = "950096963"
# Do not change
secrets = ["10b251c286cfbf64d6b7105f253d9a2e", "979549437fcc4a3faad4867b5cd25dcb"]

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = 200914958
country_code = "NZ"
access_token = "**"
refresh_token = "***"
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = 1728312376.7948754

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = "***"
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "/home/***/StreamripDownloads/YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "/home/***/.config/streamrip/downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "/home/***/.config/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "deezer"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = "tidal"

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Linux

### streamrip version

2.0.5
