### ISSUE TITLE
[BUG] ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by Awlexegrecki** [nathom/streamrip#752]
### Describe the bug

This is my first time using streamrip, but I encountered this error. I just inputted the example code and tried to solve the first few bugs, but I don't know what this one means.

### Command Used

```bash
rip url "https://www.qobuz.com/us-en/album/brat-and-its-completely-different-but-also-still-brat-charli-xcx/nqmgu8p2fpvdb"
```

### Debug Traceback

```text
[21:38:47] DEBUG    Showing all debug logs                                                                    cli.py:102
           INFO     App id/secrets not found, fetching                                                      qobuz.py:157
[21:38:49] DEBUG    Removing dirs set()                                                                    artwork.py:19
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in _run_module_as_main:198                                                                       │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   alter_argv = False                                                                         │ │
│ │         code = <code object <module> at 0x000001C3CC9C0030, file                             │ │
│ │                "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\__ma… │ │
│ │                line 1>                                                                       │ │
│ │ main_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,   │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,   │ │
│ │                origin='C:\\Users\\<user>\\AppData\\Local\\Programs\\Python\\Python312\\Scrip… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\<user>\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\<user>\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip… │ │
│ │                │   're': <module 're' from                                                   │ │
│ │                'C:\\Users\\<user>\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\re\\__i… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,   │ │
│ │                origin='C:\\Users\\<user>\\AppData\\Local\\Programs\\Python\\Python312\\Scrip… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│ in _run_code:88                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │       cached = 'C:\\Users\\<user>\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip… │ │
│ │         code = <code object <module> at 0x000001C3CC9C0030, file                             │ │
│ │                "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\__ma… │ │
│ │                line 1>                                                                       │ │
│ │        fname = 'C:\\Users\\<user>\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip… │ │
│ │ init_globals = None                                                                          │ │
│ │       loader = <zipimporter object                                                           │ │
│ │                "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">    │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,   │ │
│ │                origin='C:\\Users\\<user>\\AppData\\Local\\Programs\\Python\\Python312\\Scrip… │ │
│ │     pkg_name = ''                                                                            │ │
│ │  run_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,   │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,   │ │
│ │                origin='C:\\Users\\<user>\\AppData\\Local\\Programs\\Python\\Python312\\Scrip… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\<user>\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\<user>\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip… │ │
│ │                │   're': <module 're' from                                                   │ │
│ │                'C:\\Users\\<user>\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\re\\__i… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │  script_name = None                                                                          │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│ C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py:1157 in   │
│ __call__                                                                                         │
│                                                                                                  │
│ C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py:1078 in   │
│ main                                                                                             │
│                                                                                                  │
│ C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py:1688 in   │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py:1434 in   │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py:783 in    │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\decorators.py:33  │
│ in new_func                                                                                      │
│                                                                                                  │
│ C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\rip\cli.py:28 │
│ in wrapper                                                                                       │
│                                                                                                  │
│    25 def coro(f):                                                                               │
│    26 │   @wraps(f)                                                                              │
│    27 │   def wrapper(*args, **kwargs):                                                          │
│ ❱  28 │   │   return asyncio.run(f(*args, **kwargs))                                             │
│    29 │                                                                                          │
│    30 │   return wrapper                                                                         │
│    31                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   args = (<click.core.Context object at 0x000001C3D06684A0>,)                                │ │
│ │ kwargs = {                                                                                   │ │
│ │          │   'urls': (                                                                       │ │
│ │          │   │                                                                               │ │
│ │          'https://www.qobuz.com/us-en/album/brat-and-its-completely-different-but-also-sti'… │ │
│ │          │   )                                                                               │ │
│ │          }                                                                                   │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py:194 in run         │
│                                                                                                  │
│   191 │   │   │   "asyncio.run() cannot be called from a running event loop")                    │
│   192 │                                                                                          │
│   193 │   with Runner(debug=debug, loop_factory=loop_factory) as runner:                         │
│ ❱ 194 │   │   return runner.run(main)                                                            │
│   195                                                                                            │
│   196                                                                                            │
│   197 def _cancel_all_tasks(loop):                                                               │
│                                                                                                  │
│ ╭─────────────────────────────── locals ───────────────────────────────╮                         │
│ │        debug = None                                                  │                         │
│ │ loop_factory = None                                                  │                         │
│ │         main = <coroutine object url at 0x000001C3D0B60940>          │                         │
│ │       runner = <asyncio.runners.Runner object at 0x000001C3D0B392B0> │                         │
│ ╰──────────────────────────────────────────────────────────────────────╯                         │
│                                                                                                  │
│ C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py:118 in run         │
│                                                                                                  │
│   115 │   │                                                                                      │
│   116 │   │   self._interrupt_count = 0                                                          │
│   117 │   │   try:                                                                               │
│ ❱ 118 │   │   │   return self._loop.run_until_complete(task)                                     │
│   119 │   │   except exceptions.CancelledError:                                                  │
│   120 │   │   │   if self._interrupt_count > 0:                                                  │
│   121 │   │   │   │   uncancel = getattr(task, "uncancel", None)                                 │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │        context = <_contextvars.Context object at 0x000001C3D0BA7E80>                         │ │
│ │           coro = <coroutine object url at 0x000001C3D0B60940>                                │ │
│ │           self = <asyncio.runners.Runner object at 0x000001C3D0B392B0>                       │ │
│ │ sigint_handler = functools.partial(<bound method Runner._on_sigint of                        │ │
│ │                  <asyncio.runners.Runner object at 0x000001C3D0B392B0>>, main_task=<Task     │ │
│ │                  finished name='Task-1' coro=<url() done, defined at                         │ │
│ │                  C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\s… │ │
│ │                  exception=ValueError('list.remove(x): x not in list')>)                     │ │
│ │           task = <Task finished name='Task-1' coro=<url() done, defined at                   │ │
│ │                  C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\s… │ │
│ │                  exception=ValueError('list.remove(x): x not in list')>                      │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:685 in         │
│ run_until_complete                                                                               │
│                                                                                                  │
│    682 │   │   if not future.done():                                                             │
│    683 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')             │
│    684 │   │                                                                                     │
│ ❱  685 │   │   return future.result()                                                            │
│    686 │                                                                                         │
│    687 │   def stop(self):                                                                       │
│    688 │   │   """Stop running the event loop.                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   future = <Task finished name='Task-1' coro=<url() done, defined at                         │ │
│ │            C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamr… │ │
│ │            exception=ValueError('list.remove(x): x not in list')>                            │ │
│ │ new_task = False                                                                             │ │
│ │     self = <ProactorEventLoop running=False closed=True debug=False>                         │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\rip\cli.py:16 │
│ 6 in url                                                                                         │
│                                                                                                  │
│   163 │   │   │   version_coro = None                                                            │
│   164 │   │                                                                                      │
│   165 │   │   async with Main(cfg) as main:                                                      │
│ ❱ 166 │   │   │   await main.add_all(urls)                                                       │
│   167 │   │   │   await main.resolve()                                                           │
│   168 │   │   │   await main.rip()                                                               │
│   169                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │          cfg = <streamrip.config.Config object at 0x000001C3D0B66FC0>                        │ │
│ │          ctx = <click.core.Context object at 0x000001C3D06684A0>                             │ │
│ │         main = <streamrip.rip.main.Main object at 0x000001C3D0A53CB0>                        │ │
│ │      updates = True                                                                          │ │
│ │         urls = (                                                                             │ │
│ │                │                                                                             │ │
│ │                'https://www.qobuz.com/us-en/album/brat-and-its-completely-different-but-als… │ │
│ │                )                                                                             │ │
│ │ version_coro = <Task finished name='Task-2' coro=<latest_streamrip_version() done, defined   │ │
│ │                at                                                                            │ │
│ │                C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\str… │ │
│ │                result=('2.0.5', None)>                                                       │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\rip\main.py:1 │
│ 21 in add_all                                                                                    │
│                                                                                                  │
│   118 │   │   │   │   │   f"[red]Found invalid url [cyan]{urls[i]}[/cyan], skipping.",           │
│   119 │   │   │   │   )                                                                          │
│   120 │   │   │   │   continue                                                                   │
│ ❱ 121 │   │   │   url_client_pairs.append((p, await self.get_logged_in_client(p.source)))        │
│   122 │   │                                                                                      │
│   123 │   │   pendings = await asyncio.gather(                                                   │
│   124 │   │   │   *[                                                                             │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                i = 0                                                                         │ │
│ │                p = <streamrip.rip.parse_url.GenericURL object at 0x000001C3D0C0CC80>         │ │
│ │           parsed = [<streamrip.rip.parse_url.GenericURL object at 0x000001C3D0C0CC80>]       │ │
│ │             self = <streamrip.rip.main.Main object at 0x000001C3D0A53CB0>                    │ │
│ │ url_client_pairs = []                                                                        │ │
│ │             urls = (                                                                         │ │
│ │                    │                                                                         │ │
│ │                    'https://www.qobuz.com/us-en/album/brat-and-its-completely-different-but… │ │
│ │                    )                                                                         │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\rip\main.py:1 │
│ 47 in get_logged_in_client                                                                       │
│                                                                                                  │
│   144 │   │   │   else:                                                                          │
│   145 │   │   │   │   with console.status(f"[cyan]Logging into {source}", spinner="dots"):       │
│   146 │   │   │   │   │   # Log into client using credentials from config                        │
│ ❱ 147 │   │   │   │   │   await client.login()                                                   │
│   148 │   │                                                                                      │
│   149 │   │   assert client.logged_in                                                            │
│   150 │   │   return client                                                                      │
│                                                                                                  │
│ ╭──────────────────────────────────── locals ────────────────────────────────────╮               │
│ │   client = <streamrip.client.qobuz.QobuzClient object at 0x000001C3D0B0F320>   │               │
│ │ prompter = <streamrip.rip.prompter.QobuzPrompter object at 0x000001C3D0C0CBF0> │               │
│ │     self = <streamrip.rip.main.Main object at 0x000001C3D0A53CB0>              │               │
│ │   source = 'qobuz'                                                             │               │
│ ╰────────────────────────────────────────────────────────────────────────────────╯               │
│                                                                                                  │
│ C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\client\qobuz. │
│ py:158 in login                                                                                  │
│                                                                                                  │
│   155 │   │                                                                                      │
│   156 │   │   if not c.app_id or not c.secrets:                                                  │
│   157 │   │   │   logger.info("App id/secrets not found, fetching")                              │
│ ❱ 158 │   │   │   c.app_id, c.secrets = await self._get_app_id_and_secrets()                     │
│   159 │   │   │   # write to file                                                                │
│   160 │   │   │   f = self.config.file                                                           │
│   161 │   │   │   f.qobuz.app_id = c.app_id                                                      │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │    c = QobuzConfig(                                                                          │ │
│ │        │   use_auth_token=True,                                                              │ │
│ │        │   email_or_userid='992824',                                                         │ │
│ │        │                                                                                     │ │
│ │        password_or_token='u6lHtzb1Vv_TbNYYL_PrIzVZfkMpxUJ4Y4AkpdrfFRaj5o1sbLP7ENCKVD-wQEmkM… │ │
│ │        │   app_id='',                                                                        │ │
│ │        │   quality=2,                                                                        │ │
│ │        │   download_booklets=True,                                                           │ │
│ │        │   secrets=[]                                                                        │ │
│ │        )                                                                                     │ │
│ │ self = <streamrip.client.qobuz.QobuzClient object at 0x000001C3D0B0F320>                     │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\client\qobuz. │
│ py:383 in _get_app_id_and_secrets                                                                │
│                                                                                                  │
│   380 │                                                                                          │
│   381 │   async def _get_app_id_and_secrets(self) -> tuple[str, list[str]]:                      │
│   382 │   │   async with QobuzSpoofer() as spoofer:                                              │
│ ❱ 383 │   │   │   return await spoofer.get_app_id_and_secrets()                                  │
│   384 │                                                                                          │
│   385 │   async def _get_valid_secret(self, secrets: list[str]) -> str:                          │
│   386 │   │   results = await asyncio.gather(                                                    │
│                                                                                                  │
│ ╭─────────────────────────────────── locals ───────────────────────────────────╮                 │
│ │    self = <streamrip.client.qobuz.QobuzClient object at 0x000001C3D0B0F320>  │                 │
│ │ spoofer = <streamrip.client.qobuz.QobuzSpoofer object at 0x000001C3D0C0D4C0> │                 │
│ ╰──────────────────────────────────────────────────────────────────────────────╯                 │
│                                                                                                  │
│ C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\client\qobuz. │
│ py:120 in get_app_id_and_secrets                                                                 │
│                                                                                                  │
│   117 │   │   │   ).decode("utf-8")                                                              │
│   118 │   │                                                                                      │
│   119 │   │   vals: List[str] = list(secrets.values())                                           │
│ ❱ 120 │   │   vals.remove("")                                                                    │
│   121 │   │                                                                                      │
│   122 │   │   secrets_list = vals                                                                │
│   123                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │              app_id = '579939560'                                                            │ │
│ │          bundle_url = '/resources/7.2.0-b083/bundle.js'                                      │ │
│ │    bundle_url_match = <re.Match object; span=(3441, 3496), match='<script                    │ │
│ │                       src="/resources/7.2.0-b083/bundle.js"></s>                             │ │
│ │              extras = 'Q0NGFhMDkzYjk2MWMxZTcwZmYyNWE='                                       │ │
│ │                info = 'U5MWFhOWUxNzg=ZDRkMGNhZjVjNT'                                         │ │
│ │ info_extras_matches = <callable_iterator object at 0x000001C3D0C0ED70>                       │ │
│ │   info_extras_regex = 'name:"\\w+/(?P<timezone>Abidjan|London|Berlin)",info:"(?P<info>[\\w=… │ │
│ │            keypairs = [                                                                      │ │
│ │                       │   (                                                                  │ │
│ │                       │   │   'london',                                                      │ │
│ │                       │   │   [                                                              │ │
│ │                       │   │   │   'YjM0ZmM4Y2M5MzBhNzljMzg3NzgyNj',                          │ │
│ │                       │   │   │   'c5Yzk2MTI3M2Y=MWUxYTI5MGEzN2',                            │ │
│ │                       │   │   │   'IzNDkwODlmZWViOTA5YzU3NTQ0NDA='                           │ │
│ │                       │   │   ]                                                              │ │
│ │                       │   ),                                                                 │ │
│ │                       │   (                                                                  │ │
│ │                       │   │   'abidjan',                                                     │ │
│ │                       │   │   [                                                              │ │
│ │                       │   │   │   'ZTFlZTllNmEwYWYxZTllNjM0M2M3MT',                          │ │
│ │                       │   │   │   'U1ODc3MTBjYzI=Y2JjMjdhOGY0NG',                            │ │
│ │                       │   │   │   'Q0NGU3OWJjNTNkYWQ5MzBhMzA5OWE='                           │ │
│ │                       │   │   ]                                                              │ │
│ │                       │   ),                                                                 │ │
│ │                       │   (                                                                  │ │
│ │                       │   │   'berlin',                                                      │ │
│ │                       │   │   [                                                              │ │
│ │                       │   │   │   'ZmEzMWZjMTNlN2EyOGU3ZDcwYmI2MW',                          │ │
│ │                       │   │   │   'U5MWFhOWUxNzg=ZDRkMGNhZjVjNT',                            │ │
│ │                       │   │   │   'Q0NGFhMDkzYjk2MWMxZTcwZmYyNWE='                           │ │
│ │                       │   │   ]                                                              │ │
│ │                       │   )                                                                  │ │
│ │                       ]                                                                      │ │
│ │          login_page = '<!DOCTYPE html>\n<html>\n<head>\n  <meta charset="utf-8">\n  <meta    │ │
│ │                       http-equiv="X-UA-'+3433                                                │ │
│ │               match = <re.Match object; span=(2522417, 2522513),                             │ │
│ │                       match='name:"Europe/Berlin",info:"U5MWFhOWUxNzg=ZDRkMGNh>              │ │
│ │                 req = <ClientResponse(https://play.qobuz.com/resources/7.2.0-b083/bundle.js) │ │
│ │                       [200 OK]>                                                              │ │
│ │                       <CIMultiDictProxy('Accept-Ranges': 'bytes', 'Cache-Control':           │ │
│ │                       'max-age=300', 'Content-Type': 'text/javascript', 'Date': 'Sun, 13 Oct │ │
│ │                       2024 01:38:48 GMT', 'Etag': '"4e4b9b6717d77ab2324b98638cfc4a75"',      │ │
│ │                       'Expires': 'Sun, 13 Oct 2024 01:43:48 GMT', 'Last-Modified': 'Fri, 11  │ │
│ │                       Oct 2024 10:18:01 GMT', 'Server': 'nginx', 'x-amz-meta-s3cmd-attrs':   │ │
│ │                       'md5:4e4b9b6717d77ab2324b98638cfc4a75',                                │ │
│ │                       'x-amz-server-side-encryption': 'AES256', 'Content-Length': '8362962', │ │
│ │                       'Connection': 'keep-alive')>                                           │ │
│ │         secret_pair = 'berlin'                                                               │ │
│ │             secrets = OrderedDict({'abidjan': 'e1ee9e6a0af1e9e6343c715587710cc2', 'london':  │ │
│ │                       'b34fc8cc930a79c387782679c961273f', 'berlin':                          │ │
│ │                       'fa31fc13e7a28e7d70bb61e91aa9e178'})                                   │ │
│ │                seed = 'ZmEzMWZjMTNlN2EyOGU3ZDcwYmI2MW'                                       │ │
│ │        seed_matches = <callable_iterator object at 0x000001C3D0A75B70>                       │ │
│ │                self = <streamrip.client.qobuz.QobuzSpoofer object at 0x000001C3D0C0D4C0>     │ │
│ │            timezone = 'Berlin'                                                               │ │
│ │                vals = [                                                                      │ │
│ │                       │   'e1ee9e6a0af1e9e6343c715587710cc2',                                │ │
│ │                       │   'b34fc8cc930a79c387782679c961273f',                                │ │
│ │                       │   'fa31fc13e7a28e7d70bb61e91aa9e178'                                 │ │
│ │                       ]                                                                      │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: list.remove(x): x not in list
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "D:\\<user>\\streamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 2
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = true
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = "<id>"
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = "<token>"
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 2
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = "<arl>"
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = false
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "D:\\<user>\\streamripDownloads\\YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "C:\\Users\\<user>\\AppData\\Roaming\\streamrip\\downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "C:\\Users\\<user>\\AppData\\Roaming\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = true 
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title}"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02} {title}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Windows 11

### streamrip version

2.0.5

### Additional context

i replaced my user everywhere with <user> and all the personal info with <> in some way
