### ISSUE TITLE
[BUG] Qobuz: Bails out if cover does not exist

### ISSUE THREAD

**Issue by AllKind** [nathom/streamrip#757]
### Describe the bug

This may be a rare occasion, but I think it's a case that could easily handled.
If the cover art does not exist (broken link on qobuz side), streamrip bails out, though streamrip could easily move forward without the cover.

### Command Used

```bash
rip url https://play.qobuz.com/album/n2id7srti0wjc
```

### Debug Traceback

```text
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ellen/.local/bin/rip:8 in <module>                                                         │
│                                                                                                  │
│   5 from streamrip.rip import rip                                                                │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(rip())                                                                          │
│   9                                                                                              │
│                                                                                                  │
│ /home/ellen/.local/share/pipx/venvs/streamrip/lib/python3.12/site-packages/click/core.py:1157 in │
│ __call__                                                                                         │
│                                                                                                  │
│                                     ... 14 frames hidden ...                                     │
│                                                                                                  │
│ /home/ellen/.local/share/pipx/venvs/streamrip/lib/python3.12/site-packages/streamrip/client/down │
│ loadable.py:76 in _download                                                                      │
│                                                                                                  │
│    73 │                                                                                          │
│    74 │   async def _download(self, path: str, callback: Callable[[int], None]):                 │
│    75 │   │   async with self.session.get(self.url, allow_redirects=True) as response:           │
│ ❱  76 │   │   │   response.raise_for_status()                                                    │
│    77 │   │   │   async with aiofiles.open(path, "wb") as file:                                  │
│    78 │   │   │   │   async for chunk in response.content.iter_chunked(self.chunk_size):         │
│    79 │   │   │   │   │   await file.write(chunk)                                                │
│                                                                                                  │
│ /home/ellen/.local/share/pipx/venvs/streamrip/lib/python3.12/site-packages/aiohttp/client_reqrep │
│ .py:1093 in raise_for_status                                                                     │
│                                                                                                  │
│   1090 │   │   │   # reason should always be not None for a started response                     │
│   1091 │   │   │   assert self.reason is not None                                                │
│   1092 │   │   │   self.release()                                                                │
│ ❱ 1093 │   │   │   raise ClientResponseError(                                                    │
│   1094 │   │   │   │   self.request_info,                                                        │
│   1095 │   │   │   │   self.history,                                                             │
│   1096 │   │   │   │   status=self.status,                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ClientResponseError: 404, message='Not Found', url='https://static.qobuz.com/images/covers/jc/0w/n2id7srti0wjc_org.jpg'
```

### Config File

```toml
[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1
```

### Operating System

Linux Mint 22

### streamrip version

2.0.5

### Additional context

.
