### ISSUE TITLE
[BUG] Streamrip saves corrupted coverimages on some Albums

### ISSUE THREAD

**Issue by TheParaTiger** [nathom/streamrip#762]
### Describe the bug

While downloading an Album from Qobuz, Streamrip tends to create a corrupted cover.jpg within the Albums folder. The cover which gets embedded into the FLAC however is usually completely fine. In order to fix this, you'll have to redownload the Album. It's also random where this occours. Most Albums will have completely fine cover.jpg files while some Albums end up getting corrupted ones. This is just an example below and doesn't happen just to this one Album.

### Command Used

```bash
rip url https://www.qobuz.com/de-de/album/llama-in-my-living-room-aronchupa/0886446519456
```

### Debug Traceback

```text
PS C:\Users\elias> rip -ndb -vvv url https://www.qobuz.com/de-de/album/llama-in-my-living-room-aronchupa/0886446519456
[21:46:14] DEBUG    Showing all debug logs                                                                    cli.py:102
           DEBUG    Request params {'user_id': 'REDACTED', 'user_auth_token':                                qobuz.py:180
                    'REDACTED
                    ', 'app_id': '950096963'}
           DEBUG    api_request: endpoint=user/login, params={'user_id': 'REDACTED', 'user_auth_token':      qobuz.py:432
                    'REDACTED
                    ', 'app_id': '950096963'}
⠙ Logging into qobuz           DEBUG    Login resp: {'user': {'id': REDACTED, 'publicId': 'qobuz:user:B5qVYml6j50ci', 'email':   qobuz.py:182
                    '', 'login': '', 'firstname': '',
                    'lastname': '', 'display_name': 'wzkd59aip4', 'country_code': 'DE', 'language_code':
                    'de', 'zone': 'DE', 'store': 'DE-de', 'country': 'DE', 'avatar':
                    'https://www.gravatar.com/avatar/7a19fc0f0990e3e7237e877ab2097e96?s=50&d=mm', 'genre':
                    'male', 'age': 30, 'creation_date': '2024-10-01', 'subscription': {'offer': 'studio',
                    'periodicity': 'annual', 'start_date': '2024-10-01', 'end_date': '2024-10-31',
                    'is_canceled': False, 'household_size_max': 6}, 'credential': {'id': 2350116, 'label':
                    'streaming-studio', 'description': 'Abonnent Qobuz Studio', 'parameters':
                    {'lossy_streaming': True, 'lossless_streaming': True, 'hires_streaming': True,
                    'hires_purchases_streaming': True, 'mobile_streaming': True, 'offline_streaming': True,
                    'hfp_purchase': False, 'included_format_group_ids': [1, 2, 3, 4], 'color_scheme':
                    {'logo': '#B8D729'}, 'label': 'Qobuz Studio', 'short_label': 'Studio', 'source':
                    'subscription'}}, 'last_update': {'favorite': 1727786064, 'favorite_album': 1727786064,
                    'favorite_artist': 1727786064, 'favorite_track': 1727786064, 'playlist': 1727786064,
                    'purchase': 1727786544}, 'store_features': {'download': True, 'streaming': True,
                    'editorial': True, 'club': True, 'wallet': True, 'weeklyq': True, 'autoplay': True,
                    'inapp_purchase_subscripton': True, 'opt_in': True, 'pre_register_opt_in': True,
                    'pre_register_zipcode': False, 'music_import': True, 'radio': True, 'stream_purchase':
                    True}, 'player_settings': [], 'externals': {}}, 'user_auth_token':
                    'REDACTED
                    '}
           DEBUG    Logged in to Qobuz                                                                      qobuz.py:189
           DEBUG    Raw request signature:                                                                  qobuz.py:415
                    trackgetFileUrlformat_id27intentstreamtrack_id195125741729971974.597281979549437fcc4a3f
                    aad4867b5cd25dcb
           DEBUG    Hashed request signature: 68e12bfa1d04369cffd4dfecd8e47675                              qobuz.py:417
           DEBUG    api_request: endpoint=track/getFileUrl, params={'request_ts': 1729971974.597281,        qobuz.py:432
                    'request_sig': '68e12bfa1d04369cffd4dfecd8e47675', 'track_id': '19512574', 'format_id':
                    27, 'intent': 'stream'}
           DEBUG    request params: {'app_id': '950096963', 'album_id': '0886446519456', 'limit': 500,      qobuz.py:223
                    'offset': 0}
           DEBUG    api_request: endpoint=album/get, params={'app_id': '950096963', 'album_id':             qobuz.py:432
                    '0886446519456', 'limit': 500, 'offset': 0}
⠴ Resolving URLs...[21:46:15] DEBUG    Pending tracks: [PendingTrack(id=40758516,
        album.py:92
                    album=AlbumMetadata(info=AlbumInfo(id='40758515', quality=2, container='FLAC',
                    label='Aron Ekberg', explicit=False, sampling_rate=44.1, bit_depth=16, booklets=None),
                    album='Llama In My Living Room', albumartist='AronChupa, Little Sis Nora', year='2017',
                    genre=['Électronique', 'Techno'], covers=Covers(('original',
                    'https://static.qobuz.com/images/covers/56/94/0886446519456_org.jpg',
                    'L:\\Streamrip\\AronChupa, Little Sis Nora/AronChupa, Little Sis Nora - Llama In My
                    Living Room (2017)\\cover.jpg')
                    ('large', 'https://static.qobuz.com/images/covers/56/94/0886446519456_600.jpg',
                    'L:\\Streamrip\\AronChupa, Little Sis Nora/AronChupa, Little Sis Nora - Llama In My
                    Living Room (2017)\\__artwork\\cover-8856339124838785752.jpg')
                    ('small', 'https://static.qobuz.com/images/covers/56/94/0886446519456_230.jpg', None)
                    ('thumbnail', 'https://static.qobuz.com/images/covers/56/94/0886446519456_50.jpg',
                    None)), tracktotal=1, disctotal=1, albumcomposer='Aron Ekberg', comment=None,
                    compilation=None, copyright='(P) 2017 Aron Ekberg under exclusive license to Sony Music
                    Entertainment Sweden AB', date='2017-06-02', description=None, encoder=None,
                    grouping=None, lyrics=None, purchase_date=None),
                    client=<streamrip.client.qobuz.QobuzClient object at 0x00000251596593D0>,
                    config=<streamrip.config.Config object at 0x00000251582773D0>,
                    folder='L:\\Streamrip\\AronChupa, Little Sis Nora/AronChupa, Little Sis Nora - Llama In
                    My Living Room (2017)', db=Database(downloads=<streamrip.db.Dummy object at
                    0x000002515A7DEC90>, failed=<streamrip.db.Failed object at 0x000002515A7DD610>),
                    cover_path='L:\\Streamrip\\AronChupa, Little Sis Nora/AronChupa, Little Sis Nora - Llama
                    In My Living Room (2017)\\__artwork\\cover-8856339124838785752.jpg')]
           DEBUG    request params: {'app_id': '950096963', 'track_id': 40758516, 'limit': 500, 'offset':   qobuz.py:223
                    0}
           DEBUG    api_request: endpoint=track/get, params={'app_id': '950096963', 'track_id': 40758516,   qobuz.py:432
                    'limit': 500, 'offset': 0}
           DEBUG    Raw request signature:                                                                  qobuz.py:415
                    trackgetFileUrlformat_id27intentstreamtrack_id407585161729971975.4386866979549437fcc4a3
                    faad4867b5cd25dcb
           DEBUG    Hashed request signature: 6ec13a58ae54b28e88a8abdc6e89fe81                              qobuz.py:417
           DEBUG    api_request: endpoint=track/getFileUrl, params={'request_ts': 1729971975.4386866,       qobuz.py:432
                    'request_sig': '6ec13a58ae54b28e88a8abdc6e89fe81', 'track_id': 40758516, 'format_id':
                    27, 'intent': 'stream'}
[21:46:19] DEBUG    Tagging with [('TITLE', 'Llama In My Living Room'), ('ARTIST', 'AronChupa'), ('ALBUM', tagger.py:253
                    'Llama In My Living Room'), ('ALBUMARTIST', 'AronChupa, Little Sis Nora'),
                    ('COMPOSER', 'Aron Ekberg'), ('YEAR', '2017'), ('GENRE', 'Électronique, Techno'),
                    ('COPYRIGHT', '℗ 2017 Aron Ekberg under exclusive license to Sony Music Entertainment
                    Sweden AB'), ('TRACKNUMBER', '01'), ('DISCNUMBER', '01'), ('TRACKTOTAL', '01'),
                    ('DISCTOTAL', '01'), ('DATE', '2017-06-02'), ('ISRC', 'SEYOK1600109')]
───────────────────────────────────────── Downloading Llama In My Living Room ──────────────────────────────────────────
           DEBUG    Removing dirs {'L:\\Streamrip\\AronChupa, Little Sis Nora/AronChupa, Little Sis Nora - artwork.py:19
                    Llama In My Living Room (2017)\\__artwork'}
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "L:\\Streamrip"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 4
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = true
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = "REDACTED"
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = "REDACTED"
# Do not change
app_id = "950096963"
# Do not change
secrets = ["979549437fcc4a3faad4867b5cd25dcb"]

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "C:\\Users\\elias\\StreamripDownloads\\YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "C:\\Users\\elias\\AppData\\Roaming\\streamrip\\downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "C:\\Users\\elias\\AppData\\Roaming\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist}/{albumartist} - {title} ({year})"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Windows 11

### streamrip version

2.0.5

### Screenshots and recordings

![cover](https://github.com/user-attachments/assets/d24785e3-5f22-4731-bb2f-ad0991b5574c)
