### ISSUE TITLE
[BUG] "X not in list" 

### ISSUE THREAD

**Issue by zarrar-html** [nathom/streamrip#767]
### Describe the bug

upon trying to run a command to pull an albums songs, i get an error stating "x not in list"

### Command Used

```bash
rip search qobuz album "Music of the Spheres"
```

### Debug Traceback

```text
[00:18:02] DEBUG    Showing all debug logs                                                                                                cli.py:102
           INFO     App id/secrets not found, fetching                                                                                  qobuz.py:157
[00:18:16] DEBUG    Removing dirs set()                                                                                                artwork.py:19
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/zarra/.local/bin/rip:8 in <module>                                                        │
│                                                                                                  │
│   5 from streamrip.rip import rip                                                                │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(rip())                                                                          │
│   9                                                                                              │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │  re = <module 're' from                                                                      │ │
│ │       '/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/li… │ │
│ │ rip = <HelpColorsGroup rip>                                                                  │ │
│ │ sys = <module 'sys' (built-in)>                                                              │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /Users/zarra/.local/pipx/venvs/streamrip/lib/python3.12/site-packages/click/core.py:1157 in      │
│ __call__                                                                                         │
│                                                                                                  │
│ /Users/zarra/.local/pipx/venvs/streamrip/lib/python3.12/site-packages/click/core.py:1078 in main │
│                                                                                                  │
│ /Users/zarra/.local/pipx/venvs/streamrip/lib/python3.12/site-packages/click/core.py:1688 in      │
│ invoke                                                                                           │
│                                                                                                  │
│ /Users/zarra/.local/pipx/venvs/streamrip/lib/python3.12/site-packages/click/core.py:1434 in      │
│ invoke                                                                                           │
│                                                                                                  │
│ /Users/zarra/.local/pipx/venvs/streamrip/lib/python3.12/site-packages/click/core.py:783 in       │
│ invoke                                                                                           │
│                                                                                                  │
│ /Users/zarra/.local/pipx/venvs/streamrip/lib/python3.12/site-packages/click/decorators.py:33 in  │
│ new_func                                                                                         │
│                                                                                                  │
│ /Users/zarra/.local/pipx/venvs/streamrip/lib/python3.12/site-packages/streamrip/rip/cli.py:28 in │
│ wrapper                                                                                          │
│                                                                                                  │
│    25 def coro(f):                                                                               │
│    26 │   @wraps(f)                                                                              │
│    27 │   def wrapper(*args, **kwargs):                                                          │
│ ❱  28 │   │   return asyncio.run(f(*args, **kwargs))                                             │
│    29 │                                                                                          │
│    30 │   return wrapper                                                                         │
│    31                                                                                            │
│                                                                                                  │
│ ╭──────────────────────── locals ────────────────────────╮                                       │
│ │   args = (<click.core.Context object at 0x10690c230>,) │                                       │
│ │ kwargs = {                                             │                                       │
│ │          │   'source': 'qobuz',                        │                                       │
│ │          │   'media_type': 'album',                    │                                       │
│ │          │   'query': 'I am sasha fierce',             │                                       │
│ │          │   'first': False,                           │                                       │
│ │          │   'output_file': None,                      │                                       │
│ │          │   'num_results': 100                        │                                       │
│ │          }                                             │                                       │
│ ╰────────────────────────────────────────────────────────╯                                       │
│                                                                                                  │
│ /opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12 │
│ /asyncio/runners.py:194 in run                                                                   │
│                                                                                                  │
│   191 │   │   │   "asyncio.run() cannot be called from a running event loop")                    │
│   192 │                                                                                          │
│   193 │   with Runner(debug=debug, loop_factory=loop_factory) as runner:                         │
│ ❱ 194 │   │   return runner.run(main)                                                            │
│   195                                                                                            │
│   196                                                                                            │
│   197 def _cancel_all_tasks(loop):                                                               │
│                                                                                                  │
│ ╭─────────────────────────── locals ────────────────────────────╮                                │
│ │        debug = None                                           │                                │
│ │ loop_factory = None                                           │                                │
│ │         main = <coroutine object search at 0x107a74d50>       │                                │
│ │       runner = <asyncio.runners.Runner object at 0x1074a4710> │                                │
│ ╰───────────────────────────────────────────────────────────────╯                                │
│                                                                                                  │
│ /opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12 │
│ /asyncio/runners.py:118 in run                                                                   │
│                                                                                                  │
│   115 │   │                                                                                      │
│   116 │   │   self._interrupt_count = 0                                                          │
│   117 │   │   try:                                                                               │
│ ❱ 118 │   │   │   return self._loop.run_until_complete(task)                                     │
│   119 │   │   except exceptions.CancelledError:                                                  │
│   120 │   │   │   if self._interrupt_count > 0:                                                  │
│   121 │   │   │   │   uncancel = getattr(task, "uncancel", None)                                 │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │        context = <_contextvars.Context object at 0x107aa29c0>                                │ │
│ │           coro = <coroutine object search at 0x107a74d50>                                    │ │
│ │           self = <asyncio.runners.Runner object at 0x1074a4710>                              │ │
│ │ sigint_handler = functools.partial(<bound method Runner._on_sigint of                        │ │
│ │                  <asyncio.runners.Runner object at 0x1074a4710>>, main_task=<Task finished   │ │
│ │                  name='Task-1' coro=<search() done, defined at                               │ │
│ │                  /Users/zarra/.local/pipx/venvs/streamrip/lib/python3.12/site-packages/stre… │ │
│ │                  exception=ValueError('list.remove(x): x not in list')>)                     │ │
│ │           task = <Task finished name='Task-1' coro=<search() done, defined at                │ │
│ │                  /Users/zarra/.local/pipx/venvs/streamrip/lib/python3.12/site-packages/stre… │ │
│ │                  exception=ValueError('list.remove(x): x not in list')>                      │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12 │
│ /asyncio/base_events.py:687 in run_until_complete                                                │
│                                                                                                  │
│    684 │   │   if not future.done():                                                             │
│    685 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')             │
│    686 │   │                                                                                     │
│ ❱  687 │   │   return future.result()                                                            │
│    688 │                                                                                         │
│    689 │   def stop(self):                                                                       │
│    690 │   │   """Stop running the event loop.                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   future = <Task finished name='Task-1' coro=<search() done, defined at                      │ │
│ │            /Users/zarra/.local/pipx/venvs/streamrip/lib/python3.12/site-packages/streamrip/… │ │
│ │            exception=ValueError('list.remove(x): x not in list')>                            │ │
│ │ new_task = False                                                                             │ │
│ │     self = <_UnixSelectorEventLoop running=False closed=True debug=False>                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /Users/zarra/.local/pipx/venvs/streamrip/lib/python3.12/site-packages/streamrip/rip/cli.py:371   │
│ in search                                                                                        │
│                                                                                                  │
│   368 │   │   │   │   │   source, media_type, query, output_file, num_results                    │
│   369 │   │   │   │   )                                                                          │
│   370 │   │   │   else:                                                                          │
│ ❱ 371 │   │   │   │   await main.search_interactive(source, media_type, query)                   │
│   372 │   │   │   await main.resolve()                                                           │
│   373 │   │   │   await main.rip()                                                               │
│   374                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────── locals ────────────────────────────╮                                │
│ │         cfg = <streamrip.config.Config object at 0x107992cf0> │                                │
│ │         ctx = <click.core.Context object at 0x10690c230>      │                                │
│ │       first = False                                           │                                │
│ │        main = <streamrip.rip.main.Main object at 0x107a53380> │                                │
│ │  media_type = 'album'                                         │                                │
│ │ num_results = 100                                             │                                │
│ │ output_file = None                                            │                                │
│ │       query = 'I am sasha fierce'                             │                                │
│ │      source = 'qobuz'                                         │                                │
│ ╰───────────────────────────────────────────────────────────────╯                                │
│                                                                                                  │
│ /Users/zarra/.local/pipx/venvs/streamrip/lib/python3.12/site-packages/streamrip/rip/main.py:168  │
│ in search_interactive                                                                            │
│                                                                                                  │
│   165 │   │   await asyncio.gather(*[item.rip() for item in self.media])                         │
│   166 │                                                                                          │
│   167 │   async def search_interactive(self, source: str, media_type: str, query: str):          │
│ ❱ 168 │   │   client = await self.get_logged_in_client(source)                                   │
│   169 │   │                                                                                      │
│   170 │   │   with console.status(f"[bold]Searching {source}", spinner="dots"):                  │
│   171 │   │   │   pages = await client.search(media_type, query, limit=100)                      │
│                                                                                                  │
│ ╭─────────────────────────── locals ───────────────────────────╮                                 │
│ │ media_type = 'album'                                         │                                 │
│ │      query = 'I am sasha fierce'                             │                                 │
│ │       self = <streamrip.rip.main.Main object at 0x107a53380> │                                 │
│ │     source = 'qobuz'                                         │                                 │
│ ╰──────────────────────────────────────────────────────────────╯                                 │
│                                                                                                  │
│ /Users/zarra/.local/pipx/venvs/streamrip/lib/python3.12/site-packages/streamrip/rip/main.py:147  │
│ in get_logged_in_client                                                                          │
│                                                                                                  │
│   144 │   │   │   else:                                                                          │
│   145 │   │   │   │   with console.status(f"[cyan]Logging into {source}", spinner="dots"):       │
│   146 │   │   │   │   │   # Log into client using credentials from config                        │
│ ❱ 147 │   │   │   │   │   await client.login()                                                   │
│   148 │   │                                                                                      │
│   149 │   │   assert client.logged_in                                                            │
│   150 │   │   return client                                                                      │
│                                                                                                  │
│ ╭──────────────────────────────── locals ─────────────────────────────────╮                      │
│ │   client = <streamrip.client.qobuz.QobuzClient object at 0x107a51c10>   │                      │
│ │ prompter = <streamrip.rip.prompter.QobuzPrompter object at 0x107b32fc0> │                      │
│ │     self = <streamrip.rip.main.Main object at 0x107a53380>              │                      │
│ │   source = 'qobuz'                                                      │                      │
│ ╰─────────────────────────────────────────────────────────────────────────╯                      │
│                                                                                                  │
│ /Users/zarra/.local/pipx/venvs/streamrip/lib/python3.12/site-packages/streamrip/client/qobuz.py: │
│ 158 in login                                                                                     │
│                                                                                                  │
│   155 │   │                                                                                      │
│   156 │   │   if not c.app_id or not c.secrets:                                                  │
│   157 │   │   │   logger.info("App id/secrets not found, fetching")                              │
│ ❱ 158 │   │   │   c.app_id, c.secrets = await self._get_app_id_and_secrets()                     │
│   159 │   │   │   # write to file                                                                │
│   160 │   │   │   f = self.config.file                                                           │
│   161 │   │   │   f.qobuz.app_id = c.app_id                                                      │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │    c = QobuzConfig(                                                                          │ │
│ │        │   use_auth_token=True,                                                              │ │
│ │        │   email_or_userid='2738067',                                                        │ │
│ │        │                                                                                     │ │
│ │        password_or_token='LnW5pfpKbK5DwHwDXRUav36sd2warFexZ4BcIttG7H_QTiNmAUwglbyKm9irZv579… │ │
│ │        │   app_id='',                                                                        │ │
│ │        │   quality=3,                                                                        │ │
│ │        │   download_booklets=True,                                                           │ │
│ │        │   secrets=[]                                                                        │ │
│ │        )                                                                                     │ │
│ │ self = <streamrip.client.qobuz.QobuzClient object at 0x107a51c10>                            │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /Users/zarra/.local/pipx/venvs/streamrip/lib/python3.12/site-packages/streamrip/client/qobuz.py: │
│ 383 in _get_app_id_and_secrets                                                                   │
│                                                                                                  │
│   380 │                                                                                          │
│   381 │   async def _get_app_id_and_secrets(self) -> tuple[str, list[str]]:                      │
│   382 │   │   async with QobuzSpoofer() as spoofer:                                              │
│ ❱ 383 │   │   │   return await spoofer.get_app_id_and_secrets()                                  │
│   384 │                                                                                          │
│   385 │   async def _get_valid_secret(self, secrets: list[str]) -> str:                          │
│   386 │   │   results = await asyncio.gather(                                                    │
│                                                                                                  │
│ ╭─────────────────────────────── locals ────────────────────────────────╮                        │
│ │    self = <streamrip.client.qobuz.QobuzClient object at 0x107a51c10>  │                        │
│ │ spoofer = <streamrip.client.qobuz.QobuzSpoofer object at 0x1074214f0> │                        │
│ ╰───────────────────────────────────────────────────────────────────────╯                        │
│                                                                                                  │
│ /Users/zarra/.local/pipx/venvs/streamrip/lib/python3.12/site-packages/streamrip/client/qobuz.py: │
│ 120 in get_app_id_and_secrets                                                                    │
│                                                                                                  │
│   117 │   │   │   ).decode("utf-8")                                                              │
│   118 │   │                                                                                      │
│   119 │   │   vals: List[str] = list(secrets.values())                                           │
│ ❱ 120 │   │   vals.remove("")                                                                    │
│   121 │   │                                                                                      │
│   122 │   │   secrets_list = vals                                                                │
│   123                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │              app_id = '579939560'                                                            │ │
│ │          bundle_url = '/resources/7.2.0-b091/bundle.js'                                      │ │
│ │    bundle_url_match = <re.Match object; span=(3441, 3496), match='<script                    │ │
│ │                       src="/resources/7.2.0-b091/bundle.js"></s>                             │ │
│ │              extras = 'Q0NGFhMDkzYjk2MWMxZTcwZmYyNWE='                                       │ │
│ │                info = 'U5MWFhOWUxNzg=ZDRkMGNhZjVjNT'                                         │ │
│ │ info_extras_matches = <callable_iterator object at 0x107b5f2e0>                              │ │
│ │   info_extras_regex = 'name:"\\w+/(?P<timezone>Abidjan|London|Berlin)",info:"(?P<info>[\\w=… │ │
│ │            keypairs = [                                                                      │ │
│ │                       │   (                                                                  │ │
│ │                       │   │   'london',                                                      │ │
│ │                       │   │   [                                                              │ │
│ │                       │   │   │   'YjM0ZmM4Y2M5MzBhNzljMzg3NzgyNj',                          │ │
│ │                       │   │   │   'c5Yzk2MTI3M2Y=MWUxYTI5MGEzN2',                            │ │
│ │                       │   │   │   'IzNDkwODlmZWViOTA5YzU3NTQ0NDA='                           │ │
│ │                       │   │   ]                                                              │ │
│ │                       │   ),                                                                 │ │
│ │                       │   (                                                                  │ │
│ │                       │   │   'abidjan',                                                     │ │
│ │                       │   │   [                                                              │ │
│ │                       │   │   │   'ZTFlZTllNmEwYWYxZTllNjM0M2M3MT',                          │ │
│ │                       │   │   │   'U1ODc3MTBjYzI=Y2JjMjdhOGY0NG',                            │ │
│ │                       │   │   │   'Q0NGU3OWJjNTNkYWQ5MzBhMzA5OWE='                           │ │
│ │                       │   │   ]                                                              │ │
│ │                       │   ),                                                                 │ │
│ │                       │   (                                                                  │ │
│ │                       │   │   'berlin',                                                      │ │
│ │                       │   │   [                                                              │ │
│ │                       │   │   │   'ZmEzMWZjMTNlN2EyOGU3ZDcwYmI2MW',                          │ │
│ │                       │   │   │   'U5MWFhOWUxNzg=ZDRkMGNhZjVjNT',                            │ │
│ │                       │   │   │   'Q0NGFhMDkzYjk2MWMxZTcwZmYyNWE='                           │ │
│ │                       │   │   ]                                                              │ │
│ │                       │   )                                                                  │ │
│ │                       ]                                                                      │ │
│ │          login_page = '<!DOCTYPE html>\n<html>\n<head>\n  <meta charset="utf-8">\n  <meta    │ │
│ │                       http-equiv="X-UA-'+3433                                                │ │
│ │               match = <re.Match object; span=(2523422, 2523518),                             │ │
│ │                       match='name:"Europe/Berlin",info:"U5MWFhOWUxNzg=ZDRkMGNh>              │ │
│ │                 req = <ClientResponse(https://play.qobuz.com/resources/7.2.0-b091/bundle.js) │ │
│ │                       [200 OK]>                                                              │ │
│ │                       <CIMultiDictProxy('Accept-Ranges': 'bytes', 'Cache-Control':           │ │
│ │                       'max-age=300', 'Content-Type': 'text/javascript', 'Date': 'Fri, 01 Nov │ │
│ │                       2024 19:18:08 GMT', 'Etag': '"6a3be4a28fc44fc72988b91cb5addad9"',      │ │
│ │                       'Expires': 'Fri, 01 Nov 2024 19:23:08 GMT', 'Last-Modified': 'Tue, 22  │ │
│ │                       Oct 2024 14:40:52 GMT', 'Server': 'nginx', 'x-amz-meta-s3cmd-attrs':   │ │
│ │                       'md5:6a3be4a28fc44fc72988b91cb5addad9',                                │ │
│ │                       'x-amz-server-side-encryption': 'AES256', 'Content-Length': '8371513', │ │
│ │                       'Connection': 'keep-alive')>                                           │ │
│ │         secret_pair = 'berlin'                                                               │ │
│ │             secrets = OrderedDict({'abidjan': 'e1ee9e6a0af1e9e6343c715587710cc2', 'london':  │ │
│ │                       'b34fc8cc930a79c387782679c961273f', 'berlin':                          │ │
│ │                       'fa31fc13e7a28e7d70bb61e91aa9e178'})                                   │ │
│ │                seed = 'ZmEzMWZjMTNlN2EyOGU3ZDcwYmI2MW'                                       │ │
│ │        seed_matches = <callable_iterator object at 0x107ac7880>                              │ │
│ │                self = <streamrip.client.qobuz.QobuzSpoofer object at 0x1074214f0>            │ │
│ │            timezone = 'Berlin'                                                               │ │
│ │                vals = [                                                                      │ │
│ │                       │   'e1ee9e6a0af1e9e6343c715587710cc2',                                │ │
│ │                       │   'b34fc8cc930a79c387782679c961273f',                                │ │
│ │                       │   'fa31fc13e7a28e7d70bb61e91aa9e178'                                 │ │
│ │                       ]                                                                      │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: list.remove(x): x not in list
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/Users/zarra/StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = true
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = "2738067"
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = "LnW5pfpKbK5DwHwDXRUav36sd2warFexZ4BcIttG7H_QTiNmAUwglbyKm9irZv579OsTJV056bOXsu9dlfSvvA"
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "/Users/zarra/StreamripDownloads/YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "/Users/zarra/Library/Application Support/streamrip/downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "/Users/zarra/Library/Application Support/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

MacOS 15

### streamrip version

2.0.5
