### ISSUE TITLE
[BUG] <title> Tidal authorization

### ISSUE THREAD

**Issue by Darkloke** [nathom/streamrip#771]
### Describe the bug

I suppose this error happens if Tidal is blocked in your country -> a program gets non expected response from the server. I was able to solve it by running python.exe through Proxifier via proxy server.

### Command Used

```bash
rip url https://listen.tidal.com/album/232152309
```

### Debug Traceback

```text
C:\Users\ASUP-14>rip -vvv url https://listen.tidal.com/album/232152309
[12:37:05] DEBUG    Showing all debug logs                                                                                                                                        cli.py:102
           DEBUG    Removing dirs set()                                                                                                                                        artwork.py:19
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ > 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │   alter_argv = False                                                                         │ │
│ │         code = <code object <module> at 0x000002025513D0B0, file                             │ │
│ │                "C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\Scripts\rip.exe\__… │ │
│ │                line 1>                                                                       │ │
│ │ main_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\Scripts\rip.exe\">, │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\Scripts\rip.exe\">, │ │
│ │                origin='C:\\Users\\ASUP-14\\AppData\\Local\\Programs\\Python\\Python310\\Scr… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\ASUP-14\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\r… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\ASUP-14\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\r… │ │
│ │                │   're': <module 're' from                                                   │ │
│ │                'C:\\Users\\ASUP-14\\AppData\\Local\\Programs\\Python\\Python310\\lib\\re.py… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\Scripts\rip.exe\">, │ │
│ │                origin='C:\\Users\\ASUP-14\\AppData\\Local\\Programs\\Python\\Python310\\Scr… │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code            │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ >  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │       cached = 'C:\\Users\\ASUP-14\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\r… │ │
│ │         code = <code object <module> at 0x000002025513D0B0, file                             │ │
│ │                "C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\Scripts\rip.exe\__… │ │
│ │                line 1>                                                                       │ │
│ │        fname = 'C:\\Users\\ASUP-14\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\r… │ │
│ │ init_globals = None                                                                          │ │
│ │       loader = <zipimporter object                                                           │ │
│ │                "C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\Scripts\rip.exe\">  │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\Scripts\rip.exe\">, │ │
│ │                origin='C:\\Users\\ASUP-14\\AppData\\Local\\Programs\\Python\\Python310\\Scr… │ │
│ │     pkg_name = ''                                                                            │ │
│ │  run_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\Scripts\rip.exe\">, │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\Scripts\rip.exe\">, │ │
│ │                origin='C:\\Users\\ASUP-14\\AppData\\Local\\Programs\\Python\\Python310\\Scr… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\ASUP-14\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\r… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\ASUP-14\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\r… │ │
│ │                │   're': <module 're' from                                                   │ │
│ │                'C:\\Users\\ASUP-14\\AppData\\Local\\Programs\\Python\\Python310\\lib\\re.py… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │  script_name = None                                                                          │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py:1157 in │
│ __call__                                                                                         │
│                                                                                                  │
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py:1078 in │
│ main                                                                                             │
│                                                                                                  │
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py:1688 in │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py:1434 in │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py:783 in  │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py:3 │
│ 3 in new_func                                                                                    │
│                                                                                                  │
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\rip\cli.py: │
│ 28 in wrapper                                                                                    │
│                                                                                                  │
│    25 def coro(f):                                                                               │
│    26 │   @wraps(f)                                                                              │
│    27 │   def wrapper(*args, **kwargs):                                                          │
│ >  28 │   │   return asyncio.run(f(*args, **kwargs))                                             │
│    29 │                                                                                          │
│    30 │   return wrapper                                                                         │
│    31                                                                                            │
│                                                                                                  │
│ ┌───────────────────────────── locals ─────────────────────────────┐                             │
│ │   args = (<click.core.Context object at 0x0000020258F495A0>,)    │                             │
│ │ kwargs = {'urls': ('https://listen.tidal.com/album/232152309',)} │                             │
│ └──────────────────────────────────────────────────────────────────┘                             │
│                                                                                                  │
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py:44 in run        │
│                                                                                                  │
│   41 │   │   events.set_event_loop(loop)                                                         │
│   42 │   │   if debug is not None:                                                               │
│   43 │   │   │   loop.set_debug(debug)                                                           │
│ > 44 │   │   return loop.run_until_complete(main)                                                │
│   45 │   finally:                                                                                │
│   46 │   │   try:                                                                                │
│   47 │   │   │   _cancel_all_tasks(loop)                                                         │
│                                                                                                  │
│ ┌───────────────────────────── locals ──────────────────────────────┐                            │
│ │ debug = None                                                      │                            │
│ │  loop = <ProactorEventLoop running=False closed=True debug=False> │                            │
│ │  main = <coroutine object url at 0x0000020258F125E0>              │                            │
│ └───────────────────────────────────────────────────────────────────┘                            │
│                                                                                                  │
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py:649 in       │
│ run_until_complete                                                                               │
│                                                                                                  │
│    646 │   │   if not future.done():                                                             │
│    647 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')             │
│    648 │   │                                                                                     │
│ >  649 │   │   return future.result()                                                            │
│    650 │                                                                                         │
│    651 │   def stop(self):                                                                       │
│    652 │   │   """Stop running the event loop.                                                   │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │   future = <Task finished name='Task-1' coro=<url() done, defined at                         │ │
│ │            C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\site-packages\strea… │ │
│ │            exception=ContentTypeError(RequestInfo(url=URL('https://auth.tidal.com/v1/oauth2… │ │
│ │            method='POST', headers=<CIMultiDictProxy('Host': 'auth.tidal.com', 'User-Agent':  │ │
│ │            'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0', │ │
│ │            'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '54',      │ │
│ │            'Content-Type': 'application/x-www-form-urlencoded')>,                            │ │
│ │            real_url=URL('https://auth.tidal.com/v1/oauth2/device_authorization')), (),       │ │
│ │            message='Attempt to decode JSON with unexpected mimetype: text/html',             │ │
│ │            headers=<CIMultiDictProxy('Server': 'CloudFront', 'Date': 'Mon, 11 Nov 2024       │ │
│ │            09:37:07 GMT', 'Content-Type': 'text/html', 'Content-Length': '919',              │ │
│ │            'Connection': 'keep-alive', 'X-Cache': 'Error from cloudfront', 'Via': '1.1       │ │
│ │            fd454824c672a1a7cfcbbe959ab47058.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop':    │ │
│ │            'HEL51-P3', 'X-Amz-Cf-Id':                                                        │ │
│ │            'VPzX_xiAxLiA4x4gGI3VKvVgUDrk7HZiqGODKHWZ3BqDJmQ0ZYPE5w==')>)>                    │ │
│ │ new_task = True                                                                              │ │
│ │     self = <ProactorEventLoop running=False closed=True debug=False>                         │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\rip\cli.py: │
│ 166 in url                                                                                       │
│                                                                                                  │
│   163 │   │   │   version_coro = None                                                            │
│   164 │   │                                                                                      │
│   165 │   │   async with Main(cfg) as main:                                                      │
│ > 166 │   │   │   await main.add_all(urls)                                                       │
│   167 │   │   │   await main.resolve()                                                           │
│   168 │   │   │   await main.rip()                                                               │
│   169                                                                                            │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │          cfg = <streamrip.config.Config object at 0x0000020258F4A860>                        │ │
│ │          ctx = <click.core.Context object at 0x0000020258F495A0>                             │ │
│ │         main = <streamrip.rip.main.Main object at 0x0000020258FF5BA0>                        │ │
│ │      updates = True                                                                          │ │
│ │         urls = ('https://listen.tidal.com/album/232152309',)                                 │ │
│ │ version_coro = <Task finished name='Task-2' coro=<latest_streamrip_version() done, defined   │ │
│ │                at                                                                            │ │
│ │                C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\site-packages\s… │ │
│ │                result=('2.0.5', None)>                                                       │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\rip\main.py │
│ :121 in add_all                                                                                  │
│                                                                                                  │
│   118 │   │   │   │   │   f"[red]Found invalid url [cyan]{urls[i]}[/cyan], skipping.",           │
│   119 │   │   │   │   )                                                                          │
│   120 │   │   │   │   continue                                                                   │
│ > 121 │   │   │   url_client_pairs.append((p, await self.get_logged_in_client(p.source)))        │
│   122 │   │                                                                                      │
│   123 │   │   pendings = await asyncio.gather(                                                   │
│   124 │   │   │   *[                                                                             │
│                                                                                                  │
│ ┌──────────────────────────────────────── locals ────────────────────────────────────────┐       │
│ │                i = 0                                                                   │       │
│ │                p = <streamrip.rip.parse_url.GenericURL object at 0x0000020258FF6260>   │       │
│ │           parsed = [<streamrip.rip.parse_url.GenericURL object at 0x0000020258FF6260>] │       │
│ │             self = <streamrip.rip.main.Main object at 0x0000020258FF5BA0>              │       │
│ │ url_client_pairs = []                                                                  │       │
│ │             urls = ('https://listen.tidal.com/album/232152309',)                       │       │
│ └────────────────────────────────────────────────────────────────────────────────────────┘       │
│                                                                                                  │
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\rip\main.py │
│ :142 in get_logged_in_client                                                                     │
│                                                                                                  │
│   139 │   │   │   prompter = get_prompter(client, self.config)                                   │
│   140 │   │   │   if not prompter.has_creds():                                                   │
│   141 │   │   │   │   # Get credentials from user and log into client                            │
│ > 142 │   │   │   │   await prompter.prompt_and_login()                                          │
│   143 │   │   │   │   prompter.save()                                                            │
│   144 │   │   │   else:                                                                          │
│   145 │   │   │   │   with console.status(f"[cyan]Logging into {source}", spinner="dots"):       │
│                                                                                                  │
│ ┌──────────────────────────────────── locals ────────────────────────────────────┐               │
│ │   client = <streamrip.client.tidal.TidalClient object at 0x0000020258FF5C60>   │               │
│ │ prompter = <streamrip.rip.prompter.TidalPrompter object at 0x0000020258FF6380> │               │
│ │     self = <streamrip.rip.main.Main object at 0x0000020258FF5BA0>              │               │
│ │   source = 'tidal'                                                             │               │
│ └────────────────────────────────────────────────────────────────────────────────┘               │
│                                                                                                  │
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\rip\prompte │
│ r.py:101 in prompt_and_login                                                                     │
│                                                                                                  │
│    98 │   │   return len(self.config.session.tidal.access_token) > 0                             │
│    99 │                                                                                          │
│   100 │   async def prompt_and_login(self):                                                      │
│ > 101 │   │   device_code, uri = await self.client._get_device_code()                            │
│   102 │   │   login_link = f"https://{uri}"                                                      │
│   103 │   │                                                                                      │
│   104 │   │   console.print(                                                                     │
│                                                                                                  │
│ ┌────────────────────────────────── locals ──────────────────────────────────┐                   │
│ │ self = <streamrip.rip.prompter.TidalPrompter object at 0x0000020258FF6380> │                   │
│ └────────────────────────────────────────────────────────────────────────────┘                   │
│                                                                                                  │
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\client\tida │
│ l.py:288 in _get_device_code                                                                     │
│                                                                                                  │
│   285 │   │   │   "client_id": CLIENT_ID,                                                        │
│   286 │   │   │   "scope": "r_usr+w_usr+w_sub",                                                  │
│   287 │   │   }                                                                                  │
│ > 288 │   │   resp = await self._api_post(f"{AUTH_URL}/device_authorization", data)              │
│   289 │   │                                                                                      │
│   290 │   │   if resp.get("status", 200) != 200:                                                 │
│   291 │   │   │   raise Exception(f"Device authorization failed {resp}")                         │
│                                                                                                  │
│ ┌───────────────────────────────── locals ─────────────────────────────────┐                     │
│ │ data = {'client_id': 'zU4XHVVkc2tDPo4t', 'scope': 'r_usr+w_usr+w_sub'}   │                     │
│ │ self = <streamrip.client.tidal.TidalClient object at 0x0000020258FF5C60> │                     │
│ └──────────────────────────────────────────────────────────────────────────┘                     │
│                                                                                                  │
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\site-packages\streamrip\client\tida │
│ l.py:306 in _api_post                                                                            │
│                                                                                                  │
│   303 │   │   """                                                                                │
│   304 │   │   async with self.rate_limiter:                                                      │
│   305 │   │   │   async with self.session.post(url, data=data, auth=auth) as resp:               │
│ > 306 │   │   │   │   return await resp.json()                                                   │
│   307 │                                                                                          │
│   308 │   async def _api_request(self, path: str, params=None) -> dict:                          │
│   309 │   │   """Handle Tidal API requests.                                                      │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │ auth = None                                                                                  │ │
│ │ data = {'client_id': 'zU4XHVVkc2tDPo4t', 'scope': 'r_usr+w_usr+w_sub'}                       │ │
│ │ resp = <ClientResponse(https://auth.tidal.com/v1/oauth2/device_authorization) [403           │ │
│ │        Forbidden]>                                                                           │ │
│ │        <CIMultiDictProxy('Server': 'CloudFront', 'Date': 'Mon, 11 Nov 2024 09:37:07 GMT',    │ │
│ │        'Content-Type': 'text/html', 'Content-Length': '919', 'Connection': 'keep-alive',     │ │
│ │        'X-Cache': 'Error from cloudfront', 'Via': '1.1                                       │ │
│ │        fd454824c672a1a7cfcbbe959ab47058.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop':        │ │
│ │        'HEL51-P3', 'X-Amz-Cf-Id':                                                            │ │
│ │        'VPzX_xiAxLiA4x4gGI3VKvVgUDrk7HZiqGODKHWZ3BqDJmQ0ZYPE5w==')>                          │ │
│ │ self = <streamrip.client.tidal.TidalClient object at 0x0000020258FF5C60>                     │ │
│ │  url = 'https://auth.tidal.com/v1/oauth2/device_authorization'                               │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\ASUP-14\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client_reqrep │
│ .py:1176 in json                                                                                 │
│                                                                                                  │
│   1173 │   │   if content_type:                                                                  │
│   1174 │   │   │   ctype = self.headers.get(hdrs.CONTENT_TYPE, "").lower()                       │
│   1175 │   │   │   if not _is_expected_content_type(ctype, content_type):                        │
│ > 1176 │   │   │   │   raise ContentTypeError(                                                   │
│   1177 │   │   │   │   │   self.request_info,                                                    │
│   1178 │   │   │   │   │   self.history,                                                         │
│   1179 │   │   │   │   │   message=(                                                             │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │ content_type = 'application/json'                                                            │ │
│ │        ctype = 'text/html'                                                                   │ │
│ │     encoding = None                                                                          │ │
│ │         self = <ClientResponse(https://auth.tidal.com/v1/oauth2/device_authorization) [403   │ │
│ │                Forbidden]>                                                                   │ │
│ │                <CIMultiDictProxy('Server': 'CloudFront', 'Date': 'Mon, 11 Nov 2024 09:37:07  │ │
│ │                GMT', 'Content-Type': 'text/html', 'Content-Length': '919', 'Connection':     │ │
│ │                'keep-alive', 'X-Cache': 'Error from cloudfront', 'Via': '1.1                 │ │
│ │                fd454824c672a1a7cfcbbe959ab47058.cloudfront.net (CloudFront)',                │ │
│ │                'X-Amz-Cf-Pop': 'HEL51-P3', 'X-Amz-Cf-Id':                                    │ │
│ │                'VPzX_xiAxLiA4x4gGI3VKvVgUDrk7HZiqGODKHWZ3BqDJmQ0ZYPE5w==')>                  │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://auth.tidal.com/v1/oauth2/device_authorization')
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "E:\\Tidal"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = false
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = ""
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 2
# This will download videos included in Video Albums.
download_videos = false

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "C:\\Users\\ASUP-14\\StreamripDownloads\\YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "C:\\Users\\ASUP-14\\AppData\\Roaming\\streamrip\\downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "C:\\Users\\ASUP-14\\AppData\\Roaming\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = false
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = false
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = false
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 260

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Windows 10

### streamrip version

2.0.5
