### ISSUE TITLE
[BUG] <title>Invalid Credentials from params

### ISSUE THREAD

**Issue by Jeff254** [nathom/streamrip#796]
### Describe the bug

I get the following Authentication Error: _Invalid credentials from params {'user_id': '515522', 'user_auth_token': '6K-_WX7UbxZehSAQUFmKvs0Tk1eAOqka-2zhW3VFIFg3CF6lm0ELpyJyh5qtBIjT860of-W50FutJx4aGI9YfQ', 'app_id': '579939560'}_

Not sure what i am missing.

### Command Used

```bash
rip search qobuz track "let me go"
```

### Debug Traceback

```text
[22:07:46] DEBUG    Showing all debug logs                                                                                                                                                                                        cli.py:102
           DEBUG    Request params {'user_id': '515522', 'user_auth_token': '6K-_WX7UbxZehSAQUFmKvs0Tk1eAOqka-2zhW3VFIFg3CF6lm0ELpyJyh5qtBIjT860of-W50FutJx4aGI9YfQ', 'app_id': '579939560'}                                    qobuz.py:181
           DEBUG    api_request: endpoint=user/login, params={'user_id': '515522', 'user_auth_token': '6K-_WX7UbxZehSAQUFmKvs0Tk1eAOqka-2zhW3VFIFg3CF6lm0ELpyJyh5qtBIjT860of-W50FutJx4aGI9YfQ', 'app_id': '579939560'}          qobuz.py:430
⠸ Logging into qobuz[22:07:47] DEBUG    Login resp: {'status': 'error', 'code': 401, 'message': 'Invalid username/email and password combination'}                                                                                                  qobuz.py:183
           DEBUG    Removing dirs set()                                                                                                                                                                                        artwork.py:19
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ in _run_module_as_main:198                                                                       │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │   alter_argv = False                                                                         │ │
│ │         code = <code object <module> at 0x00000228029D0030, file                             │ │
│ │                "C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\__ma… │ │
│ │                line 1>                                                                       │ │
│ │ main_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,   │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,   │ │
│ │                origin='C:\\Users\\xxxx\\AppData\\Local\\Programs\\Python\\Python312\\Scrip… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\xxxx\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\xxxx\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip… │ │
│ │                │   're': <module 're' from                                                   │ │
│ │                'C:\\Users\\xxxx\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\re\\__i… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,   │ │
│ │                origin='C:\\Users\\xxxx\\AppData\\Local\\Programs\\Python\\Python312\\Scrip… │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│ in _run_code:88                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │       cached = 'C:\\Users\\xxxx\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip… │ │
│ │         code = <code object <module> at 0x00000228029D0030, file                             │ │
│ │                "C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\__ma… │ │
│ │                line 1>                                                                       │ │
│ │        fname = 'C:\\Users\\xxxx\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip… │ │
│ │ init_globals = None                                                                          │ │
│ │       loader = <zipimporter object                                                           │ │
│ │                "C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">    │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,   │ │
│ │                origin='C:\\Users\\xxxx\\AppData\\Local\\Programs\\Python\\Python312\\Scrip… │ │
│ │     pkg_name = ''                                                                            │ │
│ │  run_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,   │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Scripts\rip.exe\">,   │ │
│ │                origin='C:\\Users\\xxxx\\AppData\\Local\\Programs\\Python\\Python312\\Scrip… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\xxxx\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\xxxx\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\rip… │ │
│ │                │   're': <module 're' from                                                   │ │
│ │                'C:\\Users\\xxxx\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\re\\__i… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │  script_name = None                                                                          │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│ C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py:1157 in   │
│ __call__                                                                                         │
│                                                                                                  │
│ C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py:1078 in   │
│ main                                                                                             │
│                                                                                                  │
│ C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py:1688 in   │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py:1434 in   │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py:783 in    │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\decorators.py:33  │
│ in new_func                                                                                      │
│                                                                                                  │
│ C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\rip\cli.py:28 │
│ in wrapper                                                                                       │
│                                                                                                  │
│    25 def coro(f):                                                                               │
│    26 │   @wraps(f)                                                                              │
│    27 │   def wrapper(*args, **kwargs):                                                          │
│ >  28 │   │   return asyncio.run(f(*args, **kwargs))                                             │
│    29 │                                                                                          │
│    30 │   return wrapper                                                                         │
│    31                                                                                            │
│                                                                                                  │
│ ┌─────────────────────────── locals ────────────────────────────┐                                │
│ │   args = (<click.core.Context object at 0x00000228056F3D10>,) │                                │
│ │ kwargs = {                                                    │                                │
│ │          │   'source': 'qobuz',                               │                                │
│ │          │   'media_type': 'track',                           │                                │
│ │          │   'query': 'let me go',                            │                                │
│ │          │   'first': False,                                  │                                │
│ │          │   'output_file': None,                             │                                │
│ │          │   'num_results': 100                               │                                │
│ │          }                                                    │                                │
│ └───────────────────────────────────────────────────────────────┘                                │
│                                                                                                  │
│ C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py:194 in run         │
│                                                                                                  │
│   191 │   │   │   "asyncio.run() cannot be called from a running event loop")                    │
│   192 │                                                                                          │
│   193 │   with Runner(debug=debug, loop_factory=loop_factory) as runner:                         │
│ > 194 │   │   return runner.run(main)                                                            │
│   195                                                                                            │
│   196                                                                                            │
│   197 def _cancel_all_tasks(loop):                                                               │
│                                                                                                  │
│ ┌─────────────────────────────── locals ───────────────────────────────┐                         │
│ │        debug = None                                                  │                         │
│ │ loop_factory = None                                                  │                         │
│ │         main = <coroutine object search at 0x00000228069696D0>       │                         │
│ │       runner = <asyncio.runners.Runner object at 0x0000022806A09760> │                         │
│ └──────────────────────────────────────────────────────────────────────┘                         │
│                                                                                                  │
│ C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py:118 in run         │
│                                                                                                  │
│   115 │   │                                                                                      │
│   116 │   │   self._interrupt_count = 0                                                          │
│   117 │   │   try:                                                                               │
│ > 118 │   │   │   return self._loop.run_until_complete(task)                                     │
│   119 │   │   except exceptions.CancelledError:                                                  │
│   120 │   │   │   if self._interrupt_count > 0:                                                  │
│   121 │   │   │   │   uncancel = getattr(task, "uncancel", None)                                 │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │        context = <_contextvars.Context object at 0x0000022806A62640>                         │ │
│ │           coro = <coroutine object search at 0x00000228069696D0>                             │ │
│ │           self = <asyncio.runners.Runner object at 0x0000022806A09760>                       │ │
│ │ sigint_handler = functools.partial(<bound method Runner._on_sigint of                        │ │
│ │                  <asyncio.runners.Runner object at 0x0000022806A09760>>, main_task=<Task     │ │
│ │                  finished name='Task-1' coro=<search() done, defined at                      │ │
│ │                  C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\s… │ │
│ │                  exception=AuthenticationError("Invalid credentials from params {'user_id':  │ │
│ │                  '515522', 'user_auth_token':                                                │ │
│ │                  '6K-_WX7UbxZehSAQUFmKvs0Tk1eAOqka-2zhW3VFIFg3CF6lm0ELpyJyh5qtBIjT860of-W50… │ │
│ │                  'app_id': '579939560'}")>)                                                  │ │
│ │           task = <Task finished name='Task-1' coro=<search() done, defined at                │ │
│ │                  C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\s… │ │
│ │                  exception=AuthenticationError("Invalid credentials from params {'user_id':  │ │
│ │                  '515522', 'user_auth_token':                                                │ │
│ │                  '6K-_WX7UbxZehSAQUFmKvs0Tk1eAOqka-2zhW3VFIFg3CF6lm0ELpyJyh5qtBIjT860of-W50… │ │
│ │                  'app_id': '579939560'}")>                                                   │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:687 in         │
│ run_until_complete                                                                               │
│                                                                                                  │
│    684 │   │   if not future.done():                                                             │
│    685 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')             │
│    686 │   │                                                                                     │
│ >  687 │   │   return future.result()                                                            │
│    688 │                                                                                         │
│    689 │   def stop(self):                                                                       │
│    690 │   │   """Stop running the event loop.                                                   │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │   future = <Task finished name='Task-1' coro=<search() done, defined at                      │ │
│ │            C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamr… │ │
│ │            exception=AuthenticationError("Invalid credentials from params {'user_id':        │ │
│ │            '515522', 'user_auth_token':                                                      │ │
│ │            '6K-_WX7UbxZehSAQUFmKvs0Tk1eAOqka-2zhW3VFIFg3CF6lm0ELpyJyh5qtBIjT860of-W50FutJx4… │ │
│ │            'app_id': '579939560'}")>                                                         │ │
│ │ new_task = False                                                                             │ │
│ │     self = <ProactorEventLoop running=False closed=True debug=False>                         │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\rip\cli.py:37 │
│ 1 in search                                                                                      │
│                                                                                                  │
│   368 │   │   │   │   │   source, media_type, query, output_file, num_results                    │
│   369 │   │   │   │   )                                                                          │
│   370 │   │   │   else:                                                                          │
│ > 371 │   │   │   │   await main.search_interactive(source, media_type, query)                   │
│   372 │   │   │   await main.resolve()                                                           │
│   373 │   │   │   await main.rip()                                                               │
│   374                                                                                            │
│                                                                                                  │
│ ┌─────────────────────────────── locals ───────────────────────────────┐                         │
│ │         cfg = <streamrip.config.Config object at 0x00000228069A1C10> │                         │
│ │         ctx = <click.core.Context object at 0x00000228056F3D10>      │                         │
│ │       first = False                                                  │                         │
│ │        main = <streamrip.rip.main.Main object at 0x00000228069D3620> │                         │
│ │  media_type = 'track'                                                │                         │
│ │ num_results = 100                                                    │                         │
│ │ output_file = None                                                   │                         │
│ │       query = 'let me go'                                            │                         │
│ │      source = 'qobuz'                                                │                         │
│ └──────────────────────────────────────────────────────────────────────┘                         │
│                                                                                                  │
│ C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\rip\main.py:1 │
│ 68 in search_interactive                                                                         │
│                                                                                                  │
│   165 │   │   await asyncio.gather(*[item.rip() for item in self.media])                         │
│   166 │                                                                                          │
│   167 │   async def search_interactive(self, source: str, media_type: str, query: str):          │
│ > 168 │   │   client = await self.get_logged_in_client(source)                                   │
│   169 │   │                                                                                      │
│   170 │   │   with console.status(f"[bold]Searching {source}", spinner="dots"):                  │
│   171 │   │   │   pages = await client.search(media_type, query, limit=100)                      │
│                                                                                                  │
│ ┌────────────────────────────── locals ───────────────────────────────┐                          │
│ │ media_type = 'track'                                                │                          │
│ │      query = 'let me go'                                            │                          │
│ │       self = <streamrip.rip.main.Main object at 0x00000228069D3620> │                          │
│ │     source = 'qobuz'                                                │                          │
│ └─────────────────────────────────────────────────────────────────────┘                          │
│                                                                                                  │
│ C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\rip\main.py:1 │
│ 47 in get_logged_in_client                                                                       │
│                                                                                                  │
│   144 │   │   │   else:                                                                          │
│   145 │   │   │   │   with console.status(f"[cyan]Logging into {source}", spinner="dots"):       │
│   146 │   │   │   │   │   # Log into client using credentials from config                        │
│ > 147 │   │   │   │   │   await client.login()                                                   │
│   148 │   │                                                                                      │
│   149 │   │   assert client.logged_in                                                            │
│   150 │   │   return client                                                                      │
│                                                                                                  │
│ ┌──────────────────────────────────── locals ────────────────────────────────────┐               │
│ │   client = <streamrip.client.qobuz.QobuzClient object at 0x00000228069D36E0>   │               │
│ │ prompter = <streamrip.rip.prompter.QobuzPrompter object at 0x0000022806AFC8C0> │               │
│ │     self = <streamrip.rip.main.Main object at 0x00000228069D3620>              │               │
│ │   source = 'qobuz'                                                             │               │
│ └────────────────────────────────────────────────────────────────────────────────┘               │
│                                                                                                  │
│ C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamrip\client\qobuz. │
│ py:186 in login                                                                                  │
│                                                                                                  │
│   183 │   │   logger.debug("Login resp: %s", resp)                                               │
│   184 │   │                                                                                      │
│   185 │   │   if status == 401:                                                                  │
│ > 186 │   │   │   raise AuthenticationError(f"Invalid credentials from params {params}")         │
│   187 │   │   elif status == 400:                                                                │
│   188 │   │   │   raise InvalidAppIdError(f"Invalid app id from params {params}")                │
│   189                                                                                            │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │      c = QobuzConfig(                                                                        │ │
│ │          │   use_auth_token=True,                                                            │ │
│ │          │   email_or_userid='515522',                                                       │ │
│ │          │                                                                                   │ │
│ │          password_or_token='6K-_WX7UbxZehSAQUFmKvs0Tk1eAOqka-2zhW3VFIFg3CF6lm0ELpyJyh5qtBIj… │ │
│ │          │   app_id='579939560',                                                             │ │
│ │          │   quality=3,                                                                      │ │
│ │          │   download_booklets=True,                                                         │ │
│ │          │   secrets=['fa31fc13e7a28e7d70bb61e91aa9e178']                                    │ │
│ │          )                                                                                   │ │
│ │ params = {                                                                                   │ │
│ │          │   'user_id': '515522',                                                            │ │
│ │          │   'user_auth_token':                                                              │ │
│ │          '6K-_WX7UbxZehSAQUFmKvs0Tk1eAOqka-2zhW3VFIFg3CF6lm0ELpyJyh5qtBIjT860of-W50FutJx4a'… │ │
│ │          │   'app_id': '579939560'                                                           │ │
│ │          }                                                                                   │ │
│ │   resp = {                                                                                   │ │
│ │          │   'status': 'error',                                                              │ │
│ │          │   'code': 401,                                                                    │ │
│ │          │   'message': 'Invalid username/email and password combination'                    │ │
│ │          }                                                                                   │ │
│ │   self = <streamrip.client.qobuz.QobuzClient object at 0x00000228069D36E0>                   │ │
│ │ status = 401                                                                                 │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
AuthenticationError: Invalid credentials from params {'user_id': '515522', 'user_auth_token': '6K-_WX7UbxZehSAQUFmKvs0Tk1eAOqka-2zhW3VFIFg3CF6lm0ELpyJyh5qtBIjT860of-W50FutJx4aGI9YfQ', 'app_id': '579939560'}
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "C:\\Users\\xxxx\\Downloads\\Streamrip"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = true
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = "2709472"
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = "BYq_BLvGf5t6BPAI_cOz2oJWB1e8LVRYuYeLr4gADcvoVVpUxAo62Mu9ZZMp7iDrkPv31wzp2SkM7IqQ9sOvAA"
# Do not change
app_id = "579939560"
# Do not change
secrets = ["fa31fc13e7a28e7d70bb61e91aa9e178"]

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "C:\\Users\\xxxx\\StreamripDownloads\\YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "C:\\Users\\xxxx\\AppData\\Roaming\\streamrip\\downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "C:\\Users\\xxxx\\AppData\\Roaming\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Windows 10

### streamrip version

2.0.5

### Additional context

This used to work just fine. Not sure what changed!
