### ISSUE TITLE
[Question] Tidal "Retrying with lower quality" clarification

### ISSUE THREAD

**Issue by girlmaya** [nathom/streamrip#801]
### Describe the bug

`WARNING  Failed to get manifest for (song). Retrying with lower quality.                 tidal.py:156`

Does this mean that the highest quality option does not exist at all on tidal, or does exist and currently streamrip is unable to access it due to the api changes in the past year?

### Command Used

```bash
rip url https://listen.tidal.com/album/id
```

### Debug Traceback

```text
N/a
```

### Config File

```toml
...
[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
...
```

### Operating System

Linux

### streamrip version

dev
