### ISSUE TITLE
[BUG] Qobuz Metadata Error

### ISSUE THREAD

**Issue by yU93r** [nathom/streamrip#805]
### Describe the bug

When I try to download MP3s from Qobuz and open them with any tag editing program (Mp3tag) (or use a program like Poweramp) I get the error “ID3v2 tag parse error”. But this error only happens for albums with more than 3-4 songs.

### Command Used

```bash
rip url https://www.qobuz.com/us-en/album/pablo-honey-radiohead/0634904077969
```

### Debug Traceback

```text
[20:26:17] DEBUG    Tagging with [('TIT2', TIT2(encoding=<Encoding.UTF8: 3>, text=['Anyone Can Play        tagger.py:253
                    Guitar'])), ('TPE1', TPE1(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TALB',
                    TALB(encoding=<Encoding.UTF8: 3>, text=['Pablo Honey'])), ('TPE2',
                    TPE2(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TCOM',
                    TCOM(encoding=<Encoding.UTF8: 3>, text=['Colin Greenwood'])), ('TYER',
                    TYER(encoding=<Encoding.UTF8: 3>, text=['1993'])), ('TT1',
                    TT1(encoding=<Encoding.UTF8: 3>, text=['Radiohead\'s debut album, Pablo Honey, is a
                    promising collection that blends U2\'s anthemic rock with long, atmospheric
                    instrumental passages and an enthralling triple-guitar attack that is alternately
                    gentle and bracingly noisy. The group has difficulty writing a set of songs that are
                    as compelling as their sound, but when they do hit the mark -- such as on "Anyone Can
                    Play Guitar," "Blow Out," and the self-loathing breakthrough single "Creep" -- the
                    band achieves a rare power that is both visceral and intelligent.<br /><br />&copy
                    Stephen Thomas Erlewine /TiVo'])), ('TCON', TCON(encoding=<Encoding.UTF8: 3>,
                    text=['Pop, Rock, Alternatif et Indé'])), ('TCOP', TCOP(encoding=<Encoding.UTF8: 3>,
                    text=['1993 XL Recordings Ltd 1993 XL Recordings Ltd'])), ('TRCK',
                    TRCK(encoding=<Encoding.UTF8: 3>, text=['6/12'])), ('TPOS',
                    TPOS(encoding=<Encoding.UTF8: 3>, text=['1/1'])), ('TSRC',
                    TSRC(encoding=<Encoding.UTF8: 3>, text=['GBAYE9300107']))]
[20:26:19] DEBUG    Tagging with [('TIT2', TIT2(encoding=<Encoding.UTF8: 3>, text=['Ripcord'])), ('TPE1',  tagger.py:253
                    TPE1(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TALB',
                    TALB(encoding=<Encoding.UTF8: 3>, text=['Pablo Honey'])), ('TPE2',
                    TPE2(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TCOM',
                    TCOM(encoding=<Encoding.UTF8: 3>, text=['Colin Greenwood'])), ('TYER',
                    TYER(encoding=<Encoding.UTF8: 3>, text=['1993'])), ('TT1',
                    TT1(encoding=<Encoding.UTF8: 3>, text=['Radiohead\'s debut album, Pablo Honey, is a
                    promising collection that blends U2\'s anthemic rock with long, atmospheric
                    instrumental passages and an enthralling triple-guitar attack that is alternately
                    gentle and bracingly noisy. The group has difficulty writing a set of songs that are
                    as compelling as their sound, but when they do hit the mark -- such as on "Anyone Can
                    Play Guitar," "Blow Out," and the self-loathing breakthrough single "Creep" -- the
                    band achieves a rare power that is both visceral and intelligent.<br /><br />&copy
                    Stephen Thomas Erlewine /TiVo'])), ('TCON', TCON(encoding=<Encoding.UTF8: 3>,
                    text=['Pop, Rock, Alternatif et Indé'])), ('TCOP', TCOP(encoding=<Encoding.UTF8: 3>,
                    text=['1993 XL Recordings Ltd 1993 XL Recordings Ltd'])), ('TRCK',
                    TRCK(encoding=<Encoding.UTF8: 3>, text=['7/12'])), ('TPOS',
                    TPOS(encoding=<Encoding.UTF8: 3>, text=['1/1'])), ('TSRC',
                    TSRC(encoding=<Encoding.UTF8: 3>, text=['GBAYE9300108']))]
[20:26:20] DEBUG    Tagging with [('TIT2', TIT2(encoding=<Encoding.UTF8: 3>, text=['How Do You?'])),       tagger.py:253
                    ('TPE1', TPE1(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TALB',
                    TALB(encoding=<Encoding.UTF8: 3>, text=['Pablo Honey'])), ('TPE2',
                    TPE2(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TCOM',
                    TCOM(encoding=<Encoding.UTF8: 3>, text=['Colin Greenwood'])), ('TYER',
                    TYER(encoding=<Encoding.UTF8: 3>, text=['1993'])), ('TT1',
                    TT1(encoding=<Encoding.UTF8: 3>, text=['Radiohead\'s debut album, Pablo Honey, is a
                    promising collection that blends U2\'s anthemic rock with long, atmospheric
                    instrumental passages and an enthralling triple-guitar attack that is alternately
                    gentle and bracingly noisy. The group has difficulty writing a set of songs that are
                    as compelling as their sound, but when they do hit the mark -- such as on "Anyone Can
                    Play Guitar," "Blow Out," and the self-loathing breakthrough single "Creep" -- the
                    band achieves a rare power that is both visceral and intelligent.<br /><br />&copy
                    Stephen Thomas Erlewine /TiVo'])), ('TCON', TCON(encoding=<Encoding.UTF8: 3>,
                    text=['Pop, Rock, Alternatif et Indé'])), ('TCOP', TCOP(encoding=<Encoding.UTF8: 3>,
                    text=['1993 XL Recordings Ltd 1993 XL Recordings Ltd'])), ('TRCK',
                    TRCK(encoding=<Encoding.UTF8: 3>, text=['3/12'])), ('TPOS',
                    TPOS(encoding=<Encoding.UTF8: 3>, text=['1/1'])), ('TSRC',
                    TSRC(encoding=<Encoding.UTF8: 3>, text=['GBAYE9300105']))]
           DEBUG    Tagging with [('TIT2', TIT2(encoding=<Encoding.UTF8: 3>, text=['You'])), ('TPE1',      tagger.py:253
                    TPE1(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TALB',
                    TALB(encoding=<Encoding.UTF8: 3>, text=['Pablo Honey'])), ('TPE2',
                    TPE2(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TCOM',
                    TCOM(encoding=<Encoding.UTF8: 3>, text=['Colin Greenwood'])), ('TYER',
                    TYER(encoding=<Encoding.UTF8: 3>, text=['1993'])), ('TT1',
                    TT1(encoding=<Encoding.UTF8: 3>, text=['Radiohead\'s debut album, Pablo Honey, is a
                    promising collection that blends U2\'s anthemic rock with long, atmospheric
                    instrumental passages and an enthralling triple-guitar attack that is alternately
                    gentle and bracingly noisy. The group has difficulty writing a set of songs that are
                    as compelling as their sound, but when they do hit the mark -- such as on "Anyone Can
                    Play Guitar," "Blow Out," and the self-loathing breakthrough single "Creep" -- the
                    band achieves a rare power that is both visceral and intelligent.<br /><br />&copy
                    Stephen Thomas Erlewine /TiVo'])), ('TCON', TCON(encoding=<Encoding.UTF8: 3>,
                    text=['Pop, Rock, Alternatif et Indé'])), ('TCOP', TCOP(encoding=<Encoding.UTF8: 3>,
                    text=['1993 XL Recordings Ltd 1993 XL Recordings Ltd'])), ('TRCK',
                    TRCK(encoding=<Encoding.UTF8: 3>, text=['1/12'])), ('TPOS',
                    TPOS(encoding=<Encoding.UTF8: 3>, text=['1/1'])), ('TSRC',
                    TSRC(encoding=<Encoding.UTF8: 3>, text=['GBAYE9200113']))]
[20:26:22] DEBUG    Tagging with [('TIT2', TIT2(encoding=<Encoding.UTF8: 3>, text=["I Can't"])), ('TPE1',  tagger.py:253
                    TPE1(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TALB',
                    TALB(encoding=<Encoding.UTF8: 3>, text=['Pablo Honey'])), ('TPE2',
                    TPE2(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TCOM',
                    TCOM(encoding=<Encoding.UTF8: 3>, text=['Colin Greenwood'])), ('TYER',
                    TYER(encoding=<Encoding.UTF8: 3>, text=['1993'])), ('TT1',
                    TT1(encoding=<Encoding.UTF8: 3>, text=['Radiohead\'s debut album, Pablo Honey, is a
                    promising collection that blends U2\'s anthemic rock with long, atmospheric
                    instrumental passages and an enthralling triple-guitar attack that is alternately
                    gentle and bracingly noisy. The group has difficulty writing a set of songs that are
                    as compelling as their sound, but when they do hit the mark -- such as on "Anyone Can
                    Play Guitar," "Blow Out," and the self-loathing breakthrough single "Creep" -- the
                    band achieves a rare power that is both visceral and intelligent.<br /><br />&copy
                    Stephen Thomas Erlewine /TiVo'])), ('TCON', TCON(encoding=<Encoding.UTF8: 3>,
                    text=['Pop, Rock, Alternatif et Indé'])), ('TCOP', TCOP(encoding=<Encoding.UTF8: 3>,
                    text=['1993 XL Recordings Ltd 1993 XL Recordings Ltd'])), ('TRCK',
                    TRCK(encoding=<Encoding.UTF8: 3>, text=['10/12'])), ('TPOS',
                    TPOS(encoding=<Encoding.UTF8: 3>, text=['1/1'])), ('TSRC',
                    TSRC(encoding=<Encoding.UTF8: 3>, text=['GBAYE9300110']))]
           DEBUG    Tagging with [('TIT2', TIT2(encoding=<Encoding.UTF8: 3>, text=['Thinking About         tagger.py:253
                    You'])), ('TPE1', TPE1(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TALB',
                    TALB(encoding=<Encoding.UTF8: 3>, text=['Pablo Honey'])), ('TPE2',
                    TPE2(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TCOM',
                    TCOM(encoding=<Encoding.UTF8: 3>, text=['Colin Greenwood'])), ('TYER',
                    TYER(encoding=<Encoding.UTF8: 3>, text=['1993'])), ('TT1',
                    TT1(encoding=<Encoding.UTF8: 3>, text=['Radiohead\'s debut album, Pablo Honey, is a
                    promising collection that blends U2\'s anthemic rock with long, atmospheric
                    instrumental passages and an enthralling triple-guitar attack that is alternately
                    gentle and bracingly noisy. The group has difficulty writing a set of songs that are
                    as compelling as their sound, but when they do hit the mark -- such as on "Anyone Can
                    Play Guitar," "Blow Out," and the self-loathing breakthrough single "Creep" -- the
                    band achieves a rare power that is both visceral and intelligent.<br /><br />&copy
                    Stephen Thomas Erlewine /TiVo'])), ('TCON', TCON(encoding=<Encoding.UTF8: 3>,
                    text=['Pop, Rock, Alternatif et Indé'])), ('TCOP', TCOP(encoding=<Encoding.UTF8: 3>,
                    text=['1993 XL Recordings Ltd 1993 XL Recordings Ltd'])), ('TRCK',
                    TRCK(encoding=<Encoding.UTF8: 3>, text=['5/12'])), ('TPOS',
                    TPOS(encoding=<Encoding.UTF8: 3>, text=['1/1'])), ('TSRC',
                    TSRC(encoding=<Encoding.UTF8: 3>, text=['GBAYE9200114']))]
[20:26:23] DEBUG    Tagging with [('TIT2', TIT2(encoding=<Encoding.UTF8: 3>, text=['Blow Out'])), ('TPE1', tagger.py:253
                    TPE1(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TALB',
                    TALB(encoding=<Encoding.UTF8: 3>, text=['Pablo Honey'])), ('TPE2',
                    TPE2(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TCOM',
                    TCOM(encoding=<Encoding.UTF8: 3>, text=['Colin Greenwood'])), ('TYER',
                    TYER(encoding=<Encoding.UTF8: 3>, text=['1993'])), ('TT1',
                    TT1(encoding=<Encoding.UTF8: 3>, text=['Radiohead\'s debut album, Pablo Honey, is a
                    promising collection that blends U2\'s anthemic rock with long, atmospheric
                    instrumental passages and an enthralling triple-guitar attack that is alternately
                    gentle and bracingly noisy. The group has difficulty writing a set of songs that are
                    as compelling as their sound, but when they do hit the mark -- such as on "Anyone Can
                    Play Guitar," "Blow Out," and the self-loathing breakthrough single "Creep" -- the
                    band achieves a rare power that is both visceral and intelligent.<br /><br />&copy
                    Stephen Thomas Erlewine /TiVo'])), ('TCON', TCON(encoding=<Encoding.UTF8: 3>,
                    text=['Pop, Rock, Alternatif et Indé'])), ('TCOP', TCOP(encoding=<Encoding.UTF8: 3>,
                    text=['1993 XL Recordings Ltd 1993 XL Recordings Ltd'])), ('TRCK',
                    TRCK(encoding=<Encoding.UTF8: 3>, text=['12/12'])), ('TPOS',
                    TPOS(encoding=<Encoding.UTF8: 3>, text=['1/1'])), ('TSRC',
                    TSRC(encoding=<Encoding.UTF8: 3>, text=['GBAYE9300111']))]
[20:26:26] DEBUG    Tagging with [('TIT2', TIT2(encoding=<Encoding.UTF8: 3>, text=['Creep'])), ('TPE1',    tagger.py:253
                    TPE1(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TALB',
                    TALB(encoding=<Encoding.UTF8: 3>, text=['Pablo Honey'])), ('TPE2',
                    TPE2(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TCOM',
                    TCOM(encoding=<Encoding.UTF8: 3>, text=['Colin Greenwood'])), ('TYER',
                    TYER(encoding=<Encoding.UTF8: 3>, text=['1993'])), ('TT1',
                    TT1(encoding=<Encoding.UTF8: 3>, text=['Radiohead\'s debut album, Pablo Honey, is a
                    promising collection that blends U2\'s anthemic rock with long, atmospheric
                    instrumental passages and an enthralling triple-guitar attack that is alternately
                    gentle and bracingly noisy. The group has difficulty writing a set of songs that are
                    as compelling as their sound, but when they do hit the mark -- such as on "Anyone Can
                    Play Guitar," "Blow Out," and the self-loathing breakthrough single "Creep" -- the
                    band achieves a rare power that is both visceral and intelligent.<br /><br />&copy
                    Stephen Thomas Erlewine /TiVo'])), ('TCON', TCON(encoding=<Encoding.UTF8: 3>,
                    text=['Pop, Rock, Alternatif et Indé'])), ('TCOP', TCOP(encoding=<Encoding.UTF8: 3>,
                    text=['1993 XL Recordings Ltd 1993 XL Recordings Ltd'])), ('TRCK',
                    TRCK(encoding=<Encoding.UTF8: 3>, text=['2/12'])), ('TPOS',
                    TPOS(encoding=<Encoding.UTF8: 3>, text=['1/1'])), ('TSRC',
                    TSRC(encoding=<Encoding.UTF8: 3>, text=['GBAYE9200070']))]
           DEBUG    Tagging with [('TIT2', TIT2(encoding=<Encoding.UTF8: 3>, text=['Vegetable'])),         tagger.py:253
                    ('TPE1', TPE1(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TALB',
                    TALB(encoding=<Encoding.UTF8: 3>, text=['Pablo Honey'])), ('TPE2',
                    TPE2(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TCOM',
                    TCOM(encoding=<Encoding.UTF8: 3>, text=['Colin Greenwood'])), ('TYER',
                    TYER(encoding=<Encoding.UTF8: 3>, text=['1993'])), ('TT1',
                    TT1(encoding=<Encoding.UTF8: 3>, text=['Radiohead\'s debut album, Pablo Honey, is a
                    promising collection that blends U2\'s anthemic rock with long, atmospheric
                    instrumental passages and an enthralling triple-guitar attack that is alternately
                    gentle and bracingly noisy. The group has difficulty writing a set of songs that are
                    as compelling as their sound, but when they do hit the mark -- such as on "Anyone Can
                    Play Guitar," "Blow Out," and the self-loathing breakthrough single "Creep" -- the
                    band achieves a rare power that is both visceral and intelligent.<br /><br />&copy
                    Stephen Thomas Erlewine /TiVo'])), ('TCON', TCON(encoding=<Encoding.UTF8: 3>,
                    text=['Pop, Rock, Alternatif et Indé'])), ('TCOP', TCOP(encoding=<Encoding.UTF8: 3>,
                    text=['1993 XL Recordings Ltd 1993 XL Recordings Ltd'])), ('TRCK',
                    TRCK(encoding=<Encoding.UTF8: 3>, text=['8/12'])), ('TPOS',
                    TPOS(encoding=<Encoding.UTF8: 3>, text=['1/1'])), ('TSRC',
                    TSRC(encoding=<Encoding.UTF8: 3>, text=['GBAYE9300109']))]
[20:26:27] DEBUG    Tagging with [('TIT2', TIT2(encoding=<Encoding.UTF8: 3>, text=['Prove Yourself'])),    tagger.py:253
                    ('TPE1', TPE1(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TALB',
                    TALB(encoding=<Encoding.UTF8: 3>, text=['Pablo Honey'])), ('TPE2',
                    TPE2(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TCOM',
                    TCOM(encoding=<Encoding.UTF8: 3>, text=['Colin Greenwood'])), ('TYER',
                    TYER(encoding=<Encoding.UTF8: 3>, text=['1993'])), ('TT1',
                    TT1(encoding=<Encoding.UTF8: 3>, text=['Radiohead\'s debut album, Pablo Honey, is a
                    promising collection that blends U2\'s anthemic rock with long, atmospheric
                    instrumental passages and an enthralling triple-guitar attack that is alternately
                    gentle and bracingly noisy. The group has difficulty writing a set of songs that are
                    as compelling as their sound, but when they do hit the mark -- such as on "Anyone Can
                    Play Guitar," "Blow Out," and the self-loathing breakthrough single "Creep" -- the
                    band achieves a rare power that is both visceral and intelligent.<br /><br />&copy
                    Stephen Thomas Erlewine /TiVo'])), ('TCON', TCON(encoding=<Encoding.UTF8: 3>,
                    text=['Pop, Rock, Alternatif et Indé'])), ('TCOP', TCOP(encoding=<Encoding.UTF8: 3>,
                    text=['1993 XL Recordings Ltd 1993 XL Recordings Ltd'])), ('TRCK',
                    TRCK(encoding=<Encoding.UTF8: 3>, text=['9/12'])), ('TPOS',
                    TPOS(encoding=<Encoding.UTF8: 3>, text=['1/1'])), ('TSRC',
                    TSRC(encoding=<Encoding.UTF8: 3>, text=['GBAYE9200115']))]
           DEBUG    Tagging with [('TIT2', TIT2(encoding=<Encoding.UTF8: 3>, text=['Lurgee'])), ('TPE1',   tagger.py:253
                    TPE1(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TALB',
                    TALB(encoding=<Encoding.UTF8: 3>, text=['Pablo Honey'])), ('TPE2',
                    TPE2(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TCOM',
                    TCOM(encoding=<Encoding.UTF8: 3>, text=['Colin Greenwood'])), ('TYER',
                    TYER(encoding=<Encoding.UTF8: 3>, text=['1993'])), ('TT1',
                    TT1(encoding=<Encoding.UTF8: 3>, text=['Radiohead\'s debut album, Pablo Honey, is a
                    promising collection that blends U2\'s anthemic rock with long, atmospheric
                    instrumental passages and an enthralling triple-guitar attack that is alternately
                    gentle and bracingly noisy. The group has difficulty writing a set of songs that are
                    as compelling as their sound, but when they do hit the mark -- such as on "Anyone Can
                    Play Guitar," "Blow Out," and the self-loathing breakthrough single "Creep" -- the
                    band achieves a rare power that is both visceral and intelligent.<br /><br />&copy
                    Stephen Thomas Erlewine /TiVo'])), ('TCON', TCON(encoding=<Encoding.UTF8: 3>,
                    text=['Pop, Rock, Alternatif et Indé'])), ('TCOP', TCOP(encoding=<Encoding.UTF8: 3>,
                    text=['1993 XL Recordings Ltd 1993 XL Recordings Ltd'])), ('TRCK',
                    TRCK(encoding=<Encoding.UTF8: 3>, text=['11/12'])), ('TPOS',
                    TPOS(encoding=<Encoding.UTF8: 3>, text=['1/1'])), ('TSRC',
                    TSRC(encoding=<Encoding.UTF8: 3>, text=['GBAYE9200116']))]
[20:26:28] DEBUG    Tagging with [('TIT2', TIT2(encoding=<Encoding.UTF8: 3>, text=['Stop Whispering'])),   tagger.py:253
                    ('TPE1', TPE1(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TALB',
                    TALB(encoding=<Encoding.UTF8: 3>, text=['Pablo Honey'])), ('TPE2',
                    TPE2(encoding=<Encoding.UTF8: 3>, text=['Radiohead'])), ('TCOM',
                    TCOM(encoding=<Encoding.UTF8: 3>, text=['Colin Greenwood'])), ('TYER',
                    TYER(encoding=<Encoding.UTF8: 3>, text=['1993'])), ('TT1',
                    TT1(encoding=<Encoding.UTF8: 3>, text=['Radiohead\'s debut album, Pablo Honey, is a
                    promising collection that blends U2\'s anthemic rock with long, atmospheric
                    instrumental passages and an enthralling triple-guitar attack that is alternately
                    gentle and bracingly noisy. The group has difficulty writing a set of songs that are
                    as compelling as their sound, but when they do hit the mark -- such as on "Anyone Can
                    Play Guitar," "Blow Out," and the self-loathing breakthrough single "Creep" -- the
                    band achieves a rare power that is both visceral and intelligent.<br /><br />&copy
                    Stephen Thomas Erlewine /TiVo'])), ('TCON', TCON(encoding=<Encoding.UTF8: 3>,
                    text=['Pop, Rock, Alternatif et Indé'])), ('TCOP', TCOP(encoding=<Encoding.UTF8: 3>,
                    text=['1993 XL Recordings Ltd 1993 XL Recordings Ltd'])), ('TRCK',
                    TRCK(encoding=<Encoding.UTF8: 3>, text=['4/12'])), ('TPOS',
                    TPOS(encoding=<Encoding.UTF8: 3>, text=['1/1'])), ('TSRC',
                    TSRC(encoding=<Encoding.UTF8: 3>, text=['GBAYE9300106']))]
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "C:\\Users\\xxxxxxxxx\\Music"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 1
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = true
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = ""
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = ""
# Do not change
app_id = "579939560"
# Do not change
secrets = ["e1ee9e6a0af1e9e6343c715587710cc2", "b34fc8cc930a79c387782679c961273f", "fa31fc13e7a28e7d70bb61e91aa9e178"]

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "C:\\Users\\xxxxxxxxx\\StreamripDownloads\\YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = false
# Path to the downloads database 
downloads_path = "C:\\Users\\xxxxxxxxx\\AppData\\Roaming\\streamrip\\downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = false
failed_downloads_path = "C:\\Users\\xxxxxxxxx\\AppData\\Roaming\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist}\\{title}"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Windows

### streamrip version

2.0.5

### Screenshots and recordings

![Image](https://github.com/user-attachments/assets/fb097c2e-65ed-4ddf-9cbe-681cae64e9c5)
