### ISSUE TITLE
[BUG] Needing help here

### ISSUE THREAD

**Issue by a7xplanets** [nathom/streamrip#811]
### Describe the bug

![Image](https://github.com/user-attachments/assets/43b30e2f-7186-47a2-a16f-af082dce2a4c)

This is the error, I fresh installed Windows and not sure what else to do

I used the normal test Tidal url to see if it will work, still not working, any help will be appreciated! 

### Command Used

```bash
rip --quality 3 url https://tidal.com/browse/album/147569387
```

### Debug Traceback

```text
[23:27:53] DEBUG    Showing all debug logs                                                                    cli.py:102
Found invalid url https://tidal.com, skipping.
           DEBUG    Removing dirs set()                                                                    artwork.py:19
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiodns\__init__.py:58   │
│ in __init__                                                                                      │
│                                                                                                  │
│    55 │   │   if sys.platform == 'win32':                                                        │
│    56 │   │   │   if not isinstance(self.loop, asyncio.SelectorEventLoop):                       │
│    57 │   │   │   │   try:                                                                       │
│ ❱  58 │   │   │   │   │   import winloop                                                         │
│    59 │   │   │   │   │   if not isinstance(self.loop , winloop.Loop):                           │
│    60 │   │   │   │   │   │   raise RuntimeError(                                                │
│    61 │   │   │   │   │   │   │   'aiodns needs a SelectorEventLoop on Windows. See more: http   │
│                                                                                                  │
│ ╭──────────────────────────── locals ─────────────────────────────╮                              │
│ │      kwargs = {}                                                │                              │
│ │        loop = None                                              │                              │
│ │ nameservers = None                                              │                              │
│ │        self = <aiodns.DNSResolver object at 0x000001B6C9A6ECF0> │                              │
│ ╰─────────────────────────────────────────────────────────────────╯                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'winloop'

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in _run_module_as_main:198                                                                       │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   alter_argv = False                                                                         │ │
│ │         code = <code object <module> at 0x000001B6C54C5E30, file                             │ │
│ │                "C:\Users\natha\AppData\Local\Programs\Python\Python313\Scripts\rip.exe\__ma… │ │
│ │                line 1>                                                                       │ │
│ │ main_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\natha\AppData\Local\Programs\Python\Python313\Scripts\rip.exe\">,   │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\natha\AppData\Local\Programs\Python\Python313\Scripts\rip.exe\">,   │ │
│ │                origin='C:\\Users\\natha\\AppData\\Local\\Programs\\Python\\Python313\\Scrip… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\natha\\AppData\\Local\\Programs\\Python\\Python313\\Scripts\\rip… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\natha\\AppData\\Local\\Programs\\Python\\Python313\\Scripts\\rip… │ │
│ │                │   're': <module 're' from                                                   │ │
│ │                'C:\\Users\\natha\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\re\\__i… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\natha\AppData\Local\Programs\Python\Python313\Scripts\rip.exe\">,   │ │
│ │                origin='C:\\Users\\natha\\AppData\\Local\\Programs\\Python\\Python313\\Scrip… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│ in _run_code:88                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │       cached = 'C:\\Users\\natha\\AppData\\Local\\Programs\\Python\\Python313\\Scripts\\rip… │ │
│ │         code = <code object <module> at 0x000001B6C54C5E30, file                             │ │
│ │                "C:\Users\natha\AppData\Local\Programs\Python\Python313\Scripts\rip.exe\__ma… │ │
│ │                line 1>                                                                       │ │
│ │        fname = 'C:\\Users\\natha\\AppData\\Local\\Programs\\Python\\Python313\\Scripts\\rip… │ │
│ │ init_globals = None                                                                          │ │
│ │       loader = <zipimporter object                                                           │ │
│ │                "C:\Users\natha\AppData\Local\Programs\Python\Python313\Scripts\rip.exe\">    │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\natha\AppData\Local\Programs\Python\Python313\Scripts\rip.exe\">,   │ │
│ │                origin='C:\\Users\\natha\\AppData\\Local\\Programs\\Python\\Python313\\Scrip… │ │
│ │     pkg_name = ''                                                                            │ │
│ │  run_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\natha\AppData\Local\Programs\Python\Python313\Scripts\rip.exe\">,   │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\natha\AppData\Local\Programs\Python\Python313\Scripts\rip.exe\">,   │ │
│ │                origin='C:\\Users\\natha\\AppData\\Local\\Programs\\Python\\Python313\\Scrip… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\natha\\AppData\\Local\\Programs\\Python\\Python313\\Scripts\\rip… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\natha\\AppData\\Local\\Programs\\Python\\Python313\\Scripts\\rip… │ │
│ │                │   're': <module 're' from                                                   │ │
│ │                'C:\\Users\\natha\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\re\\__i… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │  script_name = None                                                                          │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│ C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\core.py:1161 in   │
│ __call__                                                                                         │
│                                                                                                  │
│ C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\core.py:1082 in   │
│ main                                                                                             │
│                                                                                                  │
│ C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\core.py:1697 in   │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\core.py:1443 in   │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\core.py:788 in    │
│ invoke                                                                                           │
│                                                                                                  │
│ C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\decorators.py:33  │
│ in new_func                                                                                      │
│                                                                                                  │
│ C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\streamrip\rip\cli.py:28 │
│ in wrapper                                                                                       │
│                                                                                                  │
│    25 def coro(f):                                                                               │
│    26 │   @wraps(f)                                                                              │
│    27 │   def wrapper(*args, **kwargs):                                                          │
│ ❱  28 │   │   return asyncio.run(f(*args, **kwargs))                                             │
│    29 │                                                                                          │
│    30 │   return wrapper                                                                         │
│    31                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────── locals ────────────────────────────╮                                │
│ │   args = (<click.core.Context object at 0x000001B6C9A1B110>,) │                                │
│ │ kwargs = {'urls': ('https://tidal.com',)}                     │                                │
│ ╰───────────────────────────────────────────────────────────────╯                                │
│                                                                                                  │
│ C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py:195 in run         │
│                                                                                                  │
│   192 │   │   │   "asyncio.run() cannot be called from a running event loop")                    │
│   193 │                                                                                          │
│   194 │   with Runner(debug=debug, loop_factory=loop_factory) as runner:                         │
│ ❱ 195 │   │   return runner.run(main)                                                            │
│   196                                                                                            │
│   197                                                                                            │
│   198 def _cancel_all_tasks(loop):                                                               │
│                                                                                                  │
│ ╭─────────────────────────────── locals ───────────────────────────────╮                         │
│ │        debug = None                                                  │                         │
│ │ loop_factory = None                                                  │                         │
│ │         main = <coroutine object url at 0x000001B6C9AABE20>          │                         │
│ │       runner = <asyncio.runners.Runner object at 0x000001B6C9A6C590> │                         │
│ ╰──────────────────────────────────────────────────────────────────────╯                         │
│                                                                                                  │
│ C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py:118 in run         │
│                                                                                                  │
│   115 │   │                                                                                      │
│   116 │   │   self._interrupt_count = 0                                                          │
│   117 │   │   try:                                                                               │
│ ❱ 118 │   │   │   return self._loop.run_until_complete(task)                                     │
│   119 │   │   except exceptions.CancelledError:                                                  │
│   120 │   │   │   if self._interrupt_count > 0:                                                  │
│   121 │   │   │   │   uncancel = getattr(task, "uncancel", None)                                 │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │        context = <_contextvars.Context object at 0x000001B6C9C074C0>                         │ │
│ │           coro = <coroutine object url at 0x000001B6C9AABE20>                                │ │
│ │           self = <asyncio.runners.Runner object at 0x000001B6C9A6C590>                       │ │
│ │ sigint_handler = functools.partial(<bound method Runner._on_sigint of                        │ │
│ │                  <asyncio.runners.Runner object at 0x000001B6C9A6C590>>, main_task=<Task     │ │
│ │                  finished name='Task-1' coro=<url() done, defined at                         │ │
│ │                  C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\s… │ │
│ │                  exception=RuntimeError('aiodns needs a SelectorEventLoop on Windows. See    │ │
│ │                  more: https://github.com/saghul/aiodns/issues/86')>)                        │ │
│ │           task = <Task finished name='Task-1' coro=<url() done, defined at                   │ │
│ │                  C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\s… │ │
│ │                  exception=RuntimeError('aiodns needs a SelectorEventLoop on Windows. See    │ │
│ │                  more: https://github.com/saghul/aiodns/issues/86')>                         │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py:725 in         │
│ run_until_complete                                                                               │
│                                                                                                  │
│    722 │   │   if not future.done():                                                             │
│    723 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')             │
│    724 │   │                                                                                     │
│ ❱  725 │   │   return future.result()                                                            │
│    726 │                                                                                         │
│    727 │   def stop(self):                                                                       │
│    728 │   │   """Stop running the event loop.                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   future = <Task finished name='Task-1' coro=<url() done, defined at                         │ │
│ │            C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\streamr… │ │
│ │            exception=RuntimeError('aiodns needs a SelectorEventLoop on Windows. See more:    │ │
│ │            https://github.com/saghul/aiodns/issues/86')>                                     │ │
│ │ new_task = False                                                                             │ │
│ │     self = <ProactorEventLoop running=False closed=True debug=False>                         │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\streamrip\rip\cli.py:17 │
│ 1 in url                                                                                         │
│                                                                                                  │
│   168 │   │   │   await main.rip()                                                               │
│   169 │   │                                                                                      │
│   170 │   │   if version_coro is not None:                                                       │
│ ❱ 171 │   │   │   latest_version, notes = await version_coro                                     │
│   172 │   │   │   if latest_version != __version__:                                              │
│   173 │   │   │   │   console.print(                                                             │
│   174 │   │   │   │   │   f"\n[green]A new version of streamrip [cyan]v{latest_version}[/cyan]   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │          cfg = <streamrip.config.Config object at 0x000001B6C9A6C1A0>                        │ │
│ │          ctx = <click.core.Context object at 0x000001B6C9A1B110>                             │ │
│ │         main = <streamrip.rip.main.Main object at 0x000001B6C9A6D550>                        │ │
│ │      updates = True                                                                          │ │
│ │         urls = ('https://tidal.com',)                                                        │ │
│ │ version_coro = <Task finished name='Task-2' coro=<latest_streamrip_version() done, defined   │ │
│ │                at                                                                            │ │
│ │                C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\str… │ │
│ │                exception=RuntimeError('aiodns needs a SelectorEventLoop on Windows. See      │ │
│ │                more: https://github.com/saghul/aiodns/issues/86')>                           │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\streamrip\rip\cli.py:41 │
│ 5 in latest_streamrip_version                                                                    │
│                                                                                                  │
│   412                                                                                            │
│   413                                                                                            │
│   414 async def latest_streamrip_version() -> tuple[str, str | None]:                            │
│ ❱ 415 │   async with aiohttp.ClientSession() as s:                                               │
│   416 │   │   async with s.get("https://pypi.org/pypi/streamrip/json") as resp:                  │
│   417 │   │   │   data = await resp.json()                                                       │
│   418 │   │   version = data["info"]["version"]                                                  │
│                                                                                                  │
│ C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py:359   │
│ in __init__                                                                                      │
│                                                                                                  │
│    356 │   │   │   │   )                                                                         │
│    357 │   │                                                                                     │
│    358 │   │   if connector is None:                                                             │
│ ❱  359 │   │   │   connector = TCPConnector(loop=loop)                                           │
│    360 │   │                                                                                     │
│    361 │   │   if connector._loop is not loop:                                                   │
│    362 │   │   │   raise RuntimeError("Session and connector has to use same event loop")        │
│                                                                                                  │
│ ╭────────────────────────────────────── locals ──────────────────────────────────────╮           │
│ │                 auth = None                                                        │           │
│ │      auto_decompress = True                                                        │           │
│ │             base_url = None                                                        │           │
│ │         conn_timeout = None                                                        │           │
│ │            connector = None                                                        │           │
│ │      connector_owner = True                                                        │           │
│ │           cookie_jar = None                                                        │           │
│ │              cookies = None                                                        │           │
│ │              headers = None                                                        │           │
│ │                 loop = <ProactorEventLoop running=False closed=True debug=False>   │           │
│ │       max_field_size = 8190                                                        │           │
│ │        max_line_size = 8190                                                        │           │
│ │                proxy = None                                                        │           │
│ │           proxy_auth = None                                                        │           │
│ │     raise_for_status = False                                                       │           │
│ │         read_bufsize = 65536                                                       │           │
│ │         read_timeout = <_SENTINEL.sentinel: 1>                                     │           │
│ │ requote_redirect_url = True                                                        │           │
│ │                 self = <aiohttp.client.ClientSession object at 0x000001B6C9A6E900> │           │
│ │    skip_auto_headers = None                                                        │           │
│ │              timeout = <_SENTINEL.sentinel: 1>                                     │           │
│ │        trace_configs = None                                                        │           │
│ │            trust_env = False                                                       │           │
│ │              version = HttpVersion(major=1, minor=1)                               │           │
│ ╰────────────────────────────────────────────────────────────────────────────────────╯           │
│                                                                                                  │
│ C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py:86 │
│ 9 in __init__                                                                                    │
│                                                                                                  │
│    866 │   │                                                                                     │
│    867 │   │   self._ssl = _merge_ssl_params(ssl, verify_ssl, ssl_context, fingerprint)          │
│    868 │   │   if resolver is None:                                                              │
│ ❱  869 │   │   │   resolver = DefaultResolver(loop=self._loop)                                   │
│    870 │   │   self._resolver = resolver                                                         │
│    871 │   │                                                                                     │
│    872 │   │   self._use_dns_cache = use_dns_cache                                               │
│                                                                                                  │
│ ╭──────────────────────────────────────── locals ────────────────────────────────────────╮       │
│ │  enable_cleanup_closed = False                                                         │       │
│ │                 family = <AddressFamily.AF_UNSPEC: 0>                                  │       │
│ │            fingerprint = None                                                          │       │
│ │            force_close = False                                                         │       │
│ │   happy_eyeballs_delay = 0.25                                                          │       │
│ │             interleave = None                                                          │       │
│ │      keepalive_timeout = <_SENTINEL.sentinel: 1>                                       │       │
│ │                  limit = 100                                                           │       │
│ │         limit_per_host = 0                                                             │       │
│ │             local_addr = None                                                          │       │
│ │                   loop = <ProactorEventLoop running=False closed=True debug=False>     │       │
│ │               resolver = None                                                          │       │
│ │                   self = <aiohttp.connector.TCPConnector object at 0x000001B6C9A6EBA0> │       │
│ │                    ssl = True                                                          │       │
│ │            ssl_context = None                                                          │       │
│ │ timeout_ceil_threshold = 5                                                             │       │
│ │          ttl_dns_cache = 10                                                            │       │
│ │          use_dns_cache = True                                                          │       │
│ │             verify_ssl = True                                                          │       │
│ ╰────────────────────────────────────────────────────────────────────────────────────────╯       │
│                                                                                                  │
│ C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\resolver.py:93  │
│ in __init__                                                                                      │
│                                                                                                  │
│    90 │   │   if aiodns is None:                                                                 │
│    91 │   │   │   raise RuntimeError("Resolver requires aiodns library")                         │
│    92 │   │                                                                                      │
│ ❱  93 │   │   self._resolver = aiodns.DNSResolver(*args, **kwargs)                               │
│    94 │   │                                                                                      │
│    95 │   │   if not hasattr(self._resolver, "gethostbyname"):                                   │
│    96 │   │   │   # aiodns 1.1 is not available, fallback to DNSResolver.query                   │
│                                                                                                  │
│ ╭──────────────────────────────── locals ────────────────────────────────╮                       │
│ │   args = ()                                                            │                       │
│ │ kwargs = {}                                                            │                       │
│ │   loop = <ProactorEventLoop running=False closed=True debug=False>     │                       │
│ │   self = <aiohttp.resolver.AsyncResolver object at 0x000001B6C9A6EE40> │                       │
│ ╰────────────────────────────────────────────────────────────────────────╯                       │
│                                                                                                  │
│ C:\Users\natha\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiodns\__init__.py:63   │
│ in __init__                                                                                      │
│                                                                                                  │
│    60 │   │   │   │   │   │   raise RuntimeError(                                                │
│    61 │   │   │   │   │   │   │   'aiodns needs a SelectorEventLoop on Windows. See more: http   │
│    62 │   │   │   │   except ModuleNotFoundError:                                                │
│ ❱  63 │   │   │   │   │   raise RuntimeError(                                                    │
│    64 │   │   │   │   │   │   'aiodns needs a SelectorEventLoop on Windows. See more: https://   │
│    65 │   │   kwargs.pop('sock_state_cb', None)                                                  │
│    66 │   │   timeout = kwargs.pop('timeout', None)                                              │
│                                                                                                  │
│ ╭──────────────────────────── locals ─────────────────────────────╮                              │
│ │      kwargs = {}                                                │                              │
│ │        loop = None                                              │                              │
│ │ nameservers = None                                              │                              │
│ │        self = <aiodns.DNSResolver object at 0x000001B6C9A6ECF0> │                              │
│ ╰─────────────────────────────────────────────────────────────────╯                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: aiodns needs a SelectorEventLoop on Windows. See more: https://github.com/saghul/aiodns/issues/86
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "C:\\Users\\natha\\StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false

# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = false
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = ""
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "C:\\Users\\natha\\StreamripDownloads\\YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "C:\\Users\\natha\\AppData\\Roaming\\streamrip\\downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "C:\\Users\\natha\\AppData\\Roaming\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.3"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Windows 11 Home 24H2

### streamrip version

2.0.5
