### ISSUE TITLE
[BUG] Configured lossy_bitrate not used

### ISSUE THREAD

**Issue by cs-t1** [nathom/streamrip#823]
### Describe the bug

I'm having the issue of ffmpeg not been given the correct bitrate flag for song conversion. Upon reading through the code, it seems to me that the `lossy_bitrate` field in the config file is never used, thus the conversion engine using its default value (`-q:a 0`)

Thanks :)

### Command Used

```bash
rip --quality 1 --folder . url <url>
```

### Debug Traceback

```text
Not applicable
```

### Config File

```toml
# Convert tracks to a codec after downloading them.
[conversion]
enabled = true
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "MP3"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320
```

### Operating System

Linux

### streamrip version

2.0.5
