### ISSUE TITLE
[BUG] Constant Authentication error while ripping from Deezer

### ISSUE THREAD

**Issue by BittenBagel** [nathom/streamrip#846]
### Describe the bug

Constantly getting Authentication Errors. I've tried several authenticated arls and I always get the same output. Not sure what the issue is. I am hoping it is something simple that I am overlooking.

### Command Used

```bash
rip url https://dzr.page.link/uJfknnY6CuRuLYJF6
```

### Debug Traceback

```text
[13:50:26] DEBUG    Showing all debug logs                                                      cli.py:111
[13:50:27] DEBUG    Removing dirs set()                                                      artwork.py:19
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/xxxxx/.local/bin/rip:8 in <module>                                                      │
│                                                                                                  │
│   5 from streamrip.rip import rip                                                                │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(rip())                                                                          │
│   9                                                                                              │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │  re = <module 're' from                                                                      │ │
│ │       '/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/li… │ │
│ │ rip = <HelpColorsGroup rip>                                                                  │ │
│ │ sys = <module 'sys' (built-in)>                                                              │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /Users/xxxxx/.local/pipx/venvs/streamrip/lib/python3.13/site-packages/click/core.py:1161 in    │
│ __call__                                                                                         │
│                                                                                                  │
│ /Users/xxxxx/.local/pipx/venvs/streamrip/lib/python3.13/site-packages/click/core.py:1082 in    │
│ main                                                                                             │
│                                                                                                  │
│ /Users/xxxxx/.local/pipx/venvs/streamrip/lib/python3.13/site-packages/click/core.py:1697 in    │
│ invoke                                                                                           │
│                                                                                                  │
│ /Users/xxxxx/.local/pipx/venvs/streamrip/lib/python3.13/site-packages/click/core.py:1443 in    │
│ invoke                                                                                           │
│                                                                                                  │
│ /Users/xxxxx/.local/pipx/venvs/streamrip/lib/python3.13/site-packages/click/core.py:788 in     │
│ invoke                                                                                           │
│                                                                                                  │
│ /Users/xxxxx/.local/pipx/venvs/streamrip/lib/python3.13/site-packages/click/decorators.py:33   │
│ in new_func                                                                                      │
│                                                                                                  │
│ /Users/xxxxxx/.local/pipx/venvs/streamrip/lib/python3.13/site-packages/streamrip/rip/cli.py:29  │
│ in wrapper                                                                                       │
│                                                                                                  │
│    26 def coro(f):                                                                               │
│    27 │   @wraps(f)                                                                              │
│    28 │   def wrapper(*args, **kwargs):                                                          │
│ ❱  29 │   │   return asyncio.run(f(*args, **kwargs))                                             │
│    30 │                                                                                          │
│    31 │   return wrapper                                                                         │
│    32                                                                                            │
│                                                                                                  │
│ ╭──────────────────────────── locals ─────────────────────────────╮                              │
│ │   args = (<click.core.Context object at 0x1062de850>,)          │                              │
│ │ kwargs = {'urls': ('https://dzr.page.link/uJfknnY6CuRuLYJF6',)} │                              │
│ ╰─────────────────────────────────────────────────────────────────╯                              │
│                                                                                                  │
│ /opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13 │
│ /asyncio/runners.py:195 in run                                                                   │
│                                                                                                  │
│   192 │   │   │   "asyncio.run() cannot be called from a running event loop")                    │
│   193 │                                                                                          │
│   194 │   with Runner(debug=debug, loop_factory=loop_factory) as runner:                         │
│ ❱ 195 │   │   return runner.run(main)                                                            │
│   196                                                                                            │
│   197                                                                                            │
│   198 def _cancel_all_tasks(loop):                                                               │
│                                                                                                  │
│ ╭─────────────────────────── locals ────────────────────────────╮                                │
│ │        debug = None                                           │                                │
│ │ loop_factory = None                                           │                                │
│ │         main = <coroutine object url at 0x1062e4170>          │                                │
│ │       runner = <asyncio.runners.Runner object at 0x1062d9160> │                                │
│ ╰───────────────────────────────────────────────────────────────╯                                │
│                                                                                                  │
│ /opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13 │
│ /asyncio/runners.py:118 in run                                                                   │
│                                                                                                  │
│   115 │   │                                                                                      │
│   116 │   │   self._interrupt_count = 0                                                          │
│   117 │   │   try:                                                                               │
│ ❱ 118 │   │   │   return self._loop.run_until_complete(task)                                     │
│   119 │   │   except exceptions.CancelledError:                                                  │
│   120 │   │   │   if self._interrupt_count > 0:                                                  │
│   121 │   │   │   │   uncancel = getattr(task, "uncancel", None)                                 │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │        context = <_contextvars.Context object at 0x1054aa580>                                │ │
│ │           coro = <coroutine object url at 0x1062e4170>                                       │ │
│ │           self = <asyncio.runners.Runner object at 0x1062d9160>                              │ │
│ │ sigint_handler = functools.partial(<bound method Runner._on_sigint of                        │ │
│ │                  <asyncio.runners.Runner object at 0x1062d9160>>, main_task=<Task finished   │ │
│ │                  name='Task-1' coro=<url() done, defined at                                  │ │
│ │                  /Users/xxxxx/.local/pipx/venvs/streamrip/lib/python3.13/site-packages/st… │ │
│ │                  exception=AuthenticationError()>)                                           │ │
│ │           task = <Task finished name='Task-1' coro=<url() done, defined at                   │ │
│ │                  /Users/xxxxx/.local/pipx/venvs/streamrip/lib/python3.13/site-packages/st… │ │
│ │                  exception=AuthenticationError()>                                            │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13 │
│ /asyncio/base_events.py:719 in run_until_complete                                                │
│                                                                                                  │
│    716 │   │   if not future.done():                                                             │
│    717 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')             │
│    718 │   │                                                                                     │
│ ❱  719 │   │   return future.result()                                                            │
│    720 │                                                                                         │
│    721 │   def stop(self):                                                                       │
│    722 │   │   """Stop running the event loop.                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   future = <Task finished name='Task-1' coro=<url() done, defined at                         │ │
│ │            /Users/xxxxx/.local/pipx/venvs/streamrip/lib/python3.13/site-packages/streamri… │ │
│ │            exception=AuthenticationError()>                                                  │ │
│ │ new_task = False                                                                             │ │
│ │     self = <_UnixSelectorEventLoop running=False closed=True debug=False>                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /Users/xxxxx/.local/pipx/venvs/streamrip/lib/python3.13/site-packages/streamrip/rip/cli.py:191 │
│ in url                                                                                           │
│                                                                                                  │
│   188 │   │   │   │   version_coro = None                                                        │
│   189 │   │   │                                                                                  │
│   190 │   │   │   async with Main(cfg) as main:                                                  │
│ ❱ 191 │   │   │   │   await main.add_all(urls)                                                   │
│   192 │   │   │   │   await main.resolve()                                                       │
│   193 │   │   │   │   await main.rip()                                                           │
│   194                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │          cfg = <streamrip.config.Config object at 0x1062d8d70>                               │ │
│ │          ctx = <click.core.Context object at 0x1062de850>                                    │ │
│ │         main = <streamrip.rip.main.Main object at 0x1062da270>                               │ │
│ │      updates = True                                                                          │ │
│ │         urls = ('https://dzr.page.link/uJfknnY6CuRuLYJF6',)                                  │ │
│ │ version_coro = <Task cancelled name='Task-2' coro=<latest_streamrip_version() done, defined  │ │
│ │                at                                                                            │ │
│ │                /Users/xxxxx/.local/pipx/venvs/streamrip/lib/python3.13/site-packages/stre… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /Users/xxxxx/.local/pipx/venvs/streamrip/lib/python3.13/site-packages/streamrip/rip/main.py:12 │
│ 4 in add_all                                                                                     │
│                                                                                                  │
│   121 │   │   │   │   │   f"[red]Found invalid url [cyan]{urls[i]}[/cyan], skipping.",           │
│   122 │   │   │   │   )                                                                          │
│   123 │   │   │   │   continue                                                                   │
│ ❱ 124 │   │   │   url_client_pairs.append((p, await self.get_logged_in_client(p.source)))        │
│   125 │   │                                                                                      │
│   126 │   │   pendings = await asyncio.gather(                                                   │
│   127 │   │   │   *[                                                                             │
│                                                                                                  │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮        │
│ │                i = 0                                                                  │        │
│ │                p = <streamrip.rip.parse_url.DeezerDynamicURL object at 0x1062db620>   │        │
│ │           parsed = [<streamrip.rip.parse_url.DeezerDynamicURL object at 0x1062db620>] │        │
│ │             self = <streamrip.rip.main.Main object at 0x1062da270>                    │        │
│ │ url_client_pairs = []                                                                 │        │
│ │             urls = ('https://dzr.page.link/uJfknnY6CuRuLYJF6',)                       │        │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯        │
│                                                                                                  │
│ /Users/xxxxx/.local/pipx/venvs/streamrip/lib/python3.13/site-packages/streamrip/rip/main.py:15 │
│ 0 in get_logged_in_client                                                                        │
│                                                                                                  │
│   147 │   │   │   else:                                                                          │
│   148 │   │   │   │   with console.status(f"[cyan]Logging into {source}", spinner="dots"):       │
│   149 │   │   │   │   │   # Log into client using credentials from config                        │
│ ❱ 150 │   │   │   │   │   await client.login()                                                   │
│   151 │   │                                                                                      │
│   152 │   │   assert client.logged_in                                                            │
│   153 │   │   return client                                                                      │
│                                                                                                  │
│ ╭───────────────────────────────── locals ─────────────────────────────────╮                     │
│ │   client = <streamrip.client.deezer.DeezerClient object at 0x1062da660>  │                     │
│ │ prompter = <streamrip.rip.prompter.DeezerPrompter object at 0x1062db770> │                     │
│ │     self = <streamrip.rip.main.Main object at 0x1062da270>               │                     │
│ │   source = 'deezer'                                                      │                     │
│ ╰──────────────────────────────────────────────────────────────────────────╯                     │
│                                                                                                  │
│ /Users/xxxxx/.local/pipx/venvs/streamrip/lib/python3.13/site-packages/streamrip/client/deezer. │
│ py:53 in login                                                                                   │
│                                                                                                  │
│    50 │   │   │   raise MissingCredentialsError                                                  │
│    51 │   │   success = self.client.login_via_arl(arl)                                           │
│    52 │   │   if not success:                                                                    │
│ ❱  53 │   │   │   raise AuthenticationError                                                      │
│    54 │   │   self.logged_in = True                                                              │
│    55 │                                                                                          │
│    56 │   async def get_metadata(self, item_id: str, media_type: str) -> dict:                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │     arl = 'd979cc12012db2b23e12465eb3a05ea069dd19668212d2133ef530c8007a4db4f577ba5b2386df08… │ │
│ │    self = <streamrip.client.deezer.DeezerClient object at 0x1062da660>                       │ │
│ │ success = False                                                                              │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AuthenticationError
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "/Users/xxxxx/StreamripDownloads"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false
# Put tracks in an album with 2 or more discs into a subfolder named `Disc N`
disc_subdirectories = true
# Download (and convert) tracks all at once, instead of sequentially.
# If you are converting the tracks, or have fast internet, this will
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60
# Verify SSL certificates for API connections
# Set to false if you encounter SSL certificate verification errors (not recommended)
verify_ssl = true

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = false
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = ""
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = ""
# Do not change
app_id = ""
# Do not change
secrets = [""]

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 1
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = "d979cc12012db2b23e12465eb3a05ea069dd19668212d2133ef530c8007a4db4f577ba5b2386df08b2ecb969a255a2749b17d45b030ce930411cc98fd4145d6f2a2ef84360fac451461002e9d31fb17c9296ddb2c6daae800a13b3c4b9d41166"
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = false
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "/Users/xxxxx/StreamripDownloads/YouTubeVideos"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database
downloads_path = "/Users/xxxxx/Library/Application Support/streamrip/downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "/Users/xxxxx/Library/Application Support/streamrip/failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this.
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding.
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name.
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.6"
# Print a message if a new version of streamrip is available
check_for_updates = true
```

### Operating System

macOS 15.3.1

### streamrip version

2.1.0
