### ISSUE TITLE
[BUG] Mistake

### ISSUE THREAD

**Issue by ghost** [nathom/streamrip#849]
### Describe the bug

There are bugs in Streamrip — when I download a playlist, the album name of every song gets changed to the playlist name instead of the actual album name.

### Command Used

```bash
rip url https://tidal.com/browse/playlist/c80eaa10-5c4e-45aa-8f63-7b14a82d541f
```

### Debug Traceback

```text
rip -vvv url https://tidal.com/browse/playlist/c80eaa10-5c4e-45aa-8f63-7b14a82d541f
[16:38:14] DEBUG    Showing all debug logs                                                                   cli.py:111
           DEBUG   ⠙  Resolving URLs...{'uuid': 'c80eaa10-5c4e-45aa-8f63-7b14a82d541f', 'title': 'ALL', 'numberOfTracks': 5,  tidal.py:130
                    'numberOfVideos': 0, 'creator': {'id': 203631561}, 'description': '', 'duration': 769,
                    'lastUpdated': '2025-05-08T10:38:55.530+0000', 'created':
                    '2025-05-08T10:37:59.536+0000', 'type': 'USER', 'publicPlaylist': True, 'url':
                    'http://www.tidal.com/playlist/c80eaa10-5c4e-45aa-8f63-7b14a82d541f', 'image':
                    'b81a050f-5fa5-4500-85bf-4e36f1fd40e2', 'popularity': 0, 'squareImage':
                    '50a6fe47-62ee-4251-9011-e980aff2572d', 'customImageUrl': None, 'promotedArtists': [],
                    'lastItemAddedAt': '2025-05-08T10:38:55.530+0000', 'tracks': [{'id': 355628491,
                    'title': 'Nobody (from Kaiju No. 8)', 'duration': 154, 'replayGain': 0.0, 'peak': 0.0,
                    'allowStreaming': True, 'streamReady': True, 'payToStream': False,
                    'adSupportedStreamReady': True, 'djReady': True, 'stemReady': False,
                    'streamStartDate': '2024-04-12T00:00:00.000+0000', 'premiumStreamingOnly': False,
                    'trackNumber': 1, 'volumeNumber': 1, 'version': None, 'popularity': 30, 'copyright':
                    '℗ 2024 Mosley Music/Interscope Records', 'bpm': None, 'description': None, 'url':
                    'http://www.tidal.com/track/355628491', 'isrc': 'USUM72403353', 'editable': False,
                    'explicit': False, 'audioQuality': 'LOW', 'audioModes': ['DOLBY_ATMOS'],
                    'mediaMetadata': {'tags': ['DOLBY_ATMOS']}, 'upload': False, 'artist': {'id': 64665,
                    'name': 'OneRepublic', 'handle': None, 'type': 'MAIN', 'picture':
                    '4342534f-36a5-4af5-bf2a-795471c52499'}, 'artists': [{'id': 64665, 'name':
                    'OneRepublic', 'handle': None, 'type': 'MAIN', 'picture':
                    '4342534f-36a5-4af5-bf2a-795471c52499'}], 'album': {'id': 355628490, 'title': 'Nobody
                    (from Kaiju No. 8)', 'cover': '8b6a7e90-5f05-48e5-8543-7d689bca84a4', 'vibrantColor':
                    '#aeb867', 'videoCover': None, 'releaseDate': '2024-04-12'}, 'mixes': {'TRACK_MIX':
                    '0018767f3e5c164bcf416c80e21f39'}, 'dateAdded': '2025-05-08T10:38:12.778+0000',
                    'index': 100000, 'itemUuid': '24877971-617b-48d2-a4e9-70d3faca9b5b'}, {'id':
                    344633074, 'title': 'Who I Am', 'duration': 191, 'replayGain': -10.61, 'peak': 1.0,
                    'allowStreaming': True, 'streamReady': True, 'payToStream': False,
                    'adSupportedStreamReady': True, 'djReady': True, 'stemReady': False,
                    'streamStartDate': '2024-02-29T00:00:00.000+0000', 'premiumStreamingOnly': False,
                    'trackNumber': 3, 'volumeNumber': 1, 'version': 'Gravero\xa0Version', 'popularity':
                    43, 'copyright': 'Kreatell Music', 'bpm': None, 'description': None, 'url':
                    'http://www.tidal.com/track/344633074', 'isrc': 'NOG842302080', 'editable': False,
                    'explicit': False, 'audioQuality': 'LOSSLESS', 'audioModes': ['STEREO'],
                    'mediaMetadata': {'tags': ['LOSSLESS', 'HIRES_LOSSLESS']}, 'upload': False, 'artist':
                    {'id': 6159368, 'name': 'Alan Walker', 'handle': None, 'type': 'MAIN', 'picture':
                    'c46be937-9869-4454-8d80-ba6a6e23b6c6'}, 'artists': [{'id': 6159368, 'name': 'Alan
                    Walker', 'handle': None, 'type': 'MAIN', 'picture':
                    'c46be937-9869-4454-8d80-ba6a6e23b6c6'}, {'id': 10522031, 'name': 'Putri Ariani',
                    'handle': None, 'type': 'MAIN', 'picture': None}, {'id': 9458874, 'name': 'Gravero',
        'picture'⠹:  Resolving URLs...None}, {'id': 9744017, 'name': 'Peder
                    Elias', 'handle': None, 'type': 'MAIN', 'picture':
                    '96356e21-d400-4dde-8fd4-3edcc55397b2'}], 'album': {'id': 344633071, 'title': 'Who I
                    Am EP', 'cover': 'd726fed4-7496-4007-b200-f6d18f288ea8', 'vibrantColor': None,
                    'videoCover': None, 'releaseDate': '2024-02-29'}, 'mixes': {'TRACK_MIX':
                    '00147c523430b14714f4190fc5734d'}, 'dateAdded': '2025-05-08T10:38:44.229+0000',
                    'index': 200000, 'itemUuid': '8fbfd14d-0535-4ec6-97df-d5d8490684eb'}, {'id':
                    204469807, 'title': 'Bas Ek Baar (Lo-Fi Flip)', 'duration': 183, 'replayGain': -4.74,
                    'peak': 0.999969, 'allowStreaming': True, 'streamReady': True, 'payToStream': False,
                    'adSupportedStreamReady': True, 'djReady': True, 'stemReady': False,
                    'streamStartDate': '2021-11-13T00:00:00.000+0000', 'premiumStreamingOnly': False,
                    'trackNumber': 1, 'volumeNumber': 1, 'version': None, 'popularity': 8, 'copyright':
                    '(P) 2021 Times Music India Publishers', 'bpm': None, 'description': None, 'url':
                    'http://www.tidal.com/track/204469807', 'isrc': 'INT132103428', 'editable': False,
                    'explicit': False, 'audioQuality': 'LOSSLESS', 'audioModes': ['STEREO'],
                    'mediaMetadata': {'tags': ['LOSSLESS']}, 'upload': False, 'artist': {'id': 9458874,
                    'name': 'Gravero', 'handle': None, 'type': 'MAIN', 'picture': None}, 'artists':
                    [{'id': 9458874, 'name': 'Gravero', 'handle': None, 'type': 'MAIN', 'picture': None}],
                    'album': {'id': 204469805, 'title': 'Bas Ek Baar (Lo-Fi Flip)', 'cover':
                    'f1f9123b-1e74-4c8a-84c2-4085b1e16acc', 'vibrantColor': '#e573b0', 'videoCover': None,
                    'releaseDate': '2021-11-13'}, 'mixes': {}, 'dateAdded':
                    '2025-05-08T10:38:49.149+0000', 'index': 300000, 'itemUuid':
                    '761bd90e-9d11-492b-93aa-2f9bb67d95b8'}, {'id': 431096003, 'title': 'fizaah, tu hai
                    wahi (Gravero Flip)', 'duration': 101, 'replayGain': -7.37, 'peak': 0.987408,
                    'allowStreaming': True, 'streamReady': True, 'payToStream': False,
                    'adSupportedStreamReady': True, 'djReady': True, 'stemReady': False,
                    'streamStartDate': '2025-04-24T00:00:00.000+0000', 'premiumStreamingOnly': False,
                    'trackNumber': 1, 'volumeNumber': 1, 'version': None, 'popularity': 0, 'copyright':
                    '2025 su + vero.', 'bpm': 130, 'description': None, 'url':
                    'http://www.tidal.com/track/431096003', 'isrc': 'QZWDW2502373', 'editable': False,
                    'explicit': False, 'audioQuality': 'LOSSLESS', 'audioModes': ['STEREO'],
                    'mediaMetadata': {'tags': ['LOSSLESS', 'HIRES_LOSSLESS']}, 'upload': False, 'artist':
                    {'id': 34228668, 'name': 'sufr', 'handle': None, 'type': 'MAIN', 'picture': None},
                    'artists': [{'id': 34228668, 'name': 'sufr', 'handle': None, 'type': 'MAIN',
                    'picture': None}, {'id': 9458874, 'name': 'Gravero', 'handle': None, 'type': 'MAIN',
                    'picture': None}], 'album': {'id': 431096001, 'title': 'fizaah, tu hai wahi (Gravero
                    Flip)', 'cover': '21842bd6-986a-4bf0-88ba-2d7d6e1f57f4', 'vibrantColor': None,
                    'videoCover': None, 'releaseDate': '2025-04-24'}, 'mixes': None, 'dateAdded':
                    '2025-05-08T10:38:52.395+0000', 'index': 400000, 'itemUuid':
                    '08947fbd-1aae-408d-a5d9-b38098c1699d'}, {'id': 414859820, 'title': 'Awara',
                    'duration': 140, 'replayGain': -8.38, 'peak': 0.920593, 'allowStreaming': True,
                    'streamReady': True, 'payToStream': False, 'adSupportedStreamReady': True, 'djReady':
                    True, 'stemReady': False, 'streamStartDate': '2025-02-07T00:00:00.000+0000',
                    'premiumStreamingOnly': False, 'trackNumber': 1, 'volumeNumber': 1, 'version':
                    'Gravero Version', 'popularity': 0, 'copyright': '℗ 2025 Shubham Kabra', 'bpm': None,
                    'description': None, 'url': 'http://www.tidal.com/track/414859820', 'isrc':
                    'INUM72500056', 'editable': False, 'explicit': False, 'audioQuality': 'LOSSLESS',
                    'audioModes': ['STEREO'], 'mediaMetadata': {'tags': ['LOSSLESS']}, 'upload': False,
                    'artist': {'id': 21377053, 'name': 'Shubham Kabra', 'handle': None, 'type': 'MAIN',
                    'picture': None}, 'artists': [{'id': 21377053, 'name': 'Shubham Kabra', 'handle':
                    None, 'type': 'MAIN', 'picture': None}, {'id': 9458874, 'name': 'Gravero', 'handle':
                    None, 'type': 'MAIN', 'picture': None}], 'album': {'id': 414859819, 'title': 'Awara -
                    THE EP', 'cover': '94b5a9bf-c1c7-4589-8294-f84a2efd103b', 'vibrantColor': '#FFFFFF',
                    'videoCover': None, 'releaseDate': '2023-11-04'}, 'mixes': {}, 'dateAdded':
                    '2025-05-08T10:38:55.530+0000', 'index': 500000, 'itemUuid':
         '52a6f68f-ac8d-4adb-a14f-1262539f1ac5'⠸} Resolving URLs...]}                                                   
[16:38:20] DEBUG    Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)                               db.py:108
           INFO     Track (355628491) already logged in database. Skipping.                              playlist.py:47
           DEBUG    Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)                               db.py:108
           INFO     Track (344633074) already logged in database. Skipping.                              playlist.py:47
           DEBUG    Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)                               db.py:108
           INFO     Track (204469807) already logged in database. Skipping.                              playlist.py:47
           DEBUG    Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)                               db.py:108
           INFO     Track (431096003) already logged in database. Skipping.                              playlist.py:47
           DEBUG    Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)                               db.py:108
           INFO     Track (414859820) already logged in database. Skipping.                              playlist.py:47
           DEBUG    Removing dirs set()
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "D:\\Qobuz DL"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false
# Put tracks in an album with 2 or more discs into a subfolder named `Disc N` 
disc_subdirectories = true
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60
# Verify SSL certificates for API connections
# Set to false if you encounter SSL certificate verification errors (not recommended)
verify_ssl = true

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 2
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = true
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = ""
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = ""
# Do not change
app_id = "798273057"
# Do not change
secrets = ["806331c3b0b641da923b890aed01d04a", "f69a7734686cb9427629378a4b7ac381", "abb21364945c0583309667d13ca3d93a"]

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 2
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = 
country_code = "NZ"
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = 1747287041.6201751

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "D:\\YT-DLP"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "C:\\Users\\Hp\\AppData\\Roaming\\streamrip\\downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "C:\\Users\\Hp\\AppData\\Roaming\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = false
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.6"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Windows

### streamrip version

210
