### ISSUE TITLE
[BUG] Metadata Tags Not Skipped After Adding to exclude List

### ISSUE THREAD

**Issue by ghost** [nathom/streamrip#850]
### Describe the bug

In Streamrip v2.1.0, the skipped metadata tags are not working. I referred to your wiki page and added ["album", "albumartist"] to the exclude list, but when I downloaded, I noticed that it wasn't skipping them. The other metadata tags are also not working. I kindly request that you fix this bug as soon as possible.

### Command Used

```bash
rip url https://open.qobuz.com/track/292873373
```

### Debug Traceback

```text
C:\Users\Hp>rip -vvv url https://open.qobuz.com/track/292873373
[19:03:25] DEBUG    Showing all debug logs                                                                   cli.py:111
⠼ Logging into qobuz[19:03:26] DEBUG    Request params {'user_id': '1phgblmkvt@lgkjkjk.shop', 'user_auth_token':               qobuz.py:196
                    'cSOnx2j0ktWw8p9U32pvIcsboAVR6HQ3FtdCOG_zk8IF_ic1_6FO45kGt3hBX0NP-WQr2q-7KajqSAUbnWYLA
                    A', 'app_id': '798273057'}
           DEBUG    api_request: endpoint=user/login, params={'user_id': '1phgblmkvt@lgkjkjk.shop',        qobuz.py:447
                    'user_auth_token':
                    'cSOnx2j0ktWw8p9U32pvIcsboAVR6HQ3FtdCOG_zk8IF_ic1_6FO45kGt3hBX0NP-WQr2q-7KajqSAUbnWYLA
                    A', 'app_id': '798273057'}
⠴ Logging into qobuz[19:03:28] DEBUG    Login resp: {'user': {'id': 4282919, 'publicId': 'qobuz:user:yGeHGQ5YIUIuI', 'email':  qobuz.py:198
                    '98ktfgqjny@fakemail.info', 'login': 'tmxkwpn_us_250502_213537', 'firstname': None,
                    'lastname': None, 'display_name': '98ktfgqjny', 'country_code': 'US', 'language_code':
                    'en', 'zone': 'US', 'store': 'US-en', 'country': 'US', 'avatar':
                    'https://www.gravatar.com/avatar/cb13437f772ad5e1ae55dcd174f9caa8?s=50&d=mm', 'genre':
                    'male', 'age': 33, 'creation_date': '2025-05-02', 'subscription': {'offer': 'studio',
                    'periodicity': 'monthly', 'start_date': '2025-05-02', 'end_date': '2025-06-01',
                    'is_canceled': False, 'household_size_max': 6}, 'credential': {'id': 2740556, 'label':
                    'streaming-studio', 'description': 'Subscriber Qobuz Studio', 'parameters':
                    {'lossy_streaming': True, 'lossless_streaming': True, 'hires_streaming': True,
                    'hires_purchases_streaming': True, 'mobile_streaming': True, 'offline_streaming':
                    True, 'hfp_purchase': False, 'included_format_group_ids': [1, 2, 3, 4],
                    'color_scheme': {'logo': '#B8D729'}, 'label': 'Qobuz Studio', 'short_label': 'Studio',
                    'source': 'subscription'}}, 'last_update': {'favorite': 1746724211, 'favorite_album':
                    1746221740, 'favorite_artist': 1746221740, 'favorite_track': 1746724211,
                    'favorite_label': 1746221740, 'favorite_award': 1746221740, 'playlist': 1746221740,
                    'purchase': 1746221991}, 'store_features': {'download': True, 'streaming': True,
                    'editorial': True, 'club': True, 'wallet': True, 'weeklyq': True, 'autoplay': True,
  'opt_in': ⠦True , Logging into qobuz'pre_register_opt_in': False,
                    'pre_register_zipcode': True, 'music_import': True, 'radio': True, 'stream_purchase':
                    True}, 'player_settings': [], 'externals': {}}, 'user_auth_token':
                    'cSOnx2j0ktWw8p9U32pvIcsboAVR6HQ3FtdCOG_zk8IF_ic1_6FO45kGt3hBX0NP-WQr2q-7KajqSAUbnWYLA
                    A'}
           DEBUG    Logged in to Qobuz                                                                     qobuz.py:205
           DEBUG    Raw request signature:                                                                 qobuz.py:430
                    trackgetFileUrlformat_id27intentstreamtrack_id195125741746884008.288637806331c3b0b641d
                    a923b890aed01d04a
           DEBUG    Hashed request signature: 966257aa74f775b5a890fe1325f7a354                             qobuz.py:432
           DEBUG    api_request: endpoint=track/getFileUrl, params={'request_ts': 1746884008.288637,       qobuz.py:447
                    'request_sig': '966257aa74f775b5a890fe1325f7a354', 'track_id': '19512574',
                    'format_id': 27, 'intent': 'stream'}
           DEBUG    Raw request signature:                                                                 qobuz.py:430
                    trackgetFileUrlformat_id27intentstreamtrack_id195125741746884008.3196702f69a7734686cb9
                    427629378a4b7ac381
           DEBUG    Hashed request signature: 9eb19ed862e7f6b089680e24d032700f                             qobuz.py:432
           DEBUG    api_request: endpoint=track/getFileUrl, params={'request_ts': 1746884008.3196702,      qobuz.py:447
                    'request_sig': '9eb19ed862e7f6b089680e24d032700f', 'track_id': '19512574',
                    'format_id': 27, 'intent': 'stream'}
         Raw request signature:                                                                 ⠧qobuz.py :Logging into qobuz430
                    trackgetFileUrlformat_id27intentstreamtrack_id195125741746884008.3531551abb21364945c05
                    83309667d13ca3d93a
           DEBUG    Hashed request signature: 6c207f5c09e9ff5053490ce8b72f38ca                             qobuz.py:432
           DEBUG    api_request: endpoint=track/getFileUrl, params={'request_ts': 1746884008.3531551,      qobuz.py:447
                    'request_sig': '6c207f5c09e9ff5053490ce8b72f38ca', 'track_id': '19512574',
                    'format_id': 27, 'intent': 'stream'}
[19:03:29] DEBUG    Executing SELECT EXISTS(SELECT 1 FROM downloads WHERE id=?)                               db.py:108
           DEBUG    request params: {'app_id': '798273057', 'track_id': '292873373', 'limit': 500,         qobuz.py:239
                    'offset': 0}
           DEBUG    api_request: endpoint=track/get, params={'app_id': '798273057', 'track_id':            qobuz.py:447
                    '292873373', 'limit': 500, 'offset': 0}
⠴ Resolving URLs...[19:03:30] DEBUG    Raw request signature:                                                                 qobuz.py:430
                    trackgetFileUrlformat_id6intentstreamtrack_id2928733731746884010.2209141abb21364945c05
                    83309667d13ca3d93a
           DEBUG    Hashed request signature: 13ade846a6a8f1458dafdbf01e2554f6                             qobuz.py:432
           DEBUG    api_request: endpoint=track/getFileUrl, params={'request_ts': 1746884010.2209141,      qobuz.py:447
                    'request_sig': '13ade846a6a8f1458dafdbf01e2554f6', 'track_id': '292873373',
                    'format_id': 6, 'intent': 'stream'}
[19:04:01] DEBUG    Tagging with [('TITLE', 'Spirits'), ('ARTIST', 'The Strumbellas'), ('ALBUM', 'Hope'), tagger.py:254
                    ('ALBUMARTIST', 'The Strumbellas'), ('YEAR', '2016'), ('DESCRIPTION', 'Featuring more
                    of the sextet\'s festival- and fair-friendly, folk-infused pop, the Strumbellas third
                    long-player, Hope, loads the track list with memorable anthems and stomping rhythms.
                    The singalong opener "Spirits," the band\'s first Billboard number one after it
                    topped the Alternative Songs chart, turns out to be typical of the majority of
                    Hope\'s songs. A couple of ballads offer audiences a break from rhythmic clapping to
                    sway with phones in hand, though the piano ballad "I Still Make Her Cry" stands as
                    the lone truly intimate moment of the record which, despite its enthusiastic
                    choruses, harbors reflective, self-doubting lyrics.<br /><br />&copy Marcy Donelson
                    /TiVo'), ('GENRE', 'Rock, Alternatif et Indé, Pop'), ('COPYRIGHT', '© 2016 Glassnote
                    Entertainment Group LLC ℗ 2016 Glassnote Entertainment Group LLC'), ('TRACKNUMBER',
                    '01'), ('DISCNUMBER', '01'), ('TRACKTOTAL', '11'), ('DISCTOTAL', '01'), ('DATE',
                    '2016-04-22'), ('ISRC', 'CA6MD1500001')]
           DEBUG    Executing INSERT INTO downloads (id) VALUES (?)                                           db.py:124
           DEBUG    Items to add: ('292873373',)                                                              db.py:125
───────────────────────────────────────────────── Downloading Spirits ─────────────────────────────────────────────────
           DEBUG    Removing dirs {'D:\\Qobuz DL\\__artwork'}                                             artwork.py:19
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "D:\\Qobuz DL"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false
# Put tracks in an album with 2 or more discs into a subfolder named `Disc N` 
disc_subdirectories = true
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60
# Verify SSL certificates for API connections
# Set to false if you encounter SSL certificate verification errors (not recommended)
verify_ssl = true

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 2
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = true
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = "1phgblmkvt@lgkjkjk.shop"
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = "cSOnx2j0ktWw8p9U32pvIcsboAVR6HQ3FtdCOG_zk8IF_ic1_6FO45kGt3hBX0NP-WQr2q-7KajqSAUbnWYLAA"
# Do not change
app_id = "798273057"
# Do not change
secrets = ["806331c3b0b641da923b890aed01d04a", "f69a7734686cb9427629378a4b7ac381", "abb21364945c0583309667d13ca3d93a"]

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 2
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = 203488973
country_code = "NZ"
access_token = "eyJraWQiOiJ2OU1GbFhqWSIsImFsZyI6IkVTMjU2In0.eyJ0eXBlIjoibzJfYWNjZXNzIiwidWlkIjoyMDM0ODg5NzMsInNjb3BlIjoicl91c3Igd191c3Igd19zdWIiLCJnVmVyIjowLCJzVmVyIjowLCJjaWQiOjMyMzUsImV4cCI6MTc0NzI4NzA1Mywic2lkIjoiNWZlMGQ3MmItZjJiNi00OWUyLTlmNGUtMjE5ODZiNjZhNTAwIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLnRpZGFsLmNvbS92MSJ9.GcHTBEui1aBJw7c43H1kWpWgsWCnwJOBYoTnX6-1cxU20UZAS7JyCYzcp5qwsnnPs15oYjS1uXPPYW9WQJ7j8Q"
refresh_token = "eyJraWQiOiJoUzFKYTdVMCIsImFsZyI6IkVTNTEyIn0.eyJ0eXBlIjoibzJfcmVmcmVzaCIsInVpZCI6MjAzNDg4OTczLCJzY29wZSI6InJfdXNyIHdfdXNyIHdfc3ViIiwiY2lkIjozMjM1LCJzVmVyIjowLCJnVmVyIjowLCJpc3MiOiJodHRwczovL2F1dGgudGlkYWwuY29tL3YxIn0.AeBP9Kkk-CiG371NyJbiwirQh5eRc-Xs--QSX_TDIqWsJELpJ97g02eWO0mPGjqHyIkBtKwCrxkXR99Vu8-7lDsZAEgGIvz5UhoOG-0ak0dpX-ho6PpZ04b1IvkkaL2ryMg9xl9gmi6Kcl8kJscZ1uxAdkf1NjGqIA7_vewl6Kplko3K"
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = 1747287041.6201751

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = "D:\\YT-DLP"

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = "C:\\Users\\Hp\\AppData\\Roaming\\streamrip\\downloads.db"
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = "C:\\Users\\Hp\\AppData\\Roaming\\streamrip\\failed_downloads.db"

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = false
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = false
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = false
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = ["genre", "albumartist"]

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = false
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.6"
# Print a message if a new version of streamrip is available 
check_for_updates = true
```

### Operating System

Windows , Android (Termux)

### streamrip version

2.1.0

### Screenshots and recordings

![Image](https://github.com/user-attachments/assets/93b56ac0-6395-47d6-901f-23cd0936eadd)
