### ISSUE TITLE
[BUG] Traceback (most recent call last)

### ISSUE THREAD

**Issue by HDDP0T** [nathom/streamrip#855]
### Describe the bug

I get a "Traceback (most recent call last)" error whenever I try to download anything 

### Command Used

```bash
rip --folder D:\Music url https://soundcloud.com/user-982406791/sets/copy-of-all-i-wanted-x
```

### Debug Traceback

```text
[10:16:07] DEBUG    Showing all debug logs                                                                    cli.py:111
Exception ignored from cffi callback <function _addrinfo_cb at 0x000001E78947C400>:
Traceback (most recent call last):
  File "C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pycares\__init__.py", line 156, in _addrinfo_cb
    callback(result, status)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 872, in call_soon_threadsafe
    self._check_closed()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 550, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in _run_module_as_main:198                                                                       │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   alter_argv = False                                                                         │ │
│ │         code = <code object <module> at 0x000001E783E15E30, file                             │ │
│ │                "C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Pyth… │ │
│ │                line 1>                                                                       │ │
│ │ main_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Pyth… │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Pyth… │ │
│ │                origin='C:\\Users\\HDDP0T\\AppData\\Local\\Packages\\PythonSoftwareFo… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\HDDP0T\\AppData\\Local\\Packages\\PythonSoftwareFoundatio… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\HDDP0T\\AppData\\Local\\Packages\\PythonSoftwareFoundatio… │ │
│ │                │   're': <module 're' from 'C:\\Program                                      │ │
│ │                Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qb… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Pyth… │ │
│ │                origin='C:\\Users\\HDDP0T\\AppData\\Local\\Packages\\PythonSoftwareFo… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│ in _run_code:88                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │       cached = 'C:\\Users\\HDDP0T\\AppData\\Local\\Packages\\PythonSoftwareFoundatio… │ │
│ │         code = <code object <module> at 0x000001E783E15E30, file                             │ │
│ │                "C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Pyth… │ │
│ │                line 1>                                                                       │ │
│ │        fname = 'C:\\Users\\HDDP0T\\AppData\\Local\\Packages\\PythonSoftwareFoundatio… │ │
│ │ init_globals = None                                                                          │ │
│ │       loader = <zipimporter object                                                           │ │
│ │                "C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Pyth… │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Pyth… │ │
│ │                origin='C:\\Users\\HDDP0T\\AppData\\Local\\Packages\\PythonSoftwareFo… │ │
│ │     pkg_name = ''                                                                            │ │
│ │  run_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Pyth… │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Pyth… │ │
│ │                origin='C:\\Users\\HDDP0T\\AppData\\Local\\Packages\\PythonSoftwareFo… │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__':                                                               │ │
│ │                'C:\\Users\\HDDP0T\\AppData\\Local\\Packages\\PythonSoftwareFoundatio… │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\HDDP0T\\AppData\\Local\\Packages\\PythonSoftwareFoundatio… │ │
│ │                │   're': <module 're' from 'C:\\Program                                      │ │
│ │                Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qb… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │  script_name = None                                                                          │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│ C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0 │
│ \LocalCache\local-packages\Python313\site-packages\click\core.py:1442 in __call__                │
│                                                                                                  │
│ C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0 │
│ \LocalCache\local-packages\Python313\site-packages\click\core.py:1363 in main                    │
│                                                                                                  │
│ C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0 │
│ \LocalCache\local-packages\Python313\site-packages\click\core.py:1830 in invoke                  │
│                                                                                                  │
│ C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0 │
│ \LocalCache\local-packages\Python313\site-packages\click\core.py:1226 in invoke                  │
│                                                                                                  │
│ C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0 │
│ \LocalCache\local-packages\Python313\site-packages\click\core.py:794 in invoke                   │
│                                                                                                  │
│ C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0 │
│ \LocalCache\local-packages\Python313\site-packages\click\decorators.py:34 in new_func            │
│                                                                                                  │
│ C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0 │
│ \LocalCache\local-packages\Python313\site-packages\streamrip\rip\cli.py:29 in wrapper            │
│                                                                                                  │
│    26 def coro(f):                                                                               │
│    27 │   @wraps(f)                                                                              │
│    28 │   def wrapper(*args, **kwargs):                                                          │
│ ❱  29 │   │   return asyncio.run(f(*args, **kwargs))                                             │
│    30 │                                                                                          │
│    31 │   return wrapper                                                                         │
│    32                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   args = (<click.core.Context object at 0x000001E789C6FC50>,)                                │ │
│ │ kwargs = {                                                                                   │ │
│ │          │   'urls': (                                                                       │ │
│ │          │   │                                                                               │ │
│ │          'https://soundcloud.com/user-982406791/sets/copy-of-all-i-wanted-x?si=f4ffb0ca714'… │ │
│ │          │   )                                                                               │ │
│ │          }                                                                                   │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Program                                                                                       │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\asynci │
│ o\runners.py:195 in run                                                                          │
│                                                                                                  │
│   192 │   │   │   "asyncio.run() cannot be called from a running event loop")                    │
│   193 │                                                                                          │
│   194 │   with Runner(debug=debug, loop_factory=loop_factory) as runner:                         │
│ ❱ 195 │   │   return runner.run(main)                                                            │
│   196                                                                                            │
│   197                                                                                            │
│   198 def _cancel_all_tasks(loop):                                                               │
│                                                                                                  │
│ ╭─────────────────────────────── locals ───────────────────────────────╮                         │
│ │        debug = None                                                  │                         │
│ │ loop_factory = None                                                  │                         │
│ │         main = <coroutine object url at 0x000001E789D2C170>          │                         │
│ │       runner = <asyncio.runners.Runner object at 0x000001E789D342F0> │                         │
│ ╰──────────────────────────────────────────────────────────────────────╯                         │
│                                                                                                  │
│ C:\Program                                                                                       │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\asynci │
│ o\runners.py:118 in run                                                                          │
│                                                                                                  │
│   115 │   │                                                                                      │
│   116 │   │   self._interrupt_count = 0                                                          │
│   117 │   │   try:                                                                               │
│ ❱ 118 │   │   │   return self._loop.run_until_complete(task)                                     │
│   119 │   │   except exceptions.CancelledError:                                                  │
│   120 │   │   │   if self._interrupt_count > 0:                                                  │
│   121 │   │   │   │   uncancel = getattr(task, "uncancel", None)                                 │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │        context = <_contextvars.Context object at 0x000001E789ECB6C0>                         │ │
│ │           coro = <coroutine object url at 0x000001E789D2C170>                                │ │
│ │           self = <asyncio.runners.Runner object at 0x000001E789D342F0>                       │ │
│ │ sigint_handler = functools.partial(<bound method Runner._on_sigint of                        │ │
│ │                  <asyncio.runners.Runner object at 0x000001E789D342F0>>, main_task=<Task     │ │
│ │                  finished name='Task-1' coro=<url() done, defined at                         │ │
│ │                  C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Pyt… │ │
│ │                  exception=AssertionError()>)                                                │ │
│ │           task = <Task finished name='Task-1' coro=<url() done, defined at                   │ │
│ │                  C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Pyt… │ │
│ │                  exception=AssertionError()>                                                 │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Program                                                                                       │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\asynci │
│ o\base_events.py:719 in run_until_complete                                                       │
│                                                                                                  │
│    716 │   │   if not future.done():                                                             │
│    717 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')             │
│    718 │   │                                                                                     │
│ ❱  719 │   │   return future.result()                                                            │
│    720 │                                                                                         │
│    721 │   def stop(self):                                                                       │
│    722 │   │   """Stop running the event loop.                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   future = <Task finished name='Task-1' coro=<url() done, defined at                         │ │
│ │            C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.… │ │
│ │            exception=AssertionError()>                                                       │ │
│ │ new_task = False                                                                             │ │
│ │     self = <_WindowsSelectorEventLoop running=False closed=True debug=False>                 │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0 │
│ \LocalCache\local-packages\Python313\site-packages\streamrip\rip\cli.py:190 in url               │
│                                                                                                  │
│   187 │   │   │   else:                                                                          │
│   188 │   │   │   │   version_coro = None                                                        │
│   189 │   │   │                                                                                  │
│ ❱ 190 │   │   │   async with Main(cfg) as main:                                                  │
│   191 │   │   │   │   await main.add_all(urls)                                                   │
│   192 │   │   │   │   await main.resolve()                                                       │
│   193 │   │   │   │   await main.rip()                                                           │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │          cfg = <streamrip.config.Config object at 0x000001E789C07E00>                        │ │
│ │          ctx = <click.core.Context object at 0x000001E789C6FC50>                             │ │
│ │      updates = True                                                                          │ │
│ │         urls = (                                                                             │ │
│ │                │                                                                             │ │
│ │                'https://soundcloud.com/user-982406791/sets/copy-of-all-i-wanted-x?si=f4ffb0… │ │
│ │                )                                                                             │ │
│ │ version_coro = <Task cancelled name='Task-2' coro=<latest_streamrip_version() done, defined  │ │
│ │                at                                                                            │ │
│ │                C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Pytho… │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0 │
│ \LocalCache\local-packages\Python313\site-packages\streamrip\rip\main.py:62 in __init__          │
│                                                                                                  │
│    59 │   │                                                                                      │
│    60 │   │   c = self.config.session.database                                                   │
│    61 │   │   if c.downloads_enabled:                                                            │
│ ❱  62 │   │   │   downloads_db = db.Downloads(c.downloads_path)                                  │
│    63 │   │   else:                                                                              │
│    64 │   │   │   downloads_db = db.Dummy()                                                      │
│    65                                                                                            │
│                                                                                                  │
│ ╭──────────────────────────── locals ─────────────────────────────╮                              │
│ │      c = DatabaseConfig(                                        │                              │
│ │          │   downloads_enabled=True,                            │                              │
│ │          │   downloads_path='',                                 │                              │
│ │          │   failed_downloads_enabled=True,                     │                              │
│ │          │   failed_downloads_path=''                           │                              │
│ │          )                                                      │                              │
│ │ config = <streamrip.config.Config object at 0x000001E789C07E00> │                              │
│ │   self = <streamrip.rip.main.Main object at 0x000001E789D352B0> │                              │
│ ╰─────────────────────────────────────────────────────────────────╯                              │
│                                                                                                  │
│ C:\Users\HDDP0T\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0 │
│ \LocalCache\local-packages\Python313\site-packages\streamrip\db.py:67 in __init__                │
│                                                                                                  │
│    64 │   │   """                                                                                │
│    65 │   │   assert self.structure != {}                                                        │
│    66 │   │   assert self.name                                                                   │
│ ❱  67 │   │   assert path                                                                        │
│    68 │   │                                                                                      │
│    69 │   │   self.path = path                                                                   │
│    70                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────── locals ───────────────────────────╮                                 │
│ │ path = ''                                                    │                                 │
│ │ self = <streamrip.db.Downloads object at 0x000001E789D363C0> │                                 │
│ ╰──────────────────────────────────────────────────────────────╯                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError
'utm_source' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
'utm_medium' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
'utm_campaign' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
```

### Config File

```toml
[downloads]
# Folder where tracks are downloaded to
folder = "D:\\Music"
# Put Qobuz albums in a 'Qobuz' folder, Tidal albums in 'Tidal' etc.
source_subdirectories = false
# Put tracks in an album with 2 or more discs into a subfolder named `Disc N` 
disc_subdirectories = true
# Download (and convert) tracks all at once, instead of sequentially. 
# If you are converting the tracks, or have fast internet, this will 
# substantially improve processing speed.
concurrency = true
# The maximum number of tracks to download at once
# If you have very fast internet, you will benefit from a higher value,
# A value that is too high for your bandwidth may cause slowdowns
# Set to -1 for no limit
max_connections = 6
# Max number of API requests per source to handle per minute
# Set to -1 for no limit
requests_per_minute = 60
# Verify SSL certificates for API connections
# Set to false if you encounter SSL certificate verification errors (not recommended)
verify_ssl = true

[qobuz]
# 1: 320kbps MP3, 2: 16/44.1, 3: 24/<=96, 4: 24/>=96
quality = 3
# This will download booklet pdfs that are included with some albums
download_booklets = true

# Authenticate to Qobuz using auth token? Value can be true/false only
use_auth_token = false
# Enter your userid if the above use_auth_token is set to true, else enter your email
email_or_userid = ""
# Enter your auth token if the above use_auth_token is set to true, else enter the md5 hash of your plaintext password
password_or_token = ""
# Do not change
app_id = ""
# Do not change
secrets = []

[tidal]
# 0: 256kbps AAC, 1: 320kbps AAC, 2: 16/44.1 "HiFi" FLAC, 3: 24/44.1 "MQA" FLAC
quality = 3
# This will download videos included in Video Albums.
download_videos = true

# Do not change any of the fields below
user_id = ""
country_code = ""
access_token = ""
refresh_token = ""
# Tokens last 1 week after refresh. This is the Unix timestamp of the expiration
# time. If you haven't used streamrip in more than a week, you may have to log
# in again using `rip config --tidal`
token_expiry = ""

[deezer]
# 0, 1, or 2
# This only applies to paid Deezer subscriptions. Those using deezloader
# are automatically limited to quality = 1
quality = 2
# An authentication cookie that allows streamrip to use your Deezer account
# See https://github.com/nathom/streamrip/wiki/Finding-Your-Deezer-ARL-Cookie
# for instructions on how to find this
arl = ""
# This allows for free 320kbps MP3 downloads from Deezer
# If an arl is provided, deezloader is never used
use_deezloader = true
# This warns you when the paid deezer account is not logged in and rip falls
# back to deezloader, which is unreliable
deezloader_warnings = true

[soundcloud]
# Only 0 is available for now
quality = 0
# This changes periodically, so it needs to be updated
client_id = ""
app_version = ""

[youtube]
# Only 0 is available for now
quality = 0
# Download the video along with the audio
download_videos = false
# The path to download the videos to
video_downloads_folder = ""

[database]
# Create a database that contains all the track IDs downloaded so far
# Any time a track logged in the database is requested, it is skipped
# This can be disabled temporarily with the --no-db flag
downloads_enabled = true
# Path to the downloads database 
downloads_path = ""
# If a download fails, the item ID is stored here. Then, `rip repair` can be
# called to retry the downloads
failed_downloads_enabled = true
failed_downloads_path = ""

# Convert tracks to a codec after downloading them.
[conversion]
enabled = false
# FLAC, ALAC, OPUS, MP3, VORBIS, or AAC
codec = "ALAC"
# In Hz. Tracks are downsampled if their sampling rate is greater than this. 
# Value of 48000 is recommended to maximize quality and minimize space
sampling_rate = 48000
# Only 16 and 24 are available. It is only applied when the bit depth is higher
# than this value.
bit_depth = 24
# Only applicable for lossy codecs
lossy_bitrate = 320

# Filter a Qobuz artist's discography. Set to 'true' to turn on a filter.
# This will also be applied to other sources, but is not guaranteed to work correctly
[qobuz_filters]
# Remove Collectors Editions, live recordings, etc.
extras = false
# Picks the highest quality out of albums with identical titles.
repeats = false
# Remove EPs and Singles
non_albums = false
# Remove albums whose artist is not the one requested
features = false
# Skip non studio albums
non_studio_albums = false
# Only download remastered albums
non_remaster = false

[artwork]
# Write the image to the audio file
embed = true
# The size of the artwork to embed. Options: thumbnail, small, large, original.
# "original" images can be up to 30MB, and may fail embedding. 
# Using "large" is recommended.
embed_size = "large"
# If this is set to a value > 0, max(width, height) of the embedded art will be set to this value in pixels
# Proportions of the image will remain the same
embed_max_width = -1
# Save the cover image at the highest quality as a seperate jpg file
save_artwork = true
# If this is set to a value > 0, max(width, height) of the saved art will be set to this value in pixels
# Proportions of the image will remain the same
saved_max_width = -1


[metadata]
# Sets the value of the 'ALBUM' field in the metadata to the playlist's name. 
# This is useful if your music library software organizes tracks based on album name.
set_playlist_to_album = true
# If part of a playlist, sets the `tracknumber` field in the metadata to the track's 
# position in the playlist instead of its position in its album
renumber_playlist_tracks = true
# The following metadata tags won't be applied
# See https://github.com/nathom/streamrip/wiki/Metadata-Tag-Names for more info
exclude = []

# Changes the folder and file names generated by streamrip.
[filepaths]
# Create folders for single tracks within the downloads directory using the folder_format
# template
add_singles_to_folder = true
# Available keys: "albumartist", "title", "year", "bit_depth", "sampling_rate",
# "id", and "albumcomposer"
folder_format = "{albumartist} - {title} ({year}) [{container}] [{bit_depth}B-{sampling_rate}kHz]"
# Available keys: "tracknumber", "artist", "albumartist", "composer", "title",
# and "albumcomposer", "explicit"
track_format = "{tracknumber:02}. {artist} - {title}{explicit}"
# Only allow printable ASCII characters in filenames.
restrict_characters = false
# Truncate the filename if it is greater than this number of characters
# Setting this to false may cause downloads to fail on some systems
truncate_to = 120

# Last.fm playlists are downloaded by searching for the titles of the tracks
[lastfm]
# The source on which to search for the tracks.
source = "qobuz"
# If no results were found with the primary source, the item is searched for 
# on this one.
fallback_source = ""

[cli]
# Print "Downloading {Album name}" etc. to screen
text_output = true
# Show resolve, download progress bars
progress_bars = true
# The maximum number of search results to show in the interactive menu
max_search_results = 100

[misc]
# Metadata to identify this config file. Do not change.
version = "2.0.6"
# Print a message if a new version of streamrip is available 
check_for_updates = true

```

### Operating System

Windows 11 

### streamrip version

2.1.0

### Screenshots and recordings

![Image](https://github.com/user-attachments/assets/45e726d8-9d77-4d43-ace3-2f83671c4548)

### Additional context

My config.toml file was empty so I copy pasted another config.toml from Roaming directory
